### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by schlagkiwix** [openzim/mwoffliner#1005]
Missing fonts appears as square boxes, usually seen in non latin scripts. May be found in a few paragraphs or full pages.

http://library.kiwix.org/wikipedia_wuu_all_novid_2019-04/A/%E5%B0%81%E9%9D%A2
WUU
http://library.kiwix.org/wikipedia_arc_all_novid_2019-06/A/%DC%A6%DC%90%DC%AC%DC%90_%DC%AA%DC%9D%DC%AB%DC%9D%DC%AC%DC%90
ARC
http://library.kiwix.org/wikipedia_shn_all_nopic_2019-04/A/%E1%81%BC%E1%82%83%E1%82%88%E1%82%81%E1%80%B0%E1%80%9D%E1%80%BA%E1%82%81%E1%82%85%E1%81%B5%E1%80%BA%E1%82%88
SHN
http://library.kiwix.org/wiktionary_dv_all_novid_2019-06/A/%DE%89%DE%A6%DE%87%DE%A8_%DE%9E%DE%A6%DE%8A%DE%B0%DE%99%DE%A7
DV
http://library.kiwix.org/wikipedia_wuu_all_nopic_2019-04/A/%E5%B0%81%E9%9D%A2
WUU
http://library.kiwix.org/wikipedia_sat_all_novid_2019-04/A/%E1%B1%A2%E1%B1%A9%E1%B1%AC%E1%B1%A9%E1%B1%9B_%E1%B1%A5%E1%B1%9F%E1%B1%A6%E1%B1%B4%E1%B1%9F
SAT
http://library.kiwix.org/wiktionary_dv_all_nopic_2019-06/A/%DE%89%DE%A6%DE%87%DE%A8_%DE%9E%DE%A6%DE%8A%DE%B0%DE%99%DE%A7
DV
http://library.kiwix.org/wikipedia_arc_all_nopic_2019-06/A/%DC%A6%DC%90%DC%AC%DC%90_%DC%AA%DC%9D%DC%AB%DC%9D%DC%AC%DC%90
ARC
http://library.kiwix.org/wikipedia_dv_all_novid_2019-06/A/%DE%89%DE%A6%DE%87%DE%A8_%DE%9E%DE%A6%DE%8A%DE%B0%DE%99%DE%A7
DV
http://library.kiwix.org/wikipedia_za_all_nopic_2019-04/A/Yiebdaeuz
ZA
http://library.kiwix.org/wikipedia_cu_all_nopic_2019-06/A/%D0%93%D0%BB%D0%B0%D0%B2%D1%8C%D0%BD%D0%B0_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0
CU
http://library.kiwix.org/wikipedia_bug_all_novid_2019-06/A/Mappadec%C3%A9%C5%8B
BUG
http://library.kiwix.org/wikipedia_sat_all_nopic_2019-04/A/%E1%B1%A2%E1%B1%A9%E1%B1%AC%E1%B1%A9%E1%B1%9B_%E1%B1%A5%E1%B1%9F%E1%B1%A6%E1%B1%B4%E1%B1%9F
SAT
http://library.kiwix.org/wikipedia_got_all_nopic_2019-06/A/%F0%90%8C%B0%F0%90%8C%BD%F0%90%8C%B0%F0%90%8D%83%F0%90%8D%84%F0%90%8D%89%F0%90%8C%B3%F0%90%8C%B4%F0%90%8C%B9%F0%90%8C%BD%F0%90%8C%B9%F0%90%8C%BB%F0%90%8C%B0%F0%90%8C%BF%F0%90%8D%86%F0%90%8D%83
GOT
http://library.kiwix.org/wikipedia_bug_all_nopic_2019-06/A/Mappadec%C3%A9%C5%8B
BUG
http://library.kiwix.org/wikipedia_shn_all_novid_2019-04/A/%E1%81%BC%E1%82%83%E1%82%88%E1%82%81%E1%80%B0%E1%80%9D%E1%80%BA%E1%82%81%E1%82%85%E1%81%B5%E1%80%BA%E1%82%88
SHN

**Comment by Popolechien** [comment]
Adding [Kurdish Wiktionary](https://ku.wiktionary.org), though the issue seems broader than just fonts.
http://library.kiwix.org/wiktionary_ku_all_nopic_2019-05/A/Destp%C3%AAk

**Comment by kelson42** [comment]
I don't have this problem with my recent version of Ubuntu. The problem is probably on your OS/Browser which does not provide fonts with a fully covering of UTF8. Do you have the same problem with the official online version of Wikipedia?

I'm not 100% sure, but this might be a kind of duplicate of https://github.com/openzim/mwoffliner/issues/19

**Comment by Popolechien** [comment]
Testing was done on macOS, so yeah there might be an issue there. SAT is fine on Android 9.0, ku.wiktionary is not (for the two I tested)

**Comment by kelson42** [comment]
@Popolechien There is nothing we can do here. The only other solution would be to implement Web Fonts, see #19
