### ISSUE TITLE
Oversized text.

### ISSUE THREAD

**Issue by schlagkiwix** [openzim/mwoffliner#1006]
Wiktionary Welcome page as a huge font in its front page:
* http://library.kiwix.org/wiktionary_it_all_nopic_2019-05/A/Pagina_principale
* http://library.kiwix.org/wiktionary_it_all_maxi_2019-05/A/Pagina_principale

**Comment by kelson42** [comment]
Not reproducible with last version of the ZIM file and last version of Firefox.
