### ISSUE TITLE
Missing icons or images.

### ISSUE THREAD

**Issue by schlagkiwix** [openzim/mwoffliner#1008]
Missing icons or images.
* <s>http://library.kiwix.org/wikipedia_frp_all_maxi/A/Vouiquip%C3%A8dia:Re%C3%A7ua_princip%C3%A2la</s> OK 2020-04
* <s>http://library.kiwix.org/wikipedia_ky_all_maxi/A/%D0%91%D0%B0%D1%88%D0%B1%D0%B0%D1%80%D0%B0%D0%BA</s> OK 2020-04 (but there is a broken wiki code)
* <s>http://library.kiwix.org/wikipedia_kg_all_maxi/A/.cd</s> No picture at all on this page. Not clear what is/was the problem 2020-04
* <s>http://library.kiwix.org/wikipedia_lbe_all_maxi/A/%D0%90%D0%B3%D1%8C%D0%B0%D0%BC%D0%BC%D1%83%D1%80_%D0%BB%D0%B0%D0%B6%D0%B8%D0%BD</s> OK 2020-04
* <s>http://library.kiwix.org/wiktionary_hr_all_maxi/A/Glavna_stranica</s> OK 2020-04
* <s>http://library.kiwix.org/wikipedia_ext_all_maxi/A/P%C3%A1gina_prencipal</s> 2020-04
* <s>http://library.kiwix.org/wiktionary_hu_all_maxi/A/Kezd%C5%91lap</s> OK 2020-04
HU
http://library.kiwix.org/wikipedia_jv_all_novid_2019-05/A/Tepas
JV
http://library.kiwix.org/wikipedia_mhr_all_novid_2019-05/A/%D0%A2%D3%B1%D2%A5_%D0%BB%D0%B0%D1%88%D1%82%D1%8B%D0%BA
MHR
http://library.kiwix.org/wiktionary_hi_all_novid_2019-06/A/%E0%A4%AE%E0%A5%81%E0%A4%96%E0%A4%AA%E0%A5%83%E0%A4%B7%E0%A5%8D%E0%A4%A0
HI
http://library.kiwix.org/wikipedia_atj_all_novid_2019-06/A/Otitikowin
ATJ
http://library.kiwix.org/wikipedia_bcl_all_novid_2019-06/A/Panginot_na_Pahina
BCL
http://library.kiwix.org/wikipedia_hif_all_novid_2019-06/A/Pahila_Panna
HIF
http://library.kiwix.org/wiktionary_jv_all_novid_2019-05/A/Tepas
JV
http://library.kiwix.org/wikipedia_an_all_novid_2019-06/A/Portalada
AN
http://library.kiwix.org/wikipedia_gu_all_novid_2019-06/A/C%20(%E0%AA%AA%E0%AB%8D%E0%AA%B0%E0%AB%8B%E0%AA%97%E0%AB%8D%E0%AA%B0%E0%AA%BE%E0%AA%AE%E0%AA%BF%E0%AA%82%E0%AA%97%20%E0%AA%AD%E0%AA%BE%E0%AA%B7%E0%AA%BE)
GU
http://library.kiwix.org/wikipedia_gor_all_novid_2019-06/A/Halaman_Bungaliyo
GOR
http://library.kiwix.org/wiktionary_sa_all_novid_2019-05/A/%E0%A4%AE%E0%A5%81%E0%A4%96%E0%A5%8D%E0%A4%AF%E0%A4%AA%E0%A5%83%E0%A4%B7%E0%A5%8D%E0%A4%A0%E0%A4%AE%E0%A5%8D
SA
http://library.kiwix.org/westeros_en_all_novid_2019-04/A/Main_Page
EN
http://library.kiwix.org/wikipedia_dsb_all_novid_2019-06/A/G%C5%82owny_bok
DSB
http://library.kiwix.org/wikipedia_mwl_all_novid_2019-05/A/Biquip%C3%A9dia:P%C3%A1igina_percipal
http://library.kiwix.org/wikipedia_bo_all_novid_2019-06/A/%E0%BD%82%E0%BD%99%E0%BD%BC%E0%BC%8B%E0%BD%84%E0%BD%BC%E0%BD%A6%E0%BC%8D
BO
http://library.kiwix.org/wikipedia_nah_all_novid_2019-05/A/Cal%C4%ABxatl
NAH
http://library.kiwix.org/wiktionary_mt_all_novid_2019-05/A/Il-Pa%C4%A1na_prin%C4%8Bipali
MT
http://library.kiwix.org/wikipedia_chy_all_novid_2019-06/A/Va'ohtama
CHY
http://library.kiwix.org/wiktionary_gn_all_novid_2019-06/A/Ape
GN
http://library.kiwix.org/wikipedia_gv_all_novid_2019-06/A/Ard-ghuillag
GV
http://library.kiwix.org/wiktionary_ka_all_novid_2019-05/A/%E1%83%9B%E1%83%97%E1%83%90%E1%83%95%E1%83%90%E1%83%A0%E1%83%98_%E1%83%92%E1%83%95%E1%83%94%E1%83%A0%E1%83%93%E1%83%98
KA
http://library.kiwix.org/wikiquote_is_all_nopic_2019-07/A/Wikivitnun:Fors%C3%AD%C3%B0a
IS
http://library.kiwix.org/wikipedia_dty_all_novid_2019-06/A/%E0%A4%AE%E0%A5%81%E0%A4%96%E0%A5%8D%E0%A4%AF_%E0%A4%AA%E0%A4%A8%E0%A5%8D%E0%A4%A8%E0%A4%BE
DTY
http://library.kiwix.org/wikipedia_mzn_all_novid_2019-05/A/%DA%AF%D8%AA_%D8%B5%D9%81%D8%AD%D9%87
MZN
http://library.kiwix.org/wikisource_cs_all_novid_2019-07/A/Wikizdroje:Hlavn%C3%AD_strana
CS
http://library.kiwix.org/wikipedia_new_all_novid_2019-05/A/%E0%A4%AE%E0%A5%82_%E0%A4%AA%E0%A5%8C
ALL
http://library.kiwix.org/wikibooks_pt_all_novid_2019-07/A/Wikilivros:P%C3%A1gina_principal
PT
http://library.kiwix.org/wiktionary_ang_all_novid_2019-06/A/H%C4%93afodtramet
ANG
http://library.kiwix.org/wikipedia_koi_all_novid_2019-05/A/%D0%9F%D0%BE%D0%BD%D0%B4%D3%A7%D1%82%D1%87%D0%B0%D0%BD_%D0%BB%D0%B8%D1%81%D1%82%D0%B1%D0%BE%D0%BA
KOI
http://library.kiwix.org/wikipedia_io_all_novid_2019-05/A/Frontispico
IO
http://library.kiwix.org/wiktionary_ku_all_novid_2019-05/A/Destp%C3%AAk
KU
http://library.kiwix.org/wikipedia_gn_all_novid_2019-06/A/Ape
GN
http://library.kiwix.org/wikipedia_ur_all_novid_2019-05/A/%D8%B5%D9%81%D8%AD%DB%82_%D8%A7%D9%88%D9%84
UR
http://library.kiwix.org/wikipedia_ks_all_novid_2019-05/A/%D8%A7%DB%81%D9%85_%D8%B5%D9%8E%D9%81%DB%81%D9%95
KS
http://library.kiwix.org/wikipedia_ang_all_novid_2019-06/A/H%C4%93afodtramet
ANG
http://library.kiwix.org/wikipedia_as_all_novid_2019-06/A/%E0%A6%AC%E0%A7%87%E0%A6%9F%E0%A7%81%E0%A6%AA%E0%A6%BE%E0%A6%A4
AS
http://library.kiwix.org/wikipedia_glk_all_novid_2019-06/A/%DA%AF%D8%AA%CB%87_%D9%88%D9%84%DA%AF
GLK
http://library.kiwix.org/wikipedia_ln_all_novid_2019-05/A/Lok%C3%A1s%C3%A1_ya_libos%C3%B3
LN
http://library.kiwix.org/wiktionary_gv_all_novid_2019-06/A/Ard-ghuillag
GV
http://library.kiwix.org/wikipedia_av_all_novid_2019-06/A/%D0%91%D0%B5%D1%82%D3%80%D0%B5%D1%80%D0%B0%D0%B1_%D0%B3%D1%8C%D1%83%D0%BC%D0%B5%D1%80
AV
http://library.kiwix.org/wikibooks_yo_all_novid_2019-04/A/Oj%C3%BAew%C3%A9_%C3%80k%E1%BB%8D%CC%81k%E1%BB%8D%CC%81
YO
http://library.kiwix.org/wikipedia_haw_all_novid_2019-06/A/Ka_papa_kinohi
HAW
http://library.kiwix.org/wiktionary_la_all_novid_2019-05/A/Victionarium:Pagina_prima
LA
http://library.kiwix.org/wiktionary_gu_all_novid_2019-06/A/%E0%AA%AE%E0%AB%81%E0%AA%96%E0%AA%AA%E0%AB%83%E0%AA%B7%E0%AB%8D%E0%AA%A0
GU
http://library.kiwix.org/wikipedia_kab_all_novid_2019-05/A/Asebtar_amenzu
KAB
http://library.kiwix.org/wiktionary_csb_all_novid_2019-06/A/Prz%C3%A9dn%C3%B4_starna
CSB
http://library.kiwix.org/wikipedia_nds-nl_all_novid_2019-05/A/V%C3%B6%C3%A4rblad
NDS-NL
http://library.kiwix.org/wikipedia_jbo_all_novid_2019-05/A/uikipedi'as:ralju 
JBO
http://library.kiwix.org/wikipedia_li_all_novid_2019-05/A/Veurblaad
LI
http://library.kiwix.org/wikipedia_arz_all_novid_2019-06/A/%D8%A7%D9%84%D8%B5%D9%81%D8%AD%D9%87_%D8%A7%D9%84%D8%B1%D8%A6%D9%8A%D8%B3%D9%8A%D9%87
ARZ
http://library.kiwix.org/wikipedia_co_all_novid_2019-06/A/Pagina_maestra
CO
http://library.kiwix.org/wikipedia_mai_all_novid_2019-05/A/%E0%A4%B8%E0%A4%AE%E0%A5%8D%E0%A4%AE%E0%A5%81%E0%A4%96_%E0%A4%AA%E0%A4%A8%E0%A5%8D%E0%A4%A8%E0%A4%BE
MAI
http://library.kiwix.org/wiktionary_br_all_novid_2019-06/A/Wikeriadur:Degemer
MAI
http://library.kiwix.org/wikipedia_inh_all_novid_2019-05/A/%D0%9A%D0%B5%D1%80%D1%82%D1%82%D0%B5%D1%80%D0%B0_%D0%BE%D0%B0%D0%B3%D3%80%D1%83%D0%B2
INH
http://library.kiwix.org/wikipedia_sgs_all_novid_2019-06/A/P%C4%97rms_poslapis
SGS
http://library.kiwix.org/wiktionary_co_all_novid_2019-06/A/Pagina_maestra
CO
http://library.kiwix.org/wikipedia_kaa_all_novid_2019-05/A/Bas_bet
KAA
http://library.kiwix.org/wikem_en_all_novid_2019-05/A/Main_Page
EN
http://library.kiwix.org/wiktionary_kn_all_novid_2019-05/A/%E0%B2%AE%E0%B3%81%E0%B2%96%E0%B3%8D%E0%B2%AF_%E0%B2%AA%E0%B3%81%E0%B2%9F
KN
http://library.kiwix.org/wiktionary_cy_all_novid_2019-06/A/Hafan
CY
http://library.kiwix.org/wikipedia_fr_geography_novid_2019-06/A/index
FR
http://library.kiwix.org/wiktionary_mn_all_novid_2019-05/A/%D0%9D%D2%AF%D2%AF%D1%80_%D1%85%D1%83%D1%83%D0%B4%D0%B0%D1%81
MN
http://library.kiwix.org/wikipedia_roa-tara_all_novid_2019-05/A/Pagene_Prengep%C3%A1le
ROA-TARA
http://library.kiwix.org/wikipedia_ps_all_novid_2019-05/A/%D9%84%D9%88%D9%85%DA%93%DB%8C_%D9%85%D8%AE
PS
http://library.kiwix.org/wikipedia_nov_all_novid_2019-05/A/Chefi_pagine
NOV
http://library.kiwix.org/wikipedia_ff_all_novid_2019-06/A/Hello_ja%C9%93%C9%93orgo
FF
http://library.kiwix.org/wiktionary_gl_all_novid_2019-06/A/Wiktionary:P%C3%A1xina_principal
GL
http://library.kiwix.org/wikipedia_km_all_novid_2019-05/A/%E1%9E%91%E1%9F%86%E1%9E%96%E1%9F%90%E1%9E%9A%E1%9E%8A%E1%9E%BE%E1%9E%98
KM
http://library.kiwix.org/wikipedia_chr_all_novid_2019-06/A/%E1%8E%A4%E1%8E%B5%E1%8E%AE%E1%8E%B5%E1%8F%8D%E1%8F%97
CHR
http://library.kiwix.org/wikipedia_fj_all_novid_2019-06/A/Tabana_levu
FJ
http://library.kiwix.org/wikipedia_mh_all_nopic_2019-04/A/Main_Page
MH
http://library.kiwix.org/wikipedia_mdf_all_novid_2019-05/A/%D0%9F%D1%80%D1%8F_%D0%BB%D0%BE%D0%BF%D0%B0
MDF
http://library.kiwix.org/wikipedia_bpy_all_novid_2019-06/A/%E0%A6%AA%E0%A6%AF%E0%A6%BC%E0%A6%B2%E0%A6%BE_%E0%A6%AA%E0%A6%BE%E0%A6%A4%E0%A6%BE
BPY
http://library.kiwix.org/wikipedia_lez_all_novid_2019-05/A/%D0%9A%D1%8C%D0%B8%D0%BB%D0%B8%D0%BD_%D1%87%D1%87%D0%B8%D0%BD
LEZ
http://library.kiwix.org/wikipedia_na_all_novid_2019-05/A/Bwiema_peij
NA
http://library.kiwix.org/wiktionary_fi_all_novid_2019-06/A/Wikisanakirja:Etusivu
FI
http://library.kiwix.org/wiktionary_ar_all_novid_2019-06/A/%D8%A7%D9%84%D8%B5%D9%81%D8%AD%D8%A9_%D8%A7%D9%84%D8%B1%D8%A6%D9%8A%D8%B3%D9%8A%D8%A9
AR
http://library.kiwix.org/wiktionary_nds_all_novid_2019-05/A/Wiktionary:H%C3%B6%C3%B6ftsiet
NDS
http://library.kiwix.org/wiktionary_ca_all_novid_2019-06/A/Viccionari:Portada
CA
http://library.kiwix.org/wiktionary_mr_all_novid_2019-05/A/%E0%A4%AE%E0%A5%81%E0%A4%96%E0%A4%AA%E0%A5%83%E0%A4%B7%E0%A5%8D%E0%A4%A0
MR
http://library.kiwix.org/wikipedia_vro_all_novid_2019-06/A/P%C3%A4%C3%A4leht
VRO
http://library.kiwix.org/wikipedia_gan_all_novid_2019-06/A/%E5%B0%81%E9%9D%A2
GAN
http://library.kiwix.org/wikipedia_my_all_novid_2019-05/A/%E1%80%97%E1%80%9F%E1%80%AD%E1%80%AF%E1%80%85%E1%80%AC%E1%80%99%E1%80%BB%E1%80%80%E1%80%BA%E1%80%94%E1%80%BE%E1%80%AC
MY
http://library.kiwix.org/wikipedia_hsb_all_novid_2019-06/A/H%C5%82owna_strona
HSB
http://library.kiwix.org/wikipedia_fo_all_novid_2019-06/A/Fors%C3%AD%C3%B0a
FO
http://library.kiwix.org/wikipedia_lo_all_novid_2019-05/A/%E0%BB%9C%E0%BB%89%E0%BA%B2%E0%BA%AB%E0%BA%BC%E0%BA%B1%E0%BA%81
LO
http://library.kiwix.org/wiktionary_sv_all_novid_2019-05/A/Wiktionary:Huvudsida
SV
http://library.kiwix.org/wikipedia_nap_all_novid_2019-05/A/Paggena_prencepale
NAP
http://library.kiwix.org/westeros_en_all_2018-10/A/Main_Page.html
EN
http://library.kiwix.org/wiktionary_bs_all_novid_2019-06/A/Po%C4%8Detna_strana
BS
http://library.kiwix.org/wikipedia_hak_all_novid_2019-06/A/Th%C3%A8u-Ya%CC%8Dp
HAK
http://library.kiwix.org/wikipedia_cu_all_novid_2019-06/A/%D0%93%D0%BB%D0%B0%D0%B2%D1%8C%D0%BD%D0%B0_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0
CU

**Comment by kelson42** [comment]
@schlagkiwix Thank you for reporting this. We have really many scenarios which can explain why we are missing pictures. This is one of the reason this ticket is not super helfpul for us. The startegy is to fix the problems already known and improve the Q&A automated process to identify new problems. I will keep this ticket a bit open, but I guess it will be closed without much additional work here.

**Comment by Jaifroid** [comment]
I'm not sure whether this is a new issue, but I have noticed a large number of missing images -- including main images (top image on a page) -- in `wikipedia_en_medicine_maxi_2020_03.zim`. A good example of this is the article "Heart failure"., or "Ovarian cancer" or "2020 coronavirus pandemic in Spain".

**Comment by kelson42** [comment]
@Jaifroid Thank you for reporting new problems. The problem here is that we have many reasons to have missing pictures. Actually, it seems that we have detected a new reasons a few days ago. Therefore, for the moment, we fix the clearly identified problems, and then we might tackle this one.

**Comment by kelson42** [comment]
@schlagkiwix @Popolechien @Jaifroid I have tested the few first reported URLs with missing images. They are all OK now. Las WikiMed ZIM file seems OK as well, see http://library.kiwix.org/wikipedia_en_medicine_maxi_2020-04/A/Ovarian_cancer.

It looks like the problems we had at that time have been fixed or simply did occur during last run. I can not explain it better but many things have been done to improve the robustness of the image retrieval in the last 6 months.

We are currently improving/build/polishing our ZIM QA automatic system within the Zimfarm. I'm confident this should really start to work fine during the summer. It will then be able to catch all ZIM files with a massive missing images problem. In the meantime I really encourage you to continue to report problems here.

**Comment by Wikinaut** [comment]
I noticed the issue with
* wikipedia_en_all_maxi_2018-10.zim (the biggest file)

and articles:
* Prince (musician)
* Apollo 11
* Apollo 13

**Comment by Jaifroid** [comment]
@kelson42 Just to report that the very recent `wikivoyage_en_all_maxi_2020-05` has quite a few missing images, e.g. the landing page has its main image missing, and I noticed also the newish article on "Self-isolation after travel" (see screenshotss below). More generally, I notice that the size of the May ZIM is 786MB, whereas the size of the March ZIM was 810MB, implying that we have lost some 24MB (probably mostly images). 

![image](https://user-images.githubusercontent.com/4304337/82186833-5a683b80-98e3-11ea-9996-d053c5b14f73.png)


![image](https://user-images.githubusercontent.com/4304337/82186878-723fbf80-98e3-11ea-97b8-b2bba0e1736f.png)

**Comment by kelson42** [comment]
@bakshiutkarsha What is the root cause of this last report by @Jaifroid ?

**Comment by bakshiutkarsha** [comment]
> @bakshiutkarsha What is the root cause of this last report by @Jaifroid ?

I am checking the issue, will report back as soon as I find something.

**Comment by bakshiutkarsha** [comment]
These are my findings, after going through the logs:
1. The main page images mentioned in this ticket are going through this process:
First Time: Find Cache download --> Downloading --->  Caching response
Second Time: Find Cache download ---> Download cache hit
There can be two things that can go wrong here:

- Uploading of image is not done correctly
- Caching is not written correctly.

I tried with both the scenarios on the local and they work fine. So, the only thing left is to check in the production bucket that the image was uploaded correctly or not and I will try to get access for that.

2. Most of the images are failed due to `404: Not Found` error. I verified some of them by opening in browser and I got the same error. Listing some examples here:

https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/AfghanVisa.jpg/300px-AfghanVisa.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/WilmingtonMA-seal.png/220px-WilmingtonMA-seal.png
https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Muddy_Waters_exhibit_at_the_Delta_Blues_Museum.jpg/220px-Muddy_Waters_exhibit_at_the_Delta_Blues_Museum.jpg

**Comment by kelson42** [comment]
Everything I have tested (but I don't have tested all the links) have the pictures. We deal here with sporadic problems. The introduction of a stricter Q&A at ZIM level will help to narrow down the problem. For the moment, I believe that most of the problems around pictures have been fixed. Closting this ticket.
