### ISSUE TITLE
Is python required for node.js?

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#101]
In line 27 of [Dockerfile](https://github.com/openzim/mwoffliner/blob/master/docker/Dockerfile#L27), it is installing python in node.js installation section. Is python required for using node.js? If not, we should remove it.

**Comment by kelson42** [comment]
strange, have you try to build the image without it please?

**Comment by fattredd** [comment]
Yes. Python 2.6 or 2.7 is required for Node's build tools.
https://github.com/nodejs/node/wiki/Installation#building-prerequisites

**Comment by kelson42** [comment]
@fattredd thx
