### ISSUE TITLE
Closed wikis need to be removed

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1010]
The following wikis have been closed and should be removed from our lists:

http://library.kiwix.org/wikibooks_ch_all_nopic_2019-04/A/Fanhaluman
CH
http://library.kiwix.org/wikibooks_mn_all_nopic_2019-04/A/%D0%9D%D2%AF%D2%AF%D1%80_%D1%85%D1%83%D1%83%D0%B4%D0%B0%D1%81
MN
http://library.kiwix.org/wikibooks_ch_all_novid_2019-04/A/Fanhaluman
CH
http://library.kiwix.org/wikibooks_tk_all_nopic_2019-04/A/Ba%C5%9F_Sahypa
TK
http://library.kiwix.org/wikibooks_aa_all_nopic_2014-11/A/Main_Page.html
AA
http://library.kiwix.org/wikibooks_mn_all_novid_2019-04/A/%D0%9D%D2%AF%D2%AF%D1%80_%D1%85%D1%83%D1%83%D0%B4%D0%B0%D1%81
MN
http://library.kiwix.org/wikiquote_gsw_all_nopic_2014-11/A/Houptsyte.html
GSW
http://library.kiwix.org/wikibooks_xh_all_novid_2019-04/A/Iphepha_Elingundoqo
XH
http://library.kiwix.org/wikibooks_wa_all_nopic_2019-04/A/Mwaisse_p%C3%A5dje
WA
http://library.kiwix.org/wikibooks_lb_all_nopic_2019-04/A/Haapts%C3%A4it
LB
http://library.kiwix.org/wikibooks_zu_all_novid_2019-04/A/Ikhasi_Elikhulu
ZU
http://library.kiwix.org/wiktionary_om_all_novid_2019-04/A/Fuula_Dura
OM
http://library.kiwix.org/wikibooks_lb_all_novid_2019-04/A/Haapts%C3%A4it
LB
http://library.kiwix.org/wikibooks_sw_all_novid_2019-04/A/Mwanzo
SW
http://library.kiwix.org/wiktionary_za_all_novid_2019-03/A/Yiebdaeuz
ZA
http://library.kiwix.org/wikiquote_tt_all_novid_2019-04/A/%D0%91%D0%B0%D1%88_%D0%B1%D0%B8%D1%82
TT
http://library.kiwix.org/wikipedia_rn_all_nopic_2019-04/A/Main_Page
RN
http://library.kiwix.org/wikibooks_ug_all_nopic_2019-04/A/%D8%A8%D8%A7%D8%B4_%D8%A8%DB%95%D8%AA
UG
http://library.kiwix.org/wikibooks_zu_all_nopic_2019-04/A/Ikhasi_Elikhulu
ZU
http://library.kiwix.org/wikibooks_rm_all_novid_2019-04/A/Pagina_principala
RM
http://library.kiwix.org/wikibooks_xh_all_nopic_2019-04/A/Iphepha_Elingundoqo
XH
http://library.kiwix.org/wiktionary_om_all_nopic_2019-04/A/Fuula_Dura
OM
http://library.kiwix.org/wikibooks_tk_all_novid_2019-04/A/Ba%C5%9F_Sahypa
TK
http://library.kiwix.org/wikibooks_rm_all_nopic_2019-04/A/Pagina_principala
RM
http://library.kiwix.org/wikibooks_ug_all_novid_2019-04/A/%D8%A8%D8%A7%D8%B4_%D8%A8%DB%95%D8%AA
UG
http://library.kiwix.org/wikibooks_yo_all_nopic_2019-04/A/Oj%C3%BAew%C3%A9_%C3%80k%E1%BB%8D%CC%81k%E1%BB%8D%CC%81
YO

**Comment by kelson42** [comment]
@Popolechien Why removing them? They are not interesting?
