### ISSUE TITLE
Docker run command in README not working

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#102]
From docker/README.md, the way to directly run mwoffliner without docker-compose is as follows:
```
docker run --link=redis:redis --name=mwoffliner mwoffliner \
       mwoffliner --redis="redis://redis" --verbose --mwUrl=https://en.wikipedia.org/ --adminEmail=foo@bar.net
```
But this is not working!

## Problem 1:  `mwoffliner` is not the correct image name
When directly run the command above, the following error shows up:
```
docker: Error response from daemon: repository mwoffliner not found: does not exist or no pull access.
```
The correct name should be `openzim/mwoffliner`

## Problem 2: Error when running container
After replacing image name to `openzim/mwoffliner`, the following error is produced:
```
module.js:471
    throw err;
    ^

Error: Cannot find module '/mwoffliner'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
```

## Why can't we just use ENTRYPOINT?
Why not replacing:
```
# Boot commands
COPY .custom-bashrc /root/
CMD mwoffliner; bash --init-file /root/.custom-bashrc
```
with:
```
ENTRYPOINT ["mwoffliner"]
```

To quote Dockerfile reference:
> If you would like your container to run the same executable every time, then you should consider using ENTRYPOINT in combination with CMD. See ENTRYPOINT.
Which I do believe is our case, since we never seem to run commands other than `mwoffliner` in this container

If we use ENTRYPOINT, the command to run mwoffliner directly would look like this:
```
docker run --link=REDIS_CONTAINER_NAME:redis openzim/mwoffliner --redis="redis://redis" --mwUrl=https://en.wikipedia.org/ --adminEmail=foo@bar.net --verbose
```

**Comment by kelson42** [comment]
Yes, for problem1

For problem2, I suspect the image on Docker hub is not updated, do you still have the problem if you build mwofflienr from the Dockerfile?

For problem3, I want the image to be runnable both with an interactive shell and non-interactively, that's why I do that way (custom bash config and CMD).

**Comment by automactic** [comment]
For problem2, I no longer have problem after I build them locally. But why is docker hub version not working?

For problem3, why does it need to be run interactively? It's not like people need to perform additional task before or after `mwoffliner`. If `mwoffliner` is supposed to be used as the one and only command in this container, we should use `ENTRYPOINT`. Plus, when run interactively under current dockerfile configuration, user will see help of `mwoffliner`, then `Missing required arguments: mwUrl, adminEmail`, then shell. This is likely to be confusing to user who has no previously knowledge of mwoffliner project, because it seems like something is wrong.

**Comment by kelson42** [comment]
@automactic I have rebuild the Docker hub image, hope problem2 disappeared there too.

For the problem3, this is a feature requirement on my side: I want to have the interactive mode working properly. But agree with your remark about the error message, will fix it https://github.com/openzim/mwoffliner/issues/106.

May I close this ticket? Can you deal with the mwoffliner image now?

**Comment by automactic** [comment]
it works.
