### ISSUE TITLE
Set proper page title to selection welcome page

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1022]
It is currently `<title></title>`, it should be the title of the ZIM file.

**Comment by bakshiutkarsha** [comment]
@kelson42  I confirmed that title is not empty for the welcome page, eg. In bm.wikipedia.org it is taking "Nyɛ fɔlɔ" as the title, which seems to be default heading on the page.  

1. Do you want this title to be replaced with "wikipedia_bm_all_xxxx-xx" ?
2. Do we have any particular wiki for which the title set is empty?

**Comment by kelson42** [comment]
@bakshiutkarsha You confirm that this is empty? or you confirm this is not empty? Like written in the title, this happens only with selection (so using `--articleList`).

**Comment by bakshiutkarsha** [comment]
@kelson42 Yes I am able to confirm that it is empty with using "--articleList" param. I have a query regarding this, if the customZimTitle is not given then what should be the title? Or do we always take customZimTitle with articleList param?

**Comment by kelson42** [comment]
@bakshiutkarsha I don't have written it should be the customZimTitle, I have written it should be the title of the ZIM.
