### ISSUE TITLE
MWoffliner does not scrap articles with question mark at end of title

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1024]
See for instance [Have I been pwned?](http://library.kiwix.org/wikipedia_en_all_maxi_2018-10/I/Have_I_Been_Pwned%3F.html) or [Que faire?](http://library.kiwix.org/wikipedia_fr_all_maxi_2019-09/A/Que_faire_?)
The both appear in their respective indexes, though, and the error is seemingly limited to titles with a question mark at the end: [Saint-Louis du Ha! Ha!](http://library.kiwix.org/wikipedia_fr_all_maxi_2019-09/A/Saint-Louis-du-Ha!_Ha!) is ok, as well as [...and then there were three...](http://library.kiwix.org/wikipedia_en_all_maxi_2018-10/A/...And_Then_There_Were_Three....html)

**Comment by trevyn** [comment]
FWIW, "Have I been pwned?" exists and is readable in wikipedia_en_all_maxi_2018-10 on Kiwix for iOS v1.10. Perhaps a problem with the web reader?

**Comment by Popolechien** [comment]
@trevyn I suspect the regression is posterior to 2018-10

**Comment by bakshiutkarsha** [comment]
@Popolechien I am able to scrape "Have I been pwned?" article successfully. However there is a problem with "Que faire ?" article because of the extra space before question mark.

**Comment by Popolechien** [comment]
How about `Avanti! (film)` ?

**Comment by kelson42** [comment]
@bakshiutkarsha We have now 3 examples with question marks. It looks like a few works and other don't. If you agree 3 things need to be done:
* Understand the problem
* Explain in a comment the problem and the possible solution
* Fix it and create corresponding automated test.

Does that make sense?

**Comment by bakshiutkarsha** [comment]
> How about `Avanti! (film)` ?

Yes, this too is also successful.

**Comment by bakshiutkarsha** [comment]
> @bakshiutkarsha We have now 3 examples with question marks. It looks like a few works and other don't. If you agree 3 things need to be done:
> 
> * Understand the problem
> * Explain in a comment the problem and the possible solution
> * Fix it and create corresponding automated test.
> 
> Does that make sense?

Yes.
