### ISSUE TITLE
Some images not exported in english zim

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#103]
At least one reproducible (2 users on 2 machines) instance at Black Forest.
![exportpb](https://user-images.githubusercontent.com/21675885/28742831-bbdea67c-743a-11e7-9a83-0eed4efa9ca2.png)

**Comment by kelson42** [comment]
This is a really old ticket, not sure anymore what we should do with it as MWoffliner as really evolved. That said we still face this kind of problem, see #724. I will close this ticket and a new one should be reopen if this still occur.
