### ISSUE TITLE
lzma-error 5: LZMA_MEM_ERROR - throwing instance of 'zim::writer::LzmaError'

### ISSUE THREAD

**Issue by danielboven** [openzim/mwoffliner#1032]
I have been running `mwoffliner` for around a day on a PC to scrape [en.wiktionary.org](https://en.wiktionary.org/) myself. This has been working great until I just got an error and the whole script failed. 

```
[log] [2020-02-15T09:52:47.630Z] Worker [2] Processing batch of article ids [["buttercup_anemones","+8 more +","atkeliautumėte"]]
terminate called after throwing an instance of 'zim::writer::LzmaError'
what(): lzma-error 5: LZMA_MEM_ERROR
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! mwoffliner@1.9.14 start: `ts-node ./src/cli.ts "--mwUrl=https://en.wiktionary.org/" "--adminEmail=xxxxxxxxx@outlook.com" "--outputDirectory=/home/daan/Documents/zim/13-02-2020" "--redis=redis://127.0.0.1:6379"`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the mwoffliner@1.9.14 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/daan/.npm/_logs/2020-02-15T09_52_48_883Z-debug.log
```
Here you can find the npm debug log:
[debug_log error.txt](https://github.com/openzim/mwoffliner/files/4208406/debug_log.error.txt)

I'm running the script on a Ubuntu Server, 18.04 LTS with 3GB of RAM.
What can be the cause of this error? Could it perhaps be a lack of memory?

**Comment by kelson42** [comment]
@danielboven Pretty sure, you don't have enough memory. If you look at our recipe, we have configured 5GB https://farm.openzim.org/recipes/wiktionary_en
