### ISSUE TITLE
enwp landing page is incorrect

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#104]
The file opens at !!! instead of taking a copy of https://en.wikipedia.org/wiki/User:Stephane_(Kiwix)/Landing

**Comment by kelson42** [comment]
Should already be fixed in mwoffliner. To be checked in, to be published soon, new WPEN ZIM file.

**Comment by kelson42** [comment]
Fixed, at least in last wikipedia_en_all_novid_2017-08.zim
