### ISSUE TITLE
"Unable to parse href" kills process

### ISSUE THREAD

**Issue by darkenvy** [openzim/mwoffliner#105]
`Unable to parse href ./Vladimir_Lenin#CITEREFFischer1964`

Can we have an option to not kill the process and simply ignore the article?

`sudo node mwoffliner.js --mwUrl=https://en.wikipedia.org/ --adminEmail darkenvy@protonmail.com --articleList selections/wiki_list.lst --cacheDirectory ~/cache/working --outputDirectory ~/cache/out --deflateTmpHtml ~/cache/tmp --filenamePrefix mwoffliner --withZimFullTextIndex --format "nopic,novid" --verbose`

**Comment by kelson42** [comment]
@darkenvy "mwoffliner.js" does not exist (anymore) in that repo.... not sure what you are doing, but you do not work with the last version of MWoffliner.

**Comment by darkenvy** [comment]
I went back to mwoffliner.js because I can get it to complete on small lists. Where I cannot on the container. Just having two 'attack vectors' :P

**Comment by kelson42** [comment]
OK, Then I will close that ticket. Please open an other one if you have an other problem with a recent/up2date version of mwoffliner.
