### ISSUE TITLE
Edutechwiki has not title at the top of its pages

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1058]
See for example http://library.kiwix.org/edutechwiki_fr_all_maxi_2020-03/A/Instrumentation

**Comment by danielkschneider** [comment]
If this can help (sorry I am not a developer: I maintain this wiki and do not modify anything in the code or the theme (that being said, only tiny little things if something breaks + MediaWiki:Common.css). But we do use extensions that wikipedia does not have. https://edutechwiki.unige.ch/fr/Sp%C3%A9cial:Version - greetings and thanks !

**Comment by kelson42** [comment]
@danielkschneider Thank you for your comment. I'm convince this is a bug on our side, even if this is the first time I see it at all. In an attempt to keep a good overview of problems we have with Edutech Wiki scraping, I have created an "edutech" tag. Feel free to tag any already existing bug using it, if you are impacted as well.

**Comment by midik** [comment]
@danielkschneider would you please consider to upgrade MediaWiki to the latest version? That will allow us to use REST API introduced in v.1.35 and will fix this issue.

**Comment by kelson42** [comment]
@midik You mean Mediawiki or Parsoid?

**Comment by midik** [comment]
@kelson42 
I mean Mediawiki. My bad, REST API introduced in 1.34 not 1.35 that I said above. 
https://www.mediawiki.org/wiki/API:REST_API#Enabling_the_REST_API_on_your_wiki

**Comment by kelson42** [comment]
For the record, the problem is the following. With edutechwiki, the only way to get the HTML is the API `action=visualeditor`. This is not unusual, in fact this the normal way to do for non Wikimedia wikis which have Parsoid/VisualEditor installed. The problem is that this approach does not deliver the `<h1>` DOM not which at the top of each page contains the title of an article. This makes sense because this is not editable, so the VisualEditor does not need it. We face here an old bug in MWoffliner and which impact a lot of ZIM files.

Three solutions can be implemented:
1 - We stop using this, and we use a local Parsoid instead. This has proven to work but use a lot of CPU and can be fragile.
2 - We retrieve the information about the title do display using the Mediawiki API and insert manually a `<h1>` node. See https://www.mediawiki.org/wiki/API:Info for example.
3 - We insert the `<h1>` node an compute an approximation of the title based on the articleid (just replacing the underscores with spaces should be good enough).

I think we should really try to do the (2) smartly (to avoid overhead for all other wikis which don't need this)... in particular Wikipedia.

**Comment by danielkschneider** [comment]
> 
> 
> @danielkschneider would you please consider to upgrade MediaWiki to the latest version? That will allow us to use REST API introduced in v.1.35 and will fix this issue.

Hi, unfortunately this is a bit difficult right now. An upgrade sometimes takes 1 day and sometimes two weeks because of some extensions that are critical for use, e.g. the visual editor, the PDF book generator and semantic mediawiki. Two or these are nasty pieces of work for non professional wiki administrators. We certainly will upgrade in the summer. Maybe in 2-3 weeks we can do it but would have to start fresh in a new virtual machine. I usually just upgraded the life system, but that's too disruptive in the middle of the semester.

**Comment by kelson42** [comment]
@danielkschneider Thank you for the feedback. I understand and confirm the hassle of doing all the maintenance work by yourself. We will manage anyway to get this bug fixed. Thank you for your patience.

**Comment by midik** [comment]
@kelson42 I think this has fixed with #1089.
(The solution was to pick the betters from solution 2 and 3 - so that the title is natural while we don't need for an extra request).

**Comment by kelson42** [comment]
@midik Merging the corresponding PR will close automatically the ticket. We should avoid to close manually tickets if there is a PR fixing the problem.

**Comment by midik** [comment]
@kelson42 there's no PRs linked here
![image](https://user-images.githubusercontent.com/6795530/80730396-35697f80-8b12-11ea-98e8-34e369913fbd.png)

**Comment by midik** [comment]
however, you're right, I should have linked it.

**Comment by kelson42** [comment]
@midik sorry, things got mixed a bit by me. But indeed, proper tagging in PR helps to keep clarity :)

**Comment by danielkschneider** [comment]
Thanx a lot guys for looking into this :)

I also have a little question:  Could you please give me the precise API call you use to retrieve the pages ? I would like to retrieve manually some pages in order to improve the kiwix pages. Thanks.

**Comment by kelson42** [comment]
@danielkschneider The two recipes to make the Edutech FR/EN scrapes are available at https://farm.openzim.org/recipes/edutech_fr and https://farm.openzim.org/recipes/edutech_en. You should be able to get all the information needed and the full log of each scrape (so more details about what happens exactly).

What seems important to me is that if something is not rendered properly it gets reported here in a bug report. I thought we mostly had bugs left around category mgmt, but was a bit afraid to detect two other bugs around "standard" URL rewritting (we will fix them soon as well). See https://github.com/openzim/mwoffliner/labels/edutech

**Comment by danielkschneider** [comment]
Thanx that helps. If I find a bug I will do a bug report.

**Comment by danielkschneider** [comment]
(a bit late, sorry) thanx much for fixing the title problem !
