### ISSUE TITLE
Footer links are not always OK

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1059]
See the bad link https://edutechwiki.unige.ch/fmediawiki/index.phpInstrumentation?oldid=5758 in http://library.kiwix.org/edutechwiki_fr_all_maxi_2020-03/A/Instrumentation for example.

**Comment by kelson42** [comment]
@midik The problem here I believe is that the values given as argument are not normalized (with `/` at the end or without ... or withy `?`). We should secure the form of these paths/URLs given as argument.

**Comment by midik** [comment]
@kelson42 I've found this problem while working on #1058. The cause is that we don't handle urls and paths properly yet. Instead, we just concatenate them as strings everywhere. I've made some steps in the right direction while fixing #1058 and I'm going to clean up that as a part of this issue.
