### ISSUE TITLE
Saving favicon fails without imagemagick installed

### ISSUE THREAD

**Issue by midik** [openzim/mwoffliner#1069]
Saving `favicon` without `imagemagick` installed fails with non-relevant error:

![image](https://user-images.githubusercontent.com/6795530/78693880-849e0500-7904-11ea-877c-42d8b11efe2c.png)

I think would be great to either add `imagemagick` to Readme/Prerequisites or/and make the error meaningful.

**Comment by kelson42** [comment]
Almost a duplicate of #990.
