### ISSUE TITLE
S3 failure should display some details

### ISSUE THREAD

**Issue by rgaudin** [openzim/mwoffliner#1072]
For debugging purpose, I think it would be good to have a few details printed to the log when the process is halted due to an S3 failure:

* endpoint being used
* bucket being used
* public IP of user.

Given the nature of this I think we can simply use an external service like https://ipinfo.io/ip for that. I'll make sure these info are printed out by all the scrapers in case of S3 failure.

**Comment by kelson42** [comment]
@rgaudin Getting public IP might be difficult if S3 does not give it itself.

**Comment by rgaudin** [comment]
what do you mean? We just want to log the public IP of the worker so that we can check if it was not in our white-list.
Querying https://ipinfo.io/ip returns your public IP and that should be enough for this

**Comment by kelson42** [comment]
We should use https://www.npmjs.com/package/ipinfo

**Comment by midik** [comment]
I would recommend this one: https://www.npmjs.com/package/public-ip because:
- it supports fallback and not to rely to single service
- doesn't require to remember callbacks :)
- has much more weekly downloads, stars, and contributors.

**Comment by kelson42** [comment]
@bakshiutkarsha Could you please implement this quickly? Sounds trivial and would be helfpul.
