### ISSUE TITLE
Unresolved wiki templates appearing on maths pages

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#1074]
Open `wikipedia_en_mathematics_maxi_2020-04.zim` in a reader and search for `1`. Compare screenshots of what is shown in the reader (top) with what is shown on Wikipedia (bottom) - look at the panel on right.  Same happens with all the numbers that have pages.

![image](https://user-images.githubusercontent.com/4304337/79073696-e92fda00-7cdf-11ea-945f-589388eb8229.png)

![image](https://user-images.githubusercontent.com/4304337/79073753-2c8a4880-7ce0-11ea-911e-d07d10f7bb11.png)

**Comment by kelson42** [comment]
@Jaifroid Thank you for the report, quite clearly a bug which has to be reported upstream IMO.

**Comment by kelson42** [comment]
The problem is still there in latest version

**Comment by kelson42** [comment]
It has been fixed upstream, see https://library.kiwix.org/viewer#wikipedia_en_mathematics_maxi_2023-03/A/1
