### ISSUE TITLE
URLs in the pages reappend parent page to the link in some domains

### ISSUE THREAD

**Issue by trappedinspacetime** [openzim/mwoffliner#1077]
I used the following liner to create a zim file:

        mwoffliner --mwUrl=https://tr.wikibooks.org customMainPage="Anasayfa" --adminEmail=contact@kiwix.org --outputDirectory=vikikitap

When I open it in my local server it loads fine and open pages when I
click the links but it fails to redirect the parent page. It appends
parent page to current page link.
For example :
In the page 
`http://localhost:2023/wikibooks_tr_all_2020-04/A/wikibooks_tr_all_2020-04/A/Merkezi_Sinir_Sistemi_Tümörleri`

When I click the url < Merkezi Sinir Sistemi Tümörleri
it redirects the link to :

`http://localhost:2023/wikibooks_tr_all_2020-04/A/wikibooks_tr_all_2020-04/A/Merkezi_Sinir_Sistemi_Tümörleri/Merkezi_Sinir_Sistemi_Tümörleri`

pay attention to reappended page.
I get the below error message:

     Not Found

     The requested URL
     "/wikibooks_tr_all_2020-04/A/Merkezi_Sinir_Sistemi_Tümörleri/Merkezi_Sinir_Sistemi_Tümörleri"
     was not found on this server.

I also checked the zim archive of the same wikibooks in
farm.openzim.org, it's the same error.

**Comment by kelson42** [comment]
@trappedinspacetime Thank you for your bug report but it seems I can not reproduce the problem with our online demo which has been done in March. See http://library.kiwix.org/wikibooks_tr_all_maxi/A/Merkezi_Sinir_Sistemi_T%C3%BCm%C3%B6rleri. Do your ZIM/kiwix-serve behave differently or I have misunderstood something?

**Comment by trappedinspacetime** [comment]
@kelson42 Thank you for responding. I tried to find version of `kiwix-serve` but it has no option to print the version. 
I'll build latest version of it and let you know the result.

**Comment by kelson42** [comment]
@trappedinspacetime Thx, use `kiwix-serve --version`. Last version is downloadable at https://www.kiwix.org/en/downloads/kiwix-serve/.

**Comment by trappedinspacetime** [comment]
@kelson42 In my `kiwix-serve` there was no `--version` switch. Anyway, I built latest version of it and tested it again.
I used the `zim` file in this [link](https://ftp.fau.de/kiwix/zim/wikibooks/wikibooks_tr_all_maxi_2020-04.zim)

       kiwix-serve --version
       3.1.0

       kiwix-serve --port=2023 wikibooks_tr_all_maxi_2020-04.zim

The result is the same plus `kiwix-serve` fails to render favicon of `zim` file in home.
![Ekran Görüntüsü - 2020-04-25 18-46-25](https://user-images.githubusercontent.com/1314821/80284167-7e41c280-8725-11ea-951c-e7ff53a9b6a9.png)

**Comment by kelson42** [comment]
@trappedinspacetime Please open one ticket per problem, the favicon problem is probably because of a bug in library Mustache 4.0 (fixed in 4.1)

**Comment by kelson42** [comment]
@trappedinspacetime For the rest, please tel me exactly your HTTP request and the part of the HTML output you get which is wrong because wihtout being able to understand and/or reproduce the problem, I can not go further.

**Comment by kelson42** [comment]
We can perfectly see here that the link `Merkezi_Sinir_Sistemi_Tümörleri/Merkezi_Sinir_Sistemi_Tümörleri` is not delivered in that page:

```
$ curl --silent https://library.kiwix.org/wikibooks_tr_all_maxi_2020-04/A/Merkezi_Sinir_Sistemi_T%C3%BCm%C3%B6rleri | grep "Merkezi_Sinir_Sistemi_Tümörleri/"
<p id="mwCA">Bu bir Wiki ve Türk Onkoloji Grubu Santral Sinir Sistemi Çalışma Grubu ortak projesidir. Bu proje açık kaynaklı ve ücretsiz ulaşılabilen bir kaynak kitaptır. Herkes (konuyla ilgisi olan) katkıda bulunmaya, içeriği geliştirmeye davetlidir. Gerek yazım hatalarını düzelten gerekse yeni bölümler ekleyen tüm yazarlara şimdiden teşekkür ediyoruz. <a href="Merkezi_Sinir_Sistemi_Tümörleri/Yazarlar_Listesi" title="Merkezi Sinir Sistemi Tümörleri/Yazarlar Listesi" id="mwCQ">Yazarlar</a></p>
<p><a href="Merkezi_Sinir_Sistemi_Tümörleri/Giriş" title="Merkezi Sinir Sistemi Tümörleri/Giriş">Giriş</a> - 
<a href="Merkezi_Sinir_Sistemi_Tümörleri/Glial_Tümörler" title="Merkezi Sinir Sistemi Tümörleri/Glial Tümörler">Glial Tümörler</a> - 
<a href="Merkezi_Sinir_Sistemi_Tümörleri/Primer_SSS_Lenfoması" title="Merkezi Sinir Sistemi Tümörleri/Primer SSS Lenfoması">Primer SSS Lenfoması</a> - 
<a href="Merkezi_Sinir_Sistemi_Tümörleri/Pineal_Gland_Tümörleri" title="Merkezi Sinir Sistemi Tümörleri/Pineal Gland Tümörleri">Pineal Gland Tümörleri</a> - 
<a href="Merkezi_Sinir_Sistemi_Tümörleri/Beyin_Metastazları" title="Merkezi Sinir Sistemi Tümörleri/Beyin Metastazları">Beyin Metastazları</a> - 
<a href="Merkezi_Sinir_Sistemi_Tümörleri/BOS_Tutulumu" title="Merkezi Sinir Sistemi Tümörleri/BOS Tutulumu">BOS tutulumu</a> - 
<a href="Merkezi_Sinir_Sistemi_Tümörleri/Diğer_Malign_SSS_Tümörleri" title="Merkezi Sinir Sistemi Tümörleri/Diğer Malign SSS Tümörleri">Diğer Malign SSS Tümörleri</a> - 
<a href="Merkezi_Sinir_Sistemi_Tümörleri/Meningioma" title="Merkezi Sinir Sistemi Tümörleri/Meningioma">Meningioma</a>
<a href="Merkezi_Sinir_Sistemi_Tümörleri/Akustik_Nöroma" title="Merkezi Sinir Sistemi Tümörleri/Akustik Nöroma">Akustik Nöroma (Vestibular Schwannoma)</a> - 
<a href="Merkezi_Sinir_Sistemi_Tümörleri/Hipofiz_Adenomu" title="Merkezi Sinir Sistemi Tümörleri/Hipofiz Adenomu">Hipofiz Adenomu</a> - 
<a href="Merkezi_Sinir_Sistemi_Tümörleri/Paraganglioma" title="Merkezi Sinir Sistemi Tümörleri/Paraganglioma">Paraganglioma</a> - 
<a href="Merkezi_Sinir_Sistemi_Tümörleri/Arteriyovenöz_Malformasyonlar" title="Merkezi Sinir Sistemi Tümörleri/Arteriyovenöz Malformasyonlar">Arteriyovenöz Malformasyonlar (AVM)</a> - 
<a href="Merkezi_Sinir_Sistemi_Tümörleri/Kavernöz_Malformasyonlar" title="Merkezi Sinir Sistemi Tümörleri/Kavernöz Malformasyonlar">Kavernöz Malformasyonlar</a> - 
<a href="Merkezi_Sinir_Sistemi_Tümörleri/Trigeminal_Nevralji" title="Merkezi Sinir Sistemi Tümörleri/Trigeminal Nevralji">Trigeminal Nevralji</a> - 
<a href="Merkezi_Sinir_Sistemi_Tümörleri/Sfenopalatine_Nevralji" title="Merkezi Sinir Sistemi Tümörleri/Sfenopalatine Nevralji">Sfenopalatine Nevralji</a> - 
<a href="Merkezi_Sinir_Sistemi_Tümörleri/Cluster_Tipi_Başağrısı" title="Merkezi Sinir Sistemi Tümörleri/Cluster Tipi Başağrısı">Cluster Tipi Başağrısı</a> - 
<a href="Merkezi_Sinir_Sistemi_Tümörleri/Kanser_Ağrısı" title="Merkezi Sinir Sistemi Tümörleri/Kanser Ağrısı">Kanser Ağrısı</a> - 
<a href="Merkezi_Sinir_Sistemi_Tümörleri/WHO_Sınıflaması" title="Merkezi Sinir Sistemi Tümörleri/WHO Sınıflaması">WHO Sınıflaması</a> - 
<a href="Merkezi_Sinir_Sistemi_Tümörleri/Yazarlar_Listesi" title="Merkezi Sinir Sistemi Tümörleri/Yazarlar Listesi">Yazarlar Listesi</a></p>
$ curl --silent https://library.kiwix.org/wikibooks_tr_all_maxi_2020-04/A/Merkezi_Sinir_Sistemi_T%C3%BCm%C3%B6rleri | grep "Merkezi_Sinir_Sistemi_Tümörleri/Merkezi_Sinir_Sistemi_Tümörleri/"
$
```

**Comment by trappedinspacetime** [comment]
Thank you for the tip for the `Mustache` library. I used the `4.1` version and it fixed the favicon problem.

I updated the dependent libraries such as `pugixml`, `libcurl`, `zlib`, and rebuilt `libzim`, kiwix-libs` and `kiwix-tools` the bug is still there.

I tried different browsers.

curl output is the same as yours:


    curl --silent http://localhost:2026/wikibooks_tr_all_maxi_2020-04/A/Merkezi_Sinir_Sistemi_T%C3%BCm%C3%B6rleri | grep "Merkezi_Sinir_Sistemi_Tümörleri/"
    <p id="mwCA">Bu bir Wiki ve Türk Onkoloji Grubu Santral Sinir Sistemi Çalışma Grubu ortak projesidir. Bu proje açık kaynaklı ve ücretsiz ulaşılabilen bir kaynak kitaptır. Herkes (konuyla ilgisi olan) katkıda bulunmaya, içeriği geliştirmeye davetlidir. Gerek yazım hatalarını düzelten gerekse yeni bölümler ekleyen tüm yazarlara şimdiden teşekkür ediyoruz. <a href="Merkezi_Sinir_Sistemi_Tümörleri/Yazarlar_Listesi" title="Merkezi Sinir Sistemi Tümörleri/Yazarlar Listesi" id="mwCQ">Yazarlar</a></p>
    <p><a href="Merkezi_Sinir_Sistemi_Tümörleri/Giriş" title="Merkezi Sinir Sistemi Tümörleri/Giriş">Giriş</a> - 
    <a href="Merkezi_Sinir_Sistemi_Tümörleri/Glial_Tümörler" title="Merkezi Sinir Sistemi Tümörleri/Glial Tümörler">Glial Tümörler</a> - 
    <a href="Merkezi_Sinir_Sistemi_Tümörleri/Primer_SSS_Lenfoması" title="Merkezi Sinir Sistemi Tümörleri/Primer SSS Lenfoması">Primer SSS Lenfoması</a> - 
    <a href="Merkezi_Sinir_Sistemi_Tümörleri/Pineal_Gland_Tümörleri" title="Merkezi Sinir Sistemi Tümörleri/Pineal Gland Tümörleri">Pineal Gland Tümörleri</a> - 
    <a href="Merkezi_Sinir_Sistemi_Tümörleri/Beyin_Metastazları" title="Merkezi Sinir Sistemi Tümörleri/Beyin Metastazları">Beyin Metastazları</a> - 
    <a href="Merkezi_Sinir_Sistemi_Tümörleri/BOS_Tutulumu" title="Merkezi Sinir Sistemi Tümörleri/BOS Tutulumu">BOS tutulumu</a> - 
    <a href="Merkezi_Sinir_Sistemi_Tümörleri/Diğer_Malign_SSS_Tümörleri" title="Merkezi Sinir Sistemi Tümörleri/Diğer Malign SSS Tümörleri">Diğer Malign SSS Tümörleri</a> - 
    <a href="Merkezi_Sinir_Sistemi_Tümörleri/Meningioma" title="Merkezi Sinir Sistemi Tümörleri/Meningioma">Meningioma</a>
    <a href="Merkezi_Sinir_Sistemi_Tümörleri/Akustik_Nöroma" title="Merkezi Sinir Sistemi Tümörleri/Akustik Nöroma">Akustik Nöroma (Vestibular Schwannoma)</a> - 
    <a href="Merkezi_Sinir_Sistemi_Tümörleri/Hipofiz_Adenomu" title="Merkezi Sinir Sistemi Tümörleri/Hipofiz Adenomu">Hipofiz Adenomu</a> - 
    <a href="Merkezi_Sinir_Sistemi_Tümörleri/Paraganglioma" title="Merkezi Sinir Sistemi Tümörleri/Paraganglioma">Paraganglioma</a> - 
    <a href="Merkezi_Sinir_Sistemi_Tümörleri/Arteriyovenöz_Malformasyonlar" title="Merkezi Sinir Sistemi Tümörleri/Arteriyovenöz Malformasyonlar">Arteriyovenöz Malformasyonlar (AVM)</a> - 
    <a href="Merkezi_Sinir_Sistemi_Tümörleri/Kavernöz_Malformasyonlar" title="Merkezi Sinir Sistemi Tümörleri/Kavernöz Malformasyonlar">Kavernöz Malformasyonlar</a> - 
    <a href="Merkezi_Sinir_Sistemi_Tümörleri/Trigeminal_Nevralji" title="Merkezi Sinir Sistemi Tümörleri/Trigeminal Nevralji">Trigeminal Nevralji</a> - 
    <a href="Merkezi_Sinir_Sistemi_Tümörleri/Sfenopalatine_Nevralji" title="Merkezi Sinir Sistemi Tümörleri/Sfenopalatine Nevralji">Sfenopalatine Nevralji</a> - 
    <a href="Merkezi_Sinir_Sistemi_Tümörleri/Cluster_Tipi_Başağrısı" title="Merkezi Sinir Sistemi Tümörleri/Cluster Tipi Başağrısı">Cluster Tipi Başağrısı</a> - 
    <a href="Merkezi_Sinir_Sistemi_Tümörleri/Kanser_Ağrısı" title="Merkezi Sinir Sistemi Tümörleri/Kanser Ağrısı">Kanser Ağrısı</a> - 
    <a href="Merkezi_Sinir_Sistemi_Tümörleri/WHO_Sınıflaması" title="Merkezi Sinir Sistemi Tümörleri/WHO Sınıflaması">WHO Sınıflaması</a> - 
    <a href="Merkezi_Sinir_Sistemi_Tümörleri/Yazarlar_Listesi" title="Merkezi Sinir Sistemi Tümörleri/Yazarlar Listesi">Yazarlar Listesi</a></p>

**Comment by trappedinspacetime** [comment]
Hover over link is also showing corrupted url 
In page `http://localhost:2026/wikibooks_tr_all_maxi_2020-04/A/Merkezi_Sinir_Sistemi_T%C3%BCm%C3%B6rleri/Merkezi_Sinir_Sistemi_T%C3%BCm%C3%B6rleri`
`< Merkezi Sinir Sistemi Tümörleri` points to
`http://localhost:2026/wikibooks_tr_all_maxi_2020-04/A/Merkezi_Sinir_Sistemi_T%C3%BCm%C3%B6rleri/Merkezi_Sinir_Sistemi_T%C3%BCm%C3%B6rleri`

**Comment by kelson42** [comment]
I will close the ticket as there an agreement that the served HTML is OK.
