### ISSUE TITLE
ZIM of https://wiki.archlinux.org/

### ISSUE THREAD

**Issue by fattredd** [openzim/mwoffliner#108]
Hello,

I'd like a Zim file made of https://wiki.archlinux.org/
The Arch Wiki is one of the largest linux wikis, and is used daily by thousands.

Thank you!

**Comment by kelson42** [comment]
Will give a try. If the Mediawiki is recent then it should be easy.

**Comment by fattredd** [comment]
Have you gotten a chance to check it out yet?

**Comment by kelson42** [comment]
A first version is here http://download.kiwix.org/zim/other/archlinux_en_all_2017-08.zim. A new version should be released each month.

**Comment by hashworks** [comment]
`A new version should be released each month` - since that didn't happen I tried it out myself. However I had some problems:

`mwoffliner --verbose --mwUrl "https://wiki.archlinux.org/" --mwWikiPath "/" --mwApiPath "/api.php" --adminEmail "mail@hashworks.net"`
https://fb.hash.works/ZEMa/

There are some errors while retrieving articles:
```
Downloading https://wiki.archlinux.org//api.php?action=visualeditor&format=json&paction=parse&page=Autofs&oldid=525497...
Error by retrieving article: Unrecognized value for parameter "action": visualeditor.
Getting (desktop) article from https://wiki.archlinux.org//api.php?action=visualeditor&format=json&paction=parse&page=APC_UPS&oldid=494104
```

This results in a `./tmp` directory of 196K in size.

Also ZIM file creation failes:
```
Building ZIM file /mnt/hotswap/MediaWiki/newArch/out/archlinux_en_all_2018-06.zim (zimwriterfs --welcome=index.htm --favicon=favicon.png --language=eng --welcome=Main_page.html --verbose  --tags="archlinux" --name="kiwix.archlinux_en_all" --redirects="/mnt/hotswap/MediaWiki/newArch/cac/archlinux_en/archlinux_en_all.redirects" --title="ArchWiki" --description="From ArchWiki" --creator="Archlinux" --publisher="Kiwix" "/mnt/hotswap/MediaWiki/newArch/tmp/archlinux_en_all_2018-06/" "/mnt/hotswap/MediaWiki/newArch/out/archlinux_en_all_2018-06.zim")...
RAID: kiwix.archlinux_en_all
zimwriterfs: unable to find welcome page at '/mnt/hotswap/MediaWiki/newArch/tmp/archlinux_en_all_2018-06/Main_page.html'. --welcome path/value must be relative to HTML_DIRECTORY.
Failed to build successfuly the ZIM file /mnt/hotswap/MediaWiki/newArch/out/archlinux_en_all_2018-06.zim (Error when executing zimwriterfs)
``` 

Any idea? zimwriterfs is v1.2 and mwoffliner is v1.4.1.

**Comment by kelson42** [comment]
@hashworks done
