### ISSUE TITLE
What does it take to get all labels in the target language?

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1088]
A user sent this screenshot asking that labels be translated to Chinese as much as the zim titles already are, but where/how would we do it? Is it in the zimfarm recipe or somewhere else?

![Capture d’écran 2020-04-27 à 11 02 29](https://user-images.githubusercontent.com/21675885/80354287-cde3d380-8876-11ea-8560-df1101fff119.png)

**Comment by kelson42** [comment]
"Kiwix" is the publisher and can not and should not be translated.

**Comment by kelson42** [comment]
"Wikipedia" comes from the tag I guess and might be translated. Someone to give more insight how this works?
