### ISSUE TITLE
Urls with `:` are not properly encoded

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1095]
In http://library.kiwix.org/edutechwiki_fr_all_maxi/A/Accueil, we have this link `<a href="Guidelines:Règles_d'édition" title="Guidelines:Règles d'édition"> règles d'édition</a>` which is a broken link, because the character `:` is not URL encoded... and interpreted as protocol scheme separator.

**Comment by bakshiutkarsha** [comment]
@kelson42 I highly doubt there is any problem with ":", I am able to scape the articles with ":", successfully. I tried with this article as well:
The Combat: Woman Pleading for the Vanquished.

If you just inspect and "open in new tab" from that href, the link is working perfectly its not broken:
http://library.kiwix.org/edutechwiki_fr_all_maxi/A/Guidelines:R%C3%A8gles_d'%C3%A9dition

But, when you will hover on that text on browser you will see "guidelines:Règles_d'édition" at the left corner of your screen(indicates the link)which starts from small "g", and that's the problem. It should have started from capital "G". I am trying to figure out the cause behind it.

**Comment by kelson42** [comment]
@bakshiutkarsha You are wrong here. On way to immediatly see is to replace `G` by `g` in the DOM and you still see then that the URL is still broken.

**Comment by bakshiutkarsha** [comment]
I don't think my comment was able to explain what I am trying to say. The href is correct in DOM, it is with capital G.
`g` is wrong anyways, so we don't have to replace it with `G`

**Comment by kelson42** [comment]
@bakshiutkarsha If the URL is correct how do you explain that it does not open the right article if we click on it?

**Comment by bakshiutkarsha** [comment]
<img width="827" alt="Screenshot 2020-05-07 at 3 01 45 AM" src="https://user-images.githubusercontent.com/13726478/81264403-56990700-900f-11ea-970f-8bcdde76880d.png">

WIth this screenshot, if you see on left corner, it highlights the link with small "g".

**Comment by kelson42** [comment]
@bakshiutkarsha This is not an explanation where is the problem, this is a screenshot. Do you try to tell me the browser is buggy?

**Comment by bakshiutkarsha** [comment]
This is the screenshot explains one possible reason of this problem.

As I mentioned in my previous comment, I am trying to figure out the cause of why it is happening(could be the buggy browser or something else), but I am pretty sure it isn't happening because of  ":"  not encoded.

**Comment by kelson42** [comment]
The only reason why a link can not be open is that the URL is wrong. If you encode the character `:` then the URL works.

**Comment by kelson42** [comment]
@bakshiutkarsha You should not use the hint as a debugging tool, this is just a visual hint for end user which play no role in the machinery to open a link. You have been sidetracked here. The reason which the `G` is lowercase is almost given in my bug report. The part before the `:` is interpreted as the protocol and the spec says that the protocol should be lowercased. I guess the browser just systematically lowercase the protocol to be more flexible and avoid problems.

**Comment by bakshiutkarsha** [comment]
> The only reason why a link can not be open is that the URL is wrong. If you encode the character `:` then the URL works.

Agreed, I tried with encoded ":", it worked.
Will do the changes in PR.
