### ISSUE TITLE
Missing gallery stylesheet causes incorrect display of media galleries 

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#110]
These ZIM files: 

`wikipedia_en_all_2016-12.zim` and
`wikipedia_es_all_2017-05.zim` (most likely other languages too) 

do not contain the `mediawiki.page.gallery.styles.css` stylesheet, which causes the rendering issue illustrated in the first screenshot below. Although these screenshots are taken from Kiwix JS, desktop Kiwix (exe) also shows the example article (Colombia) in the same way as the top screenshot, i.e. it does not render the gallery correctly. Therefore the problem is with the ZIM file. I understand that the mobile-first approach of the new ZIM files may no longer contain this issue, but @kelson42 asked me to report it here in any case.

Incorrectly rendered [article: "Colombia" from `wikipedia_en_all`]:

![image](https://user-images.githubusercontent.com/4304337/28287812-e79a249e-6b34-11e7-9c8e-35f83312a222.png)

Corrected:

![image](https://user-images.githubusercontent.com/4304337/28287864-136c7202-6b35-11e7-9804-c9065bbf1bd6.png)

**Comment by ISNIT0** [comment]
This seems to render correctly in the mobile view but break in the desktop view.

I think this may be related to #388

**Comment by Jaifroid** [comment]
@kelson42 Just to say that if you do go all mobile, I hope at least these would be fixed first: #164 , #182 and #110 (this issue), as they all seem to affect mobile style in particular.

**Comment by ISNIT0** [comment]
@Jaifroid I found this issue was not affecting mobile views, are you seeing something different?
