### ISSUE TITLE
"Logs for getting total articles" has a few problems

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1108]
They appear by running the E2E automated tests:

* <s>By running the scrape of WPEN, I can see
```
    [log] [2020-05-09T12:56:05.063Z] Got [394] articles from namespace [0]
    [log] [2020-05-09T12:56:05.541Z] Got [357] articles from namespace [0]
    [log] [2020-05-09T12:56:05.541Z] Total articles found by namespace 751
    [log] [2020-05-09T12:56:05.542Z] Total articles found in Redis  751
```
Why the two first lines give contradictory numbers? and the third one seems to be the sum or the two first ones? This is pretty unclear.</s>

* By running later the WPEN top 10 scrape, I can see:
```
    [log] [2020-05-09T12:56:25.938Z] Total articles found by namespace 751
    [log] [2020-05-09T12:56:25.938Z] Total articles found in Redis  10
```

`751` is the number from WPBM?! How is that possible to have a side effect here?

**Comment by kelson42** [comment]
@bakshiutkarsha The first point of this report is invalid. I have been fooled by the ambiguous log message and the fact we had only two of them. I have fixed "the problem" directly on master https://github.com/openzim/mwoffliner/commit/3b802183602fe2b24dd0e571f4ae664b829c4bc2. But the second one is a real problem I believe.

**Comment by bakshiutkarsha** [comment]
> @bakshiutkarsha The first point of this report is invalid. I have been fooled by the ambiguous log message and the fact we had only two of them. I have fixed "the problem" directly on master [3b80218](https://github.com/openzim/mwoffliner/commit/3b802183602fe2b24dd0e571f4ae664b829c4bc2). But the second one is a real problem I believe.

I debugged this issue and the problem is that getTotalArticlesNumberByNS() value is never getting over-ridden, which is fine because it will never actually happen in the real scenario. This is happening only because the first wiki "bm.wikipedia" is getting total 750 article chunks and after that the wikis which are getting articles have no such chunks present(they are have very less articles to download), so no looping with namespace and hence no over-riding.

**Comment by kelson42** [comment]
This is everything but fine. You have a global variable at `let totalArticles = 0;`. This problem is that this is a module global variable and not in the right module. Please remove this, and secure `getArticlesByNS` returns the value and just print it. I think that should solve the problem.

**Comment by kelson42** [comment]
@bakshiutkarsha Or even simplier, just print it at the end of `getArticlesByNS`.
