### ISSUE TITLE
Travis "S3 image not found" test Failure

### ISSUE THREAD

**Issue by bakshiutkarsha** [openzim/mwoffliner#1110]
Sometime, due to parallel running of different node version in Travis CI, the build fails with error :

S3 image not found, it fails because one version is deleting the image and other is trying to find the same image in S3 bucket at the same time, hence the test fails.

**Comment by kelson42** [comment]
What is the scenario to delete the entry in S3?

**Comment by bakshiutkarsha** [comment]
@kelson42 It is a test case where we
1. Delete the image to be sure it is gone from S3. Also, because we are only using one image for the S3 test cases. 
2. Then we upload it, (test checks the uploading functionality)
3. Lastly, check if it already exists in S3 (test the already exists check)

**Comment by kelson42** [comment]
@bakshiutkarsha Ok, so this is not a legitimate scenrio while MWoffliner is running. Just use a random name for the S3 key then.

**Comment by bakshiutkarsha** [comment]
> @bakshiutkarsha Ok, so this is not a legitimate scenrio while MWoffliner is running. Just use a random name for the S3 key then.

Yes, correct. It won't ever happen with the production build of MWoffliner running.
