### ISSUE TITLE
Missing article in wikipedia_de_all_maxi_2020-04.zim

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1111]
Magnus Carlsen seems missing from the latest German release (the article was created in 2004, so not exactly an oversight).

Interestingly, there's a regular blue link to his page in other articles: https://library.kiwix.org/wikipedia_de_all_maxi_2020-04/A/Kandidatenturnier_London_2013
but it leads to a `not found` page.

I remember seeing a similar ticket a while back but could not find it.

**Comment by kelson42** [comment]
This is indeed strange. It is missing in mini/nopic/maxi. If the link is blue then it means it was in the list of article to retrieve. Which tends to lead to the fact that an error occured by scraping the article content... but no error in the log. In the new version https://library.kiwix.org/wikipedia_de_all_mini_2020-05/A/Magnus_Carlsen the article is there. There is not big size change between 2020-04 and 2020-05, so we didn't have a big problem in 2020-04.

I suspect that the best we can do with this ticket is just verifying again the retry/logging strategy if something goes wrong at article content retrieving.

One time zimcheck will be fully integrated in Zimfarm (and revamped), we will be better at detecting/fixing this kind of small problems.

**Comment by Popolechien** [comment]
Ok, the article is available in https://library.kiwix.org/wikipedia_de_all_maxi_2020-08/A/Magnus_Carlsen and no one else has come forward with a similar issue. Closing the ticket for the time being.
