### ISSUE TITLE
Many PDF download errors with Wikibooks FR

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1112]
```
./node_modules/.bin/ts-node ./src/cli.ts --mwUrl="https://fr.wikibooks.org" --adminEmail="kelson@kiwix.org"  --format="nopic:nopic" --addNamespaces="4" --noLocalParserFallback --osTmpDir=/dev/shm

```
log] [2020-05-12T09:31:50.955Z] Progress downloading files [10540/17538] [60.1%]
[log] [2020-05-12T09:31:50.988Z] Not able to download content for ./Special:FilePath/Électricité-fr.pdf due to Error: connect ECONNREFUSED 127.0.0.1:80
[log] [2020-05-12T09:31:51.036Z] Progress downloading files [10550/17538] [60.2%]
[log] [2020-05-12T09:31:51.367Z] Progress downloading files [10570/17538] [60.3%]
[log] [2020-05-12T09:31:51.515Z] Not able to download content for ./Special:FilePath/Sony_Ericsson_W995-fr.pdf due to Error: connect ECONNREFUSED 127.0.0.1:80
[log] [2020-05-12T09:31:51.617Z] Not able to download content for ./Special:FilePath/Sony_Ericsson_W995-fr.pdf due to Error: connect ECONNREFUSED 127.0.0.1:80
[log] [2020-05-12T09:31:51.817Z] Not able to download content for ./Special:FilePath/Sony_Ericsson_W995-fr.pdf due to Error: connect ECONNREFUSED 127.0.0.1:80
[log] [2020-05-12T09:31:51.901Z] Progress downloading files [10590/17538] [60.4%]
[log] [2020-05-12T09:31:52.059Z] Progress downloading files [10610/17538] [60.5%]
[log] [2020-05-12T09:31:52.218Z] Not able to download content for ./Special:FilePath/Sony_Ericsson_W995-fr.pdf due to Error: connect ECONNREFUSED 127.0.0.1:80
[log] [2020-05-12T09:31:52.238Z] Progress downloading files [10620/17538] [60.6%]
[log] [2020-05-12T09:31:52.288Z] Progress downloading files [10640/17538] [60.7%]
[log] [2020-05-12T09:31:52.691Z] Progress downloading files [10660/17538] [60.8%]
[log] [2020-05-12T09:31:52.718Z] Progress downloading files [10680/17538] [60.9%]
[log] [2020-05-12T09:31:52.733Z] Progress downloading files [10690/17538] [61.0%]
[log] [2020-05-12T09:31:52.904Z] Progress downloading files [10710/17538] [61.1%]
```

**Comment by kelson42** [comment]
I should recheck this.

**Comment by pavel-karatsiuba** [comment]
This error cannot be reproduced with the current source code version. Because this is an old error I think it is not actual anymore.
I propose to close this ticket. If the error appears again then we can open another ticket.

**Comment by kelson42** [comment]
OK, closing the ticket.
