### ISSUE TITLE
Heading styles feedback

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#1124]
Edit: I fixed 2 & 3 below in #1135 

------

Hi, I am the dev of Kiwix for iOS, and I use offline Wikipedia on my iPhone and iPad a lot everyday. (Thank you for your hard work!) Here are a few styling feedbacks / suggestions for heading elements that bothers me:

1. Could we stop using `font-family: 'Linux Libertine', 'Georgia', 'Times', serif;` for headings, and just let them use the default font from `body`? I think it look really out of place when heading and content looks differently.
2. Could we get rid of the blue box on the headings, please?
3. `h3` has more weight than `h2` and `h1`
4. Is it possible to move the triangle to vertically align with the text? (instead of bottom or baseline)
5. This one is probably already a lost battle, but could we *not* collapse all sections when on phone like devices? I find this one particularly annoying when I have to expand these sections when reading. 

![Screenshot 2020-05-18 at 10 48 58 AM](https://user-images.githubusercontent.com/8294252/82228943-cbb1e980-98f7-11ea-9ec2-3e91448aa354.png)
![Screenshot 2020-05-18 at 10 49 34 AM](https://user-images.githubusercontent.com/8294252/82228944-cbb1e980-98f7-11ea-936c-8d14f74b84e5.png)

**Comment by automactic** [comment]
@kelson42 Hey, do you agree with my comments? For 1-3 they are easy to fix (I just need to change the css). I can create a PR if it is ok with you

**Comment by rgaudin** [comment]
:+1 on all those comments.

**Comment by kelson42** [comment]
Why this ticket is still open? A PR has already solved it.

**Comment by automactic** [comment]
I only fixed 2 & 3

**Comment by automactic** [comment]
Since @kelson42 is not very happy with me putting 5 items in one issue, I have separated the remaining items in this issue into another three: #1140, #1141 and #1142
