### ISSUE TITLE
question: Reading List

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1130]
Please tell me why there is a **Reading List** in **Kiwix** (**Glasses** are drawn there)?
Clicking on **Glasses** opens an additional column on the left.
Maybe someone will make a small **GIF animation**.
I just **can't understand** the idea of **Reading List** in **Kiwix**.

**Comment by kelson42** [comment]
The reading list is like a bookmark system. Work the same manner.
