### ISSUE TITLE
Geographical coordinates from Wikipedia are not displayed in Kiwix

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1131]
Geographical coordinates from Wikipedia articles are **not displayed** in the Kiwix program.
Open [any Wikipedia article](https://en.wikipedia.org/wiki/Deepwater_Horizon_explosion) where the coordinates are shown **at the top**.
And then open this article in Kiwix and you will see that the coordinates are **not displayed**.
I checked in the **Russian Wikipedia** in the **ZIM** file.

**Comment by kelson42** [comment]
This is not available in the mobile version either online. See https://en.m.wikipedia.org/wiki/Deepwater_Horizon_explosion. We use the mobile version and try to provide the same user experience. If this is not there, there is nothing we can do.

**Comment by JensKorte** [comment]
If the coordinates are not available in the mobile page, then an extra request for every page would be too much. If the coordinates available in the mobile page, but not shown, wouldn't it then be possible to do one extra check at every wiki page for the coordinates {{coord...}} and add them, if available?
