### ISSUE TITLE
Could we use default font for headings?

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#1141]
Could we stop using font-family: 'Linux Libertine', 'Georgia', 'Times', serif; for headings, and just let them use the default font from body? I think it look really out of place when heading and content looks differently.
![82228943-cbb1e980-98f7-11ea-9ec2-3e91448aa354](https://user-images.githubusercontent.com/8294252/83332361-d316b280-a268-11ea-9233-ea7924234ab1.png)

**Comment by kelson42** [comment]
@automactic Do you mean with use another font and an other size that what is done in the online Wikipedia?

**Comment by automactic** [comment]
I just wish all text in the article is using the same font -- the default font from the OS / user style sheet, or some other font should we one day allow user to specify what font to use.

The behavior right now is indeed consistent with the wikipedia site. So it doesn't bother me a lot.

**Comment by kelson42** [comment]
I don’t really think there is anything we should do here. I want to stick as much as possible (for the moment) to the online/upstream UX.

**Comment by MananJethwani** [comment]
> I don’t really think there is anything we should do here. I want to stick as much as possible (for the moment) to the online/upstream UX.
>
@kelson42 then is this issue closed?

**Comment by automactic** [comment]
I am ok with closing it as won't do
