### ISSUE TITLE
Avoid hardcoded ETAG in automated tests

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1145]
One of our S3 automated - relying on a Wikipedia image - test has an ETAG hardcoded. This is weak and within a few months the test has been broken becuase things has been changed on Wikipedia side.

We should remove the hardcoded ETAG in our test.

The test should be rewritten like this:
* Delete the image in S3
* Make a (download) run to test we download the image from Wikipedia (ETAG dynamically retrieved from online request).
* Test the image is properly uploaded to S3 with the proper ETAG
* Make an other run to secure the image comes from the S3 this time
* Make an other run and screwing the ETAG, check the image comes this time from Wikipedia
* Check that the image in S3 has been refreshed properly with proper ETAG

**Comment by kelson42** [comment]
@bakshiutkarsha What is the status here? This is one of the blocker for the rest!

**Comment by bakshiutkarsha** [comment]
> @bakshiutkarsha What is the status here? This is one of the blocker for the rest!
I took care of this in PR 1147.
