### ISSUE TITLE
Redis default configuration should be normal

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1163]
I made the configuration special to us to avoid to specify it all the time. Now that the tool is more broadly use and that we have the ZIMfarm, we should come back to the "normal" configuration per default so user don't have to tune either the MWoffliner configuration or the Redis configuration to start to play with MWoffliner.

One time done, the configuration parameter to get it work on the ZIMfarm should be given to @rgaudin so it can be populated to all our MWoffliner recipes.

**Comment by bakshiutkarsha** [comment]
@kelson42 Do we need to add this config using a configuration parameter?
```
unixsocket /dev/shm/redis.sock
unixsocketperm 777
save ""
appendfsync no
```

**Comment by kelson42** [comment]
@bakshiutkarsha This is the server config, you can't change it from the client side. On the client side (MWoffliner) you already have `--redis`.

**Comment by bakshiutkarsha** [comment]
Can you point me to the config that needs to be updated?

**Comment by kelson42** [comment]
You mean this? https://github.com/openzim/mwoffliner/blob/master/src/config.ts#L7. I don't have more technical information than you.
