### ISSUE TITLE
Document the API we rely on

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1167]
We need to better understand on which API we rely on to do a proper software architecture. Something has started here https://species.wikimedia.org/api/rest_v1/#/Mobile but we need to complete and get things in a form of a table.

The information for which API is:
* The URL scheme (with the dynamic part)
* The nature output
* A description of the output
* The software delivering it
* Where is this available (local Parsoid, restbase, old mediawiki, new mediawiki)
* Why we need it

Ideally they should be grouped by nature.

It seems the current MWoffliner "parse wikitext", this should not happen and this table should really help to understand why.

**Comment by midik** [comment]
Process is going there https://docs.google.com/spreadsheets/d/1oNX9XAILHemks4BW9mXOLb4gnpn7w-j_VBMXwastNY0/edit#gid=0

**Comment by kelson42** [comment]
@midik Looks a good start. Would you be able to move it in the wiki (if you struggle with the table, a coherent list of bullet points shoudl be good enough). It seems the local instances (parsoid) is missing. Ping me we your effort is over.

**Comment by VadimKovalenkoSNF** [comment]
PCS docs might be used as a reference here: https://www.mediawiki.org/wiki/Page_Content_Service

**Comment by kelson42** [comment]
Basic documentation available at https://github.com/openzim/mwoffliner/wiki/API-end%E2%80%90points. To be extended
