### ISSUE TITLE
Correctly detect mimetype of article.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/mwoffliner#1183]
Few zim files (as wikipedia_ar_history_maxi_2020-05.zim) have complex url for image (`m/osm-intl,15,33.333055555556,69.916944444444,300x300.png?lang=ar&domain=ar.wikipedia.org&title=حصار+خوست&groups=_41d389aefe5f67866d9b480e5c44559d54fb9683.svg`).
Those images are png but as the url ends with svg, it is detected as svg and :
- added to a compressed cluster.
- the wrong mimetype is returned to the reader.

Mwoffliner should use a better method to detect the mimetype of the data:
- remove what after `?` before detect the mimetype
- check the content of the data and not just the url
- Use other method (As we are on web world, there is no guaranty at all that an url have a extension we can base on to detect the mimetype)

**Comment by kelson42** [comment]
@MananJethwani Could you please have a look to that one? I believe this might have been already fixed as we rely more on the HTTP response header than on the file extension now!

**Comment by MananJethwani** [comment]
@mgautierfr can you give me link to the article

**Comment by kelson42** [comment]
@mgautierfr @MananJethwani I have used `zimdump` to inspect `wikipedia_ar_history_maxi_2020-10.zim` and all the SVG starting with `osm-intl` have the `image/svg+xml`. I believe the problem has been fixed during the implementation of the `--webp` option which implied that we rely more the HTTP response mime-type (and not the filename) than before.

**Comment by mgautierfr** [comment]
The problem is that they ARE png.
```
$ zimdump list --ns I --url 'm/osm-intl,8,57.628997,18.307109,300x300.png?lang=ar&domain=ar.wikipedia.org&title=فيسبي&groups=_b046510b40c3fe91f8c3d9ba6321e82901cc85c2.svg' wikipedia_ar_history_maxi_2020-10.zim
url: m/osm-intl,8,57.628997,18.307109,300x300.png?lang=ar&domain=ar.wikipedia.org&title=فيسبي&groups=_b046510b40c3fe91f8c3d9ba6321e82901cc85c2.svg
	title:           m/osm-intl,8,57.628997,18.307109,300x300.png?lang=ar&domain=ar.wikipedia.org&title=فيسبي&groups=_b046510b40c3fe91f8c3d9ba6321e82901cc85c2.svg
	idx:             38571
	namespace:       I
	type:            article
	mime-type:       image/svg+xml
	article size:    15998
$ zimdump show --ns I --url 'm/osm-intl,8,57.628997,18.307109,300x300.png?lang=ar&domain=ar.wikipedia.org&title=فيسبي&groups=_b046510b40c3fe91f8c3d9ba6321e82901cc85c2.svg' wikipedia_ar_history_maxi_2020-10.zim | head -1
�PNG
```

You can see that the stored mime-type in zim is `image/svg+xml` but if you look at the content of the entry, it is PNG.

**Comment by kelson42** [comment]
@mgautierfr Great, thx for the clarification.

**Comment by kelson42** [comment]
@MananJethwani I believe the problem is in the regexp testing the URL, we should remove/ignore everything after the question mark.

**Comment by kelson42** [comment]
After discussing the issue with @MananJethwani yesterday it seems that we need to have a look/fix a few different things:
* New/update automated tests the involved REGEX (related functions) properly
* Clarify/fix why PNG delvered content (so with what should be `image/png` HTTP response `content-type` header) ends up with an `image/png` mime-type in the ZIM. We should take the ZIM mime-type from the HTTP response IMO.
* Fix the file extension related REGEX, because in such a case it is probably broken (we should have a proper webp image in case of `--webp` but we don't).
