### ISSUE TITLE
Wikivoyage_es_all_maxi scrapes pictures but does not display them

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1194]
See https://download.kiwix.org/zim/wikivoyage/wikivoyage_es_all_maxi_2020-06.zim - it's about 70Mb (vs. 13Mb for the nopic version), but it only shows empty squares

![Screenshot 2020-06-25 at 11 44 02](https://user-images.githubusercontent.com/21675885/85696546-534dfd80-b6d9-11ea-8b7f-be771af7784f.png)

The problem might broader than this specifi zim however because I've had reports of a similar issue with klexikon_de_all_maxi_2020-05.zim

**Comment by Jaifroid** [comment]
Problem seems to be that 2020.-06 version of this file is in fact only 46MB, whereas the 2020-05 version is 79MB, so some 33MBs of (presumably) images are missing.

**Comment by Popolechien** [comment]
I was going to say the same but I restarted the scraper and got the same result (no images) with a large-enough file. Then I re-restarted it and now it's fine.
Bottom line - scraper works somehow, sometimes, but not reliably.

**Comment by kelson42** [comment]
@Popolechien You don't have always used the same version of MWoffliner. The most probable explaination.
