### ISSUE TITLE
Redirects are not captured

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1202]
A good test is with the [latest Stupidedia zim file](https://download.kiwix.org/zim/other/stupidedia_de_all_maxi_2020-07.zim) as most article links seem to be redirects (e.g., all those in the leade of the Stupidedia article). I've noticed the same issue with the last enwp release.

![toto](https://user-images.githubusercontent.com/21675885/86573131-384e7980-bf74-11ea-868d-881160178677.png)

Basically, if a link points to a redirect or is even simply coded with a pipe (e.g. [[Deutschland|deutsch-]] in the example above) the scraper correctly identifies an hyperlink and shows it in blue, but fails to properly link to it - meaning that it's non-clickable.
Tested on macOS, but Kiwix-JS additionally indicates `Article with title wiki/Deutschland not found in the archive`

**Comment by kelson42** [comment]
@Popolechien You confirm http://library.kiwix.org/stupidedia_de_all_maxi_2020-01/A/Stupidedia:Hauptseite works fine for you?

**Comment by Popolechien** [comment]
Yep. That's the oddest part because it does have redirects also.

**Comment by kelson42** [comment]
@Popolechien Why this is odd? You have bugs in the readers. For macOS I believe you are impacted by https://github.com/kiwix/apple/issues/227. I can not say for Kiwix-JS, I would recommend to open a bug there.

**Comment by Popolechien** [comment]
Well I would not think it's a reader issue, check any one link on http://library.kiwix.org/stupidedia_de_all_maxi_2020-01/A/Stupidedia to see that the articles are not, in fact, available.

**Comment by Popolechien** [comment]
duplicate of #1203
