### ISSUE TITLE
Totally broken link in stupidepedia

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1203]
See for example http://library.kiwix.org/stupidedia_de_all_maxi_2020-07/A/Stern, all the links which start with `/wiki/`.

**Comment by kelson42** [comment]
@bakshiutkarsha I'm sure we had this and thought this is fixed... but this is still there.

**Comment by kelson42** [comment]
Fixed with #1238

**Comment by bakshiutkarsha** [comment]
> Fixed with #1238

This issue has not been fixed. #1238 was a PR for a separate issue(there was no ticket created for it.)

**Comment by bakshiutkarsha** [comment]
@kelson42  There is an already created PR to close this issue #1225

**Comment by bakshiutkarsha** [comment]
> @bakshiutkarsha Next time please open a bug ticket. I don't know which bug and which impact has the bug this PR fixes.

Sure.

**Comment by Ammarpad** [comment]
To serve the main page from the domain root, you need to set the `$wgMainPageIsDomainRoot` config flag to true. Note that it's marked as experimental and is only available from Mediawiki 1.34 and onward.

**Comment by bakshiutkarsha** [comment]
@Ammarpad  Thanks for the explanation. I checked for this wiki, the version they use is 1.27.4. Also, is there any way I can check the `$wgArticlePath` value for this wiki?

**Comment by kelson42** [comment]
Closed via https://github.com/openzim/mwoffliner/pull/1246
