### ISSUE TITLE
PDF file icon

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1215]
Wikipedia has many **links** and **references**. Frequently found links/references to **PDF** files. In Wikipedia, there is a small Adobe icon after the link to the PDF file:
![pdf-Wiki](https://user-images.githubusercontent.com/65112331/87562698-f84f6b00-c6c6-11ea-81d3-4af74b0a1c70.gif)

In ZIM files, there is **no** small icon from Adobe. Instead of the icon there is an empty space:
![pdf-Kiwix](https://user-images.githubusercontent.com/65112331/87562715-fbe2f200-c6c6-11ea-9668-de3579c6829d.gif)

If it possible, please add this small Adobe icon in ZIM files to indicate the PDF file. It must weigh very little.
But with this icon, **links** / **references** looks much more beautiful.

**Comment by devangmukherjee** [comment]
Hi, will it work if we insert the same image of a pdf in this place?

**Comment by devangmukherjee** [comment]
@kelson42 I am interested in working on this issue, can I work on it?

**Comment by kelson42** [comment]
@devangmukherjee You are welcome, but before coding anything, please explain here the root cause of the problem and your approach to fix it.

**Comment by devangmukherjee** [comment]
@kelson42   I am actually unable to figure out how does the pdf icon even appear at the wikipedia screen cause I looked at source and for an image <a href> should be present linking the image form somewhere.

![Screenshot from 2020-10-13 14-40-46](https://user-images.githubusercontent.com/44459138/95962024-7ab10d80-0e23-11eb-8175-0f0a8543eeb4.png)

Can you please tell me what am I understanding incorrectly here?

**Comment by devangmukherjee** [comment]
@kelson42  I think the problem is that pdf icon is a background image to the link and that's why isn't showing anything there. So for the link element we can extract that background image and show it there. Will this work?

**Comment by Ubuntu-2020** [comment]
@kelson42 Two years later... Maybe add in a **Milestone** to fix this problem?

**Comment by kelson42** [comment]
Closing in favour of #1807 (duplicate)
