### ISSUE TITLE
The block with links to related Wikipedia projects is not visible

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1217]
At the very bottom of the article in the **Links section**, there is usually a **block** with links to related Wikipedia projects. But it is not visible in Kiwix!
Here is an example of an article about the **[football club Barcelona](https://ru.wikipedia.org/wiki/Барселона_(футбольный_клуб)#Ссылки)**:
![wikipedia_ru](https://user-images.githubusercontent.com/65112331/87874278-356e7280-c9d1-11ea-9c97-d45c69635e63.gif)

And this is what the **Links section** looks like in **Kiwix 2.8.0** (file **wikipedia_ru_football_maxi_2020-04.zim**):
![wikipedia_ru_football_maxi_2020-04](https://user-images.githubusercontent.com/65112331/87874282-3b645380-c9d1-11ea-9822-e7e8ca190fc2.gif)

**Comment by kelson42** [comment]
@Ubuntu-2020 Probably because there is the CSS ‘noprint’ class in the ‘div’. We remove all of them. To be confirmed.

**Comment by kelson42** [comment]
Like I said two days ago, this is what happened here:
```
<div class="ts-Родственные_проекты tright metadata plainlinks plainlist noprint ruwikiWikimediaNavigation">
```
