### ISSUE TITLE
The block with quoting the original text is not expanded

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1221]
The block with quoting the original text in **"small" ZIM files** is not expanded. What do I mean by **"small" ZIM files**?
This is any **ZIM** file. For example, this one: **wikipedia_ru_movies_maxi_2020-06.zim**
In other words, all **ZIM** files are small. Only this big one: **wikipedia_ru_all_maxi_2020-07.zim**.

Example. Article about [Quentin Tarantino](https://ru.wikipedia.org/wiki/Тарантино,_Квентин#«Бесславные_ублюдки»):
![Quentin Jerome Tarantino-Wiki](https://user-images.githubusercontent.com/65112331/87923641-796f7f00-ca86-11ea-9d61-fa45264db1ec.gif)

And this is what this part of the article in **Kiwix 2.8.0** looks like (**wikipedia_ru_movies_maxi_2020-06.zim**):
![Quentin Jerome Tarantino-Kiwix](https://user-images.githubusercontent.com/65112331/87923787-a6239680-ca86-11ea-8493-17ec6eef950c.gif)

**Comment by Jaifroid** [comment]
@Ubuntu-2020 What app does the top version show? I'm not clear whether you're identifying an inconsistency in Kiwix JS, or an inconsistency in the other app, but you should probably move these reports to the GitHub of the app in question if the problem is with the app.

**Comment by Ubuntu-2020** [comment]
> @Jaifroid What app does the top version show?

This is how the Internet page of an **[article](https://ru.wikipedia.org/wiki/Тарантино,_Квентин#«Бесславные_ублюдки»)** from Wikipedia looks in a web browser. And I would like it to look exactly the same in **Kiwix**.

> @Jaifroid if the problem is with the app.

The problem is not in the app but in the ZIM file!
I already wrote above that in a **large file** (**30 GB**) (**wikipedia_ru_all_maxi_2020-07.zim**) there is an expanded text of the original quote in English. And in _small_ ZIM files, for example in this (**wikipedia_ru_movies_maxi_2020-06.zim**), the quotation is always collapsed and only the text with the translation into Russian is visible, that is, the original quote in this case in English is not visible.

**Comment by kelson42** [comment]
@Jaifroid To me this is a duplicate of #1033

**Comment by kelson42** [comment]
I believe the problem to be fixed now (by #1701)- even if the wiki/rendering is very different now.
