### ISSUE TITLE
Tables are not expanded

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1222]
**wikipedia_ru_movies_maxi_2020-06.zim**
Tables are not expanded.
Example. Article about [Quentin Tarantino](https://ru.wikipedia.org/wiki/Тарантино,_Квентин#Режиссёрский_почерк):
![Quentin Tarantino-Wiki](https://user-images.githubusercontent.com/65112331/87925467-00bdf200-ca89-11ea-9bfe-55e7a187c151.gif)

I didn't click on the tables just because they are **very large** in the expanded state!

And this is what this part of the article in **Kiwix 2.8.0** looks like (**wikipedia_ru_movies_maxi_2020-06.zim**):
![Quentin Tarantino-Kiwix](https://user-images.githubusercontent.com/65112331/87925510-0ddae100-ca89-11ea-996e-ea6756246a90.png)

**Comment by Jaifroid** [comment]
@Ubuntu-2020 I'm not sure whether you're using the Kiwix JS browser extension/add-in here or not, but not all extensions are allowed to run inline JavaScript. This is an API limitation. You can try switching to Service Worker mode (in Configuration) if you are using the Kiwix JS browser extension -- it will help with running JavaScript, but still may not run inline JS in some contexts.

**Comment by MananJethwani** [comment]
@kelson42 collapse button is actually an a tag and by default we search those a tag links in article list if no present we delete which is right but you can clearly see in the screenshot what the link is so we can do 2 things we can change link removal to keep these kind of links(not sure this will work or how will it work) or change our script.js to find such collapsible tables and add this link on it's own

**Comment by MananJethwani** [comment]
@kelson42 sorry for the false observation above
ok I just looked into it we don't recieve that colapsing link from upstream only
https://ru.wikipedia.org/api/rest_v1/page/mobile-sections/%D0%A2%D0%B0%D1%80%D0%B0%D0[…]B8%D0%BD%D0%BE%2C_%D0%9A%D0%B2%D0%B5%D0%BD%D1%82%D0%B8%D0%BD
this is the link from where we fetch the article
and this doesn't have this tag `<a id="collapseButton0" href="javascript:collapseTable(0);">показать</a>`

**Comment by kelson42** [comment]
@MananJethwani the given URL is invalid and returns and error. From your comment I don't understand what is wrong, do you mean the DOM is wrong? If "yes" is that different from the online version?
