### ISSUE TITLE
What articles are included in **wikipedia_ru_top.zim** ?

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1224]
Question. What articles are included in this ZIM file: **wikipedia_ru_top_maxi_2020-05.zim**

For example, the Russian Wikipedia has: [1346 Featured articles](https://ru.wikipedia.org/wiki/Википедия:Избранные_статьи), [3640 Good articles](https://ru.wikipedia.org/wiki/Википедия:Хорошие_статьи), [6601 Good articles](https://ru.wikipedia.org/wiki/Википедия:Добротные_статьи), [1036 Featured lists and 32 Featured portals](https://ru.wikipedia.org/wiki/Википедия:Избранные_списки_и_порталы).

Here are some articles for example:
- [Мирмекийский саркофаг](https://ru.wikipedia.org/wiki/Мирмекийский_саркофаг), [Шёрстный покров собаки](https://ru.wikipedia.org/wiki/Шёрстный_покров_собаки), [Пихта одноцветная](https://ru.wikipedia.org/wiki/Пихта_одноцветная) - Featured articles.
- [Кизил-кобинская культура](https://ru.wikipedia.org/wiki/Кизил-кобинская_культура), [Гаультерия шаллон](https://ru.wikipedia.org/wiki/Гаультерия_шаллон), [Город Груйтуйзена](https://ru.wikipedia.org/wiki/Город_Груйтуйзена) - Good articles.

But all of the above articles are missing in the **wikipedia_ru_top_maxi_2020-05.zim**:
![wikipedia_ru_top_maxi_2020-05](https://user-images.githubusercontent.com/65112331/87928559-b0955e80-ca8d-11ea-8ee1-35b3cc721153.png)

PS: all the above **Featured** and **Good** articles were assigned the corresponding status back in 2019 that is, long before the ZIM file was created **wikipedia_ru_top_maxi_2020-05.zim**.

**Comment by Jaifroid** [comment]
Hi, does the landing page not show anything? (Press Home in the extension.) Another trick is to type a single upper-case (or lower-case) letter in the search box, and it will give you all articles beginning with that letter. You can increase the number of articles shown from Configuration.

**Comment by kelson42** [comment]
Here is the list of articles http://download.openzim.org/wp1/ruwiki_2020-07/tops/50000.tsv

**Comment by Ubuntu-2020** [comment]
@kelson42 Thank you very much for the list of articles.
But please **explain by what criteria articles are included in this list**? I thought that since this ZIM file contains 50,000 of the best articles that it means that it should contain all the **Featured** and **Good** articles. But as I pointed out above, it lacks some (six) Featured and Good articles.

**Comment by kelson42** [comment]
@Ubuntu-2020 This is a whole algorithm, I'm not going to explain it, but this is open source here https://github.com/openzim/wp1_selection_tools
