### ISSUE TITLE
fr.wiktionary ZIM improperly renders tables

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1227]
Looking at http://library.kiwix.org/wiktionary_fr_app_nopic here are situations where a word's variation are indicated in table aligned to the left of the screen - see, e.g. [pars](https://fr.wiktionary.org/wiki/pars#Forme_de_verbe):

![Capture d’écran 2020-07-21 à 15 14 56](https://user-images.githubusercontent.com/21675885/88059344-02f57e80-cb65-11ea-98f8-ea6cca54b607.png)

The table is however improperly rendered in the corresponding zim:

![Capture d’écran 2020-07-21 à 15 16 24](https://user-images.githubusercontent.com/21675885/88059462-2c160f00-cb65-11ea-8982-bae771baced6.png)

- It is not aligned to the right
- it is not rendered as two columns
- there are some new, weird colors and improper fonts.

**Comment by kelson42** [comment]
This is only the mobile rendering which is like this. See https://fr.m.wiktionary.org/wiki/pars. There is nothing we can do here.
