### ISSUE TITLE
wikileaks.org - there are no suggestions when hovering the mouse cursor

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1228]
**wikileaks_en_afghanistan-war-diary_2012-01.zim**
There are no suggestions when hovering the mouse cursor:
![wikileaks_en_afghanistan-war-diary-comments](https://user-images.githubusercontent.com/65112331/88061977-e4958000-cb70-11ea-80fe-e4f5b831cb3f.png)

Here's what the suggestions look like when you hover your mouse over the **[Wikileaks site](https://wikileaks.org/)**:
![wikileaks_en_afghanistan-war](https://user-images.githubusercontent.com/65112331/88063057-499da580-cb72-11ea-996a-dd6b48e184b2.gif)

**Comment by kelson42** [comment]
I had a look and this ZIM suffers of many problem. It is one of the first one we have done and does not respect new standards. I have removed it from the portofolio and archived it.
