### ISSUE TITLE
Failed scraping of HTML content

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1229]
I had a go at [Lowtechlab](https://farm.openzim.org/recipes/lowtechlab_fr) and the [corresponding zim](https://download.kiwix.org/zim/other/lowtechlab_fr_all_nopic_2020-07.zim) output shows html-like code. 

![Capture d’écran 2020-07-21 à 16 28 40](https://user-images.githubusercontent.com/21675885/88067413-40f7a000-cb6f-11ea-9327-feceaf7257a4.png)

**Comment by kelson42** [comment]
Duplicate of #1326
