### ISSUE TITLE
[Regression] wikisource en_all_maxi only scraps first page and a couple of images

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1230]
With the two latest iterations we end up with a [25Mb file](https://farm.openzim.org/pipeline/5f17ef3be2aaee590569667d) instead of [20 Gb](https://farm.openzim.org/pipeline/5ed3f0a658b7a2d9e72630a9).

**Comment by kelson42** [comment]
https://farm.openzim.org/recipes/wikibooks_el is smaller

**Comment by bakshiutkarsha** [comment]
@kelson42  I debugged the issue, my findings:

1. It seems the **remote API** is failing for all the articles. The main page article is the only one that is getting created. For articleId `Προγραμματισμός_του_Ανθρωπίνου_Δυναμικού_στις_Επιχειρήσεις_και_στους_Οργανισμούς`

Eg: `https://el.wikibooks.org/api/rest_v1/page/mobile-sections/%CE%A0%CF%81%CE%BF%CE%B3%CF%81%CE%B1%CE%BC%CE%BC%CE%B1%CF%84%CE%B9%CF%83%CE%BC%CF%8C%CF%82_%CF%84%CE%BF%CF%85_%CE%91%CE%BD%CE%B8%CF%81%CF%89%CF%80%CE%AF%CE%BD%CE%BF%CF%85_%CE%94%CF%85%CE%BD%CE%B1%CE%BC%CE%B9%CE%BA%CE%BF%CF%8D_%CF%83%CF%84%CE%B9%CF%82_%CE%95%CF%80%CE%B9%CF%87%CE%B5%CE%B9%CF%81%CE%AE%CF%83%CE%B5%CE%B9%CF%82_%CE%BA%CE%B1%CE%B9_%CF%83%CF%84%CE%BF%CF%85%CF%82_%CE%9F%CF%81%CE%B3%CE%B1%CE%BD%CE%B9%CF%83%CE%BC%CE%BF%CF%8D%CF%82` 

Giving 404 [here](https://www.mediawiki.org/wiki/HyperSwitch/errors/not_found#route).

2. Main Page API:

`https://el.wikibooks.org/w/api.php?action=visualeditor&mobileformat=html&format=json&paction=parse&page=%CE%9A%CF%8D%CF%81%CE%B9%CE%B1_%CE%A3%CE%B5%CE%BB%CE%AF%CE%B4%CE%B1`

which is successful

3. I checked without the `noLocalParserFallback`, the full wiki is getting created.

**Comment by kelson42** [comment]
@bakshiutkarsha We have broken something here... This web site does not have any mobile API.

**Comment by Popolechien** [comment]
Just adding wikiquote_en_all_maxi_2020-08.zim as another reported and similar issue.

**Comment by Popolechien** [comment]
Just had a quick check: [every single Wikibook](http://download.kiwix.org/zim/wikibooks/?C=S;O=A) is impacted and returns almost-empty zim files of varying size (a few hundred Kb to 5.8 Mb max). Something must have happened in June because the only 3 zim files that are ok (`el` and `hi`) are from then.

Same thing for Wikiversity, Wikisource, Wikiquote, Wikinews.
Wikipedia, Wikivoyage and Wiktionary do not seem to be impacted.
