### ISSUE TITLE
Is it possible to translate the text at the bottom of the page into your native language?

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1231]
Is it possible to translate the text at the bottom of the page into your native language?
Now the text at the bottom of any Wikipedia page from ZIM file is in English:
![Page-footer](https://user-images.githubusercontent.com/65112331/88168894-c76db980-cc23-11ea-95a8-5d7c677bde0e.png)

I would like to translate it to Russian for all ZIM files from the **Russian Wikipedia**:
> Текст доступен по [лицензии Creative Commons Attribution-ShareAlike](https://creativecommons.org/licenses/by-sa/3.0/deed.ru); в отдельных случаях могут действовать дополнительные условия. Подробнее см. [Условия использования](https://foundation.wikimedia.org/wiki/Terms_of_Use/ru).
> Wikipedia® — зарегистрированный товарный знак некоммерческой организации [Wikimedia Foundation, Inc.](https://wikimediafoundation.org)

PS №1: also, all ZIM files **should have the two pages** listed above ([by-sa 3.0 ru](https://creativecommons.org/licenses/by-sa/3.0/deed.ru)  + [Terms of Use](https://foundation.wikimedia.org/wiki/Terms_of_Use/ru)). And now if you click on the license, a page opens in the web browser.

PS №2: It is good that a hint appears when the page was last edited when hovering over the word **Wikipedia**: _**Last edited on 2020-05-08**_ But I would like to translate this hint into Russian: **_Эта страница в последний раз была отредактирована 2020-05-08_**.
![Last-edited-on-2020](https://user-images.githubusercontent.com/65112331/88171040-56c89c00-cc27-11ea-8221-2cbcdfb8b701.gif)

PS №3: As far as I noticed in **Kiwix 2.0.4** (*. appimg) does not appear hint **Last edited on 2020-05-08**.

**Comment by kelson42** [comment]
Yes, we should work on this. This ticket is basically a duplicate of #1116
