### ISSUE TITLE
The table is not displayed correctly + there are no licenses at the bottom

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1233]
**wikipedia_en_computer_maxi_2020-07.zim**
The table in the article about the [**Ubuntu**](https://en.wikipedia.org/wiki/Ubuntu#Releases) operating system is displayed incorrectly:
![Ubuntu releases-Kiwix](https://user-images.githubusercontent.com/65112331/88282415-34e81b80-ccf2-11ea-9924-53f0cadf2d2d.png)

Here's what the table should look like ([**Ubuntu releases**](https://en.wikipedia.org/wiki/Ubuntu#Releases)):
![Ubuntu releases](https://user-images.githubusercontent.com/65112331/88282125-9f4c8c00-ccf1-11ea-9dc2-22b572ca6b93.png)

In addition, some articles from the above-mentioned **ZIM** file do not contain information about licenses at the bottom. This label is missing in the articles: **[Ubuntu](https://en.wikipedia.org/wiki/Ubuntu)**, **[Ubuntu version history](https://en.wikipedia.org/wiki/Ubuntu_version_history)**, etc.:
![bottom](https://user-images.githubusercontent.com/65112331/88283220-ae343e00-ccf3-11ea-8ab7-7cb420561ca3.gif)

**Comment by kelson42** [comment]
The table problem seems to be fixed in latest version of the ZIM. But indeed the footer is not there which is a problem I have never seen before. @MananJethwani An idea?

**Comment by kelson42** [comment]
@MananJethwani Latest zim file made by zimfarm is here https://mirror.download.kiwix.org/zim/wikipedia/wikipedia_en_computer_maxi_2020-11.zim. Please check.

**Comment by kelson42** [comment]
@MananJethwani The big is still there in latest ZIM.
