### ISSUE TITLE
The Expanding tables and Category section at the bottom of the page are not visible

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1235]
The **Expanding table** and **Category section** at the bottom of the page are not visible.
The bottom of the page **[looks like this](https://en.wikipedia.org/wiki/Windows_Vista#External_links)**:
![Bottom](https://user-images.githubusercontent.com/65112331/88369877-a038f880-cd99-11ea-9d6f-3324a35a3a45.gif)

But in **Kiwix**, neither the **expanding tables** nor the **categories** are visible.
It seems to me that there are **no articles about categories** in ZIM files at all !!!

**Comment by Jaifroid** [comment]
@Ubuntu-2020 mwoffliner has never scraped these navigation tables AFAIK. Many of the issues you are opening are in fact instances of the more general issue of mwoffliner only scraping core DOM content. There are lots of navigation-style tables omitted. See #179 for example.

You could help debug these by checking if the information is available with the Parsoid API. See https://github.com/openzim/mwoffliner/issues/182#issuecomment-356982682 (and subsequent) on how you can check the Parsoid output that mwoffliner relies on.

**Comment by kelson42** [comment]
This tables are not display with mobile style. This is an upstream decisin.
