### ISSUE TITLE
More obvious reporting for failed pages

### ISSUE THREAD

**Issue by Lucent** [openzim/mwoffliner#1247]
If fed an article list for downloading, my primary concern is determining which titles the run failed to download, (usually due to nonexistence). The following catches some of the fails and makes them obvious, but on a run of 300 titles that had 9 failures, this only showed 3 lines and I have no idea what other pages failed or if they were other types of failures:

`mwoffliner … --verbose --articleList=articles.txt 2> >(grep "Failed to get") 1> log.txt`

**Comment by Lucent** [comment]
Upon further attempts to match up the summary report, error log, and what's actually missing from the .zim, I discovered the following:

```
Summary of scrape actions: {
    "files": { "success": 1695, "fail": 0 },
    "articles": { "success": 309, "fail": 9 }, // correct total, articles.txt had 318 entries
    "redirects": { "written": 2001 }
}

[warn] Failed to get [https://en.wikipedia.org/api/rest_v1/page/mobile-sections/Other_nonmetals] [status=404]
[warn] Failed to get [https://en.wikipedia.org/api/rest_v1/page/mobile-sections/Bismuth-219] [status=404]
[warn] Failed to get [https://en.wikipedia.org/api/rest_v1/page/mobile-sections/Other%20nonmetals] [status=404]

[warn] Error downloading article [Post-transition metals], skipping TypeError: Cannot read property 'subCategories' of null
[warn] Error downloading article [Alkaline earth metals], skipping TypeError: Cannot read property 'subCategories' of null
[warn] Error downloading article [Mercury (element)], skipping TypeError: Cannot read property 'subCategories' of null
[warn] Error downloading article [Other_nonmetals], skipping Error: Request failed with status code 404
[warn] Error downloading article [Noble gases], skipping TypeError: Cannot read property 'subCategories' of null
[warn] Error downloading article [Transition metals], skipping TypeError: Cannot read property 'subCategories' of null
[warn] Error downloading article [Alkali metals], skipping TypeError: Cannot read property 'subCategories' of null
[warn] Error downloading article [Bismuth-219], skipping Error: Request failed with status code 404
[warn] Error downloading article [Other nonmetals], skipping Error: Request failed with status code 404
```

The 404 pages genuinely did not make it to the final .zim, only 3. The other 6 "cannot read property of subCategories" made it in as a redirect, so I'm not sure what that error actually means or whether it should even be counted as 6 additional failures in the "Summary of scrape actions."

**Comment by kelson42** [comment]
@Lucent Thank you for the bug report, I believe this should work better with https://github.com/openzim/mwoffliner/pull/1260. Otherwise please share the complete command and the `articles.txt`.
