### ISSUE TITLE
Add --webp option

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1254]
With this option, GIF, PNG and JPEG should be converted to WEBP images.

**Comment by Jaifroid** [comment]
But this would leave a number of platforms behind. See https://caniuse.com/webp . I don't think browser support is ready for this?

**Comment by kelson42** [comment]
@Jaifroid Few clarifications:
* For the moment this would be an option (so not run everywhere)
* You probably need to read https://github.com/openzim/python_scraperlib/issues/45
* First candidates would be the ZIM to be put in the Android custom apps

**Comment by Jaifroid** [comment]
Ah, OK, thanks! I see there is a polyfill that supports old browsers, including IE11, so it's not the breaking change I thought it was at first.

**Comment by arjungarg07** [comment]
Hey @kelson42, I am willing to work on this issue. Can you assign this to me?

**Comment by arjungarg07** [comment]
Hey @kelson42, I am willing to work on this as my first issue. Can you assign this to me? and Can you brief me more about this issue, please!

**Comment by arjungarg07** [comment]
Hey @kelson42, I am willing to work on this as my first issue. Can you assign this to me?

**Comment by kelson42** [comment]
@arjungarg07 Thx, good to me.

**Comment by arjungarg07** [comment]
Do i have to add this option in the parameters of mwoffliner API?
Can you please brief me more about this.

**Comment by kelson42** [comment]
@arjungarg07 yes, this is a new option.
