### ISSUE TITLE
Automated tests fails because of lack of `offline.css`.

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1259]
This file https://en.wikipedia.org/wiki/MediaWiki:Offline.css existed before but does not exists anymore. I believe the automated tests fail because of this changement. But this file is optional, so tests should pass.

**Comment by MananJethwani** [comment]
@kelson42 while using axios when status code is 404 axios throws an error which is causing test to fail

**Comment by kelson42** [comment]
@MananJethwani If there is a 404, then no ero should happe, maybe just a log entry and the process shoudl just continue.

**Comment by MananJethwani** [comment]
@kelson42 adding `validateStatus(status) { return ((status >= 200 && status < 300) || status === 304 || status ===404);}` removes the error but still string includes function in styles.test.ts is showing false even when it is present there I logged finalCss and offlineCssContent

**Comment by MananJethwani** [comment]
it is due to different time stamp is being appended during 404 request

**Comment by MananJethwani** [comment]
@kelson42 please close this ticket
