### ISSUE TITLE
Error: @openzim/libzim@2.4.2 install

### ISSUE THREAD

**Issue by Venipa** [openzim/mwoffliner#1261]
info lifecycle @openzim/libzim@2.4.2~install: Failed to exec install script
Error: @openzim/libzim@2.4.2 install: `npm run download && node-gyp rebuild -v && npm run bundle`
tried installing on node 10, 11 and 12
also tried it on windows and linux
![image](https://user-images.githubusercontent.com/17952364/93723275-8d765080-fb9d-11ea-8824-96d86edcd9c4.png)

**Comment by kelson42** [comment]
@Venipa Thank you for your bug report. Neither libzim nor mwoffliner packages support Windows out of the box. Nobody has ever tried to use this on Windows. For the reset, was do you try to achieve exactly? What do you do exactly? What kind of Linux do you have?

**Comment by Venipa** [comment]
tried to install it on debian 10, also have tried to run it on a wsl debian distro (OS: Debian GNU/Linux 10 (buster) on Windows 10 x86_64)

```
npm WARN notsup Unsupported engine for wikimedia-page-library@6.5.0: wanted: {"node":"10.15.3","npm":"6.4.1"} (current: {"node":"14.8.0","npm":"6.14.7"})
npm WARN notsup Not compatible with your version of node/npm: wikimedia-page-library@6.5.0

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @openzim/libzim@2.4.2 install: `npm run download && node-gyp rebuild -v && npm run bundle`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @openzim/libzim@2.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Venipa\AppData\Roaming\npm-cache\_logs\2020-09-21T07_39_47_969Z-debug.log```

**Comment by kelson42** [comment]
I confirm I have problems with buster, not clear what so far. I recommend to use the Docker image https://hub.docker.com/r/openzim/mwoffliner or to use checkout this repo and run it locally.

**Comment by aaronduce** [comment]
Same issue experienced on Ubuntu 20.04, using Node 11.14.0 via nvm.

I then installed make and build-essential via apt and it got further but now fails at gifsicle. See below.

`(node:7242) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
  ⚠ Response code 404 (Not Found)
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c autoreconf -ivf
/bin/sh: 1: autoreconf: not found
...
...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gifsicle@5.1.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gifsicle@5.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aaronduce/.npm/_logs/2020-11-09T11_55_08_091Z-debug.log
`

**Comment by kelson42** [comment]
We will have a look soon, but we use MWoffliner on Docker based on Debian... so not sure exactly what goes wrong.

**Comment by aaronduce** [comment]
Strange, for now I got the archive I needed using docker version instead.

**Comment by kelson42** [comment]
@Venipa @aaronduce The proposed PR shoudl give you the necessary information. Will be merged soon.
