### ISSUE TITLE
Implement images lazy loading

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1264]
This would help to reduce energy consumption:
https://web.dev/native-lazy-loading/

This shoudl be trivial to implement.

Remark: no implementation so far at Mediawiki level, see https://phabricator.wikimedia.org/T230812

**Comment by Jaifroid** [comment]
I think one thing to consider is the extent to which this should be implemented in the ZIM or in the reader. Some browsers (e.g. Chromium) have implemented native lazy loading (see https://www.androidpolice.com/2019/04/08/google-chrome-to-support-lazy-loading-by-default-starting-with-version-75/) whereas others need scripts to help them. Of course a web view is not necessarily the same as a browser, but I thought I should mention this.

**Comment by kelson42** [comment]
@Jaifroid My asumption is that when `<img loading=lazy>` is supported by the browser (Firefox, Chrome) then it will work fine and otherwise this will be ignored (so work like before).
