### ISSUE TITLE
Documentation needs improvement

### ISSUE THREAD

**Issue by kaldari** [openzim/mwoffliner#1282]
The README.md file leaves me with some questions:
* What is included in the HTML snapshot? I'm assuming it's just the article content and not the interface, but does it include images, videos, or audio? Does it include the categories?
* How does it actually scrap the articles? Via the MediaWiki Revisions API?
* Does it always get the latest revisions or can you specify a certain date?
* How does the article selection process work (if you don't want to scrap an entire wiki)? Do you give it a list of articles? A list of revisions? A category?

**Comment by kelson42** [comment]
> The README.md file leaves me with some questions:
> 
>     * What is included in the HTML snapshot? I'm assuming it's just the article content and not the interface, but does it include images, videos, or audio? Does it include the categories?

I will give more details about what can be downloaded, for the rest it scrapes the content, it does not emulate Mediawiki.

Category scraping does not work properly so far: https://github.com/openzim/mwoffliner/issues/829

>     * How does it actually scrap the articles? Via the MediaWiki Revisions API?

Yes, have put a sentence in the README.md about that.

>     * Does it always get the latest revisions or can you specify a certain date?

Yes and no. There is a feature request to specify the revid, see https://github.com/openzim/mwoffliner/issues/982

>     * How does the article selection process work (if you don't want to scrap an entire wiki)? Do you give it a list of articles? A list of revisions? A category?
