### ISSUE TITLE
Better WebP Polyfill

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1286]
Discussing about WebP polyfill with @Jaifroid of the Kiwix JS team, it appears we could be smarter in the way we test and introduced the polyfill scripts.

This would allow us to:
* Don't modify the DOM
* Avoid loading the polyfill in memory if this is not used.

The discussion runs here:
https://github.com/kiwix/kiwix-js/issues/650

But the key comment is the one by @Jaifroid showing us how this could be done concretly:
https://github.com/kiwix/kiwix-js/issues/650#issuecomment-706704503

The MWoffliner code should be changed that way. I believe this code could be introduced in `res/script.js`

**Comment by Jaifroid** [comment]
Sorry about not having time to engage this week -- all a bit mad at the moment. If you need anything testing at the weekend, let me know.
