### ISSUE TITLE
On WikiMed ZIM it looks likes redirects are scraped but links to redirect are removed

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1289]
For example:
in https://en.wikipedia.org/wiki/Book:Cancer, the link to "Colon cancer" exists

In the ZIM:
http://library.kiwix.org/wikipedia_en_medicine_maxi/A/Book%3ACancer it is black,

although:
http://library.kiwix.org/wikipedia_en_medicine_maxi/A/Colon%20cancer exists.

I believe there is a problem of article id comparison (with or without space/underscore).

**Comment by devangmukherjee** [comment]
Hi, I would like to work on this. Can you please tell me where can I find the code related to this?
