### ISSUE TITLE
Does Docker/Zimfarm uses Redis via TCP or Socket?

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1293]
Since #1163, MWoffliner uses default Redis localhost port (so no custom socket anymore).

I wonder if we use now socket:
* in Docker?
* in Zimfarm?

To me it seems not, but I’m unsure.

**Comment by kelson42** [comment]
@rgaudin Are you able to comfirm?

**Comment by rgaudin** [comment]
dockerfile clearly shows that it uses the socket

**Comment by kelson42** [comment]
https://github.com/openzim/mwoffliner/blob/42ca4ece88358f5a1f668c3f702be1b89a369e0c/docker/node_redis-entrypoint.sh#L5 It seems it listen ob both socket and txp?!

**Comment by rgaudin** [comment]
I wrote `Dockerfile`.

https://github.com/openzim/mwoffliner/blob/42ca4ece88358f5a1f668c3f702be1b89a369e0c/docker/Dockerfile#L31

To me, unless the `REDIS` env is set, it uses socket.
