### ISSUE TITLE
mwoffliner Cloud VPS project?

### ISSUE THREAD

**Issue by sivaraam** [openzim/mwoffliner#1298]
Wikimedia's [Cloud VPS](https://wikitech.wikimedia.org/wiki/Portal:Cloud_VPS) service is doing a [cleanup for 2020](https://wikitech.wikimedia.org/wiki/News/Cloud_VPS_2020_Purge#mwoffliner). While browsing through the [currently unclaimed list of projects](https://lists.wikimedia.org/pipermail/wikitech-l/2020-November/094014.html), I noted that [mwoffliner](https://wikitech.wikimedia.org/wiki/News/Cloud_VPS_2020_Purge#mwoffliner) is one of them. I'm not sure if that project is maintained by the mwoffliner project or not. So, I thought of checking here. If this isn't the right place, let me know what would be a more appropriate place to ask this.

If it's needed, kindly claim it by following the [instructions in the cleanup page](https://wikitech.wikimedia.org/wiki/News/Cloud_VPS_2020_Purge#What_we_need_from_you). If this isn't related, then apologies for the noise.

**Comment by kelson42** [comment]
@sivaraam Thank you for the warning, I missed that news. I have updated the page, https://wikitech.wikimedia.org/w/index.php?title=News%2FCloud_VPS_2020_Purge&type=revision&diff=1887719&oldid=1887671.
