### ISSUE TITLE
Internal links loop back to landing page

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1300]
Tried with Termux Wiki https://github.com/openzim/zim-requests/issues/307
and got https://farm.openzim.org/pipeline/5faac766ae273d23c74cd243

There are some minor layout issues and the wiki is surprisingly small (1.7Mb) but most importantly when clicking on any link on the front page (e.g. "getting started") I get sent back.. to the front page.

**Comment by kelson42** [comment]
I confirm the problem. Really Funky. First time I see this.

**Comment by kelson42** [comment]
We have the same problem with vikidia, so this is a regression we have introduced recently.
