### ISSUE TITLE
Docker container does not return if resource timeout

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#131]
The stderr is 

`
Unable to download content [1] https://bm.wikipedia.org/wiki/Mediawiki:offline.css?action=raw (statusCode=403).\nUnable to download content [2] https://bm.wikipedia.org/wiki/Mediawiki:offline.css?action=raw (statusCode=403).\nUnable to download content [3] https://bm.wikipedia.org/wiki/Mediawiki:offline.css?action=raw (statusCode=403).\nAbsolutly unable to retrieve async. URL: Unable to download content [3] https://bm.wikipedia.org/wiki/Mediawiki:offline.css?action=raw (statusCode=403).\nUnable to download content [1] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-silver-star.png?70a8c (statusCode=404).\nUnable to download content [1] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-golden-star.png?ed948 (statusCode=404).\nUnable to download content [1] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-problematic.png?f3177 (statusCode=404).\nUnable to download content [2] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-silver-star.png?70a8c (statusCode=404).\nUnable to download content [1] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-proofread.png?e81f9 (statusCode=404).\nUnable to download content [2] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-golden-star.png?ed948 (statusCode=404).\nUnable to download content [2] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-problematic.png?f3177 (statusCode=404).\nUnable to download content [3] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-silver-star.png?70a8c (statusCode=404).\nAbsolutly unable to retrieve async. URL: Unable to download content [3] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-silver-star.png?70a8c (statusCode=404).\nUnable to download content [2] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-proofread.png?e81f9 (statusCode=404).\nUnable to download content [3] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-problematic.png?f3177 (statusCode=404).\nAbsolutly unable to retrieve async. URL: Unable to download content [3] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-problematic.png?f3177 (statusCode=404).\nUnable to download content [3] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-golden-star.png?ed948 (statusCode=404).\nAbsolutly unable to retrieve async. URL: Unable to download content [3] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-golden-star.png?ed948 (statusCode=404).\nUnable to download content [1] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-validated.png?6232c (statusCode=404).\nUnable to download content [3] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-proofread.png?e81f9 (statusCode=404).\nAbsolutly unable to retrieve async. URL: Unable to download content [3] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-proofread.png?e81f9 (statusCode=404).\nUnable to download content [2] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-validated.png?6232c (statusCode=404).\nUnable to download content [1] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-digitaldocument.png?d1c50 (statusCode=404).\nUnable to download content [2] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-digitaldocument.png?d1c50 (statusCode=404).\nUnable to download content [3] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-digitaldocument.png?d1c50 (statusCode=404).\nAbsolutly unable to retrieve async. URL: Unable to download content [3] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-digitaldocument.png?d1c50 (statusCode=404).\nUnable to download content [3] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-validated.png?6232c (request error: Error: connect ETIMEDOUT 208.80.154.224:443 ).\nAbsolutly unable to retrieve async. URL: Unable to download content [3] http://bm.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-validated.png?6232c (request error: Error: connect ETIMEDOUT 208.80.154.224:443 ).\nFailed to start to optim /cac/wikipedia_bm/m/ca6b55aa215de053445a.png. Size should be 293 (331)\nUnable to download content [1] http://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Fratelli_Lumiere.jpg/220px-Fratelli_Lumiere.jpg (request error: Error: connect ETIMEDOUT 208.80.154.240:80 ).\nUnable to download content [1] http://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Tanzania_in_its_region.svg/300px-Tanzania_in_its_region.svg.png (request error: Error: connect ETIMEDOUT 208.80.154.240:80 ).\n
`

**Comment by automactic** [comment]
Never mind, I think it was because I have some resource timeout, and the container is still running

**Comment by automactic** [comment]
So far, the container has been running for 15 mins, still haven't exited. The mwURL I am using is `https://bm.wikipedia.org/`. I understand this could totally be problem with my internet. But I was wondering if anyone have seen anything similar?

**Comment by automactic** [comment]
that container has been running for 6 hours, still stuck

**Comment by kelson42** [comment]
Really strange, this looks more like a system error than a software error. Would be great to get a shell in the container and see what goes wrong.

**Comment by ISNIT0** [comment]
@automactic Is this still an issue?
