### ISSUE TITLE
Wpes should not use parsoid 

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1318]
https://farm.openzim.org/pipeline/506d67c207825269cd729cf5/debug

Why api is not detected?

**Comment by kelson42** [comment]
This was a configuration problem.

**Comment by kelson42** [comment]
@MananJethwani Would you be able to check if the `--customMainpage` does not point to a HTTP 404 or even a redirection? We should in `sanitizeArguments` be able to verify that it gets a proper HTTP 200 response.

**Comment by MananJethwani** [comment]
@kelson42 sure
