### ISSUE TITLE
Article heading doesn't appear when we use Desktop Rest Api

### ISSUE THREAD

**Issue by MananJethwani** [openzim/mwoffliner#1325]

**Comment by kelson42** [comment]
Actually, this is a feature. The feature is that: on the welcome page we don't want to see the title. We should be able to specify if we want the title or not, independently of the kind of API.

**Comment by kelson42** [comment]
Here clearly the solution is that the Desktop Rest Render should keep the article title `h1`. The removal of the title `h1` should not be related to the desktop rendering. We should somehow apply a dedicated treatment if the article is main article.

**Comment by kelson42** [comment]
Pretty sure this has been fixed. I will verify
