### ISSUE TITLE
lowtechlab is broken

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1326]
lowtechlab_fr_all_maxi_2020-11.zim seems broken.

**Comment by kelson42** [comment]
@MananJethwani Maybe it even work fine now after our fixes. Here is the recipe https://farm.openzim.org/recipes/lowtechlab_fr

**Comment by MananJethwani** [comment]
@kelson42 will check it once

**Comment by holta** [comment]
Just fyi the new ZIM file from [2020-12-14](http://download.kiwix.org/zim/other/lowtechlab_fr_all_maxi_2020-12.zim) remains broken, as seen here:

http://iiab.me/kiwix/lowtechlab_fr_all_maxi_2020-12/

**Comment by MananJethwani** [comment]
@holta yes thanks for the information we are still working on this and have discussed it on slack will try to resolve it asap

**Comment by kelson42** [comment]
@holta @MananJethwani This a problem on their backend, see my comment at https://github.com/openzim/zim-requests/issues/270#issuecomment-750906774. Closing this as duplicate, there is nothing wrong in MWoffliner.

**Comment by holta** [comment]
Sad News.

But thanks @kelson42 for the update!
