### ISSUE TITLE
method to stop scrapping when lot of article fail from rendering needed

### ISSUE THREAD

**Issue by MananJethwani** [openzim/mwoffliner#1329]
while scrapping mdwiki [offliner command available here](https://farm.openzim.org/recipes/mdwiki/config)
due to slow mdwiki server rendering of many articles fails.

logs are provided in file given below

[2020-12-17.txt](https://github.com/openzim/mwoffliner/files/5705509/2020-12-17.txt)

**Comment by kelson42** [comment]
@MananJethwani It looks like we will have to implement this quickly as we generate ZIM file with missing content and user legitimly complain about that.

**Comment by MananJethwani** [comment]
@kelson42 sure I will start working on it
