### ISSUE TITLE
WikiMed zim still contains link to php script

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#133]
I am using `wikipedia_en_medicine_novid_2017-08.zim`, during article loading process, the following resource is loaded.
`
/load.php?debug=false&lang=en&modules=jquery.accessKeyLabel%2Cclient%7Cmediawiki.RegExp%2Cnotify%2Cstorage%2Cutil%7Cuser.defaults&skin=vector&version=1d1t2eb
`

**Comment by automactic** [comment]
For example, if load main page, the following resources are requested
`
kiwix://161bebed-8b09-515f-2d3e-15837b5396fa/A/Wikipedia:WikiProject_Medicine_Open_Textbook_of_Medicine2.html
kiwix://161bebed-8b09-515f-2d3e-15837b5396fa/-/s/css_modules/ext.cite.a11y.css
kiwix://161bebed-8b09-515f-2d3e-15837b5396fa/-/s/css_modules/ext.cite.styles.css
kiwix://161bebed-8b09-515f-2d3e-15837b5396fa/-/s/css_modules/skins.minerva.base.reset%7Cskins.minerva.content.styles%7Cext.cite.style%7Cmediawiki.page.gallery.styles%7Cmobile.app.pagestyles.android%7Cmediawiki.skinning.content.parsoid.css
kiwix://161bebed-8b09-515f-2d3e-15837b5396fa/-/s/css_modules/mobile.css
kiwix://161bebed-8b09-515f-2d3e-15837b5396fa/-/s/css_modules/content.parsoid.css
kiwix://161bebed-8b09-515f-2d3e-15837b5396fa/-/s/css_modules/inserted_style_mobile.css
kiwix://161bebed-8b09-515f-2d3e-15837b5396fa/I/m/MedLogoNoWiFi.png
kiwix://161bebed-8b09-515f-2d3e-15837b5396fa/-/j/js_modules/jsConfigVars.js
kiwix://161bebed-8b09-515f-2d3e-15837b5396fa/-/j/js_modules/startup.js
kiwix://161bebed-8b09-515f-2d3e-15837b5396fa/-/j/js_modules/jquery.js
kiwix://161bebed-8b09-515f-2d3e-15837b5396fa/-/j/js_modules/mediawiki.js
kiwix://161bebed-8b09-515f-2d3e-15837b5396fa/-/j/js_modules/site.js
kiwix://161bebed-8b09-515f-2d3e-15837b5396fa/-/j/js_modules/ext.cite.a11y.js
kiwix://161bebed-8b09-515f-2d3e-15837b5396fa/w/load.php?debug=false&lang=en&modules=jquery.accessKeyLabel%2Cclient%7Cmediawiki.RegExp%2Cnotify%2Cstorage%2Cutil%7Cuser.defaults&skin=vector&version=1d1t2eb
`

**Comment by automactic** [comment]
this issue seems to have been fixed in 2017 Oct zim files

**Comment by automactic** [comment]
the following url is loaded in every article in *.zim
`
/w/load.php?debug=false&lang=en&modules=jquery.accessKeyLabel%2Cclient%7Cmediawiki.RegExp%2Cnotify%2Cstorage%2Cutil%7Cuser.defaults&skin=vector&version=1ckyskj`

**Comment by kelson42** [comment]
I can not reproduce the problem with last mwoffliner. Hope this time the bug is really fixed. That said, that part is pretty sensitive as the calls are made dynamically.
