### ISSUE TITLE
la_chaine_de_maths_et_tiques_fr_all_2020-07.zim seems broken

### ISSUE THREAD

**Issue by tim-moody** [openzim/mwoffliner#1331]
download http://download.kiwix.org/zim/other/la_chaine_de_maths_et_tiques_fr_all_2020-07.zim

kiwix-manage  /tmp/library.xml add /library/zims/content/la_chaine_de_maths_et_tiques_fr_all_2020-07.zim doesn't add anything to the library

result is just <library version="20110515" />

kiwix version is 3.1.2

**Comment by holta** [comment]
Just for comparison this older (much smaller, 7.6GB) ZIM file (la_chaine_de_maths_et_tiques_fr_all_2015-07.zim) generally works, as seen here:

http://iiab.me/kiwix/la_chaine_de_maths_et_tiques_fr_all_2015-07/

ASIDE: does anybody happen to know why the new ZIM files is almost 5X bigger?  (35GB la_chaine_de_maths_et_tiques_fr_all_2020-07.zim)
