### ISSUE TITLE
Xml error in library_zim.xml

### ISSUE THREAD

**Issue by mgautierfr** [openzim/mwoffliner#134]
There are some strange tags in `library_zim.xml`.

For example (not exhaustive) :
- book "kiwix.wikipedia_lo_medicine", "2017-08-06"(id="04283ccc-0138-d1ce-9d63-1d2d2bef8c78") has `tags=""nopic";_ftindex"`.
- book "kiwix.wikipedia_lo_medicine", "2017-08-06"(id="63e41478-6d35-c08a-a5ca-3d40153b4682") has `tags=""=novid";_ftindex"`.

I'm not even sure this is a valid xml file.

As a bonus question : Is the tag `_ftindex` (and so why a `_` ?) or `ftindex` (and there is a error in the xml) ?

**Comment by kelson42** [comment]
@mgautierfr The "=" character comes from a bug in the mwoffliner. I have fixed it there:
https://github.com/openzim/mwoffliner/commit/dbda5bf6531ff7f50800792a54fcc42a27cc7ead

I suspect the problem with the double-quotes comes from "kiwix-manage".

**Comment by kelson42** [comment]
Finally, the double-quoting was also a mwoffliner bug, I have fixed it:
https://github.com/openzim/mwoffliner/commit/c2797e89d86d8b760cf3da44f0c27fba9abf979d

**Comment by mgautierfr** [comment]
There are still errors in the `library_zim.xml`

**Comment by kelson42** [comment]
I do not see that anymore, I suppose all old "broken" ZIM have been replaced meanwhile.
