### ISSUE TITLE
question: optimisationCacheUrl

### ISSUE THREAD

**Issue by tim-moody** [openzim/mwoffliner#1344]
Is there a way to utilize an S3 cache using a kiwix account or must each mwoffliner user have an S3 account? Alternatively can local storage be used for the cache?

**Comment by tim-moody** [comment]
Has anyone tried using an S3 emulator running locally as a cache mechanism?

**Comment by kelson42** [comment]
@tim-moody Kiwix S3 accounts are for Kiwix devs+prod. If you want to benefit from a Kiwix S3 account, then you have to request us to make a ZIM file for you at https://github.com/openzim/zim-requests.

If you or us don't want to rely on our Zimfar to make your ZIM file, then you can do it on your own. Either without cache (but indeed this could be around 3x longer) or by using your own S3 access. You can have one at AWS, we use Wasabi.com and I'm sure you can find other alternatives. If you don't want to have a S3 as SaaS, then you will need to deploy one yourself with MinIO.

Concerning MWoffliner, we had a fs based cache until early 2020. This has been removed for multiple reasons, see https://github.com/openzim/mwoffliner/issues/996. We don't plan so far to re-implement one so far.

**Comment by tim-moody** [comment]
@kelson42 if the mwoffliner docker image provided a means to use MinIO for farmers would it reduce Kiwix costs?

**Comment by kelson42** [comment]
@tim-moody At Kiwix, so far, we don't really want to operate our own S3 cluster. Wasabi.com costs are super competitive. But I believe documenting/ease the use of https://hub.docker.com/r/minio/minio with our MWoffliner Docker image would be a nice improvement for you and many other potential users.

**Comment by tim-moody** [comment]
@kelson42 is it possible to cache images after webp conversion?

**Comment by kelson42** [comment]
@tim-moody The are cached after conversion

**Comment by tim-moody** [comment]
@kelson42 any interest in a deal whereby if you help us implement/integrate minio, we document it?

**Comment by darkenvy** [comment]
@kelson42 , how about this MR? https://github.com/openzim/mwoffliner/pull/1348/files

It adds support for non-SSL connections. Now `--optimisationCacheUrl` works with localhost and/or any setup that doesn't have a SSL cert.
