### ISSUE TITLE
Many articles missing from recent Vikidia zim files

### ISSUE THREAD

**Issue by pyroshroom** [openzim/mwoffliner#1345]
There are many articles missing from vikidia_en_all_maxi_2020-12.zim and vikidia_en_all_maxi_2020-11.zim at https://download.kiwix.org/zim/vikidia/ (Likely a similar issue with the nopic versions judging by the file sizes).

Some example pages missing: Zero; Main page from 2020-12.zim file

The last proper back up that I am aware of from Vikidia was on 2020-08, which was 54.3 MB in size.

**Comment by kelson42** [comment]
I think this is somehow a problem of rendering when the Vikidia backend returns an  error and we just continue. We should probably better die, see #1329

**Comment by kelson42** [comment]
@pyroshroom We have implemented a hard die if upstream backend does not deliver articles, see #1329. I have request a new scraped which should work anyway, see https://farm.openzim.org/pipeline/7d10fdc61172d81fed8d1ff5. Please reopen this ticket if you still see missing articles in the Vikidia in English ZIM file.
