### ISSUE TITLE
Bulbapedia incompletely scraped pages

### ISSUE THREAD

**Issue by pyroshroom** [openzim/mwoffliner#1346]
bulbagarden_en_all_maxi_2020-12.zim at https://download.kiwix.org/zim/other/ is missing the whole table of Pokemon in the article "List of Pokémon by National Pokédex number" - https://library.kiwix.org/bulbagarden_en_all_nopic_2020-12/A/List_of_Pok%C3%A9mon_by_National_Pok%C3%A9dex_number

This table was present on the bulbagarden_en_all_maxi_2020-11.zim

The actual article still has the table: https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_National_Pok%C3%A9dex_number

**Comment by kelson42** [comment]
Hmmm sounds like a duplicate of #1332

**Comment by kelson42** [comment]
@pyroshroom I believe the problem to be fixed now and we have made a new ZIM file of Bulbapedia. See https://library.kiwix.org/bulbagarden_en_all_maxi_2021-01/A/List_of_Pok%C3%A9mon_by_National_Pok%C3%A9dex_number. Please reopen if I'm wrong.

**Comment by pyroshroom** [comment]
Thanks for the update! The files appear to be complete now.
