### ISSUE TITLE
Wikivoyage incompletely scraped pages

### ISSUE THREAD

**Issue by pyroshroom** [openzim/mwoffliner#1347]
This might just be a duplicate of #1332 and #1346

The wikivoyage_en_all_maxi_2020-12.zim is also missing random sections from different articles which were present on the wikivoyage_en_all_maxi_2020-11.zim as well as the original article on wikivoyage.

The Tokyo page in the backup is missing the "Connect" section and the "Cope" section
https://library.kiwix.org/wikivoyage_en_all_maxi_2020-12/A/Tokyo
Which are present here:
https://en.wikivoyage.org/wiki/Tokyo

The Tanzania page is missing the "Get around", "Buy", "Stay Safe" section
https://library.kiwix.org/wikivoyage_en_all_maxi_2020-12/A/Tanzania
Which are present here:
https://en.wikivoyage.org/wiki/Tanzania

**Comment by kelson42** [comment]
@pyroshroom we will generate a new one and see if it looks better. Thank you anyway for the bug report.

**Comment by kelson42** [comment]
@pyroshroom I believe the problem to be fixed now, see with latest ZIM:
* https://library.kiwix.org/wikivoyage_en_all_maxi_2021-01/A/Tokyo
* https://library.kiwix.org/wikivoyage_en_all_maxi_2021-01/A/Tanzania

Thank you for having reported the bug.
