### ISSUE TITLE
should #1348 include parameter list?

### ISSUE THREAD

**Issue by tim-moody** [openzim/mwoffliner#1349]
https://github.com/openzim/mwoffliner/blob/master/src/parameterList.ts

**Comment by kelson42** [comment]
I don't understand this ticket. What is the problem?

**Comment by tim-moody** [comment]
@kelson42 I'm simply asking if changes in #1348 should be reflected in the text of the above parameter list, especially:

optimisationCacheUrl: 'S3 url, including credentials and bucket name',

Based on your response I guess not.

**Comment by kelson42** [comment]
@tim-moody what would be a better description? Still not sure to fully understand.

**Comment by tim-moody** [comment]
How about 

'Remote or local S3 url (assumes https), including credentials and bucket name'

or close if this is not an issue for anyone but me.

**Comment by kelson42** [comment]
@tim-moody I think it would be more helpful to have a new small section in `docker/README.md` about how to use it with a local man.io Docker container.

**Comment by tim-moody** [comment]
OK
