### ISSUE TITLE
Question: are S3 errors a problem

### ISSUE THREAD

**Issue by tim-moody** [openzim/mwoffliner#1358]
with minio as S3 cache I sometimes get errors like:

`[log] [2021-01-02T21:05:40.619Z] Not able to upload upload.wikimedia.org/wikipedia/commons/thumb/5/53/%D0%A1%D0%BE%D0%BB%D0%BD%D0%B5%D1%87%D0%BD%D0%BE%D0%B5_%D0%B7%D0%B0%D1%82%D0%BC%D0%B5%D0%BD%D0%B8%D0%B5_11_%D0%B0%D0%B2%D0%B3%D1%83%D1%81%D1%82%D0%B0_2018_%D0%B3%D0%BE%D0%B4%D0%B0_%D0%B2_%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B5_%28%D0%BF%D0%B0%D1%80%D0%BA_%D0%90%D1%80%D1%82%D1%91%D0%BC%D0%B0_%D0%91%D0%BE%D1%80%D0%BE%D0%B2%D0%B8%D0%BA%D0%B0%29_%28cropped%29.jpg/120px-%D0%A1%D0%BE%D0%BB%D0%BD%D0%B5%D1%87%D0%BD%D0%BE%D0%B5_%D0%B7%D0%B0%D1%82%D0%BC%D0%B5%D0%BD%D0%B8%D0%B5_11_%D0%B0%D0%B2%D0%B3%D1%83%D1%81%D1%82%D0%B0_2018_%D0%B3%D0%BE%D0%B4%D0%B0_%D0%B2_%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B5_%28%D0%BF%D0%B0%D1%80%D0%BA_%D0%90%D1%80%D1%82%D1%91%D0%BC%D0%B0_%D0%91%D0%BE%D1%80%D0%BE%D0%B2%D0%B8%D0%BA%D0%B0%29_%28cropped%29.jpg: XMinioInvalidObjectName: Object name contains unsupported characters.`

What will happen to such an image? Will it just be skipped? Would it be skipped if there were no S3 cache?

**Comment by kelson42** [comment]
@tim-moody Not sure for now, but this kind of error should not happen. Do you which article scraping generates such a bug?

**Comment by tim-moody** [comment]
searching google I got a file name in Cyrillic, but if I copy paste it comes again as a web safe string

![image](https://user-images.githubusercontent.com/5678731/103467203-a523b000-4d1a-11eb-887b-0199956dcc81.png)

**Comment by tim-moody** [comment]
it is too long to search in wp or commons

**Comment by tim-moody** [comment]
gotcha

https://en.wikipedia.org/wiki/Solar_eclipse_of_August_11,_2018

**Comment by kelson42** [comment]
@tim-moody Thx. I will try to reproducete poblem and fix it and answer your otignal question.

**Comment by kelson42** [comment]
@tim-moody I can not reproduce this problem with our S3 provider, maybe there is something you could improve in your Min.io configuration? Concerning the error management, nothing special is made, so I guess nothing will be uploaded and next time it will try again to download/optimize/upload the image.

**Comment by darkenvy** [comment]
It should be noted I too get the same error. But I also get a ton of "Error: file name too long (cmd.StorageErr)" from minio.

**Comment by tim-moody** [comment]
I think the issue is that AWS S3 (and presumably Wasabi) allow object names of up to 1024 characters, including url encoded unicode, see https://stackoverflow.com/questions/6870824/what-is-the-maximum-length-of-a-filename-in-s3.

but minio tries to use the file system for object names and the maximum is 255 chars.
