### ISSUE TITLE
mwUrl is not valid

### ISSUE THREAD

**Issue by jakern** [openzim/mwoffliner#1359]
Running

`sudo docker run -v test:/output:rw --name mwAlpine --detach --cpu-shares 3072 --memory-swappiness 0 --memory 6442450944 ghcr.io/openzim/mwoffliner:1.11.3 mwoffliner --mwUrl="https://wiki.alpinelunx.org/wiki/Main_Page" --adminEmail="contact@kiwix.org" --format="nopic:nopic" --format="novid:maxi" --noLocalParserFallback --osTmpDir="/dev/shm"  --zstd --webp --outputDirectory="/output"
`

simply gives the error in the docker log:
`mwUrl [https://wiki.alpinelinux.org/wiki/Main_Page] is not valid.`

Also fails with just https://wiki.alpinelinux.org. Is mwoffliner limited to Wikipedia?

**Comment by kelson42** [comment]
@jakern It is not limited to Wikipedia. I will try to reproduce the problem.

**Comment by kelson42** [comment]
`--mwUrl="https://wiki.alpinelinux.org/"` should work. Like the doc says:
```
--mwUrl                    Mediawiki base URL.
```

So no a direct link to the main page.

**Comment by kelson42** [comment]
I have generated in our ZIMfarm a recipe for Alpine Linux Wiki at https://farm.openzim.org/recipes/alpinelunx_wiki. New ZIM files should appear soon in our catalog. Let us know if any new problem with MWoffliner.

**Comment by jakern** [comment]
Thank you, I appreciate you. Part of my issue was an embarrassing typo that made it into the recipe name "Lunx". Your updated command in the recipe worked fine for me too.

**Comment by jakern** [comment]
Also, I don't know if you want me to open a separate issue for youzim.it but this seemed to be my issue there. The input asked for the full URL so I entered "https://wiki.alpinelinux.org/wiki/Main_Page" which [errored](https://youzim.it/e56487ddd09f64ab69af0ff5). I tried https://wiki.alpinelinux.org and it [worked](https://youzim.it/0dfb87f03c34a4401b0e1ff5)

**Comment by kelson42** [comment]
Fixed https://farm.openzim.org/recipes/alpinelinux_wiki

**Comment by kelson42** [comment]
@jakern Please open a new ticket for youzim.it. But not in this repo. This is avery different software stack.
