### ISSUE TITLE
Mobile layout breaks references internal links

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#136]
Because the the "references" paragraph is not open. Probably the paragraph should be open on demand, but this is not "easy". The click on the reference links (back and forward) should simply open the paragraph automatically.

**Comment by nataren** [comment]
fwiw, I have seen this on both `android` and `ios`.

**Comment by kelson42** [comment]
This is not really working fine (anymore?) with 1.9.4. It seems to work most of the time, but not always. For example in article "Piracetam" of WPEN. In mobile mode (all section collapsed) if I click on reference 15, in the first section... nothing happen, but if I click on reference 14 just beside it works fine.

**Comment by ISNIT0** [comment]
Am I looking at the same thing as you?
Both [14] and [15] work fine for me on a fresh scrape:
![image](https://user-images.githubusercontent.com/5173131/61202075-70630980-a6de-11e9-9aa0-870d5a534a23.png)

**Comment by kelson42** [comment]
@ISNIT0 Yes... I will try again and upload a ZIM. Have you tried with closed references section?

**Comment by kelson42** [comment]
The problem happens with both [15] links. I have tried again - with last version of Firefox and MWoffliner- and it fails **if the "Notes" section is collapsed**. Otherwise it works fine. On the FF dev console I have the following message:
```
Error: Syntax error, unrecognized expression: #cite_note-(eMC)_2017-15 jquery.js:20:775
    jQuery 9
        error
        tokenize
        select
        Sizzle
        find
        find
        init
        init
        jQuery
    click http://localhost:8080/wikipedia_en_articles_2019-07/-/j/js_modules/script.js:9
    jQuery 2
        dispatch
        handle
``

**Comment by ISNIT0** [comment]
@kelson42 Have you uploaded the zim somewhere?

**Comment by kelson42** [comment]
@ISNIT0 http://tmp.kiwix.org/wikipedia_en_ref_2019-07.zim

**Comment by ISNIT0** [comment]
Odd, with Kiwix for mac both links work fine

**Comment by ISNIT0** [comment]
Possibly an issue with the characters in the ID.
