### ISSUE TITLE
Free registration required - the gray lock is not visible

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1365]
**wikipedia_en_astronomy_maxi_2020-12.zim**
Probably this error is present in other ZIM files from the **English Wikipedia**.
In the English Wikipedia a **gray lock** is sometimes found in the **[References](https://en.wikipedia.org/wiki/Introduction_to_the_mathematics_of_general_relativity#References)**.
It means **Free registration required**:
![Free registration required](https://user-images.githubusercontent.com/65112331/103662149-452a4500-4f78-11eb-904f-98c32223970d.gif)

The gray lock is **not visible** in **Kiwix**:
![Kiwix Free registration required](https://user-images.githubusercontent.com/65112331/103662637-d994a780-4f78-11eb-88e1-4a8827604c62.gif)

P.S. №1: here is an **[example article](https://en.wikipedia.org/wiki/Introduction_to_the_mathematics_of_general_relativity#References)**.
P.S. №2:  the gray lock is **not visible**, but the hint **Free registration required** is still there! Unfortunately, I didn't show it in the picture.

**Comment by kelson42** [comment]
@Ubuntu-2020 Thank you for your bug rerpot, but this is the same bug as #1234
