### ISSUE TITLE
Offline HomePage

### ISSUE THREAD

**Issue by Stamimail** [openzim/mwoffliner#137]
https://sourceforge.net/p/kiwix/feature-requests/894/

In this [Offline HomePage](https://he.wikipedia.org/wiki/%D7%95%D7%99%D7%A7%D7%99%D7%A4%D7%93%D7%99%D7%94:%D7%A2%D7%9E%D7%95%D7%93_%D7%A8%D7%90%D7%A9%D7%99/%D7%9C%D7%90-%D7%9E%D7%A7%D7%95%D7%95%D7%9F) you will be able to find this line:
מעודכן לתאריך: ט' בתשרי ה'תשע"ח, 29/09/2017
Which means: (The ZIM) Updated to date: 2017-09-29

We meant that when this page is scanned to the ZIM file, it will collect the date of that day.
Please check this,
For some reason it doesn't work.

**Comment by kelson42** [comment]
@Stamimail in wikipedia_he_all_2017-05.zim you can find " מעודכן לתאריך: ט' באייר ה'תשע"ז, 05/05/2017". So it works. That said, it is true that if you/we use a cache in mwoffliner this page is not changed. We use less and less the caching system.
