### ISSUE TITLE
Farm returns 404 error eventhough the target site is up

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1380]
I've created this recipe for the [Fire Emblem wiki](https://fireemblemwiki.org/wiki/Main_Page) 

https://farm.openzim.org/recipes/fireemblem/edit

(the recipe was cloned from https://farm.openzim.org/recipes/europa_universalis_iv_en which works fine)

Surprisingly the first run returned a `404 error` even though the Fire Emblem site is up and running. I've then asked zimit to do a run... and it worked: https://farm.youzim.it/pipeline/093450a4ef42d7d0efb49006 

I realize this could be a mwoffliner issue as well, but not sure where's most appropriate.

**Comment by nerkla** [comment]
I am also having issues when trying to get mwoffliner to complete this website:

https://fireemblemwiki.org/

We are using a docker image to run mwoffliner on a digitalocean
instance. For the past week, we have tried to get it complete the job
but can't get it to finish. The farthest that it has gotten is ~25% or
so before it terminates.

The command that we are using is:

```
docker run -v /var/www/mwoffliner/mwoffliner:/output:rw --name few12
--cpu-shares 3072 --memory 7516192768
ghcr.io/openzim/mwoffliner:1.11.3 mwoffliner
--adminEmail="wiksiapps@gmail.com"
--customMainPage="Fire_Emblem_Wiki:About" --customZimDescription="The
community run Fire Emblem encyclopedia." --customZimTitle="Fire Emblem
Wiki" --format="novid:maxi" --mwUrl="https://old.fireemblemwiki.org/"
--optimisationCacheUrl="" --osTmpDir="/dev/shm"
--outputDirectory="/output" --webp --zstd --speed=0.1
```
