### ISSUE TITLE
White stripes on the left and right in Kiwix (part 2)

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1381]
Since the **[previous request](https://github.com/openzim/mwoffliner/issues/1375)** was quickly closed, I decided to create a new request and continue the discussion.

@kelson42
> This is on purpose, we have the Wikipedia mobile layout, see: https://en.m.wikipedia.org/wiki/History_of_Lima. Nothing much we can/want to do here.

Ok.
But there were times when there were no smartphones and Wikipedia articles were **wide**:
![Kiwix-width](https://user-images.githubusercontent.com/65112331/104843497-a2f15200-58d3-11eb-892d-17b26f366d2f.png)

Take a look at the **[statistics for 2016](https://commons.wikimedia.org/wiki/File:Kiwix_2016_Annual_Report.pdf)** and we will see that there are more downloads from desktop computers than from smartphones:
![Kiwix_2016_Annual_Report-page 07](https://user-images.githubusercontent.com/65112331/105357695-dac30700-5bfd-11eb-9206-26116c4261c5.png)

Why focus on the **[mobile version of Wikipedia](https://en.m.wikipedia.org/wiki/Main_Page)**?
After all, in most cases, it is from desktop computers that ZIM files are downloaded!
In my opinion, it would be ideal if the item **_expand the article to the full width of the monitor_** appeared in the **settings** of the Kiwix program. After all, desktop computers have a **very large width of monitors**.

**Comment by kelson42** [comment]
@Ubuntu-2020 I know all of that. Things are moving. You can put comments on closed tickets.
