### ISSUE TITLE
mwoffliner won't complete entire mediawiki site before ending

### ISSUE THREAD

**Issue by nerkla** [openzim/mwoffliner#1383]
I am having issues when trying to get mwoffliner to complete this website:

https://fireemblemwiki.org/

We are using a docker image to run mwoffliner. For the past week, we have tried to get it complete the job
but can't get it to finish. The farthest that it has gotten is ~25% or
so before it terminates. It is a mediawiki site.

The command that we are using is:

```
docker run -v /var/www/mwoffliner/mwoffliner:/output:rw --name few12
--cpu-shares 3072 --memory 7516192768
ghcr.io/openzim/mwoffliner:1.11.3 mwoffliner
--adminEmail="wiksiapps@gmail.com"
--customMainPage="Fire_Emblem_Wiki:About" --customZimDescription="The
community run Fire Emblem encyclopedia." --customZimTitle="Fire Emblem
Wiki" --format="novid:maxi" --mwUrl="https://fireemblemwiki.org/"
--optimisationCacheUrl="" --osTmpDir="/dev/shm"
--outputDirectory="/output" --webp --zstd --speed=0.1
```

Any help would be very much appreciated!

**Comment by kelson42** [comment]
The backend is too slow, we have achieved a first pass at https://farm.openzim.org/pipeline/d7f596c3d2f2423f135c9006

**Comment by nerkla** [comment]
Hi Kelson,

I appreciate you guys helping. It looks like the ZIM file did in fact complete, but I have a bit of an issue. When I went to test the ZIM file in our app, only the search function seems to work - the articles themselves
won't load up at all. They just continue to load indefinitely. Upon further investigation, any chance that it could be the way the ZIM was compiled (maybe not being compatible)?

Strange because our app uses the same code base as the bulbapedia app
which uses an older zim file from mwoffliner that works just fine. The only
thing I can think of is the flag at the end of the mwoffliner command that was used,
--zstd but I'm not sure if this would cause compatibility issues or
not. Any idea what might be going on?
