### ISSUE TITLE
ZIM file compatibility issues?

### ISSUE THREAD

**Issue by nerkla** [openzim/mwoffliner#1384]
Hi there,

I appreciate you guys helping. It looks like the ZIM file did in fact succeed on the zim farm (https://farm.openzim.org/pipeline/d7f596c3d2f2423f135c9006), but I have a bit of an issue. When I went to test the ZIM file in our app, only the search function seems to work - the articles themselves
won't load up at all. They just continue to load indefinitely. Upon further investigation, any chance that it could be the way the ZIM was compiled (maybe not being compatible)? I tested the ZIM in the official kiwix app and it appears to function normally.

Strange because our app uses the same code base as the bulbapedia app
which uses an older zim file from mwoffliner that works just fine (Kelson helped Rashiq create this ZIM file here: https://github.com/openzim/mwoffliner/issues/149). The only
thing I can think of is the flag at the end of the mwoffliner command that was used,
--zstd but I'm not sure if this would cause compatibility issues or
not. Any idea what might be going on?

**Comment by kelson42** [comment]
It is difficult to answer you. The ZIM file being OK, I guess your code is not OK, but I'm not in charge of that code? You should ask the creator of your reader. But "yes" you should probably check that your reader supports the new file encoded using zstd.

**Comment by nerkla** [comment]
Is it possible to please try regenerating the ZIM file without the --zstd flag?

**Comment by kelson42** [comment]
We don't really want to generate new ZIM files using lzma compression, but you can do one yourself or update the reader.

**Comment by nerkla** [comment]
I see, well thank you again for your help Kelson. Really appreciate you taking the time.
