### ISSUE TITLE
The number of articles is less than it should be

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1386]
**wikipedia_ru_all_maxi_2021-01.zim**
There are **1 636 223** articles in this ZIM file:
![wiki-kiwix-zim](https://user-images.githubusercontent.com/65112331/105628169-fe778e80-5e43-11eb-9b10-b92f1f6b9d0c.png)

And there should be [**1 693 088** articles](https://ru.m.wikipedia.org/wiki/Заглавная_страница)!
**56 865** articles are missing.
I think it started at the end of last year when ZIM files became a little bit lighter.
Although in theory, ZIM files should add a little weight.

**Comment by kelson42** [comment]
The way how articles are counted are pretty different, see https://www.mediawiki.org/wiki/Manual:Article_count. On our side, we count all contents with text/html mimetype, but not redirects. This probably explains the differences. I will make a few additional checks.

**Comment by kelson42** [comment]
The scraper reports `A total of [1689371] articles has been found in namespace [0]`. So it looks like that it should have indgested that amount of articles... The counter value is coherent with a similar value `text/html=1689303` at http://library.kiwix.org/wikipedia_ru_all_maxi/M/Counter (Looks like around 50 articles have not been scraped for some reason... maybe deleted in the meantime).

So all looks correct, maybe WPRU has ~60.000 without any wikilinks.
