### ISSUE TITLE
ZIM of wikifab

### ISSUE THREAD

**Issue by dattaz** [openzim/mwoffliner#139]
ZIM of http://wikifab.org/ and http://lab.lowtechlab.org/ (they use wikilab which is based on mediawiki)

**Comment by Popolechien** [comment]
The site is available in five languages, we should generate five separate zim files (it's probably obvious but just in case ^^).

**Comment by kelson42** [comment]
I should have try, but I see two difficulties:
* Multilanguage wiki (with custom solution to switch from one language to an other)
* Video coming from youtube (not supported in mwoffliner)

**Comment by kelson42** [comment]
This issue was moved to openzim/zim-requests#95
