### ISSUE TITLE
TypeError: Cannot set property 'extsrc' of undefined

### ISSUE THREAD

**Issue by senayuki** [openzim/mwoffliner#1394]
{"name":"mwoffliner","hostname":"e2bb2f0818ff","pid":13,"level":30,"logType":"info","wiki":"wiki$0","title":"碧蓝航线:绊爱·ELEGANT","oldId":4507574,"reqId":null,"userAgent":"service-mobileapp-node","msg":"redirecting to revision 4507574 for html","longMsg":"redirecting to revision\n4507574\nfor\nhtml","levelPath":"info","time":"2021-02-02T04:44:54.625Z","v":0}
{"name":"mwoffliner","hostname":"e2bb2f0818ff","pid":13,"level":60,"err":{"message":"","name":"TypeError","stack":"TypeError: Cannot set property 'extsrc' of undefined\n    at Object.modifyArgDict (/tmp/mwoffliner/node_modules/parsoid/lib/ext/Gallery/index.js:400:24)\n    at ExtensionHandler._onDocument (/tmp/mwoffliner/node_modules/parsoid/lib/wt2html/tt/ExtensionHandler.js:188:14)\n    at ExtensionHandler.parseExtensionHTML (/tmp/mwoffliner/node_modules/parsoid/lib/wt2html/tt/ExtensionHandler.js:76:8)\n    at /tmp/mwoffliner/node_modules/parsoid/lib/wt2html/tt/ExtensionHandler.js:147:33\n    at /tmp/mwoffliner/node_modules/parsoid/node_modules/prfun/lib/index.js:593:20\n    at tryCatch1 (/tmp/mwoffliner/node_modules/parsoid/node_modules/babybird/lib/promise.js:40:12)\n    at promiseReactionJob (/tmp/mwoffliner/node_modules/parsoid/node_modules/babybird/lib/promise.js:269:19)\n    at PromiseReactionJobTask.call (/tmp/mwoffliner/node_modules/parsoid/node_modules/babybird/lib/promise.js:284:3)\n    at flush (/tmp/mwoffliner/node_modules/parsoid/node_modules/asap/raw.js:50:29)\n    at processTicksAndRejections (internal/process/task_queues.js:75:11)\n    at runNextTicks (internal/process/task_queues.js:62:3)\n    at processImmediate (internal/timers.js:434:9)","levelPath":"fatal/service-runner/unhandled"},"msg":"Cannot set property 'extsrc' of undefined","time":"2021-02-02T04:44:54.626Z","v":0}
{"name":"mwoffliner","hostname":"e2bb2f0818ff","pid":13,"level":60,"err":{"message":"","name":"TypeError","stack":"TypeError: Cannot set property 'extsrc' of undefined\n    at Object.modifyArgDict (/tmp/mwoffliner/node_modules/parsoid/lib/ext/Gallery/index.js:400:24)\n    at ExtensionHandler._onDocument (/tmp/mwoffliner/node_modules/parsoid/lib/wt2html/tt/ExtensionHandler.js:188:14)\n    at ExtensionHandler.parseExtensionHTML (/tmp/mwoffliner/node_modules/parsoid/lib/wt2html/tt/ExtensionHandler.js:76:8)\n    at /tmp/mwoffliner/node_modules/parsoid/lib/wt2html/tt/ExtensionHandler.js:147:33\n    at /tmp/mwoffliner/node_modules/parsoid/node_modules/prfun/lib/index.js:593:20\n    at tryCatch1 (/tmp/mwoffliner/node_modules/parsoid/node_modules/babybird/lib/promise.js:40:12)\n    at promiseReactionJob (/tmp/mwoffliner/node_modules/parsoid/node_modules/babybird/lib/promise.js:269:19)\n    at PromiseReactionJobTask.call (/tmp/mwoffliner/node_modules/parsoid/node_modules/babybird/lib/promise.js:284:3)\n    at flush (/tmp/mwoffliner/node_modules/parsoid/node_modules/asap/raw.js:50:29)\n    at processTicksAndRejections (internal/process/task_queues.js:75:11)\n    at runNextTicks (internal/process/task_queues.js:62:3)\n    at processImmediate (internal/timers.js:434:9)","levelPath":"fatal/service-runner/unhandled"},"msg":"Cannot set property 'extsrc' of undefined","time":"2021-02-02T04:44:54.627Z","v":0}
{"name":"mwoffliner","hostname":"e2bb2f0818ff","pid":13,"level":60,"err":{"message":"","name":"TypeError","stack":"TypeError: Cannot set property 'extsrc' of undefined\n    at Object.modifyArgDict (/tmp/mwoffliner/node_modules/parsoid/lib/ext/Gallery/index.js:400:24)\n    at ExtensionHandler._onDocument (/tmp/mwoffliner/node_modules/parsoid/lib/wt2html/tt/ExtensionHandler.js:188:14)\n    at ExtensionHandler.parseExtensionHTML (/tmp/mwoffliner/node_modules/parsoid/lib/wt2html/tt/ExtensionHandler.js:76:8)\n    at /tmp/mwoffliner/node_modules/parsoid/lib/wt2html/tt/ExtensionHandler.js:147:33\n    at /tmp/mwoffliner/node_modules/parsoid/node_modules/prfun/lib/index.js:593:20\n    at tryCatch1 (/tmp/mwoffliner/node_modules/parsoid/node_modules/babybird/lib/promise.js:40:12)\n    at promiseReactionJob (/tmp/mwoffliner/node_modules/parsoid/node_modules/babybird/lib/promise.js:269:19)\n    at PromiseReactionJobTask.call (/tmp/mwoffliner/node_modules/parsoid/node_modules/babybird/lib/promise.js:284:3)\n    at flush (/tmp/mwoffliner/node_modules/parsoid/node_modules/asap/raw.js:50:29)\n    at processTicksAndRejections (internal/process/task_queues.js:75:11)\n    at runNextTicks (internal/process/task_queues.js:62:3)\n    at processImmediate (internal/timers.js:434:9)","levelPath":"fatal/service-runner/unhandled"},"msg":"Cannot set property 'extsrc' of undefined","time":"2021-02-02T04:44:54.627Z","v":0}
{"name":"mwoffliner","hostname":"e2bb2f0818ff","pid":13,"level":30,"logType":"info","wiki":"wiki$0","title":"碧蓝航线:绊爱·ELEGANT","oldId":null,"reqId":null,"userAgent":"service-mobileapp-node","msg":"started wt2html","longMsg":"started wt2html","levelPath":"info","time":"2021-02-02T04:44:54.637Z","v":0}
[info] [2021-02-02T04:44:54.639Z] Getting JSON from [https://zh.moegirl.org.cn/api.php?action=parse&format=json&prop=modules%7Cjsconfigvars%7Cheadhtml&page=%E6%88%91%E6%98%AF%E5%AF%82%E5%AF%9E%E7%9A%84%E5%A4%AA%E7%A9%BA%E4%BA%BA]
[log] [2021-02-02T04:44:54.748Z] Exiting with code [1]
[log] [2021-02-02T04:44:54.748Z] Deleting temporary directory [/tmp/mwoffliner-1612239824467]

self-build docker image from commit b58f
`docker run --link=redis:redis --name=mwoffliner -e REDIS="redis://redis" openzim/mwoffliner:latest mwoffliner --verbose --mwUrl="https://zh.moegirl.org.cn" --adminEmail="wiki@moegirl.org" --mwApiPath="/api.php" --customMainPage="Mainpage" --customZimTitle="moegirl" --customZimDescription="moegirl"  --mwWikiPath= --requestTimeout=65530 --optimisationCacheUrl="http://172.17.0.3:9000/?bucketName=mwoffliner&keyId=minioadmin&secretAccessKey=minioadmin"`

**Comment by MananJethwani** [comment]
@senayuki can you point out any particular article or point where this error occurred.

**Comment by MananJethwani** [comment]
@kelson42 the backend seems to be a bit slow and sometimes return 504 error while fetching articles but other than that some modules are not present like `site` or `mediawki.page.galery` maybe because of a different skin or because the configuration doesn't have anything written for `--mwWikiPath=`

**Comment by kelson42** [comment]
@senayuki What about the bug? fixed?

**Comment by senayuki** [comment]
> @senayuki What about the bug? fixed?

The site has now added traffic control, and the bug can no longer be verified (because it will be banned
