### ISSUE TITLE
Feature request: support non-JavaScript HTML browsers

### ISSUE THREAD

**Issue by archenemies** [openzim/mwoffliner#1401]
I'm guessing that "Kiwix" is supposed to sound like "Quick" and it certainly lives up to this name, for me, since I can query it ten times faster than Wiktionary (20 milliseconds vs 200).

However, all of this efficiency is wiped out if I have to load the URL in Firefox (2000 ms).

I prefer to use w3m for browsing text-heavy documents such as Wiktionary and Wikipedia pages; some people prefer lynx or links or other text-based browsers. It's a matter of simplicity, speed, and less distraction.

I don't need JavaScript to read Wiktionary and don't miss it.

In issue #1382, @kelson42 stated that there are no plans to have Kiwix serve a functional table of contents to non-JavaScript browsers. This represents a severe limitation on the usefulness of Kiwix to me, since Wiktionary articles are especially difficult to browse without the table of contents (how do you jump to the desired language in a [multi-language entry](https://en.wiktionary.org/wiki/kasa)?).

Apparently the TOC feature existed in earlier versions of Kiwix, and is presumably technically simpler than whatever is currently under development. I would certainly be pleased to have the earlier behavior restored, and apparently @Ubuntu-2020 is of the same opinion. How can we move in this direction? I'd rather have Kiwix just serve copies of Wiktionary or Wikipedia pages, rather than trying to do anything fancy.

But if you are intent on doing something fancy, why delete the whole table of contents? Why not just put it into a `<div>` which could be hidden with some JavaScript that executes when the document loads in a JavaScript-aware browser? Then everyone could be happy...?

**Comment by kelson42** [comment]
@archenemies How do you measure your 200 ms in Firefox?

**Comment by archenemies** [comment]
Not in Firefox... I hope I wasn't oversimplifying, 20-200 was measured with `wget` on the command-line, and 2000 was opening Firefox while counting to myself.

    $ time wget 'https://en.wiktionary.org/wiki/toll' -O /dev/null >& /dev/null
    wget 'https://en.wiktionary.org/wiki/toll' -O /dev/null >&/dev/null  0.11s user 0.01s system 56% cpu 0.202 total
    $ time wget 'http://localhost:8080/wiktionary_en_all_maxi_2020-12/A/toll' -O /dev/null >& /dev/null
    wget 'http://localhost:8080/wiktionary_en_all_maxi_2020-12/A/toll' -O  >&  0.00s user 0.01s system 70% cpu 0.012 total

This is of course optimistic, when I factor in the time it takes to run w3m and my little Perl script which creates the URL from the command line (a homebrew [SurfRaw](https://en.wikipedia.org/wiki/Surfraw) variant), it's more like 400ms vs 600ms. Most people wouldn't notice 200ms anyway. But I place a high value on responsiveness. I don't like my dictionary lookups to be too suspenseful!

Also, as I said, simplicity is important. With a graphical browser I get nice typesetting, but distracting side-bars, headers, and menu-bars; on the terminal I have the consistency of a single font and the speed of a keyboard interface. Unicode support has long been at a state where I can read all the Greek and Hebrew and Arabic in etymologies easily on the terminal. Less than 10% of the time I'll re-open the URL in Firefox to benefit from a more polished formatting, but this is accomplished with a couple of keystrokes I set up one day.

Please let me know if there is anything else I can do to help.

**Comment by kelson42** [comment]
I'm not responsible of the browser UI. You have really simple browser alternatives to Firefox. You can easily run in fullscreen as well as with F11. Kiwix Desktop itself has a really simple UI.

Regarding the speed, if 200ms matters, then I guess that if you stop the js runtime of Firefox, you should get a similar speed of 400ms... I strongly believe as well that the page is visible before the 600ms... Humans are not able to handle less than 100ms... all of this is anyway a pretty reality disconnected discussion.

So we have probably something like 0.1% of the audience which does not run js for various good and bad reasons. They can enjoy the ZIM files and to a large extend we take care that it still works fine without js.

But there might be part of the advanced features missings. This is the result of a tradeoff beetween multiple contraints. I stand on the decision to not include the TOC in the static DOM of Articles.

**Comment by archenemies** [comment]
@kelson42 If I want to compile my own ZIM files with HTML TOC included, what is the last version of your software that can do that?

**Comment by kelson42** [comment]
@archenemies No clue, honestly I can not remember that we had this feature in MWoffliner... maybe in a previous scraper.
