### ISSUE TITLE
Older version or different skins of mediawiki have different modules (Unable to hack startup module)

### ISSUE THREAD

**Issue by MananJethwani** [openzim/mwoffliner#1409]
like in case of https://artofproblemsolving.com/wiki/ the content of startupscript is different most probably because of the older version or the different skin they use.
this causes a problem in resource loading as we hack a startup script considering the latest code in it and also the modules loaded for this version or skin is different newer version are using base modules `mediawiki.base and jquery` while this site uses `mediawiki and jquery`

**Comment by MananJethwani** [comment]
to solve #1402 we need to fix this first

**Comment by MananJethwani** [comment]
@kelson42 do you have anything in mind for what I should do?.....I have one suggestion we should use the mediawiki version to decide which modules to download and how to hack them

**Comment by kelson42** [comment]
@MananJethwani Which version are we talking about here? When this has been released?

**Comment by MananJethwani** [comment]
I am talking about the mediawiki version....if a page is using older mediawiki version the base modules are different look at this here https://farm.openzim.org/pipeline/08b73d234bcd752699fc1606/debug,
it fails because content of startup module is different and names of base module in this different startup module are different...so we should change our method and base modules depending on version and skins

**Comment by kelson42** [comment]
Then we should clearly have a better code to support few different versions.

**Comment by kelson42** [comment]
We have support all the Mediawiki from `1.27.0`. Website `artofproblemsolving.com`use (now) version `1.31`, so it is now supported by MWoffliner. Recipe is here https://farm.openzim.org/recipes/art_of_problem_solving and even if it still fails, this is not because of this problem. If we have problems to hack the startup module on a Mediawiki more recent than `1.27`, then this is a bug and it should be fixed.
