### ISSUE TITLE
Sharp module issue

### ISSUE THREAD

**Issue by gajanangitte** [openzim/mwoffliner#1411]
Hey, i recently tried to run mwoffliner using the src/cli.ts module. i have tried to run it using bash as well as using npm but the error related to sharp module remains.

/home/gajanan/Desktop/gsoc/kiwix/mwoffliner/node_modules/sharp/lib/constructor.js:34
  throw new Error(error);
        ^
Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
Require stack:
- /home/gajanan/Desktop/gsoc/kiwix/mwoffliner/node_modules/sharp/lib/constructor.js
- /home/gajanan/Desktop/gsoc/kiwix/mwoffliner/node_modules/sharp/lib/index.js
- /home/gajanan/Desktop/gsoc/kiwix/mwoffliner/src/mwoffliner.lib.ts
- /home/gajanan/Desktop/gsoc/kiwix/mwoffliner/src/cli.ts

- Run "npm rebuild --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (/home/gajanan/Desktop/gsoc/kiwix/mwoffliner/node_modules/sharp/lib/constructor.js:34:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/gajanan/Desktop/gsoc/kiwix/mwoffliner/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

please help me out with this error : )

**Comment by gajanangitte** [comment]
i had installed it using "npm ci" as well as using "npm i". same problem persists. also, the command "npm rebuild --verbose sharp" is not helping. 

npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'rebuild',
npm verb cli   '--verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@6.14.10
npm info using node@v14.15.3
npm info readInstalled object
npm verb rebuild path, id [
npm verb rebuild   '/home/gajanan/Desktop/gsoc/kiwix/mwoffliner/node_modules/sharp',
npm verb rebuild   'sharp@0.26.2'
npm verb rebuild ]
npm info build /home/gajanan/Desktop/gsoc/kiwix/mwoffliner/node_modules/sharp
npm info lifecycle sharp@0.26.2~preinstall: sharp@0.26.2
npm info linkStuff sharp@0.26.2
npm verb rebuildBundles [ 'node-addon-api' ]
npm info lifecycle sharp@0.26.2~install: sharp@0.26.2
npm info lifecycle sharp@0.26.2~install: ignored because ignore-scripts is set to true sharp@0.26.2
npm info lifecycle sharp@0.26.2~postinstall: sharp@0.26.2
sharp@0.26.2 /home/gajanan/Desktop/gsoc/kiwix/mwoffliner/node_modules/sharp
npm verb exit [ 0, true ]
npm timing npm Completed in 2571ms
npm info ok

**Comment by MananJethwani** [comment]
@gajanangitte can I know what are your machine details?

**Comment by kelson42** [comment]
@gajanangitte I believe you shoukd try to install sharp separatly and if still fail open a ticket on sharp side.

**Comment by gajanangitte** [comment]
@MananJethwani I am using ubuntu 20.04
Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz   2.40 GHz
8gbRam HP paviloin series

**Comment by MananJethwani** [comment]
@gajanangitte can you send me the exact commands you used to try to install mwoffliner, because when I tried it installed without any problem I have set up a VM to reproduce the problem.

**Comment by gajanangitte** [comment]
git clone *repo*
cd mwoffliner
npm ci
./node_modules/.bin/ts-node ./src/cli.ts --mwUrl=https://en.wikipedia.org --adminEmail=gajanansgitte07@gmail.com


i also tried using "npm start" 

same result, updated all npm, nodejs, but to no avail. problem still persists. there was a similar issue raised but the solution which was provided then, isn't helping.

**Comment by MananJethwani** [comment]
can you please delete `node_modules`, `.cache`, `public`  and try these steps again....might be some node related error

also try to build it again using `node-gyp rebuild`

**Comment by kelson42** [comment]
No feedback from the reporter, is anyway not a problem in mwoffliner.
