### ISSUE TITLE
Unable to scrape wiktionary CHR any more

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1419]
https://farm.openzim.org/recipes/wiktionary_chr

Seems to be a 1.11.4 regression

**Comment by MananJethwani** [comment]
@kelson42 this is a problem in the article list we receive, the article which makes it fail is `incarner` you won't be able to find it as it was deleted look [here](https://chr.wiktionary.org/wiki/incarner).
I found another one similar to this name `fiore`

**Comment by kelson42** [comment]
The article list comes from Mediawiki, so what is exactly the problem? Why do we get an article in the namespace which does not exist?
