### ISSUE TITLE
Article titles not visible in wikiquote zim file

### ISSUE THREAD

**Issue by MananJethwani** [openzim/mwoffliner#1421]
article title are not available in the latest zim file for wikiqutoe 
http://library.kiwix.org/wikiquote_af_all_maxi/A/Sarel_Cilliers

**Comment by kelson42** [comment]
@MananJethwani can you please share a fix or an analysis for that one?

**Comment by kelson42** [comment]
This is not a MWoffliner 1.11.4 regression and I suspect this is a direct consequence of the usual problem that we don't know if we deal with json or html....

**Comment by MananJethwani** [comment]
@kelson42 I suppose that's the case but I will make a deeper analysis soon

**Comment by MananJethwani** [comment]
@kelson42 you were right this is because Wikiquote uses desktop rest API so this is a copy of #1325
