### ISSUE TITLE
Wikimedia REST API returns sporadicaly a HTTP 413 error

### ISSUE THREAD

**Issue by MananJethwani** [openzim/mwoffliner#1424]
look at https://farm.openzim.org/pipeline/5f374943c46928031faaf506/debug
while fetching articles using URL like [this](https://hi.wikibooks.org/api/rest_v1/page/html/%E0%A4%B5%E0%A4%BF%E0%A4%95%E0%A4%BF%E0%A4%AA%E0%A5%81%E0%A4%B8%E0%A5%8D%E0%A4%A4%E0%A4%95%3A%E0%A4%9A%E0%A5%8C%E0%A4%AA%E0%A4%BE%E0%A4%B2%2F%E0%A4%B8%E0%A4%AE%E0%A4%BE%E0%A4%9A%E0%A4%BE%E0%A4%B0) we are receiving 413 error @kelson42 any idea how we should resolve it?

**Comment by MananJethwani** [comment]
@kelson42 I asked someone on discord and they replied that it is an issue in mediawiki......also I couldn't find any arguments or query option I should add to avoid this error so I am opening a phabricator ticket for now is that fine with you?

**Comment by kelson42** [comment]
I will have a look.

**Comment by MananJethwani** [comment]
the same response here https://www.mediawiki.org/wiki/Topic:W657nwdmjt0cshfk

**Comment by kelson42** [comment]
@MananJethwani The onky question is where is the phabricator ticket.

**Comment by MananJethwani** [comment]
https://phabricator.wikimedia.org/T280381 opened a ticket

**Comment by kelson42** [comment]
@MananJethwani Thank you, to me this is really a bug on Wikimedia side. Would you be able please to verify if this very specific article is available in past ZIM? This would allow us to see if we face a regression.

**Comment by kelson42** [comment]
Part of the problem has been fixed upstream. An other part will be fixed in two weeks.

**Comment by kelson42** [comment]
Fully fixed upstream
