### ISSUE TITLE
fetching article fails with 400 status code

### ISSUE THREAD

**Issue by MananJethwani** [openzim/mwoffliner#1426]
have a look at https://farm.openzim.org/pipeline/c84d0fa92a4c21b9d25df506/debug
will investigate into it and let everyone know soon

**Comment by MananJethwani** [comment]
@kelson42 can you try to re run scrapping this file once.....I can't complete the scrapping on my local machine it gives me a 503 error most probably due to slow internet speed and I fetched the whole article list by namespace and according to zimfile logs the article on which it fails `function_Object()_{_[native_code]_}` doesn't exist in the list maybe there was a issue and is now resolved please try to scrape it once more

**Comment by MananJethwani** [comment]
@kelson42 the issue is still there and it is because of an article named `constructor` this type of article when called like this
`normalized[page.title]` instead of referring to an article with name constructor refer to the actual constructor of an object.

**Comment by kelson42** [comment]
@MananJethwani Trying to come back on this error, i have difficulties to understand how this explains the 400 error code and how this would fix this other case https://farm.openzim.org/pipeline/e7dc95196b3f34ea443eb806/debug

**Comment by MananJethwani** [comment]
@kelson42 if you look at the image attached below these are the logs for https://farm.openzim.org/pipeline/e7dc95196b3f34ea443eb806/debug in the case of Wiktionary there is no normalize section in article details we fetch, so the normalized array is empty, and hence when we try to find an article named `constructor` in `normalized` the array returns a function as by default all arrays are objects in JS and they have their constructor.

![Screenshot (115)](https://user-images.githubusercontent.com/50267986/116807272-df2d8300-ab4f-11eb-9628-f5d6f8749b24.png)

**Comment by kelson42** [comment]
@MananJethwani Where do you see we try to retrieve an article called `constructor` on hy.wiktionary.org`?
