### ISSUE TITLE
WikiMed zim article section headers not working

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#143]
I downloaded the October wikimed zim and wanted to update my WikiMed app, but sadly none of the article section expands when I tap on the headers.

**Comment by kelson42** [comment]
This is serious, there is a javascript error:
        TypeError: $ is not a function
at line:
        $('#mf-section-'+id).toggleClass('open-block').prev().toggleClass('open-block')

Looks like jquery is not loaded properly!...

@subbuss @darkenvy This is quite urgent and massive problem as this avoid mobile users to read the article content. May you please have a looks  quickly?

http://download.kiwix.org:8080/wikipedia_en_medicine_2017-10
