### ISSUE TITLE
jpg.webp and png.webp instead of jpg and png

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1431]
**At the end of last year**, something changed in the ZIM files.
If earlier it was possible to click on the image and save it, for example, **test.jpg** or **tests.png**, it is now when saving images, they are saved in the format **test.jpg.webp** or **tests.png.webp**.
Question: why **webp**?
I checked it in **wikipedia_en_computer_maxi_2021-03.zim** in ***.appimage 2.0.5**.

P.S.: ***.gif** earlier saved and now saved in the ***.gif**

**Comment by MananJethwani** [comment]
@Ubuntu-2020 this is no bug but a feature, webp format takes less storage space so now mwoffliner compresses jpeg and png to webp format

**Comment by kelson42** [comment]
...and it is still possible to save them.
