### ISSUE TITLE
Selecting text in a section title cause the section to collapse

### ISSUE THREAD

**Issue by zkosk** [openzim/mwoffliner#1438]
When selecting some text in the title of a section, the selecting action also trigger a click event which collapse the section. Not sure whether the online version behave like this, but selecting text in some section title should not trigger the click event on the title.

This should be a problem of kiwix-serve, not the off liner.

**Comment by kelson42** [comment]
@zkosk I can not confirm this behaviour with Kiwix serve. For example http://library.kiwix.org/wikipedia_en_all_maxi/A/Dance with Firefox. What reader do you use?

**Comment by kelson42** [comment]
No feedback or other complaints about that. Closing.
