### ISSUE TITLE
Template incorrectly removed from Wikimed Mini

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#144]
The template {{infobox medical intervention}} is incorrectly parsed in Wikimed Mini (see image
). 

Interestingly, the template specifies "infobox" but the remaining string only says "template Medical intervention", although {{Medical intervention}} did not exist (I've since created it as a redirect). 

![template3](https://user-images.githubusercontent.com/21675885/31376444-496b515e-ada5-11e7-8780-14ae0e871633.png)

**Comment by kelson42** [comment]
@Popolechien I can not really explain that problem... but it seems to not happen anymore with a newly created ZIM file. Probably a temporary problem with the wiki text or a problem which has been fixed meanwhile in Parsoid or MWoffliner. Thx for the report.
