### ISSUE TITLE
question re: anecdote on mdwiki

### ISSUE THREAD

**Issue by tim-moody** [openzim/mwoffliner#1440]
I am recording this in case it is relevant.

https://github.com/openzim/mwoffliner/blob/d98d04b46abab217831f72b3ae5e53777a988040/src/Downloader.ts#L145

looks like retry logic. I added 503 to the list of status codes and ran mwoffliner against mdwiki.

Nothing broke and it ran to completion, whereas it had failed before often timing out on some articles. (I admit not all timeouts come back as bad gateway.)

If this line is indeed the retry conditions would it make sense to broaden them or even always retry?

**Comment by kelson42** [comment]
@tim-moody If you add `503` to the list of code `400, 403, 404` then it just pass through. Which means there was an error in the Mediawiki backend, the rendering is not proper but this is tolerated by MWoffliner. But the ZIM is broken and this is just a matter of time before someone remarks it and opens a bug. This is I believe exactly what I have explained in #1372.

**Comment by tim-moody** [comment]
@kelson42 Yes, this is similar to a previous issue. The reason I have raised it again is that according to the hosting company articles that timeout and fail will likely succeed on retry as the hosting server will have loaded its cache and not timeout.

Are you saying I have not understood the app and that it will not retry when it encounters one of the codes listed?

**Comment by kelson42** [comment]
@tim-moody yes, @MananJethwani you confirm?

**Comment by MananJethwani** [comment]
@tim-moody please have a look closely that line goes something like `![400, 403, 404].includes(err.response?.status)` there is `!` which means it is already retrying for 503

**Comment by tim-moody** [comment]
@MananJethwani yes. you're right I got it backwards. sorry. I realized it after the ticket was closed, but didn't reply.
