### ISSUE TITLE
Unable to scrap fandom/wikia wiki

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1444]
[fd9cd](https://farm.openzim.org/pipeline/fd9cd3c65404da2e73c9e706) returns 404 error (not found).

Interestingly, though the URL input is `https://minecraft.fandom.com/de/wiki/Minecraft_Wiki` it crashed because it looked for `https://minecraft.fandom.com/de/wiki/Minecraft_Wiki/index.php`

**Comment by uriesk** [comment]
@kelson42 fixed that in #1707 and https://github.com/openzim/zim-requests/issues/543
