### ISSUE TITLE
Creating ZIM file from old MediaWiki server

### ISSUE THREAD

**Issue by williamjshipman** [openzim/mwoffliner#1447]
I have a very old MediaWiki server work from which I'd like to create a ZIM file for offline reading. The MediaWiki version is 1.16.0. I do realise that this is so old it is not even on the [MediaWiki release timeline](https://www.mediawiki.org/wiki/Version_lifecycle), but is it possible to use MWOffliner to create a ZIM file from this wiki? Here's what I've managed so far. I'm using the default docker image: ```docker pull openzim/mwoffliner```. Running the following command:

`docker run -ti openzim/mwoffliner mwoffliner --mwUrl "http://[ServerName]/[WikiName]" --mwWikiPath=/ --adminEmail Me@work.com --mwUsername [UserName] --mwPassword [Password] --verbose --mwApiPath=api.php --forceLocalParser`

Generated the following error:

`starting redis-server in the background…
[log] [2021-04-25T12:43:23.328Z] closing sanitize redis DB
[log] [2021-04-25T12:43:23.329Z] Starting mwoffliner v1.11.4...
[info] [2021-04-25T12:43:23.332Z] Using custom flavour: no
[info] [2021-04-25T12:43:23.333Z] Downloading [http://[ServerName]/[WikiName]/api.php?action=query&meta=tokens&type=login&format=json]
Failed to run mwoffliner after [0s]: {
        "stack": "SyntaxError: Unexpected token ﻿ in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at MediaWiki.<anonymous> (/tmp/mwoffliner/lib/MediaWiki.js:81:39)\n    at Generator.next (<anonymous>)\n    at fulfilled (/tmp/mwoffliner/lib/MediaWiki.js:24:58)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
        "message": "Unexpected token ﻿ in JSON at position 0"
}

**********

Unexpected token ﻿ in JSON at position 0

**********`

Running the API query in my browser generated the following response from the wiki:

`{"warnings":{"query":{"*":"Unrecognized value for parameter 'meta': tokens"}}}`

From the API help, it seems that my outdated version doesn't support that tokens value for meta, it only supports `siteinfo`, `userinfo` and `allmessages`.

Is there a workaround? Of course, other than upgrading the server. If not, well that's understandable.

**Comment by kelson42** [comment]
@williamjshipman It is probably too old. We have a minimal Mediawiki version supported and we should print the appropriate message... not clear why you don't get it here. @MananJethwani any idea?

**Comment by MananJethwani** [comment]
@kelson42 I need to have a look at the metadata URL to understand the core of this problem may be there is no key named generator present in the older version of MediaWiki in that case also we should fail. but, this is just an assumption I need a proper URL to understand the main problem.

**Comment by kelson42** [comment]
@MananJethwani Does not really matter, minimum Mediawiki version is anyway 1.27, so this is a Mediawiki which is to old. @williamjshipman Update your Mediawiki and then this should be OK.

**Comment by MananJethwani** [comment]
@kelson42 you are right but we should add a check that if mediawiki version is present under some other key we should fail. wouldn't that be the right thing to do?

**Comment by kelson42** [comment]
@MananJethwani We fail... yes you are right. Would you be able to implement that quickly?

**Comment by MananJethwani** [comment]
yeah sure will make a pr.

**Comment by williamjshipman** [comment]
Thanks. Not too surprised. I decided to give some older versions of MWOffliner a try, but no luck either. Oh well, will leave it for after I upgrade that server.
