### ISSUE TITLE
Links not working on Wikimed front page

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1459]
Weird issue here on [wikipedia_en_medicine](http://library.kiwix.org/wikipedia_en_medicine_maxi_2021-04) (but also Wikimed app in English 2020-11 build 6203070): frontpage link to Eye Disease does work (as well as Mental Health and Skin disease  on the app). The text appears in blue but is not clickable. No such issue [on the original page](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Medicine/Open_Textbook_of_Medicine2). 

It could be because it pointed to a redirect (Book:Ophthalmology) but the latter two are not redirects.

**Comment by kelson42** [comment]
Yes, I have seen this but the explanation is not obvious :(
