### ISSUE TITLE
MWoffliner only picks up landing page

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1461]
I ran a [chabadpedia](https://farm.openzim.org/pipeline/0870e3084c6327bb4e7f8906) recipe which landed a zim file after a few minutes without apparent incident. 

It appears however than none of the frontpage links (though they appear as hyperlink) is clickable, and that only that page was in fact scraped. Clicking on links leads to no apparent action, and the zim file is only 1.17 Mb. From the log, it looks like all links returned a 404.

**Comment by kelson42** [comment]
@MananJethwani We ahould really have a look to this one as users get broken ZIM files.

**Comment by MananJethwani** [comment]
@kelson42 this is a regression caused by https://github.com/openzim/mwoffliner/pull/1443
 I looked into the URLs before this change and after it, I found they were exactly the same but strangely it passed without the change and failed with the change.

**Comment by kelson42** [comment]
@MananJethwani I'm sure you will find out :)
