### ISSUE TITLE
offliners should add categories to tags

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#147]
It would be very useful for offliners to add categories to zim files. For example, wikipedia, Wikibooks, etc. Kiwix apps could use this info to group books into categories to better manage them.

We could simply add this to tags attribute. But a better (and maybe correct way) is to create a category attribute and add to the book elements.

**Comment by kelson42** [comment]
Yes, will do that soon.

**Comment by tim-moody** [comment]
@kelson42 Yes. I prefer a category attribute to simply creating a tag and would like these to be human readable, so Wikipedia, not wikipedia, PhET, not phet, etc.

**Comment by kelson42** [comment]
done, but everything lowercase as the information comes from the hostname (so far)
