### ISSUE TITLE
Is it possible to create a ZIM file from a MediaWiki dump?

### ISSUE THREAD

**Issue by kmpoppe** [openzim/mwoffliner#1473]
Hello everyone,

I would like to create an offline ZIM for a Wiki that has very strict API limits and where I currently have no way of implementing mwoffliner at the source of the Wiki.

Fortunately, the Wiki provider creates a dump file (4.5 Gig) every night.

Is there any feasible way to create a ZIM file from said dump WITHOUT going through the pain of importing it into a locally running L/A/M/P for MediaWiki?

Any information is greatly appreciated!

Kai

**Comment by kelson42** [comment]
@kmpoppe Hi, no it is not possible with MWoffliner which works with the Mediawiki APIs. I'm not well informed about other ways which would avoid the Mediawiki import stage.

**Comment by Jaifroid** [comment]
@kmpoppe I have never tried it, but I understand Xowa (https://github.com/gnosygnu/xowa) can read Wiki dumps if downloaded in the format it understands. It looks like it **might** serve pages from the dump. Whether those pages could then be accessed outside of the prgoramme (i.e. if it serves them to a browser) is for you to research! If that is possible, or the software can be modified to make it possible (it is Open Source), you could have a way to set mwoffliner loose on the served pages. It would probably be a major project...

**Comment by kmpoppe** [comment]
@Jaifroid I'll check whether Xowa would help.

By the way (also @kelson42), the mwoffliner used by Kiwix in their ZIMfarm, trying to download said specific wiki fails miserably since about 3 months. Protocols are [here](https://farm.openzim.org/pipeline/dcdbc3304296788d35d11a06/debug), [here](https://farm.openzim.org/pipeline/728cc38399f46f34a6c37a06/debug), [here](https://farm.openzim.org/pipeline/0063040dac22ebc88de31806/debug) and [here](https://farm.openzim.org/pipeline/880246c69e91ffe9dc82f606/debug).

In openstreetmap/operations#536 I was asking, whether the API limits that seem to be hit could be lifted, I provided an example:
```
[error] [2021-04-08T16:05:38.013Z] Error downloading article Oc:Elements_cartografics
Failed to run mwoffliner after [243s]: {
	"code": "apierror-visualeditor-docserver-http-error",
	"info": "⧼apierror-visualeditor-docserver-http-error⧽",
	"*": "See https://wiki.openstreetmap.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes."
}
```
Yet, we are unsure as to why this is happening, as seemingly a totally different script seems not to be hitting any Limits.

Is there any way to get more meaningful information as to what and why mwoffliner keeps failing downloading this specific Wiki?

Kai

**Comment by matkoniecz** [comment]
> Yet, we are unsure as to why this is happening, as seemingly a totally different script seems not to be hitting any Limits.

To be clear my script retries on encountering errors (and some are typically encountered)

**Comment by kmpoppe** [comment]
@kelson42 May I direct your attention to the error log I posted - I don't understand what's going wrong with the apierror-visualeditor - because it fails with that exact same error at different times. Would you be able to provide any more insight as to what's going wrong?

**Comment by kelson42** [comment]
@kmpoppe please open a new ticket
