### ISSUE TITLE
mwoffliner returns 404 error on perfectly functional website

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1475]
See https://farm.openzim.org/pipeline/597cc39f2dce2672b550eb06/debug trying to scrape https://www.svrwiki.com/Main_Page

Not sure if it is the `bug fixing` or `enhancement` tags that is most appropriate, but at the very least the error log should be a little more specific as to what happened.

**Comment by kelson42** [comment]
--mwUrl is obviulsy wrong.
