### ISSUE TITLE
Missing images in custom Wikipedia scrap

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1477]
When generating a test zim file from https://farm.openzim.org/recipes/wikipedia_en_for_schools the corresponding zim file seems to have missed an image.
I ran the recipe twice, and the same image (https://en.wikipedia.org/wiki/Wikipedia:Wikipedia_for_Schools/Welcome/Mathematics#/media/File:Fisher_iris_versicolor_sepalwidth.png) is always missing:
![Capture d’écran 2021-06-08 à 14 55 48](https://user-images.githubusercontent.com/21675885/121188743-af1d8200-c869-11eb-9a22-62fbf9170499.png)

**Comment by Popolechien** [comment]
Transferred to [Kiwix-android](../../../kiwix/kiwix-android/issues/2664) and [Kiwix-JS](../../../kiwix/kiwix-js/issues/730)

**Comment by Popolechien** [comment]
Bug is upstream: https://en.wikipedia.org/api/rest_v1/page/html/Wikipedia%3AWikipedia_for_Schools%2FWelcome%2FMathematics

@kelson42 Does this mean we should close this ticket?

**Comment by kelson42** [comment]
This is indeed an upstream bug, see ticket https://phabricator.wikimedia.org/T284570

**Comment by kelson42** [comment]
Actually, it seems this upstream bug has already been report 2 years ago. See https://github.com/openzim/mwoffliner/issues/616

**Comment by kelson42** [comment]
Looks good in latest scrape.
