### ISSUE TITLE
Wikipedia cite/ref links are not rewritten properly

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#148]
The local anchor (#foobar) is simply squeeze from the URLs. I strongly suspect the piece of code which was responsible for that:
https://github.com/openzim/mwoffliner/blob/master/lib/mwoffliner.lib.js#L1333

Is not applying anymore because of this test:
https://github.com/openzim/mwoffliner/blob/master/lib/mwoffliner.lib.js#L1328

I suspect this regression has been introduced during the refactoring effort.

**Comment by subbuss** [comment]
Looking at the old code ( https://github.com/openzim/mwoffliner/blob/5affd206485fe259c9ca54ed57fb6bf7c1d6de80/lib/mwoffliner.lib.js#L1509-L1525 ) and the new code ( https://github.com/openzim/mwoffliner/blob/master/lib/mwoffliner.lib.js#L1328-L1344 ), I don't see any code changes in the refactoring. So, I suspect this is unrelated to the refactor.

It could be that the code has not kept up with Parsoid HTML output changes, but that can be investigated separately.

**Comment by kelson42** [comment]
@subbuss You are right, the bug must have been introduced earlier that year... but we still have bug. What is strange is that it occurs only with Desktop view (default) not with mobile view.
