### ISSUE TITLE
English Wikipedia: Article broken

### ISSUE THREAD

**Issue by Inbefortus** [openzim/mwoffliner#1487]
Using Kiwix 3.4.3. ZIM is English Wikipedia 2021-03.

This article https://en.wikipedia.org/wiki/List_of_films_that_most_frequently_use_the_word_%22fuck%22
is broken.

Article in Kiwix:

![Screenshot_20210625-112920_Kiwix](https://user-images.githubusercontent.com/71934042/123404460-4b08f680-d5a9-11eb-8b77-adf413eb6aea.jpg)

Article in original English Wikipedia:
![Screenshot_20210625-113019_Samsung Internet](https://user-images.githubusercontent.com/71934042/123404672-5e1bc680-d5a9-11eb-945b-9da542114b71.jpg)

**Comment by kelson42** [comment]
This was a problem in Wikipedia API render. We need to check what exactly happened there.

**Comment by Inbefortus** [comment]
@kelson42 Update: This seems to be fixed in 2021-11 English Wikipedia (no pic).

http://library.kiwix.org/wikipedia_en_all_nopic/A/List_of_films_that_most_frequently_use_the_word_%22fuck%22

- ![Screenshot_20211124-122514_Samsung Internet](https://user-images.githubusercontent.com/71934042/143236613-888621c8-73e5-4a97-bdbc-46b39488c46d.jpg)
