### ISSUE TITLE
Some "click to show" not working

### ISSUE THREAD

**Issue by zkosk** [openzim/mwoffliner#1500]
For example in the page "Angular_momentum_operator", there are two instance of "Click [show] on the right to see", but there is no "show" to click on the right. The version is around 2021 Q1 maxi "6,134,097 articles in English".

**Comment by kelson42** [comment]
Probably fixed by #1701. I will check.

**Comment by kelson42** [comment]
It seems there is not anymore this in this article but the bug has been fixed a few days ago. It will be available in the next release. `1.12.0`
