### ISSUE TITLE
Deteriorated image quality

### ISSUE THREAD

**Issue by Inbefortus** [openzim/mwoffliner#1509]
The quality of the images is poorer than those in 2021-03 English Wikipedia. I am talking about 2021-02 + 2021-03 + 2021-07 English Wikipedia 0.8 and 2021-07 English Wikipedia Top Articles.

Here are a few examples.

On the left: 2021-03 English Wikipedia
On the right: 2021-07 English Wikipedia 0.8 (and the others)

![ZomboDroid 22072021095419](https://user-images.githubusercontent.com/71934042/126606384-cb569fcb-c077-493d-8049-248b22a328dc.jpg)
![ZomboDroid 22072021095430](https://user-images.githubusercontent.com/71934042/126606405-fabec38b-afee-45b2-bfdf-ffbf09346958.jpg)

This can be seen most clearly in the first image. There is undoubtedly a decline in quality.

You can see it best in the second image when you compare the traffic lights.

Since 2021-02 English Wikipedia 0.8 also gives the equal result, I wonder if this might just be the case, particularly as it's not the major English Wikipedia, and these small "stripped down" versions are intended from the start?

**Comment by kelson42** [comment]
This is done on purpose to reduce the storage size of media files.

**Comment by Inbefortus** [comment]
@kelson42 Okay.

Now, does this apply in the same way specifically to the next big, complete English Wikipedia?

**Comment by kelson42** [comment]
It applies everywhere the same manner

**Comment by Inbefortus** [comment]
@kelson42 All right, then this is settled.
