### ISSUE TITLE
Ubuntu Doc Zim

### ISSUE THREAD

**Issue by MattyBoy4444** [openzim/mwoffliner#151]
I see there is a French Ubuntu Docs zim file at [http://download.kiwix.org/zim/other/ubuntudoc_fr_all_2015-12.zim](url).  What wiki is this from and could we get an update for english?

Thanks.

**Comment by kelson42** [comment]
@MattyBoy4444 This comes from ubuntu-fr.org and was built from a snapshot they had provided. ubuntu-fr.org runs dokuwiki and mwoffliner is for Mediawiki.

Regarding a version in English, please be specific about the website you want to provide offline, but please check first that this runs Mediawiki and that the content is free before opening a ticket here.

All that said, you might be interested by the AskUbuntu ZIM file http://download.kiwix.org/zim/stack_exchange/askubuntu.com_en_all_2017-10.zim
