### ISSUE TITLE
Article scraped incompletely

### ISSUE THREAD

**Issue by Inbefortus** [openzim/mwoffliner#1510]
ZIM: 2021-03 English Wikipedia
         2021-07 English Wikipedia 0.8

This article https://en.wikipedia.org/wiki/1760s is missing a large amount of information, most notably in 2021-03.

2021-03 English Wikipedia:

https://user-images.githubusercontent.com/71934042/126863828-3184543c-9398-4990-a16d-04c26872f47e.mp4

2021-07 English Wikipedia 0.8:

https://user-images.githubusercontent.com/71934042/126863850-a53d7a39-c554-462e-91b0-63d8bcf41389.mp4

Original English Wikipedia:

https://user-images.githubusercontent.com/71934042/126863925-1b20e8ec-ab97-4b5e-81da-f0de0b8c5c45.mp4

It looks like everything that follows past this error is not scraped. Both versions output a different variant.

2021-03 English Wikipedia:

![Screenshot_20210724-111742_Samsung Internet](https://user-images.githubusercontent.com/71934042/126864269-9636dcdb-835f-4320-a0cf-8e152c1255ef.jpg)

2021-07 English Wikipedia 0.8:

![Screenshot_20210724-111806_Samsung Internet](https://user-images.githubusercontent.com/71934042/126864276-760d1f0e-8942-4573-ac2e-8f3e5bd8a55a.jpg)

**Comment by kelson42** [comment]
Quite sure an upstream problem, but should be clearly identified.

**Comment by Inbefortus** [comment]
@kelson42 After quite a while, this bug is at last no more!

![Screenshot_20220925-195415_Samsung Internet Beta](https://user-images.githubusercontent.com/71934042/192161745-b6c2e672-5f78-40b5-ae9f-1a1ec7739c34.jpg)

ZIM: https://farm.openzim.org/pipeline/2b9cc933987bbbb3c55ce236

Upstream: https://en.wikipedia.org/api/rest_v1/page/html/1760s
