### ISSUE TITLE
Succession boxes not scraped

### ISSUE THREAD

**Issue by Inbefortus** [openzim/mwoffliner#1514]
ZIM: 2021-08 English Wikipedia (Top Articles)

This table is lacking in every article. More precisely, every table of this type is lacking.

2021-08:

![Screenshot_20210804-160507_Kiwix](https://user-images.githubusercontent.com/71934042/128196271-999abbbe-7f2b-46b7-b6bf-66c3fb19f5be.jpg)

2021-07 English Wikipedia (Top Articles):

![Screenshot_20210804-160536_Kiwix](https://user-images.githubusercontent.com/71934042/128196356-6767e89a-faf4-4693-85df-4a5b9ef6fd2e.jpg)

For some reason, 2021-07 is fine.

**Comment by Inbefortus** [comment]
@kelson42 If this helps:

The original Wikipedia app also has these tables:

![Screenshot_20210810-091034_Wikipedia](https://user-images.githubusercontent.com/71934042/128825621-2d5e2ea2-0f3c-4cf2-8330-6d252a74fc90.jpg)

![Screenshot_20210810-091440_Wikipedia](https://user-images.githubusercontent.com/71934042/128825678-d67db281-8ae8-4504-84ff-8ff59f050157.jpg)
![Screenshot_20210810-091507_Wikipedia](https://user-images.githubusercontent.com/71934042/128825681-b4bf69f8-8518-4f79-80e1-5736a5b96127.jpg)
![Screenshot_20210810-091559_Wikipedia](https://user-images.githubusercontent.com/71934042/128825683-01a95f49-bb88-4f62-96a1-65c9d113e344.jpg)
![Screenshot_20210810-091840_Wikipedia](https://user-images.githubusercontent.com/71934042/128825684-2b865271-8ff5-4747-898f-5f083ce730b6.jpg)
![Screenshot_20210810-091703_Wikipedia](https://user-images.githubusercontent.com/71934042/128825690-cecc7794-7192-4e20-a695-bf5a61768cc7.jpg)

Still present in 2021-07, but in a build only a few days old, all of a sudden no longer. Strange.

**Comment by Inbefortus** [comment]
It looks like 2021-08 Simple English Wikipedia (scraped by mwoffliner 1.11.9) is fine:

![Screenshot_20210818-162525_Kiwix](https://user-images.githubusercontent.com/71934042/130013721-79a554c3-0c12-4b2d-a45c-cc9abfde55bb.jpg)

Strangely enough, they are missing in 2021-08 English Wikipedia Endless (also scraped by mwoffliner 1.11.9). Maybe this will be different in the big edition. I will keep this updated.

**Comment by kelson42** [comment]
Simple English and English are two different Wikipedia.

**Comment by Inbefortus** [comment]
> Simple English and English are two different Wikipedia.

@kelson42 That's true, and that's probably the reason it still works in Simple English.

I just compared 2021-07 English Wikipedia 100 with 2021-06:

2021-06:

![Screenshot_20210820-114440_Kiwix](https://user-images.githubusercontent.com/71934042/130214778-ee9c9261-8df0-4c3f-91f6-6e4cbd51ce2b.jpg)

2021-07:

![Screenshot_20210820-114501_Kiwix](https://user-images.githubusercontent.com/71934042/130214820-2e0cfbfc-404a-4469-afaf-84685bdd3660.jpg)

They were always included in all builds, the strange thing is that suddenly they are no longer scraped, no matter which variant of the English Wikipedia. I suspect that the large variant will potentially be affected.

**Comment by Inbefortus** [comment]
I took a closer look.


- http://library.kiwix.org/wikipedia_en_history_maxi/A/Julius_Caesar

Original Wikipedia app:

![20211101_142148](https://user-images.githubusercontent.com/71934042/139686895-83cb94bf-dab1-4b01-bf92-4a01b1f73e8e.jpg)

Mobile API:

![20211101_141809](https://user-images.githubusercontent.com/71934042/139686790-6a4b23b5-363b-4cc0-b0c8-8d39ff340dbd.jpg)

These succession boxes are definitively in the mobile API, as can be seen above.

But this one might be different:

- http://library.kiwix.org/wikipedia_en_all_maxi/A/Steve_Nash

Mobile API:

- https://en.wikipedia.org/api/rest_v1/page/mobile-sections/Steve_Nash

If you would only stick to the mobile API about this article, then the succession box should be displayed in the mobile version as well (which is not the case, even in the original). See here:

- Original Wikipedia app:

![Screenshot_20211101-144840_Wikipedia](https://user-images.githubusercontent.com/71934042/139688403-735394aa-4958-4e10-ac58-90c0b9d0425d.jpg)

- Mobile API:

![20211101_144728](https://user-images.githubusercontent.com/71934042/139688654-f97e290c-5e9e-49bf-bb19-3a33dab80605.jpg)

- Succession box:

![20211101_145110](https://user-images.githubusercontent.com/71934042/139688834-cfd38a1d-3dae-4389-8a70-5ecd21d9b671.jpg)

**Comment by Inbefortus** [comment]
As there are some succession boxes that are scraped, I compared the source code with the original and 2021-02 + 2021-12 English Wikipedia and may have identified the reason.


This article has a succession box.
- http://library.kiwix.org/wikipedia_en_all_maxi/A/Omar_Figueroa_Jr.

![Screenshot_20211231-231320_Samsung Internet](https://user-images.githubusercontent.com/71934042/147840527-8aad219d-ce25-4fd5-a843-b7217e4f13a6.jpg)


The source code of English Wikipedia 2021-02 + 2021-12 and the original is the same `table class`. This could explain why MWOffliner has scraped the succession box:

![20211231_231541](https://user-images.githubusercontent.com/71934042/147840551-363ebae7-19f8-4b6d-bebf-13cf3e00c26c.jpg)

![20211231_231606](https://user-images.githubusercontent.com/71934042/147840558-bdfbb504-d9f6-4363-8a2b-d2558640a79f.jpg)

Here it gets interesting.

- https://en.wikipedia.org/wiki/Augustus
- https://ipfs.io/ipns/en.wikipedia-on-ipfs.org/wiki/Augustus

Original:

![20211231_232106](https://user-images.githubusercontent.com/71934042/147840641-8e46bc94-87ec-48dd-b0df-211ab705c56a.jpg)

2021-02 English Wikipedia:

![20211231_232041](https://user-images.githubusercontent.com/71934042/147840626-1ad15e67-ccc3-4cf8-9784-3863c7d09fe8.jpg)

In 2021-02 it is

` wikitable succession-box`

and in the original it is

`wikitable succession-box noprint`

Since upstream is fine, my guess is that `table class` changed at the end of July and MWOffliner needs to be updated to pick it up again, something like that, but that is just a guess. I have a feeling I couldn't be more wrong, and it's entirely something else.

**Comment by Inbefortus** [comment]
I had completely forgotten that class `noprint` is excluded from scraping, as described by @kelson42 below. This is preconditioned behavior by MWOffliner:
- https://github.com/openzim/mwoffliner/issues/1495#issuecomment-883309121

Makes you wonder why this change occurred in the first place (from `wikitable succession-box` to `wikitable succession-box noprint`). This is truly a pity, since they are of great relevance... :-(

I'm closing this, as MWOffliner works as expected in this regard. 

However, if and when there is something else, feel free to reopen!
