### ISSUE TITLE
Images scraped for landing page of 'mini' ZIMs should also appear in their respective articles

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#1516]
This suggestion would not require any more space in the "mini" ZIM, because the images are already included for the landing page. My suggestion is that where an image is included for the landing page, it should **not** be removed from the article in which it was originally found. This would make the "mini" ZIMs a little less "boring" (a picture is woth a thousand words!) at no extra ZIM size cost.

**Comment by kelson42** [comment]
Seems really expensive in term of resource consumption at runtime, dev time, code complexification... for a very little improvement.

**Comment by Jaifroid** [comment]
OK, I don't know the code. I thought it might just be a case of a simple exception to the code that removes images "if image is required for landing page, do not remove".

**Comment by Jaifroid** [comment]
An alternative to this would be to remove all images entirely from "mini" ZIMs. If "mini" = "only lede and no images", then arguably the landing page should just be a list, like `wikipedia_en_100`.

**Comment by kelson42** [comment]
> An alternative to this would be to remove all images entirely from "mini" ZIMs. If "mini" = "only lede and no images", then arguably the landing page should just be a list, like `wikipedia_en_100`.

@Jaifroid What is exactly the problem you want to fix? Why having the welcome page with thumbnails whereas the rest of the articles doesn't is something "to fix"?

**Comment by kelson42** [comment]
> OK, I don't know the code. I thought it might just be a case of a simple exception to the code that removes images "if image is required for landing page, do not remove".

Yes, but to do so, I have to test that for all images in all articles. Which is far more costly than just say if mini/nopic, just remove all pictures.

**Comment by Jaifroid** [comment]
@kelson42 Maybe this is just my confusion with the nomenclature. "mini" currently seems to mean both "only a subset of the text is available" and (in practice) "no pictures", but in fact some have pictures on the landing page but not in the corresponding articles (e.g. `wikipedia_en_climate_change_mini`) and others have no pictures at all even on the landing page (e.g. `wikipedia_en_100_mini`).

Maybe in an ideal world with oodles of developer time, we'd have a `_mini-nopic_` flavour with subset of text and no images, and a `_mini_` flavour with the lede and the lede image included.

But I recognize my suggestion has come off topic now, so I'll close this issue. Sorry for the distraction - the original suggestion I made just seemed like a good idea at the time without my knowing the underlying code and effort that it would require.

**Comment by kelson42** [comment]
@Jaifroid Landing page has always thumbnails, except if only a few articles available (with a thumbnail) or (I believe) the browser does not have a javascript runtime . I think the limit is 100 articles/thumnails.

If you look at this recipe https://farm.openzim.org/recipes/wikipedia_en_top/config (just an example), you wil understand what "mini" means: https://farm.openzim.org/recipes/wikipedia_en_top/config
