### ISSUE TITLE
Fails to render gallery article link

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1520]
From [zim-requests/issues/350](../../zim-requests/issues/350): a gallery is improperly scraped as a couple of links under the images are not captured (zim shows picture names instead, see below).
Source is here: https://en.wikipedia.org/wiki/Wikipedia:Wikipedia_for_Schools/Welcome/Natural_Science
Zim is here: https://farm.openzim.org/pipeline/06c74eb3b2f47b15ba5a3116

![Screenshot_20210811-141007](https://user-images.githubusercontent.com/21675885/129026718-512491b2-7383-470e-8a31-862504b414a2.png)

**Comment by kelson42** [comment]
This is an upstream bug, the REST APi does not render this article properly to the contrary to the user visible Web version:
* https://en.wikipedia.org/api/rest_v1/page/html/Wikipedia%3AWikipedia_for_Schools%2FWelcome%2FNatural_Science
* https://en.wikipedia.org/api/rest_v1/page/html/Wikipedia%3AWikipedia_for_Schools%2FWelcome%2FNatural_Science

**Comment by kelson42** [comment]
Upstream ticket open at https://phabricator.wikimedia.org/T289921

**Comment by kelson42** [comment]
was a problem with the wiki code. Fixed.
