### ISSUE TITLE
Show table of contents box in wikis

### ISSUE THREAD

**Issue by MattyBoy4444** [openzim/mwoffliner#153]
This ZIM is almost unusable.  The following are differences from the online content.
EX 1: At the top there is no way to get back to the table of contents
EX 2: The contents on each chapter is not displayed
EX 3: On the home, the Computing, Engineering etc... links at the top are not LINKS.

Is this an issue with just this Wiki?

**Comment by kelson42** [comment]
@MattyBoy4444 I do not understand EX1 and EX2 :(

**Comment by MattyBoy4444** [comment]
Referring to EX1
![ex1](https://user-images.githubusercontent.com/362606/32418568-34574be6-c232-11e7-865c-9937436484cf.jpg)

**Comment by kelson42** [comment]
EX1 and EX3 seem to be the same problem then...

**Comment by MattyBoy4444** [comment]
Sorry prev. post which I deleted was incorrect.
This is a screenshot regarding EX1, and 2.

![ex1-2](https://user-images.githubusercontent.com/362606/32418609-e4330316-c232-11e7-8f35-d7dec750fb47.jpg)

This is what I see in Kiwix
![ex2-kiwix](https://user-images.githubusercontent.com/362606/32418612-f1519468-c232-11e7-8651-7b12c17d2322.jpg)

**Comment by ISNIT0** [comment]
Issue 1 seems to now be fixed:
- 
![image](https://user-images.githubusercontent.com/5173131/48427955-45e53900-e76a-11e8-9a2d-cb11e58c8802.png)

Issue 2 is that there is no contents box. I'll rename this issue to reflect that it's about contents generation
