### ISSUE TITLE
How is the subject of a page decided?

### ISSUE THREAD

**Issue by zkosk** [openzim/mwoffliner#1531]
In BlackBerry_Limited page of all maxi there is link to BlackBerry page, but there is no such link in BlackBerry_Limited from the [computer subject](https://library.kiwix.org/wikipedia_en_computer_maxi_2021-08/A/BlackBerry_Limited).

**Comment by kelson42** [comment]
No feedback. Considering wikipedia en all maxi is 6 months old…. Pretty normal that the offline article might have a few difference with the online version.

**Comment by zkosk** [comment]
Hi I just come back. The problem is: in any subject zim like the computer zim, there will be some page like BlackBerry that should have been included but is not included. Why is it not included? That is the process that decide which page is included? If the process is automated, then there may be improvement to include pages like BlackBerry.

**Comment by zkosk** [comment]
@kelson42 Hi I just come back. The problem is: in any subject zim like the computer zim, there will be some page like BlackBerry that should have been included but is not included which is why there is no hyperlink in the BlackBerry_Limited page to BlackBerry, only plain text. I found this problem when trying to learn about Black Berry devices and finding out there is no such page at all in the computer zim.

Why is it not included? What is the proccess that decides which page is included? If the proccess is automated, then there may be improvement to the proccess to include pages like BlackBerry in the computer zim.

**Comment by kelson42** [comment]
Most of the topic selections come from here https://download.openzim.org/wp1/eowiki_2021-08/ and are based on the wikiproject. What is the exact ZIM file you are talking about.

**Comment by zkosk** [comment]
@kelson42  computer_maxi : https://library.kiwix.org/wikipedia_en_computer_maxi_2021-08/A/BlackBerry_Limited

**Comment by kelson42** [comment]
This zim file is based on http://download.openzim.org/wp1/enwiki/projects/Computing.tsv which is the list of articles of the computing project https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Computing. You should look with them.

**Comment by kelson42** [comment]
Hmm, it is part of computing https://en.wikipedia.org/wiki/Talk:BlackBerry_Limited
