### ISSUE TITLE
Article count on the homepage not up-to-date

### ISSUE THREAD

**Issue by Inbefortus** [openzim/mwoffliner#1535]
ZIM: 2021-08 German Wikipedia https://farm.openzim.org/pipeline/215bcbdc8d495809837fc216
http://library.kiwix.org/wikipedia_de_all_maxi/A/Benutzer:The_other_Kiwix_guy/Landing

The article count is not up-to-date and still shows the identical count as in 2021-03:

![Screenshot_20210904-225718_Samsung Internet](https://user-images.githubusercontent.com/71934042/132107995-84314399-a28a-43f2-9a26-5cb658c6db22.jpg)

Amount of articles as of today:

![Screenshot_20210904-230659_Samsung Internet](https://user-images.githubusercontent.com/71934042/132108148-f9fe0072-b8dc-4b79-baab-dceaba1c43a6.jpg)

Nothing groundbreaking, however I believe this slight slip deserves to be reported.

**Comment by kelson42** [comment]
This is for sure an upstream problem, will try to report a bug but quite sure this is the consequence of one of the umerous cache problem the API backend has.

**Comment by kelson42** [comment]
The reason is that the page does not have changed and therefore is still in the cache at Wikimedia side. There is nothing much we can do about that.
