### ISSUE TITLE
Missing image in 2021-08 German Wikipedia

### ISSUE THREAD

**Issue by Inbefortus** [openzim/mwoffliner#1540]
http://library.kiwix.org/wikipedia_de_all_maxi/A/William_L._Jorgensen

![Screenshot_20210919-121024_Samsung Internet](https://user-images.githubusercontent.com/71934042/133926961-2741019b-fa91-42e5-8cca-8f291e3e03f6.jpg)

Upstream is fine, see
https://de.wikipedia.org/api/rest_v1/page/html/William_L._Jorgensen
![Screenshot_20210919-120742_Samsung Internet](https://user-images.githubusercontent.com/71934042/133926986-3ef17644-2460-4ae4-826a-4a05af2d1b5e.jpg)

**Comment by kelson42** [comment]
It seems to be a recurrent problem because newer ZIM has the same problem. Upstream looks good, see https://de.wikipedia.org/wiki/William_L._Jorgensen… This deserves an investigation.

**Comment by kelson42** [comment]
It seems to be an upstream bug https://phabricator.wikimedia.org/T298011. This coupled to a weakness in mwoffliner (jpeg detection is not the same in image webp convertion and in URL rewritting).
