### ISSUE TITLE
What links here

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1542]
Wikipedia has a button in the sidebar **_What links here_**.
It would be nice if a similar button appeared in ZIM files so that the user could see which articles link to the viewed article:
![What-links-here](https://user-images.githubusercontent.com/65112331/133929390-b24470c0-4c6d-4a2e-8c8b-3cc5d23014c1.gif)

**Comment by kelson42** [comment]
Yes, but this is impossible because there no track of the all the links beetween the pages.
