### ISSUE TITLE
Some possible problem with section title

### ISSUE THREAD

**Issue by zkosk** [openzim/mwoffliner#1545]
In the page List_of_differential_geometry_topics:

from maxi zim:
![image](https://user-images.githubusercontent.com/76477726/134747298-fef1741f-c7d9-4ff9-a9e0-48a45f68eccc.png)
The section "Lie groups" exists but doesn't have content.

from https://library.kiwix.org/wikipedia_en_all_maxi/A/List_of_differential_geometry_topics:
![image](https://user-images.githubusercontent.com/76477726/134747389-47ed52fc-5335-457e-90e6-7930e5cf9331.png)
The section "Lie groups" is missing

from http://en.wiki.sxisa.org/wiki/List_of_differential_geometry_topics:
![image](https://user-images.githubusercontent.com/76477726/134747480-8058e6bb-9555-4c5a-b105-0728a13483fd.png)
This seems to be the right one.

**Comment by Inbefortus** [comment]
@kelson42 Just for your information, as you can see here, this has been fixed:

- https://library.kiwix.org/wikipedia_en_all_nopic/A/List_of_differential_geometry_topics
- ![Screenshot_20211127-184909_Samsung Internet](https://user-images.githubusercontent.com/71934042/143691664-e647a9da-0179-4a26-b6fe-e87c6b2a4988.jpg)

**Comment by kelson42** [comment]
@Inbefortus Sorry, missed your comment. Does that mean we should/close this ticket?

**Comment by Inbefortus** [comment]
@kelson42 Yeah! I just checked again to be sure. This is still fixed in 2022-05 English Wikipedia.
