### ISSUE TITLE
Delete _lrc_ zim files

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1546]
Northern Luri wiki has been deprecated, see https://incubator.wikimedia.org/wiki/Wp/lrc

I've already disabled the zimfarm recipe, four files are remaining
https://download.kiwix.org/zim/wikipedia/wikipedia_lrc_all_maxi_2021-09.zim
https://download.kiwix.org/zim/wikipedia/wikipedia_lrc_all_maxi_2021-08.zim
https://download.kiwix.org/zim/wikipedia/wikipedia_lrc_all_nopic_2021-09.zim
https://download.kiwix.org/zim/wikipedia/wikipedia_lrc_all_nopic_2021-08.zim

**Comment by kelson42** [comment]
I have deleted the zim files
