### ISSUE TITLE
Vital information missing from Wikivoyage scrapes

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#1554]
Just looking at the USA article in the latest (November 2021) English-language Wikivoyage, and comparing side-by-side with online Wikivoyage, you can see that really important information is missing from the ZIM version (see screenshot, original on left, ZIM on right).

The missing information about COVID-19 seems to me really vital for travellers. Unlike with some infoboxes in Wikipedia, this doesn't appear to be a CSS issue. But I wonder if we are failing to pick up these infoboxes, or whether it is a problem upstream with Parsoid.

![image](https://user-images.githubusercontent.com/4304337/142029876-18fab276-efc0-4f64-9d44-136f6a38f5ab.png)

**Comment by kelson42** [comment]
Agree, need to check but strongly suspect that either this is not part of mobile output because of MCS or the covid box has a class which is in our black list.

**Comment by Jaifroid** [comment]
I actually think this issue is an instance of #1397. These COVID-19 warning boxes are now shown in our scrapes (still in the January 2023 English Wikivoyage) whereas they have gone from online Wikivoyage. We are now plagues with the opposite problem: look on almost any article for a country in Latin America and you'll see completely outdated information saying that it's not possible to enter the country, etc., with the COVID warnings all displaying when they should have been removed at least a year ago.
