### ISSUE TITLE
Skip problematic pages rather than halt

### ISSUE THREAD

**Issue by Sophivorus** [openzim/mwoffliner#1556]
Hi! We've been trying to generate a ZIM file for appropedia.org for some time now. However, we've encountered several issues with problematic pages that halted the script, such as the ones described on [issue #1534](https://github.com/openzim/mwoffliner/issues/1534) but also others not reported here. The latest halt was due to a timeout from the page https://www.appropedia.org/Africa_community_action which seems pretty normal except perhaps for the map towards the bottom that may take some time to load. However these maps are pretty widespread throughout Appropedia (and other wikis) so removing them is hardly an option for us.

Thus I wonder if instead of continuing to fix problematic pages one by one, is there a configuration option that can be enabled or developed to skip problematic pages rather than halt the script completely. Thanks!

**Comment by kelson42** [comment]
The latest scrape has been stopped becuase 'Cervical Cancer Screening and Treatment Self-Administered Readiness Test' is not readble. See https://www.appropedia.org/Cervical_Cancer_Screening_and_Treatment_Self-Administered_Readiness_Test.

There is no option to skip pages which are not readable and I don't really want to build that option because it will build "broken" ZIM files (with dead links for example).

But we should understand why this page is not readable and secure that such pages are not part of the ZIM snapshot. Do you know which extension is responsible for blocking this article?

**Comment by kelson42** [comment]
Hmmm, I guess this is https://www.mediawiki.org/wiki/Extension:CategoryLockdown

**Comment by kelson42** [comment]
@Sophivorus I guess, at this stage, the most pragmatic solution would be that you provide a liste of articles ids you want us to scrape (and which are readable) and we would scrape them. A one column CSV with one title (utf8, underscores) with articles ids.

**Comment by Sophivorus** [comment]
Ah, I didn't notice the page was locked too (admins can see locked pages), my bad, sorry!
However, since this issue is about skipping problematic pages rather than about any specific problematic page, and since I think implementing such a feature would be reasonable, I won't close this issue yet, but feel free to do so if you have reasons not to implement the feature.
As to the list of ids, it's not that simple but I'll give it some thought and write back when I have something.

**Comment by kelson42** [comment]
Extension:CategoryLockdown is clearly the real problem for now. We need a way to handle it. https://www.appropedia.org/Thermal_Ablation_of_Cervical_Pre-Cancer_Lesions Fails to scrape.

**Comment by kelson42** [comment]
@Sophivorus Just realised this extension is your work, so shoule be able to confirm :)

**Comment by Sophivorus** [comment]
Hi! Do you mean a confirmation that I can make the API throw an error when the page is locked for view? Yes I think I can do that. I could also send you the current list of locked pages, or disable the extension for some minutes to run the script, but those would be one-time solutions and the next run would fail again. What do you prefer?

**Comment by kelson42** [comment]
The very best solution (for us and in term of ZIM quality) is that you provide (and maintain) online a list of titles (one column UTF8 CSV) which should/can be scraped (so excluding the locked page). So I can just linked it to `--articleList` feature of MWoffliner. This is our standard way of doing if the content want to make a selection of articles and want to keep the control and update the list of title. See for example this list http://offline.mdwiki.org/nonwiki/lists/mdwikimed.tsv

Another viable solution for us would be (but this complexify our code and I would prefer having you building the final list):
* There is somewhere online (idealy your extension provide an API end-point) a blacklist of titles (one column UTF8 CSV)
* Then we could think about implementing a `--articleBlackList` feature

Doable as well is that you return an identifiable error on the API call (via json error) or even better via 401 Unauthorized HTTP return code. That way I can clearly identified that this page is protected and implement an appropriate behaviour (and this is not the same at all than allowing all errors or allowing timeouts, etc...). But such an approach won't avoid to scrape dead links if you have other content pointing to such locked articles. So, not the best approach IMO.

We can not know when the scrape run, so this is not a good approach to modify temporarly how appropedia.org works.

**Comment by kelson42** [comment]
@Sophivorus Any news here?

**Comment by Sophivorus** [comment]
Hi! I just coded a little script that outputs a CSV with a list of encoded titles (aka database ids) of public pages in a small category of Appropedia, see https://www.appropedia.org/scripts/generateKiwixList.php

Can this be used to produce a sample ZIM file? If we can get this small sample to work, I could then expand it to include more and more public pages of Appropedia. Cheers!

**Comment by kelson42** [comment]
@Sophivorus Thank you! I have updated https://farm.openzim.org/recipes/appropedia and requested a new run, lets see if it works better.

**Comment by kelson42** [comment]
It pass now, closing the ticket.
