### ISSUE TITLE
Question: are pages linked to by pages in list included?

### ISSUE THREAD

**Issue by tim-moody** [openzim/mwoffliner#1557]
wikipedia_en_medicine_2021-11 contains the page Research, which is not in http://download.openzim.org/wp1/enwiki/customs/medicine.tsv

is this expected?

**Comment by kelson42** [comment]
Yes is there is redirects from or pointing to it.

**Comment by tim-moody** [comment]
To be clear, I am not talking about redirects. Those are included. I am talking about a link on a page that is in the --articleList that points to a page that is not in the --articleList. For example https://en.wikipedia.org/wiki/Ibuprofen has a link to https://en.wikipedia.org/wiki/Research, but Research is not in the medicine.tsv file.

**Comment by kelson42** [comment]
Then, no this is not expected.

**Comment by tim-moody** [comment]
>Then, no this is not expected.

This issue can be closed unless someone else is interested.

**Comment by kelson42** [comment]
@tim-moody Any explanation found?

**Comment by tim-moody** [comment]
@kelson42 someone would need to verify that my observation is correct, namely that mwoffliner creates a zim containing a page that is not in the article list, as in my example above. Someone who knows the code would then have to determine if mwoffliner is scraping pages and including linked pages that are not in the article list or there is some other explanation.
