### ISSUE TITLE
Expand link is missing

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1558]
Looking at the ["ne" entry in Finnish on the English Wiktionary](https://en.m.wiktionary.org/wiki/ne#Finnish), there is an expandable box for declensions (clicking on 'show').

![Capture d’écran 2021-11-29 à 13 45 55](https://user-images.githubusercontent.com/21675885/143870613-894e5559-c79e-4f11-8f93-2c8804328f0c.png)
 
This feature is however [absent from the latest zim](https://library.kiwix.org/wiktionary_en_all_maxi/A/ne#Finnish) (wiktionary_en_all_maxi_2021-10.zim)

![Capture d’écran 2021-11-29 à 13 46 05](https://user-images.githubusercontent.com/21675885/143870761-a45f7121-7c6b-4741-97bd-6121215742be.png)

**Comment by denver-39** [comment]
In the English Wiktionary, there is a span tag in the .NavHead class
![Screenshot 2021-12-25 201305](https://user-images.githubusercontent.com/88855792/147387584-38f4bce7-ec58-4895-a799-99cf0eb98292.png)
But it's absent from the latest zim
![Screenshot 2021-12-25 201412](https://user-images.githubusercontent.com/88855792/147387596-9d0d53a7-e8eb-487a-91e5-4cbb6a4e7617.png)
You can just put the tag and add the function the bug woul
![Screenshot 2021-12-25 201627](https://user-images.githubusercontent.com/88855792/147387610-a679b82a-7280-45b4-8317-f01954ca5692.png)
d be fixed

**Comment by kelson42** [comment]
Pretty sure this has been fixed today with #1701. I will check.

**Comment by kelson42** [comment]
Index, duplicated of #1701. Therefore, it's fixed.
