### ISSUE TITLE
Local Wiki Request failed with status code 404

### ISSUE THREAD

**Issue by rwslippey** [openzim/mwoffliner#1559]
I've been trying to get this working on a local private wiki for a while and have seem to hit a roadblock.

First, I find the 404 kind of odd because it is in fact getting a response from the api, turns out the response looks like crap, so it's hitting the site, so it appears.

`Failed to get [http://localhost:8080/w/api.php?action=query&meta=siteinfo&format=json&siprop=general|namespaces|statistics|variables|category|wikidesc] [status=404]
[error] [2021-12-10T16:03:40.966Z] FATAL - Failed to get MediaWiki Metadata
Failed to run mwoffliner after [0s]: {
        "message": "Request failed with status code 404",
        "name": "Error",
        "stack": "Error: Request failed with status code 404\n    at createError (/home/rslippey/.nvm/versions/node/v16.13.0/lib/node_modules/mwoffliner/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/home/rslippey/.nvm/versions/node/v16.13.0/lib/node_modules/mwoffliner/node_modules/axios/lib/core/settle.js:17:12)\n    at Unzip.handleStreamEnd (/home/rslippey/.nvm/versions/node/v16.13.0/lib/node_modules/mwoffliner/node_modules/axios/lib/adapters/http.js:269:11)\n    at Unzip.emit (node:events:390:28)\n    at Unzip.emit (node:domain:475:12)\n    at endReadableNT (node:internal/streams/readable:1343:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
        "config": {
                "url": "http://localhost:8080/w/api.php?action=query&meta=siteinfo&format=json&siprop=general|namespaces|statistics|variables|category|wikidesc",
                "method": "get",
                "headers": {
                        "Accept": "application/json",
                        "cache-control": "public, max-stale=86400",
                        "accept-encoding": "gzip, deflate",
                        "user-agent": "MWOffliner/HEAD (rwslippey@gmail.com)",
                        "cookie": ""
                },
                "transformRequest": [
                        null
                ],
                "transformResponse": [
                        null
                ],
                "timeout": 120000,
                "responseType": "json",
                "xsrfCookieName": "XSRF-TOKEN",
                "xsrfHeaderName": "X-XSRF-TOKEN",
                "maxContentLength": -1,
                "maxBodyLength": -1,
                "transitional": {
                        "silentJSONParsing": true,
                        "forcedJSONParsing": true,
                        "clarifyTimeoutError": false
                }
        }
}

**********

Request failed with status code 404

**********`

Just to see what the URL above was returning, I get a fully styled wiki page that says "No Such Action" and "The action specified by the URL is invalid. You might have mistyped the URL, or followed an incorrect link. This might also indicate a bug in the software used by POL Wiki."

I'm running the latest version of Media Wiki on docker, and I've run MWOffliner in both docker and WSL (yes, I added networking and confirmed that wget works from WSL guest to the docker service) with the same results.

I know it takes a great deal of time to work on these projects, so as always I thank everyone for their support and dedication to such a project.

**Comment by kelson42** [comment]
http://localhost:8080/w/api.php?action=query&meta=siteinfo&format=json&siprop=general%7Cnamespaces%7Cstatistics%7Cvariables%7Ccategory%7Cwikidesc

… is a Mediawiki API end-point request. It should not return a HTTP 404 and should not return HTML either. It should return XML or JSON. Give a try to wikipedia.org tomsee how it shoukd work.

**Comment by rwslippey** [comment]
Thanks for the reply @kelson42 . However, it's not been much help. 

I'm running into issue hitting Wikipedia as well. Current error when trying to run it with Wikipedia is:
`Unable to find appropriate API end-point to retrieve article HTML`

As far as your reply, I'm curious what I might be missing here...
I've looked at w/api.php on other mediawiki sites and it returns as if the page doesn't exist (which does make sense).... what I'm getting back from my wiki is different. It's not saying the page doesnt exist, it's returning a 404 to mwOffliner but in a browser it returns what looks like an article "no such action" 

Could this possibly be a hosting issue? Rewrites rules? 

Not asking for anyone to figure it out for me, just need a little more of what direction to go.
