### ISSUE TITLE
Lots of template content with braces { } appearing raw on some Wikipedia articles

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#1561]
Example below is from the English Wikipedia (maxi) article "Wiktionary". First image is from latest full English Wikipedia. Second image is from the Kiwix JS rendering of the same article in the latest Endless ZIM.

![image](https://user-images.githubusercontent.com/4304337/146178021-bb8984bd-928b-441e-9cf7-f62e3ab8f064.png)

![image](https://user-images.githubusercontent.com/4304337/146178492-3eae21be-7e56-4112-97c4-4514301a3988.png)

**Comment by kelson42** [comment]
@Jaifroid Looks like an wiki parsing error upstream, but I need to know the exact ZIM filename.

**Comment by Jaifroid** [comment]
Oops, sorry. The first one was from https://library.kiwix.org/wikipedia_en_all_maxi/ which I think means the underlying ZIM is `wikipedia_en_all_maxi_2021-03.zim`.

The second was from `wikipedia_en_endless_maxi_2021-11.zim`.

In both cases, the article in question was "Wiktionary".

**Comment by kelson42** [comment]
@Jaifroid Duplicate of #1577?

**Comment by Jaifroid** [comment]
I guess so. I'll close.
