### ISSUE TITLE
Titles within articles are missing in Wikiquote ZIMs

### ISSUE THREAD

**Issue by Inbefortus** [openzim/mwoffliner#1562]
ZIM: 2021-12 German Wikiquote

Examples:

- http://library.kiwix.org/wikiquote_de_all_maxi/A/Whisky
- http://library.kiwix.org/wikiquote_de_all_maxi/A/Geschwister
 
![ZomboDroid 17122021102750](https://user-images.githubusercontent.com/71934042/146523106-a819a00a-f065-4b78-827f-fc515b746639.jpg)

![ZomboDroid 17122021102831](https://user-images.githubusercontent.com/71934042/146523108-71df03bf-7594-45be-b922-2836c551caee.jpg)

**Comment by Inbefortus** [comment]
This seems to be the case in all languages:

- http://library.kiwix.org/wikiquote_en_all_maxi/A/Persona_5
- http://library.kiwix.org/wikiquote_fr_all_maxi/A/Armand_Jean_du_Plessis_de_Richelieu

![ZomboDroid 17122021104904](https://user-images.githubusercontent.com/71934042/146525637-2b652fc5-bcdb-4e37-a415-4a8be7737e09.jpg)
![ZomboDroid 17122021105300](https://user-images.githubusercontent.com/71934042/146525642-10c2958d-b22f-415a-8440-5b00ad5f5d66.jpg)

**Comment by kelson42** [comment]
Probably against a problem related to bad mobile/desktop scraping mgmt. This is a plague since years… pretty sure we had or have a ticket already open a bout that.

**Comment by kelson42** [comment]
Duplicate of #1325
