### ISSUE TITLE
Still some problems about tree structure of a page

### ISSUE THREAD

**Issue by zkosk** [openzim/mwoffliner#1573]
Problems in [1501](https://github.com/openzim/mwoffliner/issues/1501) are fixed. Is tree node deeper than 2 supported? Here is an example of problematic structure:
In this page : http://library.kiwix.org/wikipedia_en_all_maxi/A/Ancient_Greek
When the section "Phonemic inventory" is collapsed, its child nodes "Consonants" and "Vowels" are still shown.

**Comment by kelson42** [comment]
@zkosk #1501 is still open, bug or bugs are not fixed. What you report is just an other example of the flawed section mgmt in MWoffliner. Basically a duplicate of #1501
