### ISSUE TITLE
Put data of different types into separate files

### ISSUE THREAD

**Issue by zkosk** [openzim/mwoffliner#1574]
To speed up search , 80GB maxi zim file can be put to SSD. To save SSD space, if different types of data are put into separate files, not to put all data in a single zim file, then only some smaller files need to be put into SSD.

Example 1: 30GB Data file + 50GB Image archive file. Use 30GB SSD space.
Example 2: 1GB Index file + 29GB Data file + 50GB Image archive file. Use 1GB SSD space.

Image archive file can also use different format, such as zip or plain folder, then partial update can be supported in the future. SD and HD version image archives can also be switched as needed. Images for different fields can also be put into different archives. Video archive file can also be added in the future.

**Comment by kelson42** [comment]
Splitting ZIM files is a hassle. We have a long experience of doing that and we know that this is not user-friendly.

In addition, the search speed is pretty good, even on slow devices. Therefore, there is no real reason to add a lot of complexity on this.

@zkosk If you have a real speed problem with Kiwix, your are welcome to report it so we can have a look in detail to it.

**Comment by zkosk** [comment]
@kelson42 There is no serious speed problem. Search on SSD is instantly. Search on HDD takes several seconds. But other features that need the split, such as support for partial update/partial download of images/HD images/and video are more useful. Put medias outside the zim is better for most cases.

**Comment by kelson42** [comment]
> But other features that need the split, such as support for partial update/partial download of images/HD images/and video are more useful.

This sentence is wrong: there is no such a feature for now, and many possible ways to allow incremental updates.
