### ISSUE TITLE
Many broken articles in English Wikipedia

### ISSUE THREAD

**Issue by Inbefortus** [openzim/mwoffliner#1577]
- ZIM: 2021-12 English Wikipedia
- http://library.kiwix.org/wikipedia_en_all_maxi/A/List_of_people_who_died_climbing_Mount_Everest

![Screenshot_20211231-130236_Samsung Internet Beta](https://user-images.githubusercontent.com/71934042/147822449-0b11650d-9026-4ee4-8dc1-36c5f051ac3c.jpg)

It's an upstream problem:

- https://en.wikipedia.org/api/rest_v1/page/html/List_of_people_who_died_climbing_Mount_Everest

![Screenshot_20211231-133316_Samsung Internet](https://user-images.githubusercontent.com/71934042/147823571-5b009c17-8030-4580-bb9a-69125aeea976.jpg)

This seems to be the case for a long time already. The website uses 2021-02 English Wikipedia:

- https://ipfs.io/ipns/en.wikipedia-on-ipfs.org/wiki/List_of_people_who_died_climbing_Mount_Everest

![Screenshot_20211231-131933_Samsung Internet](https://user-images.githubusercontent.com/71934042/147823012-aa32513c-8076-466a-8851-12311e0feaa9.jpg)

**Comment by Inbefortus** [comment]
@kelson42 This is a great approach to determine how badly widespread something like this is.

- http://library.kiwix.org/search?content=wikipedia_en_all_maxi&pattern=%7B%7C+class%3D%22wikitable+sortable

A total of 70 articles are affected by this. Most harmed are lists about bridges.

![Screenshot_20211231-193010_Samsung Internet](https://user-images.githubusercontent.com/71934042/147835635-97e3c998-57e3-4663-ae82-c2adf105b1e0.jpg)

![Screenshot_20211231-193452_Samsung Internet](https://user-images.githubusercontent.com/71934042/147835637-8fe619ea-c4ba-4748-87fa-8ebc849d4dc4.jpg)

![Screenshot_20211231-193859_Samsung Internet](https://user-images.githubusercontent.com/71934042/147835752-59d79409-b151-4cca-8834-bdf8c227d155.jpg)

![Screenshot_20211231-193923_Samsung Internet](https://user-images.githubusercontent.com/71934042/147835754-04ca310f-5ae2-4fe1-814b-f20633820485.jpg)

**Comment by kelson42** [comment]
@Inbefortus I will report this upstream.

**Comment by Inbefortus** [comment]
@kelson42 Fixed!

![Screenshot_20220925-214055_Samsung Internet](https://user-images.githubusercontent.com/71934042/192162280-a5526507-4968-4da7-a92c-3668ba9676c8.jpg)

![Screenshot_20220925-214300_Samsung Internet](https://user-images.githubusercontent.com/71934042/192162362-f1179fd4-98d7-4549-b3fb-92acc31ae22f.jpg)
