### ISSUE TITLE
Remove inline javascript to comply with some CSP

### ISSUE THREAD

**Issue by mossroy** [openzim/mwoffliner#1578]
There is at least some pieces of inline javascript in every page, like :
 ```
  <script>
    function importScript() { return 1 } // this is to avoid the error from site.js
  </script>
  <script>let articleId = 'Wikivoyage:Offline_reader_Expedition/Europe_Home_page'</script>
````
the articleId is used afterwards to handle webp.

The content can be browsed anyway, at least on the few ZIM files I tested

**Comment by mossroy** [comment]
The ZIM files generated by mwoffliner are probably the most used ones, at least for kiwix-js.
It seems very important to me that this is fixed, so that they work completely, with no error/warning.

**Comment by mossroy** [comment]
The impact of the first code block still needs to be checked

**Comment by kelson42** [comment]
@Jaifroid I have launched a recipe with this fix at https://farm.openzim.org/pipeline/7fed4cc3e015578b5dc53d36. Let me know if you have any feedback.

**Comment by Jaifroid** [comment]
@kelson42 I downloaded the new ZIM and have been looking through it in the Chromium extension (the one affected). It all looks good: I can't find any inline JS remaining, and I don't see any related errors in console. So I think this issue is indeed fixed. Many thanks!
