### ISSUE TITLE
Missing section in Table of Contents

### ISSUE THREAD

**Issue by Inbefortus** [openzim/mwoffliner#1579]
ZIM: 2021-12 English Wikipedia
- http://library.kiwix.org/wikipedia_en_all_maxi/A/Thomas-Alexandre_Dumas

Original:
![20220106_211944](https://user-images.githubusercontent.com/71934042/148448060-02f81adc-2ac7-4d52-9b40-909c30885723.jpg)

2021-12:
![Screenshot_20220106-212007_Samsung Internet Beta](https://user-images.githubusercontent.com/71934042/148448088-21130357-3931-46bb-9161-3030870f4075.jpg)

**Comment by kelson42** [comment]
@Inbefortus Duplicate or similar to #1501. Wee have a PR which is unfortunately stalled. Priority bug.
