### ISSUE TITLE
Unfortunately mobile CSS are still not included properly

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#158]
This is a ```--mobileLayout``` specific bug.

Following #145 it seems that after all the refactoring of the last months we still have a regression because mobile layout is "broken" (no margin, paragraph arrow icon is not displayed, ...). It looks like that "static" CSS are not included properly (they seem to be there, but with "undefined" in them).

If I checkout 5affd206485fe259c9ca54ed57fb6bf7c1d6de80 then the rendering is OK for the following command line (put any article in the "articles" file):
```
rm -rf cac tmp out/ ; ./bin/mwoffliner.script.js --mwUrl=https://en.wikipedia.org/ --format=novid --verbose --adminEmail=kelson@kiwix.org --withZimFullTextIndex --articleList=articles --keepHtml --mobileLayout
```

**Comment by subbuss** [comment]
Please test and see if the problem is fixed.

**Comment by kelson42** [comment]
@subbuss Problem fixed so far I can see. Thank you for the (again) rapid move ahead on this. IMO we are not too far from a new release. I have a few tickets I want to fix and we have a few PRs pending... but otherwise things look (finally) good.
