### ISSUE TITLE
MWoffliner timeout error

### ISSUE THREAD

**Issue by imustbebored** [openzim/mwoffliner#1581]
Hi there,

I am using the docker image of mwoffliner on a digital ocean droplet for our site, Bulbapedia. We are trying to build an updated ZIM file that has a custom mainpage and does not use --zstd --webp flags.

I took the docker command from here https://farm.openzim.org/pipeline/94c003d7735911f49904d016/debug and edited it according to our specific needs and came up with this:

``docker run -v /var/www/mwoffliner/mwoffliner:/output:rw --name bulbapedia1 ghcr.io/openzim/mwoffliner:1.11.3 mwoffliner --adminEmail=wiksiapps@gmail.com --customZimDescription=An online Pokemon encyclopedia --customZimTitle=Bulbapedia --filenamePrefix=bulbapedia_all --format=novid:maxi --mwApiPath=/w/api.php --mwModulePath=/w/load.php --mwUrl=https://bulbapedia.bulbagarden.net/ --osTmpDir=/dev/shm --outputDirectory=/output --publisher=Wiksi --speed=0.1 --verbose --customMainPage=List_of_Pokémon_by_National_Pokédex_number``

Unfortunately, this continues to timeout after some time no matter how much we tweak/increase resources to the machine. We have tried tinkering with --memory and --memory-swappiness settings as well, but still mwoffliner times out after around an hour. It appears to be having difficulty with larger pages, thus leading to an error like this:

``{"name":"mwoffliner","hostname":"7c7d623b79c4","pid":14,"level":40,"logType":"warn/api/esockettimedout","wiki":"wiki$0","title":"Gyro_Ball_(move)","oldId":3434427,"reqId":null,"userAgent":"service-mobileapp-node","msg":"Failed API request, {\"error\":{\"stack\":\"Error: ESOCKETTIMEDOUT\\n    at ClientRequest.<anonymous> (/tmp/mwoffliner/node_modules/parsoid/node_modules/request/request.js:812:19)\\n    at Object.onceWrapper (events.js:421:28)\\n``

Could anyone help me with this issue? Maybe there are some docker settings we could tweak? We really need to use this to generate our Zim file in this way and have been trying for quite some time now with no success.

**Comment by imustbebored** [comment]
@kelson42 hope I'm not bugging, but when you have a moment, do you have any insight on how I could resolve this?

**Comment by kelson42** [comment]
AFAIK there is a recipe for bulbapedia on the zimfarm. Here it is https://farm.openzim.org/recipes/bulbagarden. IMO we should start here and understandd why it does not run anymore.

**Comment by imustbebored** [comment]
> AFAIK there is a recipe for bulbapedia on the zimfarm. Here it is https://farm.openzim.org/recipes/bulbagarden. IMO we should start here and understandd why it does not run anymore.

Thanks for the reply Kelson. I've been using that recipe from the ZimFarm as my starting point. Been trying to get it to complete via docker for the last week with no luck. I believe the farthest it's gotten is 18%-19%. I've tweaked it a whole lot but no luck. The error that I keep receiving on my end is related to an "ESOCKETTIMEDOUT" - specifically the larger pages seem to be timing out and eventually shutting down mwoffliner.

But for us, it's really important that we have a specific custom main page for our zim. Ideally, I'd like to setup a cron server side to generate our zim on a weekly basis as we need it to be updated fairly regularly.

**Comment by imustbebored** [comment]
> AFAIK there is a recipe for bulbapedia on the zimfarm. Here it is https://farm.openzim.org/recipes/bulbagarden. IMO we should start here and understandd why it does not run anymore.

It appears that the process has failed on Zimfarm again. Inspecting the logs, I see the same "ESOCKETTIMEDOUT" issue as I've been experiencing.

**Comment by kelson42** [comment]
AFAIK the web site is just not able to deliver on time everything. It always die in the same big article (a list).

**Comment by imustbebored** [comment]
> 

Is there a way to increase the time needed to wait for these larger articles to fully load?

**Comment by kelson42** [comment]
This is an unclear topic... but in that case, I suspect this is a timeout internal to the Mediawiki backend (but this is only an intuition). More realistic would be to split that article, increase the hardware or/and tune the caching of the web site.

**Comment by kelson42** [comment]
We had one successful run in February https://farm.openzim.org/pipeline/28963dbdb85459dbb8b24026

**Comment by kelson42** [comment]
I will close this ticket becuase:
* Bulbagarden does not provide (anymore?) any API to scrape
* Parsoid is no integrated anymore to MWoffliner because it is not maintained (the timeout was around Parsoid)

Bulbagarden is not scrapable anymore but we will try https://github.com/openzim/zim-requests/issues/545
