### ISSUE TITLE
Image still missing in 2022-01 German Wikipedia

### ISSUE THREAD

**Issue by Inbefortus** [openzim/mwoffliner#1582]
- http://library.kiwix.org/wikipedia_de_all_maxi/A/William_L._Jorgensen

![Screenshot_20220108-080841_Samsung Internet](https://user-images.githubusercontent.com/71934042/148635355-8cb837a0-087d-41ed-9e7f-65e2e4d1459e.jpg)

**Comment by Inbefortus** [comment]
@kelson42 I forgot that the code has not been released yet. My bad!

**Comment by kelson42** [comment]
Yes, should so a minor release... not so helpful otherwise for you an other users.

**Comment by Inbefortus** [comment]
@kelson42 I can confirm that this is fixed in the latest German Wikipedia!

![Screenshot_20220308-095826_Samsung Internet](https://user-images.githubusercontent.com/71934042/157203443-c71b4d0b-242d-4d77-8b9b-34b6fb9a4a8a.jpg)
