### ISSUE TITLE
Minify output files

### ISSUE THREAD

**Issue by ljmf00** [openzim/mwoffliner#1586]
To reduce the space usage significantly, the web pages should be minified as well as Javascript and CSS content. See also https://github.com/ipfs/distributed-wikipedia-mirror/issues/117 .

**Comment by kelson42** [comment]
There is already a `--minifyHtml` option but we don't use it as this was causing more trouble than necessary. In the ZIM file, everything is anyway strongly compressed, so the need of minifying is reduced.

**Comment by ljmf00** [comment]
> There is already a `--minifyHtml` option but we don't use it as this was causing more trouble than necessary. In the ZIM file, everything is anyway strongly compressed, so the need of minifying is reduced.

This can be concerning for huge repositories like Wikipedia on IPFS. I can't have real-world data to prove my point, but this is highly desired on unsealed IPFS blobs and will certainly improve the size of the whole CAR.

Also, if you knew this right away, why do I have to open an issue here to be closed right after? It is an unproductive action for both sides unless you intentionally wanted to document it as a question, which I can understand.

I'm going to reopen the issue there, but feel free to close it, although keep in mind that even 1% to 3% of Wikipedia shared across multiple languages can have a significant space reduction, especially if the idea is to massively store/share using cheap/affordable storage.
