### ISSUE TITLE
Search title has html tags

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#159]
_From @automactic on September 20, 2017 1:1_

Calling `kiwix::Result::get_title` sometimes results in a string with html tags. 

For example, in `wikipedia_en_medicine_novid_2017-08.zim`, if search 't', you can get results with title like `<I>Thermococcus</i>`

_Copied from original issue: kiwix/kiwix-lib#87_

**Comment by kelson42** [comment]
@automactic I'm quite sure this is a bug in mwoffliner.

**Comment by kelson42** [comment]
Yes, the problem occurs with the mobile layout. The information is there but because of the bad organisation of the code, at the time we create the title it is not available. Not so straigt forward to fix.

**Comment by ISNIT0** [comment]
I believe I have a fix for this, but the Thermococcus page doesn't seem to have the `<I>` tags anymore. What's the best way to find another page to test with?

**Comment by automactic** [comment]
I haven't seen this problem appearing for quite a while. But I am also widely testing a large number of zim files.
