### ISSUE TITLE
OSM Wiki cannot be downloaded

### ISSUE THREAD

**Issue by kmpoppe** [openzim/mwoffliner#1593]
The mwoffliner used by Kiwix in their ZIMfarm, trying to download the openstreetmap wiki fails miserably since about 11 months. 

The recurring error - alas with different pages that are to be downloaded - is this:

"[error] [2022-01-24T12:32:18.657Z] Error downloading article Ca:Elements_cartogràfics\nFailed to run mwoffliner after [1639s]: {\n\t\"code\": \"apierror-visualeditor-docserver-http-error\",\n\t\"info\": \"⧼apierror-visualeditor-docserver-http-error⧽\",\n\t\"*\": \"See https://wiki.openstreetmap.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.\"\n}\n"

The latest log history is here: https://farm.openzim.org/recipes/osm-wiki

It was not possible to get the Wiki maintainers to see what access limits get hit. Therefore the questions, (_Originally posted by @kmpoppe in https://github.com/openzim/mwoffliner/issues/1473#issuecomment-853002210_), remain: Is it possible to reduce the speed of mwoffliner even further then 0.1? It seems to be a hard-coded lower limit and thus I cannot test if the API wouldn't complain if the requests where slower? There above mentioned error message isn't meaningful enough for me to understand what problem mwoffliner encountered and what might then be handed back to the Wiki maintainer to see if they could/need to do something about that?

Thanks for maintaining this great project!

**Comment by kelson42** [comment]
The 0.1 is really the minimum because after the scrape would simply take too long. Duplicate #1445
