### ISSUE TITLE
Wikipedia: Categories and Templates in the footer of each article

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1597]
From kiwix-desktop created by [Ubuntu-2020](https://github.com/Ubuntu-2020): kiwix/kiwix-desktop#812  

When will the **Categories** and **Templates** from the footer of each article appear in Wikipedia ZIM files?
**[Article Sample](https://en.wikipedia.org/wiki/2022_Sumatra_earthquake#External_links)**:
![Categories_Templates](https://user-images.githubusercontent.com/65112331/156575093-f1abdc66-8ac4-428c-9ac7-3abd01232946.GIF)

**Templates** and **Categories** from the footer of the article make Wikipedia much easier to navigate!
**Templates** and **Categories** contain a large number of links to related articles!
Please add **Templates** and **Categories** to ***.ZIM** Wikipedia files.
Or at least in **Mileston** for the future, make such a note.

**Comment by kelson42** [comment]
This is a ticket for openzim/mwoffliner

**Comment by Inbefortus** [comment]
@Ubuntu-2020 Templates are already there, just hidden.

- Go to https://pwa.kiwix.org/

- Go into settings and enable `Display hidden block elements` and `Use Wikimedia mobile style`.

As for categories, I agree. They would take navigation to a whole new level!

**Comment by Ubuntu-2020** [comment]
@Inbefortus
> Templates are already there, just hidden.

Thanks.
But you can go into more detail.
I think this only applies to ***.appimage**.
What about the **browser extension**?
It is possible to see Templates in the browser extension?

**Comment by kelson42** [comment]
Scraping categories still does not work fine, see #829. From this problen point of view, this is a duplicate of #829.

**Comment by kelson42** [comment]
@Ubuntu-2020 The other problem has laready been reported in #1235…. By yourself!

Closing this ticket as duplicate.
