### ISSUE TITLE
 Translate footer in mwoffliner [sf #901]

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#16]
It's currently in English

**Comment by ISNIT0** [comment]
@kelson42 The footer doesn't seem to be returned by Parsoid or the MediaWiki API. Am I missing something, or will the translated footers need to be generated?

**Comment by kelson42** [comment]
@ISNIT0 The footer is hardcode in `mwoffliner` and this is OK. But the if the content language is French, then the footer should be in French and currently it is alway in English. We should have a proper translation system, where the UI strings (so the footer string) is properly specified in a separate file (like `.po` file for example). I would then have to sync that file with our online translation platform.

**Comment by ISNIT0** [comment]
I'm afraid I don't have any experience with `.po` files or our online translation platform. Could you email me some more details please?

**Comment by kelson42** [comment]
@kelson42 `.po` files was just an example how traditional app translate UI. Basically I do not care as long as all translation string are stored somewhere properly. For the rest you do like you want, I'm sure we have nice opensource frameworks for javascript.
