### ISSUE TITLE
Haiti's wikipedia_ht_all_novid_2017-08.zim is missing its internal index

### ISSUE THREAD

**Issue by holta** [openzim/mwoffliner#160]
Thanks @mgautierfr who discovered this @ https://github.com/kiwix/kiwix-tools/issues/102#issuecomment-343930567 and asked me to post here:

Full Text Search fails @ http:// iiab . me : 3000 /search?content=wikipedia_ht_all_novid_2017-08&pattern=suisse

Failure message is: 'Not Found...There is no article with the title "suisse" and the fulltext search engine is not available for this content.'

ZIM was downloaded from http://download.kiwix.org/zim/wikipedia/wikipedia_ht_all_novid_2017-08.zim on @kelson42's recommendation.

@mgautierfr explains:
> The zim file doesn't contain a full text index. You can check this in http://mirror.download.kiwix.org/library/library_zim.xml. There is no tag _ftindex for the wikipedia_ht_all_novid_2017-08.zim.
If you want it, you should open a issue on https://github.com/openzim/mwoffliner side who is generating the zim file.

**Comment by darkenvy** [comment]
You know what would be great? A `/debug` or `/dev` or `/about` screen that shows information about the zim. Such as the version of zimwriterfs that built it, wheither or not it has an internal index, ect.

I don't know how serious of a consideration this kind of feature would be, but if enough information was in it, it could help cut down on inspection time.

**Comment by kelson42** [comment]
@holta Still most of the ZIM file we make do not have an internal ft index. This is going to change with next run. I will upload a WPHT ZIM file with ft index during the day.
@darkenvy Please open a separate ticket.
