### ISSUE TITLE
what is the march mdwiki status?

### ISSUE THREAD

**Issue by tim-moody** [openzim/mwoffliner#1600]
https://farm.openzim.org/recipes/mdwiki says scraper_started, 3 days ago

but the mwoffliner log has not advanced since 2022-03-18T16:14:30.045Z.

the mdwiki-cacher log has not advanced since Mar 18 17:41:14 2022

**Comment by kelson42** [comment]
I have relaunched it and now this is done. https://farm.openzim.org/pipeline/0c281011b365858a87069326

**Comment by tim-moody** [comment]
@kelson42 thanks.
