### ISSUE TITLE
Scraping of German Wiktionary not working correctly (missing photos & translations)

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1602]
From overview created by [GPLv3-fan](https://github.com/GPLv3-fan): kiwix/overview#64  

The German Wiktionary is not being scraped properly. The code to scrape the German Wiktionary fails to obtain many photos and translations.

For example, the .zim version from February 2022 shows the headword "schütten" without any photo:

![image](https://user-images.githubusercontent.com/58692066/161354546-04ab77da-0b56-4345-97dc-ac79e125cfb6.png)

However, the online version shows a photo that was added to the Wiki on November 3, 2021:

![image](https://user-images.githubusercontent.com/58692066/161354729-4ce68a5f-8836-44ca-aa43-686fbe28568d.png)

![image](https://user-images.githubusercontent.com/58692066/161354689-192c118f-230a-4b70-80f8-26331035af7a.png)

Therefore, the "February" .zim did not include a photo that was already there. I tried the Kiwix App on Android and GoldenDict. The image is simply missing. That issue is relatively common in the German Wiktionary. The same happens with the Translations Box.

**_It seems that the code to scrape the German Wiktionary needs to be updated/improved._** 

Thanks for your hard work ! :D

**Comment by kelson42** [comment]
@GPLv3-fan I confirm indeed http://library.kiwix.org/wiktionary_de_all_maxi/A/sch%C3%BCtten

**Comment by kelson42** [comment]
@GPLv3-fan We use the mobile HTML output provided by the Wikimedia API and the image is missing there too: https://de.wiktionary.org/api/rest_v1/page/mobile-sections/sch%C3%BCtten. At best this is a bug in the Wikimedia mobile backend... but probably this is a feature.

**Comment by GPLv3-fan** [comment]
@kelson42 **where should I report that upstream issue?** 

Kiwix users benefit significantly from images and translation from the Wiktionary. If they are missing on Kiwix it is an important problem, especially for language learners.

**Comment by kelson42** [comment]
@GPLv3-fan At https://phabricator.wikimedia.org/, if you do so, feel free to link to that ticket there and here to keep the link please.

**Comment by Immunize2** [comment]
@kelson42  I opened a ticket about this issue:
https://phabricator.wikimedia.org/T319303

Dmitry Brant from Wikimedia Foundation suggested switching to a more stable API as the "Parsoid html output".

Is that feasible, or the Kiwix Project will continue with the old API ?
