### ISSUE TITLE
Feature request: Add portal pages to the full wikipedia Zim files

### ISSUE THREAD

**Issue by pyroshroom** [openzim/mwoffliner#1603]
Adding the wikipedia portal pages (Like [https://en.wikipedia.org/wiki/Portal:Science](https://en.wikipedia.org/wiki/Portal:Science)) to the full wikipedia Zim files would help make the offline wikipedia more navigatable and help with discovery of key articles in different topics. 

In the English Wikipedia there are supposedly only 533 portal pages according to [https://en.wikipedia.org/wiki/Wikipedia%3AContents%2FPortals](https://en.wikipedia.org/wiki/Wikipedia%3AContents%2FPortals), so it shouldn't add much to the current zim file size for the full wikipedia Zim files.

**Comment by Jaifroid** [comment]
I agree it would be very useful. I wonder why they are missing.

**Comment by kelson42** [comment]
I wonder as well, they shoukd be inside.

**Comment by kelson42** [comment]
I have check the Zimfarm recipes and indeed the `Portal` namespace, with code `100`, was not part of the recipes. I have fixed the following recipes to include it https://farm.openzim.org/recipes?name=wikipedia_en_all. Will move this ticket to `openzim/zim-requests` which is the right place for this kind of report. Anyway, thank you for this important feedback.
