### ISSUE TITLE
Update ZIM: German Wikipedia

### ISSUE THREAD

**Issue by Inbefortus** [openzim/mwoffliner#1609]
- https://farm.openzim.org/recipes/wikipedia_de_all

The last two runs failed because of `Request failed with status code 500`

Yesterday, when I went to visit the [article](https://de.wikipedia.org/wiki/Der_Patriot_(Tageszeitung))
that was responsible for the recent failed runs, I received this message:

![Screenshot_20220420-101956_Samsung Internet](https://user-images.githubusercontent.com/71934042/164443855-d8fcd062-bfdc-41cd-bff8-60f8fd93cea6.jpg)

All other articles were accessible, except this one. A short time later, the article seemed to work.

It would be interesting to review this and see if it works now, perhaps mwoffliner could not fight through because of the unattainable article? If that was indeed the reason it didn't pass, then I think it will certainly pass this time, since the article is retrievable.

**Comment by kelson42** [comment]
Here is the rootcause https://phabricator.wikimedia.org/T306615

**Comment by Inbefortus** [comment]
@kelson42 Definitely an interesting bug. Just a pity that 2.6 million articles have to suffer because of a single erroneous article. A blacklist where you can add articles that are ignored during scraping would surely be beneficial in such cases?

Apart from that, the [API](https://de.wikipedia.org/w/api.php?action=parse&format=json&prop=modules%7Cjsconfigvars%7Cheadhtml&page=Der%20Patriot%20(Tageszeitung)) seems to be working again, if I am not mistaken:

![Screenshot_20220425-141131_Samsung Internet](https://user-images.githubusercontent.com/71934042/165091422-4d7f9080-eec1-4f8b-9b2a-195d180d9ecc.jpg)

**Comment by kelson42** [comment]
@Inbefortus It seems it finally worked! https://farm.openzim.org/pipeline/c8ce488ead8d37d350338b26
