### ISSUE TITLE
HTTPS is on but Keep-Alive is off

### ISSUE THREAD

**Issue by kevinmcmurtrie** [openzim/mwoffliner#1610]
mwoffliner is downloading very slowly, with some scrapers now taking an estimated two weeks.  From https://github.com/openzim/mwoffliner/blob/master/src/Downloader.ts and a packet sniff, it looks like mwoffliner is using HTTPS without Keep-Alive.  That combination is a brutal killer of performance and efficiency at all points of operation.  It wouldn't surprise me if that was triggering connection rate throttling on the server side.

**Comment by kevinmcmurtrie** [comment]
This may be triggering the Linux "SNAT race" bug too.  I see containers that are temporarily unable to reach a specific host.
https://github.com/maxlaverse/snat-race-conn-test

I've added the random port workaround to iptables that should reduce faults.  HTTP Keep-Alive would would be a better fix.

**Comment by kelson42** [comment]
@kevinmcmurtrie Sorry, did not find the time to investigate more so far on this. But if confirmed, this would be indeed a nice improvement.

**Comment by kelson42** [comment]
I investigated the case and indeed it seems we don't set it. This is slightly surprising to me, I kind of get this has been removed at some point. Will make a PR to reintroduce it right now.

**Comment by kevinmcmurtrie** [comment]
:+1: 
This has a pleasant side-effect of avoiding a Docker network routing bug.

**Comment by kelson42** [comment]
@kevinmcmurtrie Will try to release soon.

**Comment by kevinmcmurtrie** [comment]
Release it soon?  I already see mwoffliner/wikipedia tasks using a single persistent IPv6 socket on pixelmemory.  The Docker routing bug hasn't been triggered even once and each scraper's CPU load has dropped from about 120% to 40%.

**Comment by kelson42** [comment]
Because i have configured exceptionaly, the dev version manually.
