### ISSUE TITLE
No output?

### ISSUE THREAD

**Issue by robhford** [openzim/mwoffliner#1613]
I am running mwoffliner docker container and after some work mwoffliner is completing processing of my wiki, but where is the output?  I have not included path as an argument, I see log message saying "Using output directory /out" but this directory is empty after completion.  May be missing something here, new to this.  Thanks!

**Comment by robhford** [comment]
Figured this out, thanks!

**Comment by githubd** [comment]
@robhford could you explain where it ultimately saves the file to when running it in docker I cannot find the files it creates

**Comment by kelson42** [comment]
Documentation seems incomplete indeed.

**Comment by tim78245** [comment]
> @robhford could you explain where it ultimately saves the file to when running it in docker I cannot find the files it creates

Yes, did it go anywhere? Doing a "find / -type f -iname "*zim" inside the docker image turns up no results.
