### ISSUE TITLE
Did not find page revisions for Index.php?title=Main_Page

### ISSUE THREAD

**Issue by robhford** [openzim/mwoffliner#1614]
Having the following issue,

[log] [2022-05-10T18:38:06.560Z] Getting articles
{"name":"mwoffliner","hostname":"4371f16a39d6","pid":130,"level":60,"logType":"fatal/request","wiki":"wiki$0","title":"index.php?title=Main_Page","oldId":null,"reqId":null,"userAgent":"MWOffliner/HEAD (x@y.org)","msg":"Did not find page revisions for Index.php?title=Main_Page","stack":"","httpStatus":404,"longMsg":"Did not find page revisions for Index.php?title=Main_Page","levelPath":"fatal/request","time":"2022-05-10T18:38:08.312Z","v":0}
[error] [2022-05-10T18:38:08.342Z] Error downloading article index.php?title=Main_Page
{"name":"mwoffliner","hostname":"4371f16a39d6","pid":130,"level":30,"logType":"info","wiki":"wiki$0","title":"Main_Page","oldId":4,"reqId":null,"userAgent":"service-mobileapp-node","msg":"redirecting to revision 4 for html","longMsg":"redirecting to revision\n4\nfor\nhtml","levelPath":"info","time":"2022-05-10T18:38:10.004Z","v":0}
{"name":"mwoffliner","hostname":"4371f16a39d6","pid":130,"level":30,"logType":"info","wiki":"wiki$0","title":"Main_Page","oldId":null,"reqId":null,"userAgent":"service-mobileapp-node","msg":"started wt2html","longMsg":"started wt2html","levelPath":"info","time":"2022-05-10T18:38:10.059Z","v":0}
{"name":"mwoffliner","hostname":"4371f16a39d6","pid":130,"level":30,"logType":"info","wiki":"wiki$0","title":"Main_Page","oldId":4,"reqId":null,"userAgent":"service-mobileapp-node","msg":"completed wt2html in 2095.757461000234ms","longMsg":"completed wt2html in 2095.757461000234ms","levelPath":"info","time":"2022-05-10T18:38:12.132Z","v":0}

**Comment by kelson42** [comment]
@robhford Sorry for the late feedback, but what is the exact command line you use to start MWoffliner?

**Comment by kelson42** [comment]
@robhford Any feedback? Maybe you solved your problem by yourself?

**Comment by kelson42** [comment]
Closing
