### ISSUE TITLE
Images improperly exported

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#163]
Made the following test with maths_nodet and full zims: same result. Some of the pictures (not all, not everywhere) are not properly exported. See, e.g. article Subtraction on maths zim:
![nodet](https://user-images.githubusercontent.com/21675885/33163556-62ce4172-d02f-11e7-95cc-71b3e73e43c9.png)

**Comment by kelson42** [comment]
I can not reproduce the problem (image is displayed) with the last nightly of kiwix-serve and wikipedia_en_maths_2017-11.zim. I strongly suspect that you have been impacted by https://github.com/kiwix/kiwix-tools/issues/108... which might also have impacted last builds of Kiwix for Android 2.3.
