### ISSUE TITLE
Feature Request: Use dumps from WikiTeam

### ISSUE THREAD

**Issue by tim78245** [openzim/mwoffliner#1655]
[WikiTeam](https://wiki.archiveteam.org/index.php/WikiTeam) has created a lot of xml dumps of wikis, some of which are no longer online.

An example of the dump structure from wikiteam:
https://archive.org/details/wiki-riskofrain2fandomcom

Their dumping tools also seem to be more flexible than mwoffliner.

Maybe this would be best served by a new tool altogether.

**Comment by kelson42** [comment]
MWoffliner don't use XML dumps.

**Comment by raptor** [comment]
Does there happen to be some other utility for converting mediawiki XML dumps to zim format?

**Comment by kelson42** [comment]
@raptor Not that I'm informeed unfortunately.
