### ISSUE TITLE
Feature request: If fail to download logo, default to favicon.ico

### ISSUE THREAD

**Issue by tim78245** [openzim/mwoffliner#1658]
I noticed some wikis I have tried to download have a broken logo (404). If mwoffliner in this instance could default to the site's favicon it would be somewhat nicer than me manually doing that. The favicon can almost always be found at  <link rel="shortcut icon" href="faviconhere"/> in the main page.

**Comment by kelson42** [comment]
Favicon are too small. If you want you can specify a custom one AFAIK.

**Comment by tim78245** [comment]
> Favicon are too small.

While the standard favicon size is 16x16, smaller than zim's 44x44, favicons these days can be any size and it's not unusual to  see a favicon of 48x48.

Perhaps try to see first if there's an apple-touch-icon, which are typically larger than 44x44, and then fallback to the favicon?

> If you want you can specify a custom one AFAIK.

Yes and it isn't very hard so this isn't that important of a feature. Though one thing in particular that makes current behavior painful is it only checks for the logo at the end of the download process (getting the logo should be changed to the start of the process).

**Comment by kelson42** [comment]
We have two different things:
* The favicon ZIM metadata, which is now called `illustration` and which can be multiple PNG, see https://wiki.openzim.org/wiki/Metadata
* The HTML article favicons which actually can be a lot of different files see https://realfavicongenerator.net

For none of these two use case the `favicon.ico` is sufficient (generaly too small resolution). The current euristic is the best but we need to be better by proposing more version of favicons (and in higher resolution).

**Comment by Jaifroid** [comment]
@kelson42 `M/Illustration` was news to me! It only seems to be available in recent Zimit and Stackexchange archives (from the ones I tested, see below), but not yet in any mwOffliner archive (e.g. the September 2022 Spanish full Wikipedia doesn't have it). Does any reader use this as a fallback currently? Do we need to add support to readers? If so, I can open an issue on Kiwix JS.

<img width="636" alt="image" src="https://user-images.githubusercontent.com/4304337/189481303-c680f5fb-c267-4e5d-a2c0-fb016fe51933.png">

**Comment by kelson42** [comment]
Kiwix-serve takes care about it and we have already a few scrapers as well.
