### ISSUE TITLE
Help in understanding the commands used in the software

### ISSUE THREAD

**Issue by zevisvei** [openzim/mwoffliner#1659]
I tried to download several websites and each one has a different error, I would like to understand more about 
  --mwWikiPath               Mediawiki wiki base path (per default "/wiki/")
  --mwApiPath                Mediawiki API path (per default "/w/api.php")
  --mwRestApiPath            Mediawiki Rest API path (per default
                             "/api/rest_v1")
  --mwModulePath             Mediawiki module load path (per default
                             "/w/load"
The sites I tried to download are http://wikigenia.org.il/index.php?title=%D7%A2%D7%9E%D7%95%D7%93_%D7%A8%D7%90%D7%A9%D7%99
https://wiki.jewishbooks.org.il/mediawiki/wiki/%D7%A2%D7%9E%D7%95%D7%93_%D7%A8%D7%90%D7%A9%D7%99
https://www.betmidrash.org.il/%D7%A2%D7%9E%D7%95%D7%93_%D7%A8%D7%90%D7%A9%D7%99
https://www.wikirefua.org.il/w/index.php?title=%D7%A2%D7%9E%D7%95%D7%93_%D7%A8%D7%90%D7%A9%D7%99

**Comment by kelson42** [comment]
Honestly, I don't know what should me more explained. Maybe we should first look to the error you get, maybe they are not explicit enough?

**Comment by zevisvei** [comment]
404 ,png not faunde and more aroors'

**Comment by kelson42** [comment]
Please open one ticket per problem with all the details, ie. at least the exact MWoffliner command line + log (in --verbose mode) which show the error. Here the guidelines about how to report a bug https://github.com/kiwix/overview/blob/master/REPORT_BUG.md
