### ISSUE TITLE
Fix wikibook_fr top menu links

### ISSUE THREAD

**Issue by letompouce** [openzim/mwoffliner#1660]
The [latest wikibooks_fr_all_maxi](https://library.kiwix.org/wikibooks_fr_all_maxi_2022-08/A/Accueil) top menu has no links (Arths, Loisirs, Histoire, etc).

**Comment by kelson42** [comment]
@letompouce Duplicate of https://github.com/openzim/mwoffliner/issues/1661 ?

**Comment by letompouce** [comment]
This issue is about wikibooks (with a S, sorry, may we edit the issue title?) ZIMs, and the other one is about Wikiversity ZIMs.

They may have the same root cause, sorry if I was noisy ^^'

**Comment by kelson42** [comment]
@letompouce If you look at https://fr.wikibooks.org/wiki/Accueil, you see that the top categories.... are pointing to `Category:...` like links.
