### ISSUE TITLE
site.js should be loaded last to avoid "Cannot read properties of undefined (reading 'getParamValue')"

### ISSUE THREAD

**Issue by zhuowei** [openzim/mwoffliner#1662]
To reproduce:
- Open a mwoffliner-created Zim file in any reader e.g. https://library.kiwix.org/wiktionary_en_all_maxi_2022-09/A/potato
- See browser console:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'getParamValue')
    at site.js:108:14
    at fire (jquery.js:3500:31)
    at Object.add [as done] (jquery.js:3559:7)
    at site.js:106:35
```
- Note that JavaScript features such as expanding the translations/conjugations on the page do not work

---

I believe what's happening is this:
- site.js calls `mw.loader.using('mediawiki.util')`

```
mw.loader.using('mediawiki.util').done(function() {
    /** &withmodule= query parameter **/
    if (mw.util.getParamValue('withmodule'))
```
- mwoffliner forces this function to return immediately, since it's assumed that in a .zim, all scripts are loaded ahead of time:

https://github.com/openzim/mwoffliner/blob/abd51529c00541b6fb5004e1d47917c9e5c34147/src/util/dump.ts#L104

- but the page's JavaScript list puts site.js ahead of mediawiki.util.js:

```
  <script src="../-/mw/jsConfigVars.js"></script>
  <script src="../-/mw/startup.js"></script>
<script src="../-/mw/jquery.js"></script>
<script src="../-/mw/mediawiki.base.js"></script>
<script src="../-/mw/site.js"></script>
<script src="../-/mw/mediawiki.util.js"></script>
<script src="../-/mw/mediawiki.page.ready.js"></script>
<script src="../-/mw/ext.tmh.player.js"></script>
```

- I believe the list of JS is generated in:
  - https://github.com/openzim/mwoffliner/blob/54dfafff4086255180b6d3ddd3fc196754926560/res/templates/page.html#L32
  - https://github.com/openzim/mwoffliner/blob/5b5cbdd8321b3e22ecc67d0aebd9278dadbc6cbe/src/util/saveArticles.ts#L895
  - https://github.com/openzim/mwoffliner/blob/5b5cbdd8321b3e22ecc67d0aebd9278dadbc6cbe/src/util/saveArticles.ts#L311

- so we can probably fix this by sorting the list of JavaScript files so that anything named "site.js" and/or is sourced from "MediaWiki:Common.js" gets put at the end?

**Comment by Jaifroid** [comment]
I confirm @zhuowei's fix! Simply moving site.js to the end of the list of JS files prevents the error from happening. It's a particularly annoying error for anyone who looks in console, as it affects every single page load. I've added some simple code that swaps the order in the PWA reader here: https://github.com/kiwix/kiwix-js-windows/commit/d77c62a134ca8b6d0f571c2a5969453354061040. Obviously it would be better if fixed here at source without needing a regex replacement. It looks like a very easy fix for someone familiar with the mwoffliner codebase.

**Comment by kelson42** [comment]
I have scheduled this for the next milestone.

**Comment by Jaifroid** [comment]
Just to add: this fix works for Wikipedia articles. For Wikivoyage, although site.js is referenced in each article, it is not found in the archive, and for Wiktionary, we get a different error in `site.js` even with this fix (see screenshot).

<img alt="image" src="https://user-images.githubusercontent.com/4304337/210176202-6d7d7d10-15dc-4f0f-97b5-f18eae62c1a7.png">

**Comment by kelson42** [comment]
@pavel-karatsiuba Please update this ticket as your fix is not 100% working.

**Comment by pavel-karatsiuba** [comment]
I changed the sequence of the js files loading but it fixed only error `Uncaught TypeError: Cannot read properties of undefined (reading 'getParamValue')`.
I defined that the scrapper did not read the page options which placed in the inline javascript of HTML. To fix this error we need to read options properly and use them in the site.js.

**Comment by Jaifroid** [comment]
@pavel-karatsiuba In some ZIMs changing the order gets rid of any error, but I've noticed that in others, it surfaces a different error instead (possibly the one you list, I'm afraid I didn't document it). I kind of wonder what this script actually does and whether we need it. Suppressing it might be a valid option (albeit the "nuclear" option).
