### ISSUE TITLE
Unacceptable profile string: text/html

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#167]
By scrapping rationalwiki.org I get a lot of these messages
```
 msg: 'Unacceptable profile string: text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.5.0"',
  longMsg: 'Unacceptable profile string: text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.5.0"' }
```

@subbuss Do you know what happens here?

**Comment by subbuss** [comment]
I updated the profile string + bumped parsoid version in mwoffliner. Did you npm install to get the latest version of Parsoid deb? If not, can you try and report back?

**Comment by kelson42** [comment]
@subbuss OK, will try again, I made a global install based on mwoffliner github repo. I suspect all the dependencies are updated that way?!

**Comment by kelson42** [comment]
@subbuss I still see this error appearing in the mwoffliner/parsoid logs

**Comment by kelson42** [comment]
That should have been fixed with the last Parsoid/MWoffliner upgrade.
