### ISSUE TITLE
Meta informations rendered by Parsoid in the content

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#169]
In last created ZIM file ofr Rationalwiki, I have used mwoffliner git master HEAD. The main page in the ZIM file suffers from a problem: two kinds of meta information seem to be rendered by Parsoid:

* The `__NO_TITLE__` wiki tag as
```
<p id="mwAQ">__NOTITLE__</p>
```

* An interwiki link ( to the version in Russian)
```
<p id="mwNQ"><a href="http://ru.rationalwiki.org/wiki/Заглавная%20страница" title="ru:Заглавная страница" id="mwNg" class="null">ru:Заглавная страница</a></p>
```

![scr](https://user-images.githubusercontent.com/1029718/45632982-f4d50380-ba9e-11e8-9a6e-b20a810684ce.png)

**Comment by kelson42** [comment]
@subbuss Is that the normal behaviour of Parsoid. Might that be that the Mediawiki version of rationalwiki.org is too old? If everything is allright, should we rely on ids `mwAQ` and `mwNQ` and simply always remove the nodes?

**Comment by subbuss** [comment]
* Siteinfo API query for rationalwiki doesn't seem to include notitle -- check https://rationalwiki.org/w/api.php?formatversion=2&action=query&meta=siteinfo&format=json&siprop=magicwords
* I didn't understand the qn about the interwiki link.

**Comment by kelson42** [comment]
* What does that mean exactly? Is that a configuration issue?
* Interwiki links should not be in the content!? How to remove them?

**Comment by kelson42** [comment]
* OK, can we remove all nodes with `id="mwNQ"`? What does this id means exactly?
* I'm not sure, but I do no think this is a new bug. I just want to know if the current behaviour of Parsoid is normal. If "yes", if you have an idea to remove it (but we need to keep the interwiki links/text within the text).

**Comment by subbuss** [comment]
* No. All Element DOM nodes in Parsoid output are assigned an id. So, you cannot make any assumptions of what those ids mean or assumptions about what nodes get what ids.
* Right now, interwiki links should have rel='mw:ExtLink' attribute. So, if you are removing links (but retaining link text) for all ext links in mwoffliner code, interwiki links should be handled automatically.

**Comment by kelson42** [comment]
* OK, so if there is nothing to do on our end. Is something doable on rationawiki' end? Can they change the configuration? Or is that simply because their version of Mediawiki is too old?
* Obviously it's not the case (see DOM dump in ticket description). Here again, it seems there is nothing we can do? Does that mean rationalwiki needs a Mediawiki upgrade to get rid of the problem?

**Comment by kelson42** [comment]
@subbuss I just checked https://rationalwiki.org/wiki/Special:Version. They use a version of November 2017... so definitely not really old.

**Comment by arlolra** [comment]
Prior to https://github.com/wikimedia/mediawiki-extensions-NoTitle/commit/1cf4475470da6fe0c1f62550e6ba869797eb3a74 the magicword isn't exposed in the siteinfo.

Get rationalwiki to update their version of the extension.

**Comment by davidgerard** [comment]
David Gerard from RationalWiki here. We don't run the mediawiki.org notitle extension - we run a handrolled thing of our own:

https://github.com/RationalWiki/mediawiki-extensions-RationalWiki/blob/master/notitle.php

Tim Starling helped us get RW upgraded and I think he looked over that one at the time so I'm assuming it's basically OK ... but I have no idea about PHP coding at all, let alone PHP for MediaWiki.

So if there's functionality you need in that extension, I can certainly accept a pull request!

**Comment by arlolra** [comment]
@davidgerard I put up a pull at https://github.com/RationalWiki/mediawiki-extensions-RationalWiki/pull/1 but needs a review.

**Comment by kelson42** [comment]
@ISNIT0 The fix has been done on Rational wiki side, let us check if it works fine during 1.8.

**Comment by ISNIT0** [comment]
Confirmed, this is fixed
