### ISSUE TITLE
Add a throttling / rate limiter option

### ISSUE THREAD

**Issue by doegox** [openzim/mwoffliner#170]
Hi,
Dumping some wikis trigger some rate limit on the server side and the client IP gets blacklisted for a few minutes. I solved the issue by an horrible hack, adding here & there some sleep() (from system-sleep) calls to limit the rate of the downloads but it would be much nicer to have a throttling option properly implemented.
Thanks.

**Comment by kelson42** [comment]
@doegox There is the speed option... But I think this is already 1 per default!? Maybe you could put 0.1 or somthing like that?

**Comment by doegox** [comment]
oO yes it seems working, thanks!!
speed unit is presented as 1=1 CPU, I didn't guess fractions were allowed.
