### ISSUE TITLE
Dealing with broken pages.

### ISSUE THREAD

**Issue by uriesk** [openzim/mwoffliner#1705]
Fandom has a mediawiki instance that likes to throw various errors.
In example, the article [Metadata table](https://minecraft.fandom.com/wiki/Bedrock_Edition_data_values/Metadata_table) will cause a parser timeout on api.php?action=visualeditor and return 503.
Another example, the article [Resource pack/Folders](https://minecraft.fandom.com/wiki/Resource_pack/Folders) will trigger a mediawiki bug and throw an api error.
Command for those:
```npm start -- --mwUrl=https://minecraft.fandom.com --mwApiPath api.php --mwModulePath load.php --adminEmail=test@examplecom --articleList ./articles```

@kelson42 suggested an option to exclude pages. I could work on that.
But in my opinion, it would be better if an article that throws an error is also a 404 in the zim file.
From a user perspective, i would prefer it to see the page in the index and search, know that it would exist, but it telling me that it is not available because of an Error when i open it.

(Follow up to pull request #1703 , possibly related to #1444 )

**Comment by kelson42** [comment]
Like I said, if the backend does not work properly:
* there is no way to make a proper ZIM
* a large variety of buggy scenarios can happen, which should not generate bug reports
* this is not the same like a 404.

**Comment by uriesk** [comment]
Are we talking about semantics, like:
> you requested a zim file of the whole thing, but we can not get the whole thing, so it's not a proper output
and
> a 404 on the wiki that is also a Not Found in the zim file is a correct representation
or are we talking about an actually broken zim file that can cause problems in readers?

**Comment by kelson42** [comment]
@uriesk Content will be incomplete and we can imagine a long number of weird scenarios.

**Comment by uriesk** [comment]
May i ask: Why doesn't a 404 that gets skipped cause the same problem?
And i guess a
```js
                        const zimArticle = new ZimArticle({
                            url: articleId,
                            data: `<h1>Article Not Available</h1>Some error text`,
                            ns: articleDetail.ns === 14 ? 'U' : 'A',
                            mimeType: 'text/html',
                            title: articleTitle,
                            shouldIndex: true,
                        });

```
would not be acceptable because we don't have translations and can't have english error page for a german zim?

I just keep asking questions because i am into manually curating a list of Articles to skip.
Lets say i have a wiki with 10k pages and 10 backend errors. At some point some could work again. But at no point all of them work. So i would have to maintain the list and specifically try each them from time to time to see when things improve on the backend.

**Comment by kelson42** [comment]
The 404 scenario happens rarely when an article is deleted between the time we scrape the list of articles and the time we scrape the HTML of a specific article. This is a legitimate scenario.

**Comment by uriesk** [comment]
How about keeping track of which article links to what, and when an error is encountered, fetch all the previous articles that linked to it again?
Then not even a 404 would cause broken links.

**Comment by kelson42** [comment]
@uriesk This is "not possible" or would make the whole scraping process far more complex/fragile/long/...

**Comment by uriesk** [comment]
Looking at it, every single link to another article goes through `removeOrEncodeLink` anyway. I am ready to do that and store those references in redis hashes.

Can libzim change an already added Item, or is it done and untouchable?

**Comment by kelson42** [comment]
@uriesk No, this will increase the memory usage and the CPU usage significantly without a sufficient reason.

**Comment by uriesk** [comment]
Well, if we got broken links, it would be handy to remove them.
Sounds like the only good solution to me, if they are unavoidable based on scrapping time and deleted articles in between anyway.
Can be optional.
