### ISSUE TITLE
git master head unable to scrapper properly Wikipedia

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#171]
This is the kind of result I get. I suspect one of the last commits.
![fireshot capture 001 - chelha tunisien_ - http___download kiwix org_8081_wik](https://user-images.githubusercontent.com/1029718/33574082-2ead3062-d938-11e7-9723-4ad636c6b5fa.png)

**Comment by subbuss** [comment]
Can you quickly tell me what is broken? I dont have a kiwix reader to compare before/after.

**Comment by kelson42** [comment]
@subbuss like you see on the screenshot, the html is somehow escaped and not interpreted anymore. See a demo here http://download.kiwix.org:8080/wikipedia_fr_tunisie_2017-12/A/Dar_Zarrouk.html.

**Comment by kelson42** [comment]
@subbuss Problem has been introduced with that commit https://github.com/openzim/mwoffliner/commit/21318435a6c938b6ad348a2d0177e0f9fd09ec60 ... but still unclear why this move escape the HTML (replace special characters with HTML entities).

**Comment by subbuss** [comment]
Ha .. that is odd. I'll take a look later today.

**Comment by kelson42** [comment]
@subbuss problem fixed, swig escapes html per default

**Comment by subbuss** [comment]
Interesting .. @kelson42 worth checking all templates in https://github.com/openzim/mwoffliner/tree/master/lib/templates to see if others need this fix too.
