### ISSUE TITLE
rest API vs. visualeditor

### ISSUE THREAD

**Issue by uriesk** [openzim/mwoffliner#1717]
[This](https://minecraft.fandom.com/rest.php/v1/page/Bedrock_Edition_data_values%2FMetadata_table/html) is good while [this](https://minecraft.fandom.com/api.php?action=visualeditor&mobileformat=html&format=json&paction=parse&page=Bedrock_Edition_data_values%2FMetadata_table) is not.
And when `rest.php` returns an upstream timeout, you can later try it again and there's a good chance that it works.

**Comment by kelson42** [comment]
REST API is more recenr than rhe Visualeditor API and does not provide a mobile friendly ouput. These are the main reason why this is not supported so far in MWoffliner.

**Comment by uriesk** [comment]
What do you think about about trying with the rest API in cases where visualeditor fails?
