### ISSUE TITLE
Batch isMirrored redis requests on article parsing

### ISSUE THREAD

**Issue by uriesk** [openzim/mwoffliner#1718]
When an article is parsed, every single wikilink within the article checks if the linked article is going to be parsed too and available in [isMirrored](https://github.com/openzim/mwoffliner/blob/main/src/util/rewriteUrls.ts#L16), which gets sequentially awaited.

I checked how big the impact is, and on parsing the 19.577 articles of the [pokemon wiki](https://pokemon.fandom.com) i got 2.685.074 wikilinks, spending 53min17s awaiting redis HGET.
A basic improvement would be to batch the requests per article and filter out duplicates.
It's impossible to say how much the performance impact will be, since we are in workers waiting for network requests, but it's well worth it to try.

(follow up to what what i raised in a comment in  https://github.com/openzim/mwoffliner/issues/1176#issuecomment-1372409102)

**Comment by kelson42** [comment]
100% supportive
