### ISSUE TITLE
Make a ZIM of psiram

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#172]

**Comment by kelson42** [comment]
done

**Comment by okkebal** [comment]
Why make a Zim of such a dis-info site?

**Comment by ISNIT0** [comment]
Hi @okkebal,
I personally stand for free access to knowledge. The hope is that if more people have access to more knowledge, eventually the in-correct information is un-earthed.

You can read more about the WikiMedia Foundation's mission statement here: https://wikimediafoundation.org/about/mission/
Many projects have similar missions to them.

Hope this helped
