### ISSUE TITLE
wikipedia_en_indian_cinema_maxi_2022-12.zim have some undefined mimetype.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/mwoffliner#1722]
Some (if not all) `.gif` entries have the namespace "undefined"

```
$ ./zimdump list --url='I/Vargam.gif' wikipedia_en_indian_cinema_maxi_2022-12.zim
path: I/Vargam.gif
* title:          Vargam.gif
* idx:            66527
* type:           item
* mime-type:      undefined
* item size:      19770
```

I don't know if it is common to all wikipedia zim files.

**Comment by kelson42** [comment]
Looks clearly like a bug.

**Comment by kelson42** [comment]
@mgautierfr Is that normal that the libzim allows this (empty mime-type)?

**Comment by mgautierfr** [comment]
It is not empty, it is "undefined"

**Comment by uriesk** [comment]
Might be ok on the dev branch already.
At least a
```
--adminEmail="contact@kiwix.org" --format="nopic:nopic" --format="novid:maxi" --mwUrl="https://en.wikipedia.org/" --customZimFavicon="https://upload.wikimedia.org/wikipedia/commons/0/01/Bollywoodbarnstar.png" --customZimTitle="Bollywood by Wikipedia" --customZimDescription="A selection of Wikipedia articles on Bollywood" --articleList="Vargam" --webp
```
gives me a zim file with said gif and correct mime-type.

**Comment by kelson42** [comment]
@uriesk Thx, will should check with latest stable 1.11.12 as well. Wonder also if a wrong value in the S3 cache could lead to such bug.
@mgautierfr OK so the "undefined" string

**Comment by mgautierfr** [comment]
Yes, it is probably a (real) `undefined` value in js which is cast to the `"undefined"` string when passed to libzim.

**Comment by uriesk** [comment]
@kelson42 
> Wonder also if a wrong value in the S3 cache could lead to such bug.
you are right,
https://github.com/openzim/mwoffliner/blob/main/src/Downloader.ts#L625
A 304 doesn't give you the content-type (and isn't supposed to per RFC, because it has no content) so it's undefined, unless the webp conversion sets it.

Have to carry it with you like the etag #1723
I can't test that, its on you :)
