### ISSUE TITLE
Wikipedia Portal:******* and others also missing in ZIM files

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1726]
The ZIM Wikipedia files are missing projects with a colon:, such as:
[Portal:Sports](https://en.wikipedia.org/wiki/Portal:Sports)
[Wikipedia:Featured lists](https://en.wikipedia.org/wiki/Wikipedia:Featured_lists)
[Wikipedia:WikiProject](https://en.wikipedia.org/wiki/Wikipedia:WikiProject)

**Comment by Inbefortus** [comment]
There are already portals in the English Wikipedia Mini:

- https://library.kiwix.org/content/wikipedia_en_all_mini_2023-01/A/Portal:Sports


Thus far, only

- https://farm.openzim.org/recipes/wikipedia_en_all


- https://farm.openzim.org/recipes/wikipedia_en_all_maxi


will include portals.



The rest I agree with. They would also be nice to have!

**Comment by kelson42** [comment]
@RavanJAltaie This is a howtomake a request, not even a ticket lifecycle explanation nor anythingv related to the zimfarm recipes... and this is what I'm talking about.
@kelson42 I'm not been involved in any documentation or knowhow transfert these last months

**Comment by Ubuntu-2020** [comment]
@Inbefortus
It is strange. In _ru Wiki_ I [did not see](https://library.kiwix.org/viewer#wikipedia_ru_all_maxi_2022-12/A/Участник:The_other_Kiwix_guy/Landing) Portals:
In online Wiki Portal:Sport [looks like this](https://ru.wikipedia.org/wiki/Портал:Спорт).

**Comment by kelson42** [comment]
@Ubuntu-2020 In principle, in favour of including portals. Actually this is already the case for a few Wikipedias ZIM.

But I'm not in favour of making it sysematicaly. Not all Wikipedias have proper portals AFAIK. Please share here the specific Wikipedias you want to benefit of this (and for each the namespace numbet, not sure thos is always the same).

Regarding the two other namespaces, they are meta. They are used to write articles (mostly). Therefore they are not included and I'm not in favour of changing this.

**Comment by Ubuntu-2020** [comment]
@kelson42
> Please share here the specific Wikipedias you want to benefit of this (and for each the namespace numbet, not sure thos is always the same).

Some **Portals** in **RU Wiki**:
Portal:Aviation / [Портал:Авиация](https://ru.wikipedia.org/wiki/Портал:Авиация)
Portal:Astronomy/ [Портал:Астрономия](https://ru.wikipedia.org/wiki/Портал:Астрономия)
Portal:Spaceflight / [Портал:Космонавтика](https://ru.wikipedia.org/wiki/Портал:Космонавтика)
Portal:Computer programming/ [Портал:Программирование](https://ru.wikipedia.org/wiki/Портал:Программирование)
[Портал:Компьютерные_технологии](https://ru.wikipedia.org/wiki/Портал:Компьютерные_технологии) and [the best articles](https://ru.wikipedia.org/wiki/Портал:Компьютерные_технологии/Лучшие_статьи)
Portal:Technology / [Портал:Техника](https://ru.wikipedia.org/wiki/Портал:Техника) and [the best articles](https://ru.wikipedia.org/wiki/Портал:Техника/Лучшие_статьи)
Portal:Cars / [Портал:Автомобиль](https://ru.wikipedia.org/wiki/Портал:Автомобиль)
Portal:Trains / [Портал:Железнодорожный транспорт](https://ru.wikipedia.org/wiki/Портал:Железнодорожный транспорт)
Portal:Fotografie / [Портал:Фотография](https://ru.wikipedia.org/wiki/Портал:Фотография)
Portal:Formula One / [Портал:Формула-1](https://ru.wikipedia.org/wiki/Портал:Формула-1)
[Портал:География](https://ru.wikipedia.org/wiki/Портал:География) and [the best articles](https://ru.wikipedia.org/wiki/Портал:География/Лучшие_статьи)

Some **Project** in **RU Wiki**:
[Проект:Автомобиль](https://ru.wikipedia.org/wiki/Проект:Автомобиль)

**Comment by kelson42** [comment]
@Ubuntu-2020 I can only scrape all portals for a wiki or none. We do that by adding a new Mediawiki namespace to scrape. Here for WPRU (maybe for all Wikipedia?) the namespace for portals is the one with number `100`. I have added it in the WPRU all recipe (no additional namespace was supported) at https://farm.openzim.org/recipes/wikipedia_ru_all/. In February ZIM files, the portals should be there.
