### ISSUE TITLE
ibanez_guitars recipe failed

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/mwoffliner#1727]
Hi,
The Recipe below has failed
https://farm.openzim.org/recipes/ibanez_guitars

Scraper stdout :
```
starting redis-server in the background…
[log] [2023-01-10T22:12:41.186Z] Successfully logged in S3
[log] [2023-01-10T22:12:41.410Z] closing sanitize redis DB
[log] [2023-01-10T22:12:41.413Z] Starting mwoffliner v1.11.12...
[log] [2023-01-10T22:12:41.680Z] Successfully logged in S3
[log] [2023-01-10T22:12:41.688Z] Getting text direction...
[log] [2023-01-10T22:12:41.690Z] Getting site info...
[log] [2023-01-10T22:12:41.690Z] Getting sub-title...
[log] [2023-01-10T22:12:41.935Z] Text direction is [ltr]

```
Scraper stderr:
```
Failed to run mwoffliner after [2s]: {
	"stack": "Error: customMainPage doesn't return 200 status code for url https://ibanez.fandom.com/en/wiki/https%3A%2F%2Fibanez.fandom.com%2Fwiki%2FIbanez_Wiki\n    at Object.<anonymous> (/tmp/mwoffliner/lib/mwoffliner.lib.js:164:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/tmp/mwoffliner/lib/mwoffliner.lib.js:26:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
	"message": "customMainPage doesn't return 200 status code for url https://ibanez.fandom.com/en/wiki/https%3A%2F%2Fibanez.fandom.com%2Fwiki%2FIbanez_Wiki"
}


**********

customMainPage doesn't return 200 status code for url https://ibanez.fandom.com/en/wiki/https%3A%2F%2Fibanez.fandom.com%2Fwiki%2FIbanez_Wiki

**********



```
Please investigate

**Comment by kelson42** [comment]
The error say the custom main page is not proper. Looks like a configuration problem.

**Comment by RavanJAltaie** [comment]
I've rechecked the main page, updated it, opened it, all looks ok
I've requested the recipe again

**Comment by kelson42** [comment]
@RavanJAltaie I have renamed the recipe to `ibanez_fandom_es_all` so they share the name with the other Fandom recipes... and put the tag. In general, look how other recipes are made and try to mimic.

**Comment by kelson42** [comment]
Look to the log accurately, you will have all the information to fix the recipe. What you have put in the mian page URL, not the main page article_id/Title. It should not be https://ibanez.fandom.com/wiki/Ibanez_Wiki, but `Ibanez_Wiki`.. actually because this is already the mainpage, specifying nothing is good enough. I will just empty the field and restart.
