### ISSUE TITLE
Wikipedia 0.8 with final version supposedly released March 2011 contains articles on COVID-19

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#1731]
I'm referencing `wikipedia_en_wp1-0.8_maxi_2023-01.zim`, the landing page of which says: "The final release of Wikipedia Version 0.8 was published on 3 March 2011 and is now available here, as a Kiwix reader + corpus.". If this is intended as a corpus, then the articles should be as they were on 3 March 2011, unless I've misunderstood the purpose of this release.

<img alt="image" src="https://user-images.githubusercontent.com/4304337/212540144-e346c47f-f6ed-426d-b312-fcc4d7d29296.png">

**Comment by Jaifroid** [comment]
I thought perhaps the articles in the alphabetical index would be their 2011 versions, and the others had just "leaked" in due to some link following, but here is an example of an article listed in the index, "Dexamethasone", which contains current text:

<img width="564" alt="image" src="https://user-images.githubusercontent.com/4304337/212540874-f370e5ad-20e0-4adb-8c86-4c081b640c38.png">

<img width="559" alt="image" src="https://user-images.githubusercontent.com/4304337/212540917-1175b883-47bd-4d8a-b32e-4d223cf1a54d.png">

**Comment by kelson42** [comment]
The article selection is from 2011, but we make a new scrape each month. Not sure to fully understand the problem. @Jaifroid  What do you propose to improve the situation?

**Comment by Jaifroid** [comment]
I think most users downloading "Wikipedia 0.8" from library.kiwix.org, and reading the description on the landing page, would assume they were accessing content as it was from 2010/11:

> The final release of Wikipedia Version 0.8 was published on 3 March 2011 and is now available here, as a Kiwix reader + corpus.
> 
> Welcome to Wikipedia Version 0.8! This test release is a general release of around 47,300 articles taken from all subject areas, using systems developed by a group of volunteers from the Wikipedia community. Articles were selected in late 2010, based on a combination of importance and quality. Articles may be found using the [search engine](http://toolserver.org/~enwp10/bin/list2.fcgi), or by browsing the alphabetical index shown below.

(see screenshot at bottom for full text)

If the intention is, in fact, to provide an updated "Wikipedia 0.8" for the current day, then the description is misleading. It implies the content is historical and is made available as a corpus. As a corpus, it has no philological value if the content cannot be dated to the time of its publication.

My suggestion depends on what is technically possible:

* If it is possible to produce a modern scrape of the Wikipedia 0.8 data (as published on 3rd March 2011), then that should be done, so that we have all the historical data in a modern ZIM format. I assume this is not currently possible with mwOffliner, so instead:

  + Make the legacy (original 2010/11) version of Wikipedia 0.8 available in library.kiwix.org;
  + Change the description of the 2023+ version, to make clear that the content is modern, not historical, and let the user know which version(s) to download if they would like historical data.

<img alt="image" src="https://user-images.githubusercontent.com/4304337/212562429-08411d81-65ef-4dbc-838f-4c432c6f36bd.png">

**Comment by kelson42** [comment]
It's not possible to scrape the content like it was 10 years ago. Maybe we should simply be better to stop publishing updates?

**Comment by Jaifroid** [comment]
> Maybe we should simply be better to stop publishing updates?

Unless you know of some other value of having updated content for Wikipedia 0.8 -- comparison of old and new, maybe? -- then a hybrid of historical structure and modern content doesn't on the face of it look like a useful publication, compared to the original Wikipedia 0.8 with historical article content (which is of historical interest 12 years on, and will be of even greater interest as time goes on!).

But maybe others should have some input here (@Inbefortus implied he was using it, @Popolechien)?

In the meantime, I've updated the information and links on https://en.wikipedia.org/wiki/Wikipedia:Version_0.8/downloads, clarifying which file contains what: i.e. that the working link for the legacy archive contains the historical data (I also corrected the torrent download link to that, which was a deadlink), and that the current most recently scraped file contains modern, not historical data.

Depending on the outcome of this issue, it might be useful to update the [landing page here](https://en.wikipedia.org/wiki/Wikipedia:Version_0.8) to make clear that browsing the articles will not give historical data (and how to access the historical version).

**Comment by Popolechien** [comment]
I think this selection should be discontinued altogether, we have enough alternatives and having to much choice is confusing, particularly for people with limited resources for download. 
TBH we are in the low connectivity business, not the _historical interest_ one.

**Comment by kelson42** [comment]
@Popolechien Agree
@rgaudin I have deactivated the recipe. Can you please move https://download.kiwix.org/zim/wikipedia/wikipedia_en_wp1-0.8_maxi_2023-01.zim to https://download.kiwix.org/archive/zim/wikipedia/ and delete all the other 0.8 ZIM files?
@walkerma FYI

**Comment by rgaudin** [comment]
@kelson42 done

**Comment by Jaifroid** [comment]
> TBH we are in the low connectivity business, not the historical interest one.

But we have a significant crossover of interest (and collaboration) with the Internet Archive, so I wouldn't personally see things in quite such either/or terms! However, I agree that there is no need to keep producing this ZIM with anomalous content. We have the definitive version of Wikipedia 0.8, and we should keep that (it is linked to from the project pages on Wikipedia).

**Comment by kelson42** [comment]
@rgaudin thx!
