### ISSUE TITLE
S3 testing should be part of the CI

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1733]
It seems is not, probably because the credentials are not available.

**Comment by kelson42** [comment]
@rgaudin Do we already have a bucket? Otherwise could you please create one?

**Comment by rgaudin** [comment]
I don't understand the ticket.

Yes there is, as for all scrapers, a second, dev bucket but it obviously requires authentication.

**Comment by rgaudin** [comment]
If it's for adding S3-related tests in unit tests or a similar goal, maybe we could have a dedicated scraper-wide bucket

**Comment by uriesk** [comment]
I believe the S3 unit tests worked before the switch to jest.
I am sure i saw the S3 etag test checked as successful before.
Can we trigger a test with 1.11.12 without having to do a pull request?

**Comment by kelson42** [comment]
@pavel-karatsiuba Can you please enlight us?

**Comment by uriesk** [comment]
tested it, also skipped it
```
  Downloader class with optimisation
    [log] [2023-01-16T10:39:31.883Z] Skip S3 tests in Downloader class
```
really weird, i could have sworn i saw the checked before...

**Comment by kelson42** [comment]
@pavel-karatsiuba Please fix, let me know per slack if you need the credentials.

**Comment by kelson42** [comment]
Automated tests for S3 depend on the `$S3_URL` env variable. This one has been set in the Github Actions workflow (using a secret). The `$S3_URL` used in the CI points to a S3 bucket reserverd for the CI. It seems to be used, because S3 automated tests are not skipped anymore... and CI fails.

I suspect this is because all the CI runs uses the same bucket and tacle the same variable names. If this is confirmed, we should IMO:
* Add a way (maybe a random prefix for S3 keys) to secure the automated tests ton override on existing objects
* Clean properly each time the automated tests are over (even in case of failure)

**Comment by kelson42** [comment]
@pavel-karatsiuba Wonder why tiff or ogg generates a problem honestly because they are legit content.

**Comment by pavel-karatsiuba** [comment]
@kelson42 The test is testing the Downloader class. Method getContentCb() stores images on S3 and other files are not. Only files with these extensions are stored in S3: jpg|gif|png|svg|jpeg.
