### ISSUE TITLE
Recipe failed (Memory Alpha)

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/mwoffliner#1736]
The recipe below has failed 
https://farm.openzim.org/recipes/memory_alpha_fandom_en_all

Scraper stdout: ```
[log] [2023-01-14T16:09:44.050Z] Progress downloading articles [31740/54665] [58.1%]
[log] [2023-01-14T16:10:14.238Z] Progress downloading articles [31790/54665] [58.2%]
[log] [2023-01-14T16:10:57.548Z] Progress downloading articles [31850/54665] [58.3%]
[log] [2023-01-14T16:11:29.074Z] Progress downloading articles [31900/54665] [58.4%]
[log] [2023-01-14T16:12:04.446Z] Progress downloading articles [31960/54665] [58.5%]
T:19910; A:32000; RA:1; CA:31998; UA:1; FA:0; IA:31978; C:173; CC:173; UC:0; WC:0
[log] [2023-01-14T16:12:34.520Z] Progress downloading articles [32010/54665] [58.6%]
[log] [2023-01-14T16:13:09.326Z] Progress downloading articles [32070/54665] [58.7%]
[log] [2023-01-14T16:13:38.408Z] Progress downloading articles [32120/54665] [58.8%]
[log] [2023-01-14T16:14:12.052Z] Progress downloading articles [32180/54665] [58.9%]
[log] [2023-01-14T16:14:40.625Z] Progress downloading articles [32230/54665] [59.0%]
[log] [2023-01-14T16:15:14.314Z] Progress downloading articles [32280/54665] [59.1%]
[log] [2023-01-14T16:15:46.847Z] Progress downloading articles [32340/54665] [59.2%]
[log] [2023-01-14T16:16:19.841Z] Progress downloading articles [32390/54665] [59.3%]
[log] [2023-01-14T16:16:57.367Z] Progress downloading articles [32450/54665] [59.4%]
[log] [2023-01-14T16:17:24.484Z] Progress downloading articles [32500/54665] [59.5%]
[log] [2023-01-14T16:18:00.376Z] Progress downloading articles [32560/54665] [59.6%]
[log] [2023-01-14T16:18:27.453Z] Progress downloading articles [32610/54665] [59.7%]
[log] [2023-01-14T16:19:03.208Z] Progress downloading articles [32670/54665] [59.8%]
[log] [2023-01-14T16:19:31.282Z] Progress downloading articles [32720/54665] [59.9%]
[log] [2023-01-14T16:20:06.396Z] Progress downloading articles [32780/54665] [60.0%]
[log] [2023-01-14T16:20:33.639Z] Progress downloading articles [32830/54665] [60.1%]
[log] [2023-01-14T16:21:08.079Z] Progress downloading articles [32890/54665] [60.2%]
[log] [2023-01-14T16:21:40.981Z] Progress downloading articles [32940/54665] [60.3%]
T:20498; A:33000; RA:1; CA:32998; UA:1; FA:0; IA:32978; C:178; CC:178; UC:0; WC:0
[log] [2023-01-14T16:22:17.596Z] Progress downloading articles [33000/54665] [60.4%]
[log] [2023-01-14T16:22:53.527Z] Progress downloading articles [33050/54665] [60.5%]
[log] [2023-01-14T16:23:21.280Z] Progress downloading articles [33100/54665] [60.6%]
[log] [2023-01-14T16:23:58.174Z] Progress downloading articles [33160/54665] [60.7%]
[log] [2023-01-14T16:24:27.361Z] Progress downloading articles [33210/54665] [60.8%]
[log] [2023-01-14T16:25:03.480Z] Progress downloading articles [33270/54665] [60.9%]
[log] [2023-01-14T16:25:38.514Z] Progress downloading articles [33320/54665] [61.0%]
[log] [2023-01-14T16:26:23.964Z] Progress downloading articles [33380/54665] [61.1%]
[log] [2023-01-14T16:26:57.483Z] Progress downloading articles [33430/54665] [61.2%]
[log] [2023-01-14T16:27:30.081Z] Progress downloading articles [33490/54665] [61.3%]
[log] [2023-01-14T16:27:58.575Z] Progress downloading articles [33540/54665] [61.4%]
[log] [2023-01-14T16:28:33.351Z] Progress downloading articles [33600/54665] [61.5%]
[log] [2023-01-14T16:29:04.146Z] Progress downloading articles [33650/54665] [61.6%]
[log] [2023-01-14T16:29:38.739Z] Progress downloading articles [33710/54665] [61.7%]
[log] [2023-01-14T16:30:07.195Z] Progress downloading articles [33760/54665] [61.8%]
[log] [2023-01-14T16:30:43.794Z] Progress downloading articles [33820/54665] [61.9%]
[log] [2023-01-14T16:31:14.395Z] Progress downloading articles [33870/54665] [62.0%]
[log] [2023-01-14T16:31:44.345Z] Progress downloading articles [33920/54665] [62.1%]
T:21115; A:34000; RA:1; CA:33998; UA:1; FA:0; IA:33978; C:183; CC:183; UC:0; WC:0
[log] [2023-01-14T16:32:21.573Z] Progress downloading articles [33980/54665] [62.2%]
[log] [2023-01-14T16:32:48.290Z] Progress downloading articles [34030/54665] [62.3%]
[log] [2023-01-14T16:33:26.569Z] Progress downloading articles [34090/54665] [62.4%]
[log] [2023-01-14T16:33:55.094Z] Progress downloading articles [34140/54665] [62.5%]
[log] [2023-01-14T16:34:30.088Z] Progress downloading articles [34200/54665] [62.6%]
[log] [2023-01-14T16:35:00.497Z] Progress downloading articles [34250/54665] [62.7%]
[log] [2023-01-14T16:35:40.099Z] Progress downloading articles [34310/54665] [62.8%]
[log] [2023-01-14T16:36:15.274Z] Progress downloading articles [34360/54665] [62.9%]
[log] [2023-01-14T16:36:49.820Z] Progress downloading articles [34420/54665] [63.0%]
[log] [2023-01-14T16:37:21.396Z] Progress downloading articles [34470/54665] [63.1%]
[log] [2023-01-14T16:37:58.540Z] Progress downloading articles [34530/54665] [63.2%]
[log] [2023-01-14T16:38:28.333Z] Progress downloading articles [34580/54665] [63.3%]
[log] [2023-01-14T16:39:04.466Z] Progress downloading articles [34640/54665] [63.4%]
[log] [2023-01-14T16:39:33.136Z] Progress downloading articles [34690/54665] [63.5%]
[log] [2023-01-14T16:40:11.342Z] Progress downloading articles [34740/54665] [63.6%]
[log] [2023-01-14T16:40:51.388Z] Progress downloading articles [34800/54665] [63.7%]
[log] [2023-01-14T16:41:25.315Z] Progress downloading articles [34850/54665] [63.8%]
[log] [2023-01-14T16:42:01.205Z] Progress downloading articles [34910/54665] [63.9%]
[log] [2023-01-14T16:42:32.144Z] Progress downloading articles [34960/54665] [64.0%]
T:21737; A:35000; RA:1; CA:34998; UA:1; FA:0; IA:34978; C:189; CC:189; UC:0; WC:0
[log] [2023-01-14T16:43:09.547Z] Progress downloading articles [35020/54665] [64.1%]
[log] [2023-01-14T16:43:40.053Z] Progress downloading articles [35070/54665] [64.2%]
[log] [2023-01-14T16:44:19.057Z] Progress downloading articles [35130/54665] [64.3%]
[log] [2023-01-14T16:44:50.783Z] Progress downloading articles [35180/54665] [64.4%]
[log] [2023-01-14T16:45:31.926Z] Progress downloading articles [35240/54665] [64.5%]
[log] [2023-01-14T16:46:04.243Z] Progress downloading articles [35290/54665] [64.6%]
[log] [2023-01-14T16:46:41.908Z] Progress downloading articles [35350/54665] [64.7%]
[log] [2023-01-14T16:47:14.793Z] Progress downloading articles [35400/54665] [64.8%]
[log] [2023-01-14T16:47:54.731Z] Progress downloading articles [35460/54665] [64.9%]
[log] [2023-01-14T16:48:22.535Z] Progress downloading articles [35510/54665] [65.0%]
[log] [2023-01-14T16:48:54.431Z] Progress downloading articles [35560/54665] [65.1%]
[log] [2023-01-14T16:49:31.834Z] Progress downloading articles [35620/54665] [65.2%]
[log] [2023-01-14T16:50:03.398Z] Progress downloading articles [35670/54665] [65.3%]
[log] [2023-01-14T16:50:39.220Z] Progress downloading articles [35730/54665] [65.4%]
[log] [2023-01-14T16:51:10.819Z] Progress downloading articles [35780/54665] [65.5%]
[log] [2023-01-14T16:51:53.372Z] Progress downloading articles [35840/54665] [65.6%]
[log] [2023-01-14T16:52:21.501Z] Progress downloading articles [35890/54665] [65.7%]
[log] [2023-01-14T16:53:02.073Z] Progress downloading articles [35950/54665] [65.8%]
T:22377; A:36000; RA:1; CA:35998; UA:1; FA:0; IA:35978; C:195; CC:195; UC:0; WC:0
[log] [2023-01-14T16:53:38.270Z] Progress downloading articles [36000/54665] [65.9%]
[log] [2023-01-14T16:54:17.185Z] Progress downloading articles [36060/54665] [66.0%]
[log] [2023-01-14T16:54:50.229Z] Progress downloading articles [36110/54665] [66.1%]
[log] [2023-01-14T16:55:26.898Z] Progress downloading articles [36170/54665] [66.2%]
[log] [2023-01-14T16:55:55.967Z] Progress downloading articles [36220/54665] [66.3%]
[log] [2023-01-14T16:56:34.652Z] Progress downloading articles [36280/54665] [66.4%]
[log] [2023-01-14T16:57:09.815Z] Progress downloading articles [36330/54665] [66.5%]
[log] [2023-01-14T16:57:42.865Z] Progress downloading articles [36380/54665] [66.6%]
[log] [2023-01-14T16:58:24.600Z] Progress downloading articles [36440/54665] [66.7%]
[log] [2023-01-14T16:58:37.474Z] Exiting with code [2]
[log] [2023-01-14T16:58:37.474Z] Deleting temporary directory [/dev/shm/mwoffliner-1673692770588]

```
Scraper stderr :
```
[error] [2023-01-14T16:58:37.471Z] Error downloading article /Xam_Abathwa
Failed to run mwoffliner after [22752s]: {
	"code": "apierror-visualeditor-docserver-http",
	"info": "Error contacting the Parsoid/RESTBase server (HTTP 500)",
	"*": "See https://memory-alpha.fandom.com/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes."
}

```
Please check.

**Comment by kelson42** [comment]
@RavanJAltaie The error of the console is pretty clear: "Error contacting the Parsoid/RESTBase server (HTTP 500)". This means that the server is not able to respond properly, and the the MWoffliner just stops because of that. With next release of MWoffliner to come soon, we will have an option to ignore certain specific solutions and this might be a solution here to apply  (if there is only one or two article with a problem)... Otherwise there is nothing else we can do.

**Comment by RavanJAltaie** [comment]
Thanks for the clarification @kelson42 
Well Noted.
