### ISSUE TITLE
E2E artileList tests failing

### ISSUE THREAD

**Issue by uriesk** [openzim/mwoffliner#1739]
in all recent pull requests, two e2e tests fail,

1. `Simple customMainPage` in ` test/e2e/extra.e2e.test.ts`
because it gets 6 out of 7 pages, probably because [Wikipedia:Books/archive/Ears_nose_throat](https://en.wikipedia.org/wiki/Wikipedia:Books/archive/Ears_nose_throat) can not be found

2. `Simple article List` in test/e2e/en10.e2e.test.ts
because it gets less files than it expects.

**Comment by uriesk** [comment]
I hope that those were just legit wikipedia edits and it's not those recent Interface Changes that mess things up

**Comment by kelson42** [comment]
I confirm the two problems. We run automated tests again en.wikipedia.org. That means that if upstream wikipedia articles are edited, it might brake the tests. This happens time to time.

**Comment by uriesk** [comment]
@kelson42 
all the code coverage reports are lower percentage now because we don't test a "subpage" anymore... whatever this is.

https://app.codecov.io/gh/openzim/mwoffliner/pull/1723
<img width="771" alt="image" src="https://user-images.githubusercontent.com/13338250/213447207-e593c129-54ab-4b9b-bcce-e2c46d873e1a.png">

**Comment by kelson42** [comment]
Readd https://en.wikipedia.org/wiki/Wikipedia:Subpages.

**Comment by kelson42** [comment]
@uriesk If we add https://en.wikipedia.org/wiki/Wikipedia:Books/archive/Algorithms, would that solve the problem?
