### ISSUE TITLE
CI builds with node 16.x Fatal Error

### ISSUE THREAD

**Issue by uriesk** [openzim/mwoffliner#1758]
About 2 out of 3 CI builds fail with

```
#
# Fatal error in , line 0
# Check failed: result.second.
#
#
#
#FailureMessage Object: 0x7ffc28eee030
 1: 0xb71fa1  [node]
 2: 0x1bf9fa4 V8_Fatal(char const*, ...) [node]
 3: 0xfb7601 v8::internal::GlobalBackingStoreRegistry::Register(std::shared_ptr<v8::internal::BackingStore>) [node]
 4: 0xd08ff8 v8::ArrayBuffer::GetBackingStore() [node]
 5: 0xae[27](https://github.com/openzim/mwoffliner/actions/runs/4026998437/jobs/6922197530#step:12:28)41  [node]
 6: 0xd3ddfe  [node]
 7: 0xd3f21f v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
 8: 0x15d9cf9  [node]
Illegal instruction (core dumped)
```

You can re-run it till it eventually succeeds. But it is getting annoying now.

Looking at the error, i find reports for node https://github.com/nodejs/node/issues/32463 and node-addon-api https://github.com/nodejs/node-addon-api/issues/799
Here some other project solves it by switching from ArrayBuffer to Externals https://github.com/Bannerets/tdl/issues/119

We could either test different node 16.x versions till we find one that is more stable, or we drag it over to openzim/node-libzim, cause that is probably what triggers it.

**Comment by kelson42** [comment]
Seems to be a regression to me as we don't have changed anythin at node-libzim since many months.

**Comment by uriesk** [comment]
Sharp is my second guess.
Also shifts ArrayBuffers with node-addon-api around and we updated it recently.

**Comment by uriesk** [comment]
We won't be able to solve this.
We would have to wait for some node 16.x or other update that fixes it.
But until then, node 16 reached end-of-life (september this year), while 18 is the current LTS.

I rather drop node 16 support and add node 19 (so we got current release and current LTS) than waste time with this.

**Comment by kelson42** [comment]
@uriesk Not super happy to drop support of Node.js 16.x... but if there is a really good reason. OK for me. AFAIK we can not automated test so far for Node.js 19, last time I tried, somehow the action which should install it was not ready.

To conclude: OK for me to drop Node.js 16 (we should take care the doc, and necessary check of Node version should be implemented/updated). At the end Node.js 18 is still pretty recent.

**Comment by uriesk** [comment]
Lets think about that in 1.13 then.
This bug is just an annoyance and not urgent.
