### ISSUE TITLE
[warn] Unable to find an appropriate video/audio source for 'undefined'

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1761]
Scraping recipe `wikipedia_en_top1m` on Zimfarm, we have seen this kind of error:
```
[warn] [2023-01-31T16:42:30.623Z] Unable to find an appropriate video/audio source for 'undefined'
```

This error/warning appearing almost 1500 times.

This is the first time I remark this error. Therefore I wonder if this is somehow a regression we have introduced recently?

Here there is a kind of hint that there is a bug at least in the error message, we should not have `undefined`.

I would also like to better know when this kind of warning appears and if this is actually legitimate here. We should also have a way to know in which article we have "a problem" (or at least with wich video filename), otherwise the error message has not much value.

**Comment by uriesk** [comment]
Looked a bit into it.
The warning happens when there is a video or audio element that has no webm or audio source.

We should make the warning message better and give us the articleId instead.

**Comment by kelson42** [comment]
@pavel-karatsiuba Please identify which artickes go wrong based on zimfarm log and explain what goes wrong

**Comment by pavel-karatsiuba** [comment]
@kelson42 The last logs from successfully finished scrapes are not contained such messages. Or this warning is not relevant anymore or need to check the future log to be sure.

**Comment by kelson42** [comment]
I confirm the error seems to have vanished in latest run.
