### ISSUE TITLE
ZIM file from `https://wiki.ubuntu.com/`

### ISSUE THREAD

**Issue by kensully** [openzim/mwoffliner#177]
How can I create `zim` file from `https://wiki.ubuntu.com/` ?

**Comment by kelson42** [comment]
@kensully It looks like wiki.ubuntu.com uses https://moinmo.in wiki engine. MWoffliner is a solution for Mediawiki, an other wiki engine. There is nothing much we can do. A scrapper should be written for MoinMoin (and then use zimwriterfs to create the ZIM file).
