### ISSUE TITLE
[REGRESSION] A large number of images are missing in the most recent Wikipedias

### ISSUE THREAD

**Issue by Inbefortus** [openzim/mwoffliner#1772]
- [ZIM](https://farm.openzim.org/pipeline/c19d0393162a6e3377871e36)

Examples:

- https://library.kiwix.org/viewer#wikipedia_en_top_maxi_2023-02/A/Centromere
![Screenshot_20230208-101107](https://user-images.githubusercontent.com/71934042/217485926-542a72d5-20b7-45a7-b093-fc139e271606.jpg)

- https://library.kiwix.org/viewer#wikipedia_en_top_maxi_2023-02/A/Carillon
![Screenshot_20230208-095243](https://user-images.githubusercontent.com/71934042/217484674-f3800bb6-2143-4c0b-af62-5b8f735f788b.jpg)

- https://library.kiwix.org/viewer#wikipedia_en_top_maxi_2023-02/A/Guangxu_Emperor
![Screenshot_20230208-095055](https://user-images.githubusercontent.com/71934042/217484677-6ea40e08-80df-45f9-8124-590e16a7c4fc.jpg)

Upstream is fine:

- https://en.wikipedia.org/api/rest_v1/page/html/Guangxu_Emperor

- https://en.wikipedia.org/api/rest_v1/page/html/Carillon

- https://en.wikipedia.org/api/rest_v1/page/html/Centromere

This month's zimcheck output is significantly longer than last month's:

![Screen_Recording_20230208-101919_Samsung Internet_1](https://user-images.githubusercontent.com/71934042/217489896-a49e85af-0ec5-4ad5-b8cd-586d9f5b8cd3.gif)
![Screen_Recording_20230208-102000_Samsung Internet_1](https://user-images.githubusercontent.com/71934042/217489900-4053e99d-1903-4512-bdee-28d50b12a778.gif)

[French Wikipedia](https://farm.openzim.org/pipeline/50da90d5f590fc71646fbd36) appears to be affected as well:

- https://library.kiwix.org/viewer#wikipedia_fr_all_maxi_2023-02/A/L%C3%A9onard_de_Vinci

![Screenshot_20230208-102810_Samsung Internet](https://user-images.githubusercontent.com/71934042/217490258-5d16353f-b966-420c-b3b3-62aa9c25da53.jpg)
- https://library.kiwix.org/viewer#wikipedia_fr_all_maxi_2023-02/A/Jacques-Louis_David
![Screenshot_20230208-102941_Samsung Internet](https://user-images.githubusercontent.com/71934042/217490263-745502d4-97e1-4fea-93ba-5763e82c1bdd.jpg)

Could all this be related to the [new approach](https://github.com/openzim/mwoffliner/pull/1751) in response to 429 errors? I sincerely hope not, because the new strategy makes a significant difference!

**Comment by kelson42** [comment]
@uriesk I guess we have built a regression here... This confirms my first impression... but I don't have run any investigation so far.

**Comment by kelson42** [comment]
Good news is that missing images are in the ZIM but, for example https://library.kiwix.org/content/wikipedia_en_top_maxi_2023-02/I/Chromosome.svg.png, but https://library.kiwix.org/content/wikipedia_en_top_maxi_2023-02/I/Chromosome.svg.png.webp is referenced.

**Comment by Inbefortus** [comment]
> Good news is that missing images are in the ZIM but, for example https://library.kiwix.org/content/wikipedia_en_top_maxi_2023-02/I/Chromosome.svg.png, but https://library.kiwix.org/content/wikipedia_en_top_maxi_2023-02/I/Chromosome.svg.png.webp is referenced.

This makes sense, as I was perplexed as to why the ZIM with so many "missing" images still remained larger than the previous one... This clarifies it. I'm relieved to hear it's not as severe!

**Comment by Inbefortus** [comment]
@kelson42 Your fix was effective 👍

![Screenshot_20230209-150754_Samsung Internet Beta](https://user-images.githubusercontent.com/71934042/217835624-c3b32eb6-a4e8-42fc-ae8c-ff8279132b8a.jpg)

**Comment by kelson42** [comment]
We will do a patch release soob
