### ISSUE TITLE
Vikidia ZIM files are all ~2 years old

### ISSUE THREAD

**Issue by holta** [openzim/mwoffliner#1778]
Does anyone know why all recent Vikidia scrapes are failing here?
https://farm.openzim.org/recipes?name=vikidia

Separately, the 10-month-old scrape of vikidia_fr "succeeded" but apparently was not transferred to download.kiwix.org ?
https://farm.openzim.org/pipeline/4145ef4050e21f3a15b05426

The result is that all ZIM files are almost ~2 years old here &mdash; might this be easily fixable?
https://download.kiwix.org/zim/vikidia/

Possibly Related:
- openzim/zimfarm#596
- openzim/zimfarm#688

**Comment by kelson42** [comment]
@pavel-karatsiuba Could you please have a look to that one?
