### ISSUE TITLE
Fails to scrape formatting on sub-subpages

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1782]
See for instance https://library.kiwix.org/viewer#wikibooks_es_all_maxi_2022-01/A/Billar/Técnica/Postura_básica where the section layout hasn't been picked up

![Capture d’écran 2023-02-15 à 15 02 04](https://user-images.githubusercontent.com/21675885/219048487-49b5f5de-d952-468f-9b29-7aa6b1b29d1a.png)

As one can see, the scraper kept the `==` rather than turn them into headers.

(this particular zim is from 2022-01 but I ran a smaller selection earlier today and [got the same result](https://dev.library.kiwix.org/viewer#wikibooks_es_billar_maxi_2023-02/A/Billar/T%C3%A9cnica/Postura_b%C3%A1sica))

The issue is [not present](https://es.wikibooks.org/wiki/Billar/T%C3%A9cnica/Postura_b%C3%A1sica) upstream on Wikibooks.

**Comment by kelson42** [comment]
@pavel-karatsiuba Can you check if bug can be reproduced here? Maybe you have a fix in mind?

**Comment by kelson42** [comment]
@Popolechien If I look to the source code, rendering is actually correct https://es.wikibooks.org/w/index.php?title=Billar/T%C3%A9cnica/Tome_de_bola&action=edit.

This is not a bug with MWoffliner.
