### ISSUE TITLE
Is `--addNamespaces="100"` no longer working? (to add Wikipedia's portal pages to ZIM files for schools!)

### ISSUE THREAD

**Issue by holta** [openzim/mwoffliner#1784]
See `--addNamespaces="100"` at the bottom of these 2 recipes:

- https://farm.openzim.org/recipes/wikipedia_en_all/config
- https://farm.openzim.org/recipes/wikipedia_en_all_maxi/config

I believe this is supposed to add Wikipedia's portal pages to a ZIM file, and if I'm understanding @kelson42 this was working in the past.  Questions:
- Is this parameter no longer working?
- If so, any idea why?
- Or, am I looking in the wrong place when trying to find [English Wikipedia's ~540 portal pages](https://en.wikipedia.org/wiki/Wikipedia:Contents/Portals) within https://library.kiwix.org/viewer#wikipedia_en_all_maxi_2022-05/ ?

Schools are _always_ urgently ask for _far more colorful pages_ so as to animate Wikipedia-centric learning &mdash; among younger people especially &mdash; who commonly turn against Wikipedia (possibly for life?)  When elders too often present Wikipedia as text-heavy + ponderous 🐢 

So the question is: Can **colorful + youth-friendly** portal pages like the following (more graphical i.e. with much less text, very intentionally more inviting!) be made available + easily findable offline &mdash; ideally in many of the 87 Wikipedia languages[*] that offer portals?
- https://en.wikipedia.org/wiki/Portal:Ancient_Egypt
- https://en.wikipedia.org/wiki/Portal:Biology
- https://en.wikipedia.org/wiki/Portal:Caribbean
- https://en.wikipedia.org/wiki/Portal:Comics
- https://en.wikipedia.org/wiki/Portal:COVID-19

[*] 87 languages appear to have Wikipedia portals, as indicated in the top-right of https://en.wikipedia.org/wiki/Wikipedia:Contents/Portals

Brief code context: https://github.com/openzim/mwoffliner/search?q=addnamespaces

**Comment by kelson42** [comment]
@pavel-karatsiuba please verify this ticket is valid, I’m really surprised it does not work?

**Comment by holta** [comment]
_Thank you @pavel-karatsiuba:_

1) Discoverability (how to find these 540 portal pages) is the key UX question if have suggestion(s) for teachers?  (After we hopefully find them!)

2) Side Question: Since `--addNamespaces` does not yet work with `--articleList`, is it possible to include all portal pages by listing them manually (e.g. listing all 540 portal pages) within `--articleList` ?

CONTEXT: Students need these **colorful/introductory pages** in ZIM files like the 1 Million article Wikipedia here: #1756

**Comment by kelson42** [comment]
@pavel-karatsiuba Please die at start if --articleList and --addNamespace are specified together

**Comment by kelson42** [comment]
Given ZIM file has indeed not the Portal pages but current version of MWoffliner seems to work fine when tested on a smaller wiki and with another namespace. We should clarify here what goes wrong.

**Comment by kelson42** [comment]
I would propose to wait https://farm.openzim.org/pipeline/d51dec8e90efcd0ad3f9be36 is over before continuing the investigation.

**Comment by holta** [comment]
Progress 🙏 

Then, very compact/quick/revealing test cases will hopefully be possible after that 😄

**Comment by Inbefortus** [comment]
From the [most recent](https://farm.openzim.org/pipeline/d51dec8e90efcd0ad3f9be36) English Wikipedia ZIM:

![Screenshot_20230220-083205_Samsung Internet Beta](https://user-images.githubusercontent.com/71934042/220042491-512cd26e-c539-4463-b1be-94123450f03a.jpg)
![Screenshot_20230220-083247_Samsung Internet Beta](https://user-images.githubusercontent.com/71934042/220042510-56f01abd-c221-4f6a-b52b-fbe3bf817f08.jpg)
![Screenshot_20230220-083357_Samsung Internet Beta](https://user-images.githubusercontent.com/71934042/220042517-004c9a54-aedd-435a-93ad-4ed1ae17fe75.jpg)

**Comment by kelson42** [comment]
@Inbefortus So basically there is not problem (anymore). Thx you for the check. I will merge the new automated test and close the ticket.

**Comment by holta** [comment]
@Inbefortus great news: Would you happen to know why Portals are now restored?

> 1. Discoverability (how to find these 540 portal pages) is the key UX question if you have suggestion(s) for teachers?  (After we hopefully find them!)

A very partial answer to the above question is below &mdash; unfortunately 540,497 pages is a flood rather than a clean UX &mdash; but still this is a start:

https://library.kiwix.org/viewer#search?books.name=wikipedia_en_all_maxi_2023-02&pattern=Portal%3A

![image](https://user-images.githubusercontent.com/2458907/220375127-f35f5c3a-75e8-4768-a8c4-aa84848ababe.png)

**Comment by Inbefortus** [comment]
> great news: Would you happen to know why Portals are now restored?

@holta I'm not even sure if portals ever existed in the first place. I don't recall them being in the 2021-03 ZIM. They must have been added around the end of 2022 or something like that.

**Comment by kelson42** [comment]
> > great news: Would you happen to know why Portals are now restored?
> 
> 
> 
> @holta I'm not even sure if portals ever existed in the first place. I don't recall them being in the 2021-03 ZIM. They must have been added around the end of 2022 or something like that.

This is actually the only logical explanation, but I don't remember and really woukd really wonder about that. As long as we can not track precisely changes on Zimfarm, we will face this kind of problem. See https://github.com/openzim/zimfarm/issues/498
