### ISSUE TITLE
Mwoffliner should mirror ResourceLoader dependences too

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#18]
The resourceLoader is the Mediawiki sub-system which allow to load, per article, javascript/css dependences. The documentation is here: https://www.mediawiki.org/wiki/ResourceLoader

MWoffliner should per article:
- Retrieve the list of modules
- Download them (if not already done)
- Offline version of the article should reload them correctly (in the ZIM)

We probably need to download each resourceLoader module separatly and store them separatly in the ZIM file. Then each article should know which one are needed and reload them.

A first attempt to provide a solution to this problem has been done here, it needs review:
https://phabricator.wikimedia.org/T114788

**Comment by kelson42** [comment]
@Skylsmoi @lebouquetin I finally have merged the code after the last modifications. Unfortunately, it seems something does not apply correctly. Just an example with the article "Lyon" https://fr.wikipedia.org/wiki/Lyon, if you have a look at the bottom of the infobox on the right, you see the map, with the links allowing to change the map dynamically. This is typically what I think should also work now, but it does not (I see only the 3 pictures on, just after the other - like before the patch).

**Comment by lebouquetin** [comment]
@kelson42, @Skylsmoi has investigated. Actually, the api.php endpoint does not return all modules required by the page. We need to load/parse the head of the page which includes a hard-written call to _mw.loader.load()_. It sounds like api.php content is not exhaustive and so we need to use both.

**Comment by kelson42** [comment]
@Skylsmoi @lebouquetin Thx for having taking a look quickly to that. If we try to focus on the "Lyon example" what is exactly missing? Which module name?

Maybe there is an other explanation: Mediawiki has also std css/js content which apply to all pages (and which are I suspect not managed through the resource loader) like:
* https://fr.wikipedia.org/wiki/MediaWiki:Common.js
* https://fr.wikipedia.org/wiki/MediaWiki:Common.css

And also the "vector" skin:
* https://fr.wikipedia.org/wiki/MediaWiki:Vector.css
* https://fr.wikipedia.org/wiki/MediaWiki:Vector.js

There is also the custom offline css:
* https://fr.wikipedia.org/wiki/MediaWiki:Offline.js

Might that be that these things are not anymore managed correctly?

**Comment by kelson42** [comment]
After many efforts it seems to me that what could reasonably be done has been done. mwoffliner can download efficiently dependencies on an article base. In addition it takes in account correctly the old/std js and css articles (commons.css, common.js, ...). That said the solution still suffers from weaknesses due to dynamic loading within the modules (not supported yet in mwoffliner) and many other small problems which impact in a way or another the offline UX.
