### ISSUE TITLE
Wikivoyage disambiguation pages have no content in ZIM

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#180]
This may be the same underlying issue as in #179, i.e., that Parsoid does not have access to data generated programmatically, but it seems that all disambiguation pages in the December 2017 English-language Wikivoyage ZIM look like the screenshot below. Compare that to 
https://en.wikivoyage.org/wiki/Cambridge 
where all the different places with related names are listed.

Is this something that needs to be generated by the client? It appears to be a Wikivoyage-specific issue, since disambiguation pages in Wikipedia ZIMs seem to function correctly (see for example "Cambridge (disambiguation)" in the latest English-language Wikipedia ZIM).

![image](https://user-images.githubusercontent.com/4304337/34466718-02aef384-eed6-11e7-906a-2dcd0b867f37.png)

**Comment by subbuss** [comment]
Shouldn't be because https://en.wikivoyage.org/api/rest_v1/page/html/Cambridge shows that Parsoid HTML is filled out.

**Comment by ISNIT0** [comment]
I'm not able to re-produce this in the latest code-base. Is this still happening @Jaifroid?

**Comment by Jaifroid** [comment]
@ISNIT0 : I'm still getting it with the September 2018 novid ZIM of Wikivoyage. If you recently made a change, I guess it will take some time to work through to ZIM releases, no? It can be tested with Cambridge or New York. Probably won't know if mwoffliner has picked this up till an October or November release? Below is from September release.
![image](https://user-images.githubusercontent.com/4304337/46734305-b9d38380-cc8a-11e8-915e-eb6f0f1ae1bc.png)

**Comment by ISNIT0** [comment]
I think it's related to our recent update of Parsoid, we'll verify soon :)

**Comment by ISNIT0** [comment]
I am seeing this, it seems to only be happening with `--mobileLayout`
