### ISSUE TITLE
It should not be possible to create a ZIM with and empty Metadata "Description"

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1805]
For the moment it seems to be possible to create a ZIM with empty "Description" ZIM metadata.

Please check as well other mandatory metadata https://wiki.openzim.org/wiki/Metadata

**Comment by pavel-karatsiuba** [comment]
The metadata `Illustration_48x48@1` is not set.
I will make the function to check other mandatory fields.
To add `Illustration_48x48@1` into metadata I need a separate ticket or at least a description.

**Comment by kelson42** [comment]
> The metadata `Illustration_48x48@1` is not set.
> 
> I will make the function to check other mandatory fields.
> 
> To add `Illustration_48x48@1` into metadata I need a separate ticket or at least a description.

Yes, please create one. Shoukd be made in place of the favicon.... but same content.
