### ISSUE TITLE
Hieroglyphs do not show correctly

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#181]
They actually do not show at all.

**Comment by kelson42** [comment]
@Popolechien Which ZIM file? Which page? Which version of Kiwix?

**Comment by Popolechien** [comment]
Nevermind, that was a Kiwix-js thing but another discussion we had makes it sound like there's no actual issue (well except for the fact that K-JS is not happy having too many images). Closing ticket.
