### ISSUE TITLE
Duplicate in cmd line arguments are not checked (was: --verbose does not accept empty value)

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1818]
```
$ mw --mwUrl="Https://de.wikipedia.org/" --verbose

....

**********

verbose should be empty or one of [info, log, warn, error, quiet].

**********

```

**Comment by pavel-karatsiuba** [comment]
@kelson42 Excidently found out that you will get such an error if you use `--verbose` parameter more than one time.

Example to reproduce the error:
`$ mw --verbose=info --adminEmail="contact@kiwix.org" --mwUrl="Https://de.wikipedia.org/" --verbose`

**Comment by kelson42** [comment]
No way to limit tp one with yargs?

**Comment by kelson42** [comment]
> @kelson42 Excidently found out that you will get such an error if you use `--verbose` parameter more than one time.
> 
> Example to reproduce the error: `$ mw --verbose=info --adminEmail="contact@kiwix.org" --mwUrl="Https://de.wikipedia.org/" --verbose`

OK, was definitly to stupid to get that error on my side. Sorry for the misleading ticket/PR.
