### ISSUE TITLE
Does wikipedia_en_all_maxi_2023-02 need a new version of kiwix-serve?

### ISSUE THREAD

**Issue by zkosk** [openzim/mwoffliner#1822]
I'v downloaded wikipedia_en_all_maxi_2023-02 but it doesn't contains entries such as GeForce_40_series. The size is 94.6GiB (101,671,784,005 bytes=101.67 "GB"). The [online version](https://library.kiwix.org/viewer#wikipedia_en_all_maxi_2023-02/A/GeForce_40_series) have this entry. Why?

**Comment by kelson42** [comment]
https://www.majordifferences.com/2018/03/differences-between-megabyte-and.html

**Comment by zkosk** [comment]
@kelson42 I'v download the zim and serve it through kiwix-serve.exe as before. But it doesn't have this entry as the former edition (2022.5). Searching for _GeForce_40_series_ or _RTX 4090_ also have no result. I'v shutdown kiwix-serve and restart it. How to know the version of the zim by the content served by kiwix-serve?

**Comment by zkosk** [comment]
I served the wrong zim through kiwix-serve.
