### ISSUE TITLE
Recent Wiktionary ZIM files don't show a search bar

### ISSUE THREAD

**Issue by ghjm** [openzim/mwoffliner#1831]
I recently updated my offline copy of Wiktionary and found that it no longer offers a home button and search bar at the top of the page. This happens both in kiwix-serve and in Kiwix Desktop. I notice that the same problem exists at the hosted copy at [library.kiwix.org](https://library.kiwix.org/content/wiktionary_en_all_maxi_2023-02/A/Wiktionary:Offline). However, an older copy at [iiab.me](https://iiab.me/kiwix/wiktionary_en_all_maxi_2022-09/A/Wiktionary:Offline) doesn't have the issue. Other ZIM files don't have the issue, like the [Simple English Wiktionary at library.kiwix.org](https://library.kiwix.org/viewer#wiktionary_en_simple_all_maxi_2023-04/A/Wiktionary:Main_Page).

**Comment by Popolechien** [comment]
Ok I looked it up and it's actually capturing a blank page with only the Wiktionary banner. More of a feature than a bug, then - not sure which reader (android, iOS, desktop) you are using OP but I would think its search bar is still available.

Anyways. I'll restart the scraper to the regular front page - we'll figure out a better landing page when we'll start work on [openzim/zim-requests/issues/578](https://github.com/openzim/zim-requests/issues/578)
