### ISSUE TITLE
Move mwoffliner to node-libzim

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#184]
This would allow to write on-the-fly ZIM files, directly in node. Without using zimwriterfs. This should speed-up things and save I/O.

**Comment by ISNIT0** [comment]
An example ZIM file made with the progress so far:
https://framadrop.org/r/eRSd6f7foj#25n0DjqyZscAZw4FS259vNyXPkn6yMgcrQtCeOb2W/o=
