### ISSUE TITLE
Markup in WikiMed (English)

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#185]
The markup shown in the top screenshot below (taken from the official x86 version of Kiwix, but the same problem exists in Kiwix JS [Windows]), appears at the top of the article on "Vitamin D" in `wikipedia_en_medicine_novid_2018-01`.

Note that to see the markup clearly you have to "select" with the cursor (drag mouse over the area) because the style of these elements is set to `"background-color:transparent"`. However, in the dark mode of Kiwix JS Windows, the content is shown clearly (bottom screenshot). You can subtly see it even without selecting it, in light-mode clients.

Not sure where the markup is coming from, but it appears as a series of 15 or so `<div>` elements all with the id `"annotation_0x0"` (therefore it is invalid markup, since no two elements should have the same id). Each `<div>` looks like this:
```
<div id="annotation_0x0" style="position:absolute; left:0px; top:0px; line-height:110% ">
<span style="background-color:transparent; ">
[[&lt;div style="display:block; width:55.5625px; height:22.2083333333355px;
overflow:hidden; position:relative; left:243.10253583241456px; top:458.813537869581px;
background:transparent; border:4px black solid"&gt;&lt;/div&gt;]]
</span>
</div>
```

![image](https://user-images.githubusercontent.com/4304337/35472980-fa5f3ae0-0370-11e8-844c-4556bc36a639.png)

![image](https://user-images.githubusercontent.com/4304337/35473021-86cba7a2-0371-11e8-859a-e093ce689cb3.png)

**Comment by kelson42** [comment]
To me it looks like a Parsoid bug, @cscott @subbuss We can see the same here: https://en.wikipedia.org/api/rest_v1/#!/Page_content/get_page_html_title. What is this big `div` node?

**Comment by subbuss** [comment]
I don't see it @ https://en.wikipedia.org/api/rest_v1/page/html/Vitamin_D

**Comment by kelson42** [comment]
@subbus Just search for `annotation_0x0` in that page, this is IMO the problematic part!

**Comment by subbuss** [comment]
Filed https://phabricator.wikimedia.org/T204967

**Comment by kelson42** [comment]
@subbuss Thx!

**Comment by kelson42** [comment]
There is no visible impact with this article:
* generated with 1.9.4
* with kiwix-desktop 2.0
* with new kiwix-JS for Windows

The problem in Parsoid is probably still there but in term of impact for the us, the mitigation introduced to hid that part of code work.
