### ISSUE TITLE
Provide a way to specify/modify the zim file name

### ISSUE THREAD

**Issue by audiodude** [openzim/mwoffliner#1855]
This is a request as part of the [WP1 project](https://github.com/openzim/wp1).

When mwoffliner is used as part of the [Zimfarm](https://github.com/openzim/zimfarm), the file name is used directly as the name of the object in S3 storage for the ZIM file. It appears that this file name is taken directly from the file name that is used in the URL that specifies the article list.

For example:

Article list: `https://org-kiwix-dev-wp1.s3.us-west-1.wasabisys.com/selections/wp1.selection.models.simple/1b767bca-8fa6-48e3-9893-eb7b6d0ada91/AlphaList8.tsv`
Zim file name: `wikipedia_en_alphalist8_2023-06.zim`

However, this causes problems. Specifically, the article list (Selection in WP1 speak) file name is derived from the name of the Selection. When WP1 automatically requests a new ZIM file when the selection data has been updated, it is unlikely that the Selection name has also changed. This means that the new URL still ends in `AlphaList8.tsv`, even though the URL is different (different id in the path).

The problem then, is that when Zimfarm or mwoffliner (not sure which) tries to upload the ZIM to S3, the object already exists and it cannot overwrite the file. This causes the ZIM creation task to fail.

Solution would be to allow a command line parameter or other method for specifying a custom ZIM file name (or partial filename).

**Comment by kelson42** [comment]
@audiodude What about:
```
  --filenamePrefix            For the part of the ZIM filename which is before t
                              he format & date parts.
```

**Comment by audiodude** [comment]
That sounds like what I need! I will re-file against Zimfarm to potentially get the parameter included.
