### ISSUE TITLE
Library does not update

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#186]
(Maybe this should be opened elsewhere but this seems the likeliest place).

There is a gentleman who wrote to complain that the hebrew zim files haven't been updated since last year (I checked and the last update is from 10 January 2018) - and another one saying that the English ones were 2 years old. They're both on desktop, so I don't know how the library there is refreshed, but apparently something is amiss.

**Comment by kelson42** [comment]
@Popolechien This is not really the right place, but that is not a big problem :) My first reaction was "not again a bug report about one of the weaknesses we already know about"... but I verified in details and indeed somethings was going wrong! I have fixed a bug I have left... and it seems to be better know, WPEN is of 2018-08 and WPHE of 2018-01 :) So thx for the bug report!
