### ISSUE TITLE
Due to the recent depreciation of the mobile-sections API MWOffliner no longer outputs Mini variants of Wikipedia

### ISSUE THREAD

**Issue by Inbefortus** [openzim/mwoffliner#1868]
Instead, an unintended [Nopic](https://farm.openzim.org/recipes/wikipedia_en_all_nopic) variation is [created.](https://farm.openzim.org/pipeline/5c088b3f-e83b-41e8-887b-1cfd946205c9)

**Comment by VadimKovalenkoSNF** [comment]
@kelson42 , @Inbefortus 
How to reproduce this issue locally?
For instance, I scrapped `bm` wiki using these commands (from mwoffliner folder):
`npm start -- --mwUrl=https://bm.wikipedia.org --adminEmail=mail@mail.com
` and got **wikipedia_bm_all_2023-08.zim** file that has a size of **58,7 Mb**

and minified version:
`npm start -- --mwUrl=https://bm.wikipedia.org --adminEmail=mail@mail.com --format=nodet,nopic:mini`
and got **wikipedia_bm_all_mini_2023-08.zim** which is **1.8 Mb**

I've tried with single articles with media content from En wiki, but I also got normal and compressed output.

**Comment by kelson42** [comment]
@VadimKovalenkoSNF build the e2e test running through all end-points... I wozld alsi force a random user-agent.

**Comment by kelson42** [comment]
@VadimKovalenkoSNF Remember, Wikimedia team has added an exception to allow access to mobile-section API to the MWOffliner based on its agent, but this ticket has been filled before this has been made (this is why I guess you can not reproduce it). Just secure that the `--format=nodet` returns only the introduction section *with all API backend* (should be automated tested).

**Comment by rgaudin** [comment]
Reopening as wikipedia_en_all_mini_2023-12 (only one after 2023-09 created on September 23rd) is still as large.

**Comment by kelson42** [comment]
@rgaudin Software is fixed, just not released.

**Comment by rgaudin** [comment]
My bad, the recipe is indeed using 1.13.0

**Comment by kelson42** [comment]
@rgaudin That said it should still work... as this is old version and mobile-section should still work for mwoffliner... something is wrong somewhere.
