### ISSUE TITLE
Titles of articles are not scraped in WikiMedia ZIMs since July 2023

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#1872]
The latest scrape of English Wikivoyage (29th July) does not appear to include the title of each article in the scrape. Compare the two images below of an article from last month's English Wikivoyage and this month's. Notice how the larger-font title "Santa Cruz de Mompox" is missing from the latest [library.kiwix.org](https://library.kiwix.org/viewer#wikivoyage_en_all_maxi_2023-07/A/Santa_Cruz_de_Mompox) version. It's the same for all other articles as far as I can tell.

![image](https://github.com/openzim/mwoffliner/assets/4304337/11479954-78d5-4be6-a8ae-9be2433c3e2e)

**Comment by Jaifroid** [comment]
Just to add some interesting data points: the Greek and French Wikivoyage scrapes that were done **after** this English-language scrape both have article titles present, but `wikivoyage_en_europe_maxi_2023-08.zim` done at the same time as the Greek and French ZIMs does **not** have article titles.

**Comment by kelson42** [comment]
@Jaifroid yes, have seen this as well, weird.

**Comment by Jaifroid** [comment]
Issue seems to be getting worse. The same symptoms are now occurring in `wikipedia_es_climate_change_maxi_2023-08.zim`. See screenshot:

![image](https://github.com/openzim/mwoffliner/assets/4304337/13114852-e5ab-49fa-802d-d0592a730a93)
