### ISSUE TITLE
Update page footer

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1879]
The WMF used to refer the CC licensing terms to a locally hosted page 

https://en.m.wikipedia.org/wiki/Wikipedia:Text_of_the_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License

but has now switched to the CC website: 

https://creativecommons.org/licenses/by-sa/4.0

We should update our link as well in the zim file footer.

**Comment by kelson42** [comment]
@Popolechien It is and always been right, see https://library.kiwix.org/viewer#wikipedia_en_100_2023-08/A/Antarctica footer for example
