### ISSUE TITLE
Failed to install dependency "node-libzim@2.4.4" when installing with npm i -g mwoffliner

### ISSUE THREAD

**Issue by yizhimengxin2233** [openzim/mwoffliner#1880]
![Screenshot_20230812_174533](https://github.com/openzim/mwoffliner/assets/58097884/b9979b1f-0e7e-4ff4-a001-7005343f2f84)

I'm having trouble trying to install mwoffliner. Whether I use Git source code or npm source installation, it will fail when compiling and installing node-libzim. I even tried installing in termux, lxc(based on my android phone), docker(arm), but always reported similar errors. Even if I try to change the dependent node-libzim and node-gyp to the latest version, they cannot be installed and started smoothly.How can I solve it? (Screenshots and logs are from archlinux-x86 yay)
(translated by google)
[2023-08-12T09_25_41_483Z-debug-0.log](https://github.com/openzim/mwoffliner/files/12327099/2023-08-12T09_25_41_483Z-debug-0.log)

**Comment by kelson42** [comment]
I think the problem might be nodejs20. Shoukd work with nodejs18.

**Comment by yizhimengxin2233** [comment]
> I think the problem might be nodejs20. Shoukd work with nodejs18.

It crashed again.
![Screenshot_20231004_160122](https://github.com/openzim/mwoffliner/assets/58097884/785d889b-7fcc-4a5f-b878-1b20257d9666)
[2023-10-04T07_54_53_827Z-debug-0.log](https://github.com/openzim/mwoffliner/files/12800887/2023-10-04T07_54_53_827Z-debug-0.log)

**Comment by kelson42** [comment]
@audiodude Any clue on this pretty old bug report?

**Comment by kelson42** [comment]
@yizhimengxin2233 This is an X86_64 CPU running a Linux? Do you have the libzim installed otherwise on the system?

**Comment by audiodude** [comment]
Yes, this is the same issue as #2029. The old version of node-gyp installed with node-libzim 2.4.4 can't build on Python > 3.10
