### ISSUE TITLE
Modularization of article treatment

### ISSUE THREAD

**Issue by VadimKovalenkoSNF** [openzim/mwoffliner#1881]
While saving articles there are multiple article transformations and treatments that apply to multimedia and text content. Considering there will be different kinds of API calls for regular articles (WikimediaMobile for Wikimedia Projects) and the main page (WikimediaDesktop or VisualEditor, see [here)](https://github.com/openzim/mwoffliner/wiki/API-end%E2%80%90points) there should be created different treatments.

These treatments should be modularized depending on the type of functionality and purpose.
https://github.com/openzim/mwoffliner/pull/1839 partly solves this by dividing treatments by articles (usually text content) and multimedia (images, video etc).

**Comment by kelson42** [comment]
The most important is to move from a dedicated monolit treatment to treatments integreated in the modularises renderer. So, just extend the `render()` method.
