### ISSUE TITLE
One or two e2e tests should be modularized

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1887]
Now that the overall architecture is healthier we should modularized the e2e tests.

The problem is that for the moment each e2e tests deal only with one API end-point. But we support 2-3 at leasts. So to be serious each e2e tests should run the very same tests on all supported end-points to sercure the treatments applys properly for each case.

We should do that for one or two tests to secure it works fine, and afterward, piece by piece, we will move all e2e tests to tests all supported API end-points.

**Comment by VadimKovalenkoSNF** [comment]
1. Current e2e tests are lying in a folder [test/e2e/articleLists.test.ts](https://github.com/openzim/mwoffliner/tree/main/test/e2e)
2. At the moment, mwoffliner supports **WikimediaDesktop** and **VisualEditor** API capabilities. **WikimediaMobile** API to be done.
3. There are a bunch of unit / international tests in [test/unit](https://github.com/openzim/mwoffliner/tree/main/test/unit). This folder contains tests for renderers, URL builders, article and media treatments, AWS S3, Redis store, etc. Overall test structure in this folder is a bit unstructured IMO.

I'm thinking about this strategy to start:
1. Take **test/e2e/bm.e2e.test.ts** 
2. Force bm wiki test to use both renderers ( **WikimediaDesktop** and **VisualEditor**) sequentially.  
3. Possibly, replace/duplicate some test cases from article and media treatments in **test/e2e/bm.e2e.test.ts**.

@kelson42 what do you think?

**Comment by kelson42** [comment]
@VadimKovalenkoSNF Your plan LGTM. T me its important that we have a clear, elegant and reusable "code template" to run an (e2e) test easily against all supported end-points without much hasdle and duplication of code.
