### ISSUE TITLE
Link color are not properly displayed in E-Inks display.

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#189]
Hi and thanks very much for your great work. I successfully ran Android 2.3.4 (rooted Ebook) with the 1.90/1.91 Versions of the Android app and the recent Zims of nopic en/de-WP. Even the german version with pics worked, system just getting a bit sluggish. Bigger filesystemsizes than 32GB are not supported in Gingerbread, so this is as much Kiwix-WP as I can get. I help myself out by swapping two 32GB-SDs according to my needs and wishes.

I have one question, though. My joy is omly slightly spoiled by the fact that the E-ink b/w-display will not show the links in the articles. They appear like the rest of the text, you have to guess. Would there be some trick or hack to have the links underlined, bold, light gray, whatever?

From https://sourceforge.net/p/kiwix/discussion/604121/thread/f14f2c0f/?limit=25#4d1e

**Comment by kelson42** [comment]
We need to check here if the problem appears also with the online version.

**Comment by kelson42** [comment]
@rgaudin @ISNIT0 @Popolechien Does one of you has a tablet to test with a recent ZIM on library.kiwix.org?

**Comment by rgaudin** [comment]
Nope, not until after the hackhathon.

**Comment by kelson42** [comment]
We need a clear reproduction case here.

**Comment by kelson42** [comment]
closing because:
* no feedback
* no other complains
* anyway something depending of upstream
