### ISSUE TITLE
"Cannot read properties of undefined (reading 'general')"

### ISSUE THREAD

**Issue by catandA** [openzim/mwoffliner#1890]
But when I tried to take https://minecraft.fandom.com/ offline, mwoffliner reported an error as follows:

(node:88392) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
[error] [2023-08-24T09:09:24.579Z] FATAL - Failed to get MediaWiki Metadata
[error] [2023-08-24T09:09:24.580Z] Failed to run mwoffliner after [6s]: {
        "stack": "TypeError: Cannot read properties of undefined (reading 'general')\n    at MediaWiki.getSiteInfo (file:///root/.nvm/versions/node/v18.17.1/lib/node_modules/mwoffliner/lib/MediaWiki.js:209:36)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Promise.all (index 1)\n    at async MediaWiki.getMwMetaData (file:///root/.nvm/versions/node/v18.17.1/lib/node_modules/mwoffliner/lib/MediaWiki.js:258:81)\n    at async Module.execute (file:///root/.nvm/versions/node/v18.17.1/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:109:22)",
        "message": "Cannot read properties of undefined (reading 'general')"
}
[error] [2023-08-24T09:09:24.580Z]

**********

Cannot read properties of undefined (reading 'general')

**********

I'm using CentOS9 stream and nodejs v18.17.1
Do you need additional configuration for this wiki or did I make a mistake? Thanks

**Comment by kelson42** [comment]
What is the full command line you use?

**Comment by catandA** [comment]
Only the two most basic command-line parameters
mwoffliner --mwUrl=https://minecraft.fandom.com/ --adminEmail=xxx@qq.com

**Comment by VadimKovalenkoSNF** [comment]
It looks like Fandom wiki stopped using `/w/` prefix in the Action API URL. This is an example of siteinfo request that mwoffliner tries to send and parse:
https://minecraft.fandom.com/w/api.php?action=query&meta=siteinfo&format=json&siprop=general|namespaces|statistics|variables|category|wikidesc

And this is how this request really should look like:
https://minecraft.fandom.com/api.php?action=query&meta=siteinfo&format=json&siprop=general|namespaces|statistics|variables|category|wikidesc

**Comment by kelson42** [comment]
We have an official recipe, https://farm.openzim.org/recipes/minecraft_fandom_en_all, look at the parameter. That said the scrape still faul there, but this is an other problem.
