### ISSUE TITLE
Latest wikipedia_en_all_mini is 57G instead of 13G

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1893]
By the look of it I'd say that https://download.kiwix.org/zim/wikipedia/wikipedia_en_all_mini_2023-07.zim now is a regular `nopic` version: https://library.kiwix.org/viewer#wikipedia_en_all_mini_2023-07

@kelson42 could this be a regression?
@RavanJAltaie Did you change anything to that recipe over the past month?

**Comment by kelson42** [comment]
@VadimKovalenkoSNF Original recipe is https://farm.openzim.org/recipes/wikipedia_en_all_mini. IMO, the format option `nodet` was probably only working fine with `mobile-section` and not with the other end-points. This is the problem.

**Comment by Jaifroid** [comment]
Seems to be a duplicate of #1868.

**Comment by kelson42** [comment]
Definitly, closing as duplicate.
