### ISSUE TITLE
A number of "mini" ZIMs are hybrids of pic and no_pic

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#1894]
[NB, this issue is nothing to do with the current problems producing mini ZIMs, it refers to longstanding behaviour.]

"Mini" ZIMs are advertised as having only the lede and not containing images. However, several of them (e.g. the climate_change ones, the top 100 ones) in fact contain an image for each article on the pictographic landing page (though not in the articles themselves). It doesn't make much sense to have the images for each article all displayed on a landing page, but not then to have the same image in the corresponding article (after all, it has already been scraped and is in the ZIM). It would be much more useful if the images were in the corresponding articles (in fact, having them all on a single landing page is pretty troublesome and slow to render for any client that has slow disk I/O or that has to transcode WebP images with the polyfill).

In my opinion, a fix to this would in fact involve producing "mini_nopic" and "mini" (with pic) versions. The pictures would of course only be those that are in the lede of each article. The "nopic" versions would be truly nopic, with a textual landing page.

If that is technically too difficult, or too confusing for end users, then I would urge that "mini" ZIMs be defined as having no images at all, and so the landing page should simply be the textual ZIM index for ZIMs <= 100 articles, and a custom page for ZIMs with more articles than that.

**Comment by kelson42** [comment]
> It doesn't make much sense to have the images for each article all displayed on a landing page, but not then to have the same image in the corresponding article (after all, it has already been scraped and is in the ZIM).

This is not like it is, because not all articles are on the homepage, only 100 (I believe) of them.

**Comment by kelson42** [comment]
> If that is technically too difficult, or too confusing for end users, then I would urge that "mini" ZIMs be defined as having no images at all, and so the landing page should simply be the textual ZIM index for ZIMs <= 100 articles, and a custom page for ZIMs with more articles than that.

To me, for the reasons you have given, this is the only thing we could indeed change. But, I have really no opinion if we should do it. I understand the argument of coherency, but sounds very much of a detail to me.

@RavanJAltaie @Popolechien Any feefback?

**Comment by Jaifroid** [comment]
I think what I'm really arguing for is indeed that `mini` ZIMs should be consistent and have no images at all, but instead a textual index of up to 100 articles (unless there is a custom organized landing page). It feels misleading to present users with a highly visual start page when the corresponding articles have no images.

I understand this is unlikely to be high priority, but there is some inconsistency across our range of `mini` ZIMs that even I as an experienced user find confusing. Some have this image-heavy landing page, others have a custom landing page of organized links, and yet others have a textual index...

**Comment by Popolechien** [comment]
I understand the reasoning (and the inconsistency) but am opposed to having _yet another_ version made available to users when the difference between mini, nopic and max already has to be explained over and over. 

I have yet to hear user feedback regarding the supposed confusion generated by having a _mini_ with images on its landing page but not the entries, and the dev work needed to fix that (e.g. replacing the image board with a simple list of links) is not worth it IMHO as it would really depreciate the UI/UX. We only get one chance to make a first impression, and the landing page is it.

**Comment by kelson42** [comment]
Pretty agree with @Popolechien. Keeping ticket open for a few additional weeks for maturation, but might end-up with a WONTFIX.

**Comment by kelson42** [comment]
Closing, current situation is a compromise, but this ticket IMHO is not going to make it better.
