### ISSUE TITLE
Failed Recipes waiting for the mwoffliner update

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/mwoffliner#1896]
In this issue, I'll place a list of recipes made with mwoffliner scraper and waiting for the new update to be ready and restart them over to check their success. I'll keep editing this issue with the related recipes:
1- https://farm.openzim.org/recipes/strategywiki
2- https://farm.openzim.org/recipes/zelda_wiki_en
3- https://farm.openzim.org/recipes/Xenharmonic_wiki_en
4- https://farm.openzim.org/recipes/necyklopedie.org_cs_all
5- https://farm.openzim.org/recipes/wiki.kernel.org_en_all
6- https://farm.openzim.org/recipes/choral_wiki_en

**Comment by kelson42** [comment]
@RavanJAltaie what is the problem with mwoffliner?

**Comment by RavanJAltaie** [comment]
@kelson42 all the wiki-like recipes (Other than Wikimedia projects) are failing consistently.
@Popolechien informed me that you & @VadimKovalenkoSNF are working on the new version of the scraper which will solve all these recipes issues.
That's why I agreed with Stephane to collect the failed recipes in an issue here to check them after the update is implemented.

**Comment by kelson42** [comment]
@RavanJAltaie without a clear hints to a bug, i will close this ticket. AFAIK these recipes are just wrongly configured.
