### ISSUE TITLE
[REGRESSION] 'Error: Input file is missing' when use --optimisationCacheUrl param

### ISSUE THREAD

**Issue by VadimKovalenkoSNF** [openzim/mwoffliner#1904]
When use `--optimisationCacheUrl`, get the error: `stack": "Error: Input file is missing`

## Steps to reproduce
Run this command with S3 credentials:
`npm start -- --adminEmail=mail@mail.org --osTmpDir=/dev/shm --optimisationCacheUrl=http://s3.us-west-1.wasabisys.com/?bucketName=org-kiwix-dev-mwoffliner&keyId=.........&secretAccessKey=....... --mwUrl=https://fr.wikipedia.org --format=nodet --articleList=Paris,Berlin --verbose`

## Expected result
Scrape articles to the destination folder

## Actual result
```
[info] [2023-09-11T18:06:55.457Z] Downloading [https://fr.wikipedia.org/static/images/project-logos/frwiki.png]
[error] [2023-09-11T18:06:55.966Z] Failed to run mwoffliner after [2s]: {
	"stack": "Error: Input file is missing: ",
	"message": "Input file is missing: "
}
[error] [2023-09-11T18:06:55.966Z] 

**********

Input file is missing: 

**********
```

After additional research, I've found that this error occured after migration to aws-sdk v3 in https://github.com/openzim/mwoffliner/pull/1865

**Comment by kelson42** [comment]
@VadimKovalenkoSNF TOP priority to fix, we/I always use mwoffliner with S3, in both dev and prod. Wonder really about the root cause.

**Comment by VadimKovalenkoSNF** [comment]
Since mwoffliner expects a response body from S3 represented by a Buffer format, this solution seems to work - https://github.com/aws/aws-sdk-js-v3/issues/1877#issuecomment-1326311437
