### ISSUE TITLE
Open link in new tab. Kiwix extension in Firefox.

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1910]
Kiwix extension 3.10.1 (and older) in Firefox.
There was a issue like this before but I can't find it.
Then it was impossible to open the link in a new tab. But then the programmers corrected this error and it became possible to open a link in a new tab with a mouse click.
Now the situation is repeating itself.
Open the browser Firefox with the extension Kiwix and click on the link with the mouse wheel. Reading a Wikipedia article from ZIM file.
We see that a new tab does not open.
Maybe I broke something myself.
Maybe for Firefox there is some code for the terminal to find out what’s wrong?
Or do I need to look at my browser settings https://en.wikipedia.org/wiki/About_URI_scheme   ???

**Comment by kelson42** [comment]
@Ubuntu-2020 Why opening this ticket here? Seems to me it should be open in https://github.com/kiwix/kiwix-js!

**Comment by Jaifroid** [comment]
@Ubuntu-2020 I didn't see this issue before because you put it in the wrong place. It should be over at kiwix-js, which is where the browser extension code is developed. I'm going to see if I can transfer it and answer it there.

**Comment by Jaifroid** [comment]
I can't transfer it, because it's in a different org account.

Opening in a new tab works fine for me using ctrl-click or right-click -> open link in new tab in Firefox. If you want to discuss more, or give more details, please open an issue at https://github.com/kiwix/kiwix-js/issues.
