### ISSUE TITLE
Make sure format option is working for WikimediaMobile renderer

### ISSUE THREAD

**Issue by VadimKovalenkoSNF** [openzim/mwoffliner#1916]
Format options (`nopic`, `nodet`, `novid`, `nopdf`) should be covered by tests and fixed if necessary for WikimediaMobile renderer. The work around this renderer is here: https://github.com/openzim/mwoffliner/pull/1903

**Comment by kelson42** [comment]
AFAIK, `nopic` and `nodet` work.

**Comment by kelson42** [comment]
@VadimKovalenkoSNF Any news here?

**Comment by VadimKovalenkoSNF** [comment]
There has been manual testing of `nopic` and `nodet` described here - https://github.com/openzim/mwoffliner/pull/1903#issuecomment-1741271174
Test of `novid` and `nopdf` in progress.

**Comment by VadimKovalenkoSNF** [comment]
@kelson42 , `.nopdf` option doesn't work for desktop and mobile renders. Others work as expected, I made a separate test suit for them in https://github.com/openzim/mwoffliner/pull/1903

**Comment by kelson42** [comment]
@VadimKovalenkoSNF Please open a ticket for `nopdf` and close this ticket.
