### ISSUE TITLE
MWoffliner should support latest mediawiki release 

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1917]
Kind of stating the obvious here but since a recent scrape of [minecraft.wiki](https://minecraft.wiki/w/Special:Version) failed (even though it is running a fairly recent ([1.39](https://minecraft.wiki/w/Special:Version)) version of mediawiki it would be good to ensure that mwoffliner is not too lagging in its support. For reference here is the recipe that ran: https://farm.openzim.org/recipes/minecraft_wiki_en_all

**Comment by kelson42** [comment]
this is a problem with the config to 99%. error is: no end point found, so either there is none or its wrongly configured. considering other recipes for fandom pass.... i tend to think: this is a config problem. Just pur logic.

**Comment by kelson42** [comment]
@Popolechien FYI MWoffliner CI runs again WP, which uses even cuuting edge unreleased versions of MW... so we are pretty sure we support recent versions of MW properly.
