### ISSUE TITLE
new zim

### ISSUE THREAD

**Issue by amirh123123** [openzim/mwoffliner#192]
hi please make zim of wikipedia nopic nodet and wikipedia full with videos and sounds and make partly of wikipedia example wikipedia sports giografi biografi history and more thanks

**Comment by kelson42** [comment]
@amirh123123 Yes, we will try and this is on our roadmap. I close the ticket as it gather diffierent requests and we are going to hardly close it. Please one request per ticket... and regarding our limited amount of resources, focus on your priorities.
