### ISSUE TITLE
Raw HTML and html entities appearing in directory entry title field

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#1924]
I'm not sure if this is fixed by #1872 or not, but I noticed in `wikipedia_en_movies_maxi_2023-09.zim` (which is missing article titles in the article HTML), that the directory entry title field has accidentally scraped HTML. See the dirEntry for `Blade Runner (film)` below.

![image](https://github.com/openzim/mwoffliner/assets/4304337/9e1d44c6-097e-4766-a7fd-4cec57dba39c)

Clearly, the spec says titles should not be URL-encoded, but in fact the directory entry title shouldn't have any HTML at all in it, AFAIK.

I've seen this also in a simple Ray Charles ZIM too.

**Comment by kelson42** [comment]
@VadimKovalenkoSNF This bug drives me crazy becaus it has been tacled for sure twice over the last year. But title in ZIM shozld not be saved with any HTML formatting.

**Comment by kelson42** [comment]
@Jaifroid Found it: https://github.com/openzim/mwoffliner/issues/1797 .... and actually there is nothing we can do IMO. This is a bug in Mediawiki.

**Comment by Jaifroid** [comment]
I'd forgotten about that issue!
