### ISSUE TITLE
Full article URL calculates two times in different parts of mwoffliner using different funtions

### ISSUE THREAD

**Issue by VadimKovalenkoSNF** [openzim/mwoffliner#1927]
While working on https://github.com/openzim/mwoffliner/issues/1601 I faced the problem that the current URL building functionality was not adapted to generate URL like `{base domain}/rest.php/v1/page/{title}/html` mainly because it expects `title` to be the last argument in `getArticleUrl()` function here https://github.com/openzim/mwoffliner/blob/main/src/util/saveArticles.ts#L245 . At this point, we totally rely on baseUrl which comes from Downloader.ts. On the other hand, there is in-progress-PR  of the set of lazy methods that check API avsilsbility (example of checking WikimediaDesktop API here - https://github.com/openzim/mwoffliner/blob/dbc3116cded996af1de25ca6c9c7aa0f3b52681a/src/MediaWiki.ts#L137)

These lazy methods use pretty much the same logic - they generate a full URL but with the main page for a specific wiki and verify whether this URL is working.

The problem here is the lack of abstraction:
 `getArticleUrl(articleId)` returns pretty the URL structure as `<UrlDirectorInstance>.buildArticleURL(articleId)` but they both serve the different purpose.

For `UrlDirectorInstance.buildArticleURL(articleId)` articleId will be the Main Page of the specific wiki, and for  `getArticleUrl(articleId)` articleId will be the article title received in `saveArticles()` loop.

And even if  `UrlDirectorInstance.buildArticleURL(articleId)` is smart enough to generate URL specific to the designated API,  `getArticleUrl(articleId)` is just a function that concats baseUrl and the title to the end and nothing more. That leads to a problem that I can't use any APIs if their titles params are not at the end such as `{base domain}/rest.php/v1/page/{title}/html`

I propose to use `<UrlDirectorInstance>.buildArticleURL(articleId)` in `saveArticles()` per specific renderer. Render name can be calculated by `renderer.constructor.name` - this way we know which specific `buildArticleURL()` to call. 

There should not be functions that do the same job in a different manner. `getArticleUrl(articleId)` is not scalable and should be refactored considering the issues I mentioned above.

**Comment by kelson42** [comment]
Here my feedback, my proposal:
* `getArticleUrl()` should not be part of `saveArticles.ts`(actually the whole `saveArticles.ts` should not exist. It should be part of `Downloader.ts`
* `Downloader.ts` should not track with private/protected varialble of the base URLs, but of the class allowing to build the URL. If I understand righ, UrlDirector... instances.
* Considering the two points above, with could have `download.getArticleUrl(articleId)` basically calling something like `this.baseUrlDirector.buildArticleURL(articleId)`.
* This method `getArticleUrl()` can be called millions of time, it has to stay CPU efficient.
* I'm concerned to still see a `baseUrl` private/protected variable in `Mediawiki` class as well and calling the director directly. Does not sound a good idea to track this in two different classes. Probably a symptom of something wrong somewhere.

**Comment by VadimKovalenkoSNF** [comment]
Another fundamental problem around saveArticles() flow - we get article url with article title first, and only then decide which render to choose. But article url already dictates render type. Another problem is about isMainPage  - we choose URL and renderer for main page and regular articles separately which looks wrong.
