### ISSUE TITLE
wikipedia

### ISSUE THREAD

**Issue by amirh123123** [openzim/mwoffliner#193]
hi please make zim for wikipedia to not template of articles

**Comment by kelson42** [comment]
@amirh123123 Sorry, but I do not get it. What is the point exactly with the "templates"? Which problem do you want to fix?

**Comment by amirh123123** [comment]
hi example i open nintendo article on wikipedia but botem of article i see templates after External links i see  Nintendo navboxes and Electronics industry in Japan and TOPIX 100 companies of Japan and Major video game companies my idea is make wikipedia not this template thanks

**Comment by kelson42** [comment]
This issue was moved to openzim/zim-requests#62
