### ISSUE TITLE
Reintroduce VisualEditor capability check in mwoffliner once issue in Phabricator:T350117 is fixed

### ISSUE THREAD

**Issue by VadimKovalenkoSNF** [openzim/mwoffliner#1940]
There is a regression with VisualEditor introduced in MW core. Check the related Phab ticket - https://phabricator.wikimedia.org/T350117. Mwoffliner relies on VisualEditor Mediawiki namespace when it comes to testing. More info in https://github.com/openzim/mwoffliner/issues/1937 - our first assumption was that the mwoffliner caused this regression because of exceeding MW infrastructure rate limits.

**Comment by kelson42** [comment]
@VadimKovalenkoSNF Please don't forget to put here the PR to revert, so there is no ambiguity about what to do.

**Comment by VadimKovalenkoSNF** [comment]
PR that introduces temporary disabling of the VisualEditor capability check - https://github.com/openzim/mwoffliner/pull/1941
