### ISSUE TITLE
Troubleshooting bitcoin wiki recipe  

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/mwoffliner#1957]
As per this [issue](https://github.com/openzim/zim-requests/issues/763), please check why this recipe is failing while we have already a successful resulted file in the past.

The link to the recipe on the Zimfarm: 
https://farm.openzim.org/recipes/bitcoin_wiki

The link to last working ZIM (if any): 
https://download.kiwix.org/zim/other/bitcoin_en_all_maxi_2021-03.zim

The error I get:
Unable to find appropriate API end-point to retrieve article HTML

**Comment by benoit74** [comment]
VisualEditor extension seems not be be installed on this wiki (at least not anymore), see https://en.bitcoin.it/wiki/Special:Version

We have to wait for a more recent mwoffliner which could use the API instead of VisualEditor.
