### ISSUE TITLE
wikipedia full

### ISSUE THREAD

**Issue by amirh123123** [openzim/mwoffliner#196]
hi please make wikipedia and other project full with all pictures sounds and videos thanks

**Comment by Popolechien** [comment]
Hello, offline Wikipedia already exists.

**Comment by kelson42** [comment]
Hmmm, we do not provide with full with videos.

**Comment by amirh123123** [comment]
no i want wikipedia with all videos all sounds and all pictures

**Comment by kelson42** [comment]
This issue was moved to openzim/zim-requests#65
