### ISSUE TITLE
Troubleshooting rationalwiki recipe

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/mwoffliner#1966]
As per this https://github.com/openzim/zim-requests/issues/763, please check why this recipe is failing while we have already a successful resulted file in the past.

The link to the recipe on the Zimfarm:
https://farm.openzim.org/recipes/rationalwiki

The link to last working ZIM (if any):
https://download.kiwix.org/zim/other/rationalwiki_en_all_maxi_2021-03.zim

The error I get:
Unable to find appropriate API end-point to retrieve article HTML\n

**Comment by benoit74** [comment]
No VisualEditor, you will have to wait for mwoffliner 1.14
