### ISSUE TITLE
Troubleshooting Stupidedia recipe

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/mwoffliner#1968]
As per this https://github.com/openzim/zim-requests/issues/763, please check why this recipe is failing while we have already a successful resulted file in the past.

The link to the recipe on the Zimfarm:
https://farm.openzim.org/recipes/stupidedia

The link to last working ZIM (if any):
https://download.kiwix.org/zim/other/stupidedia_de_all_maxi_2021-01.zim

The error I get:
Unable to connect to S3, either S3 login credentials are wrong or bucket cannot be found\n

**Comment by benoit74** [comment]
No VisualEditor at https://www.stupidedia.org/stupi/Special:Version, you will have to wait for mwoffliner 1.14
