### ISSUE TITLE
Error when trying to download UESP

### ISSUE THREAD

**Issue by DataAddict42** [openzim/mwoffliner#1975]
Has anyone had any success with the uesp? I looked in the recipes and can't find anyone has done it before. I tried and get the following error every time: "Unable to find appropriate API end-point to retrieve article HTML"

`mwoffliner --mwUrl=https://en.uesp.net/ --adminEmail=foo@bar.net --verbose --mwWikiPath="/wiki/Main_Page"`
(node:4256) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

`Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use node --trace-warnings ... to show where the warning was created)
[log] [2024-01-17T21:57:07.552Z] Starting mwoffliner v1.13.0...
[info] [2024-01-17T21:57:07.557Z] Using custom flavour: no
[log] [2024-01-17T21:57:07.558Z] Getting text direction...
[log] [2024-01-17T21:57:07.559Z] Getting site info...
[log] [2024-01-17T21:57:07.559Z] Getting sub-title...
[info] [2024-01-17T21:57:07.560Z] Downloading [https://en.uesp.net/wiki/Main_Page]
[info] [2024-01-17T21:57:07.563Z] Getting JSON from [https://en.uesp.net/w/api.php?action=query&meta=siteinfo&format=json&siprop=general|namespaces|statistics|variables|category|wikidesc]
[info] [2024-01-17T21:57:07.567Z] Downloading [https://en.uesp.net/wiki/Main_Page]
[log] [2024-01-17T21:57:07.574Z] closing sanitize redis DB
[log] [2024-01-17T21:57:08.083Z] Text direction is [ltr]
[info] [2024-01-17T21:57:08.150Z] Getting JSON from [https://en.uesp.net/w/api.php?action=query&meta=siteinfo&format=json]
[info] [2024-01-17T21:57:08.263Z] Downloading [https://images.uesp.net/4/40/NewUESPLogo1.png]
[info] [2024-01-17T21:57:10.049Z] Getting JSON from [https://en.uesp.net/w/api.php?action=query&format=json&prop=redirects%7Crevisions%7Ccoordinates&rdlimit=max&rdnamespace=]
[info] [2024-01-17T21:57:10.155Z] Coordinates not available on this wiki
[log] [2024-01-17T21:57:10.155Z] Base Url:  undefined
[log] [2024-01-17T21:57:10.156Z] Base Url for Main Page:  undefined
[error] [2024-01-17T21:57:10.157Z] Failed to run mwoffliner after [3s]: {
	"stack": "Error: Unable to find appropriate API end-point to retrieve article HTML\n    at Downloader.setBaseUrls (file:///usr/lib/node_modules/mwoffliner/lib/Downloader.js:172:19)\n    at Module.execute (file:///usr/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:134:22)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
	"message": "Unable to find appropriate API end-point to retrieve article HTML"
}
[error] [2024-01-17T21:57:10.157Z] 

Unable to find appropriate API end-point to retrieve article HTML`

**Comment by mai-gh** [comment]
I got past your error with 
```docker run ghcr.io/openzim/mwoffliner mwoffliner --mwUrl=https://en.uesp.net/ --adminEmail=foo@bar.net --verbose --mwWikiPath="/wiki/Main_Page" --mwApiPath="/w/api.php" --mwRestApiPath="/wiki/"```

**Comment by DataAddict42** [comment]
> I got past your error with `--mwRestApiPath="/wiki/"`

Thanks!
