### ISSUE TITLE
Does not pick up articles starting with a special character

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1985]
Tested on https://library.kiwix.org/viewer#wikipedia_en_all_maxi_2024-01

The following articles are not retrieved in the search bar nor do they seem to have been scraped:
+972 Magazine
+Valores

B+ tree, on the other hand, seems to work.

**Comment by Jaifroid** [comment]
https://library.kiwix.org/viewer#wikipedia_en_all_maxi_2024-01/A/+972_Magazine
https://library.kiwix.org/viewer#wikipedia_en_all_maxi_2024-01/A/+Valores

@Popolechien They seem to be in that ZIM (try links above9, and I could search for "972 magazine" (screenshot). Could it be a browser/connection issue on your side?

![image](https://github.com/openzim/mwoffliner/assets/4304337/2681a6f2-00ee-4eab-917a-688ea9e3fd6b)

**Comment by Popolechien** [comment]
Yup, works now. Odd. I'll check again with the user who reported it then, might be an android issue or, just like in my case, a _[pebcak](https://en.wiktionary.org/wiki/PEBCAK)_.
