### ISSUE TITLE
wikipedia_nl_all_maxi.zim is failing create a new .zim

### ISSUE THREAD

**Issue by TheQuickFox** [openzim/mwoffliner#1992]
I got directed here from my Reddit post:
https://www.reddit.com/r/Kiwix/comments/1apaen9/when_is_the_next_update_for_the_dutch_wikipedia/

The Dutch Maxi .zim of Wikipedia has not been updated since July 2023. I wondered when a new version would be posted and people notified that it should have been made already, but that the making of the .zim is failing. When I dive in logs I see that it may be failing at very long lists of birds.

Log: https://farm.openzim.org/recipes/wikipedia_nl_all

Mentioned lists in the fail log:
https://nl.wikipedia.org/wiki/Lijst_van_vogels_in_IOC-volgorde
https://nl.wikipedia.org/wiki/Lijst_van_vogels_alfabetisch
(11001 birds)

**Comment by Jaifroid** [comment]
This affects the mini and nopc as well as the maxi (all done with the same recipe). Next run should be later this week (16th Feb).

**Comment by kelson42** [comment]
There is an upstream API error, which should be reported in Phabricator.

**Comment by Popolechien** [comment]
Sweet mother of mercy, each page is 1.6 _million_ bytes o_0
Couldn't we (as another quickfix) blacklist/skip pages that are deemed to big?

**Comment by kelson42** [comment]
Yes, and this is IMO kind of a valid scenario for it. But IMHO before doing that it would be healthier to (1) report API bug to phabricator (2)   Try to split these two pages.

**Comment by Popolechien** [comment]
Ok I've pinged the pages' main author, and they very helpfully replied "The logical thing to do is to fix that apparently buggy software that you use. These bird lists are large but well below the maximum allowed wikipedia page size" ¯\_(ツ)_/¯

**Comment by Jaifroid** [comment]
So, we have a new run tomorrow. If we'd like it to succeed, then I think the blacklist function is the only viable thing right now, unless you feel it's better not to issue a new ZIM without these pages.

In any case, @kelson42 I think you're probably the only person with both technical understanding of the issue and a Phabricator account to open an issue there and explain clearly what's needed.... (sorry!).
