### ISSUE TITLE
mwoffliner dev missing article in error message

### ISSUE THREAD

**Issue by tim-moody** [openzim/mwoffliner#2009]
running docker mwoffliner-dev against mdwiki.org with medicine.tsv list I get

`[error] [2024-03-20T17:31:00.314Z] Unable to retrieve js/css dependencies for article '[object Object]': internal_api_error_MWException
`

[object Object] looks like an unassigned variable

I can supply the full log if it helps. (was too large for pastebinit)

**Comment by tim-moody** [comment]
To be clear, the mwoffliner I am running is ghcr.io/openzim/mwoffliner:dev

The log says Starting mwoffliner v1.13.0...

**Comment by kelson42** [comment]
@tim-moody What is your exact command?

**Comment by tim-moody** [comment]
mwoffliner \
  --adminEmail="info@iiab.me" \
  --articleList="http://offline.mdwiki.org/nonwiki/lists/mdwikimed.tsv" \
  --customMainPage="App/IntroPage" \
  --customZimTitle="MDWiki Medical Encyclopedia" \
  --customZimDescription="Collection of Healthcare Content mdwiki.org." \
  --customZimFavicon="https://en.wikipedia.org/static/images/project-logos/enwiki.png" \
  --filenamePrefix="mdwiki_en_all" \
  --format="novid:maxi" --format="" \
  --mwUrl="https://mdwiki.org/" \
  --osTmpDir="/dev/shm" \
  --outputDirectory="/output" \
  --requestTimeout="300" \
  --speed="1" \
  --webp \
  --verbose

The article list has changed since this was run.

**Comment by tim-moody** [comment]
Here is a piece of the log

```
root@iiab-content:/Scrapes/mwoffliner-dev# grep Object failed-2024-03-21.log
[info] [2024-03-21T14:23:45.341Z] Getting JSON from [https://mdwiki.org/w/api.php?action=query&format=json&prop=redirects%7Crevisions%7Ccoordinates&rdlimit=max&rdnamespace=0%7C3000%7C3002&redirects=true&formatversion=2&titles=Ober%27s_test%7CObesity_and_fertility%7CObesity_in_Brazil%7CObesity_in_China%7CObesity_in_the_Republic_of_Ireland%7CObesity_medicine%7CObesity_paradox%7CObesogen%7CObetrol%7CObex%7CObexelimab%7CObicetrapib%7CObicularis_oculi%7CObidoxime%7CObject_recognition_%28cognitive_science%29%7CObjective_structured_clinical_examination%7CObligate_aerobe%7CObligate_anaerobe%7CObligate_carrier%7CObligate_nasal_breathing%7CObligatory_synergies%7COblimersen%7COblique_arytenoid%7COblique_arytenoid_muscle%7COblique_arytenoid_muscles%7COblique_auricular_muscle%7COblique_auricular_muscles%7COblique_cord%7COblique_cords%7COblique_dendrite%7COblique_dendrites%7COblique_fissure%7COblique_fissures%7COblique_line_of_the_thyroid_cartilage%7COblique_line_of_the_thyroid_cartilages%7COblique_line_of_thyroid_cartilage%7COblique_lines_of_the_thyroid_cartilage%7COblique_lines_of_the_thyroid_cartilages%7COblique_lines_of_thyroid_cartilage%7COblique_lines_of_thyroid_cartilages%7COblique_muscle%7COblique_muscle_of_abdomen%7COblique_muscle_of_auricle%7COblique_muscle_of_auricles%7COblique_muscle_of_eye%7COblique_muscle_of_the_abdomen%7COblique_muscle_of_the_auricle%7COblique_muscle_of_the_auricles%7COblique_muscle_of_the_eye%7COblique_muscles&colimit=max]
[error] [2024-03-21T14:59:49.713Z] Unable to retrieve js/css dependencies for article '[object Object]': missingtitle

```

**Comment by kelson42** [comment]
Today we can not reproduce this problem in the Zimfarm (which dies somewhere else). I'm not eager to debug here as long as the bug is not easily reproducible and the upstream backend stable.
