### ISSUE TITLE
Scraper says nothing but "Killed" after 5 minutes of operation

### ISSUE THREAD

**Issue by benoit74** [openzim/mwoffliner#2011]
See https://github.com/openzim/zim-requests/issues/936 for first known occurence.

**Comment by kelson42** [comment]
Seems fixed in dev

**Comment by kelson42** [comment]
Last run was OK https://farm.openzim.org/pipeline/c1c65541-a9b6-4f1b-9970-70234db3e9e0, impossible to reproduce and is probably a problem upstream. I can not really do more.
