### ISSUE TITLE
Missing icons Wikiprojects in Russian Wiikpedia

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#2021]
In **Russian Wiikpedia** are missing icons **Wikiprojects** (Wikimedia Commons etc.).

For example, they have already appeared in the English Wikipedia:
![Wikimedia-Commons](https://github.com/openzim/mwoffliner/assets/65112331/6f278952-c2ca-4523-a376-e3c84d8648a9)

Maybe the Wikiproject icons are missing in the Russian Wikipedia due to the use of the code `{{Навигация}}`.

**Comment by audiodude** [comment]
I don't see those links on Russian wikipedia itself (eg https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D0%B3%D1%80%D0%B0%D1%82_(%D0%93%D0%B0%D0%BB%D1%81%D1%82%D0%B0%D0%BD%D1%8F%D0%BD)) so I don't think they are expected to be in the ZIM.

**Comment by kelson42** [comment]
I guess the reporter screenshot is desktop rendering and we do mobile rendering.
