### ISSUE TITLE
wikipedia_hi_medicine has improper title

### ISSUE THREAD

**Issue by benoit74** [openzim/mwoffliner#2022]
Recipe: https://farm.openzim.org/recipes/wikipedia_hi_medicine

```
**********

MetaData Title: must NOT have more than 30 characters

**********
```

I disabled the recipe for now.

**Comment by kelson42** [comment]
To me looks like an upstream bug in the validation library `ajv`, see https://github.com/ajv-validator/ajv/issues/2425

**Comment by kelson42** [comment]
The problem is that the ZIM specification expects a string length measure by grapheme and that we were doing a measure by bytes (or similar too).
