### ISSUE TITLE
Basque Wikipedia home page incorrectly scraped

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#2033]
Here is what they show
![Screenshot 2024-06-05 at 17 05 19](https://github.com/openzim/mwoffliner/assets/21675885/ca22fbbc-c09e-467c-bff9-b9aaf722f971)

And what we have
![Screenshot 2024-06-05 at 17 04 30](https://github.com/openzim/mwoffliner/assets/21675885/7fb51305-dca5-421a-8166-2dc43c128a57)

**Comment by kelson42** [comment]
@Popolechien please give links in bug reporta, without links i can only say that indeed the two pictures are different

**Comment by kelson42** [comment]
I have checked with https://library.kiwix.org/viewer#wikipedia_eu_all_maxi_2024-04/A/Azala and this is a version from january used (maybe a problem with the cache) in any case this is what the desktop API returns. There is nothing we can change about that.

**Comment by Popolechien** [comment]
@kelson42 My bad: https://eu.wikipedia.org/ is Basque WP. I've noticed the last run for https://farm.openzim.org/recipes/wikipedia_eu_all was canceled, but I don't know why/by whom. I have re-requested it.

**Comment by kelson42** [comment]
@Popolechien Can we close this issue?
