### ISSUE TITLE
Installation Failure on TurnKey Node.js Appliance 

### ISSUE THREAD

**Issue by TimXiedada** [openzim/mwoffliner#2048]
Hi there,

I met some difficulties when installing this command-line utility.

After executed `npm install mwoffliner -g`, 
it installed dependencies normally.

But then I encountered an error: 
![image](https://github.com/openzim/mwoffliner/assets/98872482/53dc022c-19e5-4846-bab0-d3f8fcc6ce98)
and what in the log mentioned there is exactly the same as 
this error message (so I think it is meaningless to attach the log).

I confirmed that the link mentioned there is reachable and tried to link `sh` to `/usr/bin/bash`, but still have to face this error.
I used [TurnKey Node.js Appliance](https://www.turnkeylinux.org/nodejs) and did not try it on other platforms.

**Comment by audiodude** [comment]
Is it possible that you don't have the required `libfoo-dev` packages on your system that the sharp binary needs?

**Comment by TimXiedada** [comment]
There is NO `libfoo` on Debian packages repository, not to mention `libfoo-dev`. You can try searching it on <http://packages.debian.org/>.

**Comment by audiodude** [comment]
Sorry, I was using that as a placeholder for whatever actual libraries you need to install for `sharp`. Looks like they may be listed at the URL provided by the error message? https://sharp.pixelplumbing.com/install

**Comment by kelson42** [comment]
@TimXiedada I would try to install `sharp` alone to see in detail what goes wrong there and if problem ask them directly as this is out of scope here.
