### ISSUE TITLE
Extraneous characters in id fields of WikiMed on some pages

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#205]
For example, on the latest (01-2018) WikiMed page for "Epidemiology of HIV-AIDS", the internal anchor links to some of the  regions do not work because there are extraneous `}}` characters appearing in the related id field. See the code shown below, and look at the `<span class...>` line.
```
<h3 tabindex="0" class="section-heading in-block collapsible-heading open-block"
aria-haspopup="true" aria-controls="content-collapsible-block-4">
    <span class="mw-headline" id="Sub-Saharan_Africa }}">Sub-Saharan Africa</span>
</h3>
```

**Comment by kelson42** [comment]
@Jaifroid Thx for the bug report. It is fixed https://github.com/openzim/mwoffliner/commit/2e1bcc5dc9ea8cf3c68165059ee9418f51f7df03
