### ISSUE TITLE
Dark mode roll out

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#2052]
Just saw the announcement that dark mode is becoming a new feature (though I'm pretty sure the actual backend rollout has been there for a while), but I'm not sure if this is something we can capture or not.

**Comment by audiodude** [comment]
Dark mode is a user/client preference right? I don't think it impacts the scaped data. I know that some Kiwix clients support dark mode but I'm not sure how it's implemented. Sorry, I guess this comment isn't very helpful. 😭

**Comment by Popolechien** [comment]
Well actually it does answer my question!
