### ISSUE TITLE
Wikimedia Maps HTTP 403 (acting like a bad bot)

### ISSUE THREAD

**Issue by kevinmcmurtrie** [openzim/mwoffliner#2061]
[//]: # (Pick appropriate classifiers)
- Location:  Worker
- Schedule Name/ID: wikipedia*
- Task ID: https://farm.openzim.org/pipeline/94167b91-8b89-41de-a351-6287bab02c49

## Problem

The Wikipedia scrapers request map tiles from Wikimedia Foundation but have no permission.  This results in a lot of HTTP 403 responses.  It's possibly enough to be seen as a bad bot.

https://maps.wikimedia.org/img/osm-intl,5,40.415555555556,50.008611111111,260x260.png?lang=it&domain=it.wikipedia.org&title=Ateshgah_di_Baku&revid=137071110&groups=_4ddc15001962e3bddf2312007a0240d4b5316888
`Error: 403, Forbidden: Map tiles are restricted to Wikimedia & affiliated sites only. See https://wikitech.wikimedia.org/wiki/Maps/External_usage if you believe your usage supports the Movement. at Sat, 06 Jul 2024 18:55:57 GMT`

## Reproducing steps

Caused by scraping Wikipedia articles with maps.

**Comment by benoit74** [comment]
Thank you, this is a very interesting and important thing I believe.

Transferring to openzim/mwoffliner since this must be solved in the scraper.

**Comment by kelson42** [comment]
@kevinmcmurtrie Thank you, this is a known issue, see for example #1908... but I never have achieved to understand what was going wrong. Now it is pretty clear and I see two solutions:
* Either set the referer properly (probably not set)
* Open a ticket on Phabricator

Not sure what is the best approach at this stage.

**Comment by benoit74** [comment]
Setting the referer seems to be a hack (we somehow how the very poor protection put in place by the WMF). But it works very well:

```
curl -H 'Referer: https://localhost/' https://maps.wikimedia.org/img/osm-intl,5,40.415555555556,50.008611111111,260x260.png?lang=it&domain=it.wikipedia.org&title=Ateshgah_di_Baku&revid=137071110&groups=_4ddc15001962e3bddf2312007a0240d4b5316888
```

I hence consider we need to do both things:
- adapt mwoffliner to be able to receive a referer 
- open a ticket on Phabricator to have formal approval of our use-case + decide with them which referer would make sense (just to not hack the system since we want to maintain good relations with the WMF)

Should the Phabricator ticket take time to implement, we can always use a "fake" referer until it gets resolved.

**Comment by audiodude** [comment]
I've completed the first step in the linked PR. I will file the phabricator ticket and update this issue with the ticket number.

**Comment by kelson42** [comment]
@audiodude Thank you, in case of Phabricator/upstream ticket, please systematically link tickets in both directions: from github to phabricator AND from Phabricator to Github.

**Comment by kelson42** [comment]
We still need to open an issue on Phabricator and someone had put somewhere the link to the Wikimedia conf ehere the referer is checked... but can not find it anymore! Where was that?

**Comment by benoit74** [comment]
It is mentioned in https://wikitech.wikimedia.org/wiki/Maps/External_usage where they also mention the proper way to open a Phabricator ticket with proper pre-filled information.

**Comment by audiodude** [comment]
Do we have a "Wikimedia Affiliate" @kelson42 ? It is a required field in the phabricator ticket.

**Comment by kelson42** [comment]
> Do we have a "Wikimedia Affiliate" @kelson42 ? It is a required field in the phabricator ticket.

No! What is that? But our tickets MUST have the proper tag to appear on our board https://phabricator.wikimedia.org/tag/affects-kiwix-and-openzim/

**Comment by audiodude** [comment]
Well without an "affiliate" the ticket cannot proceed, the template makes it very clear that it is required.

**Comment by benoit74** [comment]
@Popolechien any idea of how we could be considered an Affiliate from WMF point of view?

A quick look on the internets made me find this page: https://meta.wikimedia.org/wiki/Wikimedia_Affiliates_Data_Portal/Organizations_Information and from my PoV we are part of the WOW UG, which seems to be considered an affiliate: https://meta.wikimedia.org/wiki/Wikimedians_for_Offline_Wikis_User_Group

**Comment by Popolechien** [comment]
@benoit74 Yeah we shouldn't have to deal with this paperwork tbh as we have our own direct channels with the WMF devs, but I guess WoW should work.

**Comment by kelson42** [comment]
> Well without an "affiliate" the ticket cannot proceed, the template makes it very clear that it is required.

OK, this is very new!

**Comment by kelson42** [comment]
We are only missing the upstream issue then I will merge as the code  LGTM

**Comment by audiodude** [comment]
https://phabricator.wikimedia.org/T370650

**Comment by bd808** [comment]
> (we somehow hack the very poor protection put in place by the WMF)

FYI: This particular characterization of the map tiles hot linking defenses caused some SREs to chuckle and others to plot to specifically break your code.

**Comment by bd808** [comment]
https://github.com/openzim/mwoffliner/issues/2067
