### ISSUE TITLE
Allow for negative lists

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#2089]
Currently WP1 allows us to build a zim file based off a selection of articles. But we have an increasing number of deployments where would-be institutional users need to back out because some elements are deemed inappropriate:
- prisons, where apparently inmates will look up their fellow prisoners and shiv whoever has an entry to their name for sexual crimes;
- schools, where kids' first instinct is to look up 69, panda porn and so on.

Ideally we should be able to run a bespoke recipe and attach a .tsv list of articles that would be skipped entirely during the scraping process. Having looked at the rapist issue I would actually recommend that all articles containing the given strings be omitted, so that even if there is no proper article available even a cursory mention could not be searched for.

**Comment by kelson42** [comment]
This is called "Article List to ignore" and this is already implemented.
