### ISSUE TITLE
Figure out how to get emails for scheduled test run failures

### ISSUE THREAD

**Issue by audiodude** [openzim/mwoffliner#2095]
In #2094 we fix tests that have degraded due to upstream changes. In  #2059, we attempted to add daily scheduled runs of CI to catch this sort of thing early, so we wouldn't be interrupted with trying to fix failing tests when merging new code.

The scheduled part is working, but this issue has been present for over a month:
https://github.com/openzim/mwoffliner/actions/runs/10862381298

We need to figure out how to actually get emails when this fails.

**Comment by kelson42** [comment]
I get GitHub email notification. You don't?

**Comment by audiodude** [comment]
I'm not talking about general GitHub emails, I'm talking about getting a notification when the scheduled CI (see link above) fails.

Apparently this is a known issue with lots of people that want this feature, but it doesn't really exist, see https://github.com/orgs/community/discussions/18039

**Comment by audiodude** [comment]
Or maybe you were the "last one to touch" the workflow so you're getting the emails from the cron job?

**Comment by kelson42** [comment]
> I'm not talking about general GitHub emails, I'm talking about getting a notification when the scheduled CI (see link above) fails.

Me too.

I have configure to get all notifications. You too?

**Comment by audiodude** [comment]
You must have been the last one to "touch" the workflow then. I see your user avatar on the link for the failed run.

I'm going to try and switch it over to me, from what I understand you get way too many GitHub emails anyway.
