### ISSUE TITLE
wikihow

### ISSUE THREAD

**Issue by amirh123123** [openzim/mwoffliner#210]
hi please make zim file for wikihow

**Comment by Popolechien** [comment]
www.wikihow.com

There might be an issue with the illustrations so I'd put this on hold for the time being (I've sent them a mail to clarify copyright status)

**Comment by kelson42** [comment]
We can not do a dump of wikihow directly from mwoffliner. This is why a dedicated repo has been done here https://github.com/openzim/wikihow. Work to be done there.
