### ISSUE TITLE
Unable to scrape ca.wikipedia.org with 1.14.0

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#2113]
Wanted to test, what I did twice:
* https://farm.openzim.org/pipeline/d75b3ef3-3fec-4914-8bed-050be72960f7
* https://farm.openzim.org/pipeline/0349efe9-1969-4c67-926f-6dcbed5a8a11

Both died with the following error:
```
[error] [2024-12-09T11:34:26.107Z] Cannot read properties of undefined (reading 'src')
[error] [2024-12-09T11:34:26.109Z] Error downloading article Equació_de_Clairaut
[error] [2024-12-09T11:34:26.109Z] Failed to run mwoffliner after [3155s]: {
	"name": "Error",
	"message": "Cannot read properties of undefined (reading 'src')"
}
[error] [2024-12-09T11:34:26.109Z] 

**********

Cannot read properties of undefined (reading 'src')
```

**Comment by audiodude** [comment]
This is a bug introduced in #2101. Will send out a fix shortly.

**Comment by kelson42** [comment]
@audiodude Thx, important that this scenario is tested in CI IMHO.
