### ISSUE TITLE
Indexed links in Wikisource ZIMs not working and/or sub-articles not scraped

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#2119]
As per this Reddit issue: https://www.reddit.com/r/Kiwix/comments/1hggoal/indexing_not_working/ . A user reported that indices (overview articles that contain an index of contents on numbered sub-pages) are not working. I tested this in `wikisource_es_all_maxi_2024-06.zim` and it seems the issue is not the indices in themselves, but the fact that not all the links in an index have been scraped correctly. In some cases, the links work, but in the majority of cases I tested, the links merely lead to a blank page with a footer but no content scraped.

As an example, see the overview page for "La de Bringas" from that Spanish ZIM. Linkis 01, 02, 03, etc. lead to empty pages, whereas link 20 leads to a correctly scraped page.

A delay in receiving the content might explain why empty pages have been scraped in some cases, or it may be an API issue.

NB the ZIM I tested was produced with mwOffliner v1.13.0, and has minorVersion 0 (uses namespaces).

**Comment by audiodude** [comment]
I can reproduce this with just scraping es wikisource and specifying an article list of:

```
La_de_Bringas
La_de_Bringas:_01
La_de_Bringas:_02
```

Both "sub" articles (they are not actual sub pages) are blank in my scrape.

**Comment by audiodude** [comment]
The problem is that the entire content is under a `<div class="noprint">` wrapper, and mwoffliner removes any `<div>`s with that class.

**Comment by audiodude** [comment]
Funny enough, it's probably a bug in the source wikitext, because when I CTRL-P I get this:

![Image](https://github.com/user-attachments/assets/66a9407d-71bd-4a9a-8ee3-bb2d10a8f752)

**Comment by audiodude** [comment]
The article has the following:

```
<div class="noprint">{{encabe
|título=I<br>([[La de Bringas]])
|autor=[[Benito Pérez Galdós]]
|notas=}}
<div style='text-align:justify'></div>
```

It seems that someone wanted to put the `noprint` on the div wrapping the `encabe` template, but forgot to close the tag.
