### ISSUE TITLE
footballdatabase.com

### ISSUE THREAD

**Issue by amirh123123** [openzim/mwoffliner#216]
hi please make zim file for footbaldatabase.com

**Comment by kelson42** [comment]
unreachable web site to me.

**Comment by amirh123123** [comment]
The #1 Football / Soccer World Club Ranking Site on the Internet.

(CC BY-SA 4.0) FootballDatabase.co

**Comment by kelson42** [comment]
This issue was moved to openzim/zim-requests#68
