### ISSUE TITLE
OLPC Educational Packages 

### ISSUE THREAD

**Issue by amirh123123** [openzim/mwoffliner#232]
hi please make zim file for OLPC Educational Packages

**Comment by kelson42** [comment]
URL please?

**Comment by amirh123123** [comment]
http://dev.worldpossible.org/cgi/viewmod.pl?module_id=11

**Comment by kelson42** [comment]
The URL is dead.

**Comment by kelson42** [comment]
This issue was moved to openzim/zim-requests#72
