### ISSUE TITLE
Make ZIM of "Core Knowledge" http://www.coreknowledge.org

### ISSUE THREAD

**Issue by amirh123123** [openzim/mwoffliner#236]
hi please make zim file for Core Knowledge

**Comment by kelson42** [comment]
url?

**Comment by amirh123123** [comment]
https://www.coreknowledge.org

**Comment by kelson42** [comment]
"The materials made available for download are freely available for anyone to use, adapt, and share (with attribution). No one is permitted to sell either the original program, an adaptation of it, or lesson plans that reproduce any part of it. For more information, see the Guidelines to Core Knowledge and the Creative Commons License." https://www.coreknowledge.org/curriculum/

Definitly free content.

**Comment by kelson42** [comment]
This issue was moved to openzim/zim-requests#76
