### ISSUE TITLE
ZIMs of the Rachel project

### ISSUE THREAD

**Issue by amirh123123** [openzim/mwoffliner#240]
http://dev.worldpossible.org/cgi/rachelmods.pl have more files please make files to zim format example i download medline plus but format is html i want all files to this  address is zim files thanks

**Comment by kelson42** [comment]
Many of them are already in ZIM format, what do you need precisely ?

**Comment by amirh123123** [comment]
hi 
Files that do not have a zim format

**Comment by kelson42** [comment]
This issue was moved to openzim/zim-requests#86
