### ISSUE TITLE
wikipedia biology 

### ISSUE THREAD

**Issue by amirh123123** [openzim/mwoffliner#241]
hi please make zim file for wikipedia biology animals plant and other species thanks

**Comment by kelson42** [comment]
Is Wikispecies not what you need?

**Comment by amirh123123** [comment]
hi no wikipedia articles about animals example dog cat and other species thanks

**Comment by kelson42** [comment]
@Popolechien We need an offline home page and a list of articles (wikiproject).

**Comment by Popolechien** [comment]
@kelson42 Here it is https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Biology/Offline, and the logo is here: 
![biology](https://user-images.githubusercontent.com/21675885/38244767-fb5151b4-373b-11e8-991e-e8430d861a34.png)

As a side note the zim should probably not include articles intersecting with WikiProject Biography but should include those from WikiProject Mammals (if OP wants cats and dogs).

**Comment by kelson42** [comment]
This issue was moved to openzim/zim-requests#80
