### ISSUE TITLE
wikipedia nintendo

### ISSUE THREAD

**Issue by amirh123123** [openzim/mwoffliner#245]
hi please make zim file for nintendo articles on wikipedia thanks

**Comment by kelson42** [comment]
There is no wikiproject Nintendo on Wikipedia... this is going to be hard.

**Comment by amirh123123** [comment]
hi please add articles from this address 
https://en.wikipedia.org/wiki/Category:Nintendo_task_force_articles

**Comment by kelson42** [comment]
This issue was moved to openzim/zim-requests#84
