### ISSUE TITLE
Create MolCell Biology zim

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#249]
The actuall name should probably be "molecular & cellular biology"
Landing page can be found at 
https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Molecular_and_Cell_Biology/Offline

Icon file is https://commons.wikimedia.org/wiki/File:MolCell_Biol_Kiwix.png

**Comment by kelson42** [comment]
done

**Comment by Popolechien** [comment]
I do not see the zim file in https://download.kiwix.org/zim/wikipedia/

**Comment by Popolechien** [comment]
Ah and here is a more suitable logo for the zim alone. Should I upload it on Commons as well?
![logo mcbzim](https://user-images.githubusercontent.com/21675885/38237716-3a116eb6-3728-11e8-8bf9-14eac877091b.png)

**Comment by Popolechien** [comment]
Here it is (236x236) https://commons.wikimedia.org/wiki/File:MolCellBiol_Kiwix.png and 
![38237716-3a116eb6-3728-11e8-8bf9-14eac877091b](https://user-images.githubusercontent.com/21675885/38540478-5f24fc4e-3c9c-11e8-91a7-3b2164145d62.png)

**Comment by kelson42** [comment]
@Popolechien done https://github.com/kiwix/maintenance/commit/3fe289626ff57d16fde3574740eca17def3f1503
