### ISSUE TITLE
Create Chemistry ZIM file

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#251]
Landing page is here
https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Chemistry/Offline

and logo is here
https://commons.wikimedia.org/wiki/File:Chemistry_Kiwix.png

**Comment by kelson42** [comment]
done https://download.kiwix.org/zim/wikipedia/wikipedia_en_chemistry_novid_2018-03.zim
Integrated to the "montly" update scripts.
