### ISSUE TITLE
Indian wiktionaries

### ISSUE THREAD

**Issue by damooo** [openzim/mwoffliner#252]
Namaste. Many Indian language Wiktionaries(ta,te,kn,ml,hi,sa,etc) are of 2016. They all are very small of size less than 50 mb without images. So it may be easy to build zim files for them. If it is possible can you please update them? It will be very helpful if you update them atleast twice a year. Thanks again.

**Comment by kelson42** [comment]
@damooo New version of these wiktionaries have been published.
