### ISSUE TITLE
Custom welcome page have a strange name

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#253]
Typically "User:Popo le chien/Kiwix". This is puzzling for users, but at the same time this is the right place on Wikipedia to save this page. We should find a way, ideally on Wikipedia itself to get mwoffliner save that page with an other title/url.

**Comment by Popolechien** [comment]
For custom content we moved to wikiproject XYZ/offline, but I agree that either way there's no added value to this kind of information. Can we just blank it or have only the last part (e.g. Landing, Maths or whatever) be shown?

**Comment by kelson42** [comment]
I reported a bug here about this https://phabricator.wikimedia.org/T51076 and it seems it has been implemented, should verify if it really works.

**Comment by kelson42** [comment]
@Popolechien So, I have verified that we can have a solution for this long standing problem, and we do have one. Please do something similar to this https://fr.wikipedia.org/w/index.php?title=Utilisateur:Popo_le_Chien/Kiwix&type=revision&diff=152256190&oldid=130399118&diffmode=source to all custom main page you maintain and the problem will vanish.

**Comment by Popolechien** [comment]
okie dokie.
