### ISSUE TITLE
MWoffliner should be able to work without a cache

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#263]
In many cases we do not want a cache. Having one just makes the whole stuff work slower and cache needs to be deleted manually afterward.

**Comment by ISNIT0** [comment]
The `--useCache` defaults to true, to disable the cache, use `--useCache=false`

**Comment by kelson42** [comment]
@ISNIT0 ok, this is a bit "complicated", would be better to just use nocache per default and then just have `--useCache` to activate it?

**Comment by ISNIT0** [comment]
@kelson42 
Okay, I will do this
