### ISSUE TITLE
landing page

### ISSUE THREAD

**Issue by amirh123123** [openzim/mwoffliner#275]
hi i want see landig pages for project please adding example i want see landing wikipedia computer

**Comment by Popolechien** [comment]
Hey @amirh123123 would you like to help us prepare these landing pages in Farsi? It looks like it's your home language and we don't speak it. If yes I'll show you how to do it.

**Comment by amirh123123** [comment]
yes i am ready

**Comment by amirh123123** [comment]
hi Popolechien  **** i am ready

**Comment by Popolechien** [comment]
@amirh123123 Let me prepare the template and get back to you in a few days.

**Comment by kelson42** [comment]
@Popolechien ping?

**Comment by kelson42** [comment]
We have a solution for now.
