### ISSUE TITLE
library

### ISSUE THREAD

**Issue by amirh123123** [openzim/mwoffliner#280]
hi library.kiwix.org in iran is filter do way to desible filtering

**Comment by kelson42** [comment]
@amirh123123 What you say is that it is censored?

Have you tried both?
* http://library.kiwix.org AND
* https://library.kiwix.org

**Comment by amirh123123** [comment]
yes i use browser example fire fox but not go to 
http://library.kiwix.org/

**Comment by kelson42** [comment]
There is nothing we can do here, this is censorship by the Iranian government.

**Comment by amirh123123** [comment]
sory cant go to https say this page cant dis play
