### ISSUE TITLE
wikipedia chess

### ISSUE THREAD

**Issue by amirh123123** [openzim/mwoffliner#316]
all wikipedia articles about chess

**Comment by Popolechien** [comment]
@amirh123123 Please stop opening so many tickets - we're not Santa Claus and this is not your wishlist. You need to make a good business case that 1) there is a Wikipedia Project relevant to the subject 2) that there is an actual DEMAND for that kind of zim file (e.g. high number of page views, many apps on the subject already with many downloads) and 3) we will ask you to prepare the corresponding landing page (I'll give you an example later).

Do you understand?

**Comment by amirh123123** [comment]
ok

**Comment by kelson42** [comment]
This issue was moved to openzim/zim-requests#40

**Comment by RavanJAltaie** [comment]
@amirh123123 We are working on a tool which makes it possible to include all the articles related to a specific project in 1 zim file, it should be ready soon, I will close this issue for now and if you still need these project articles please open a new issue with these specific steps mentioned in the link below so we can respond quickly and effectively to your request
https://github.com/openzim/zim-requests/blob/master/README.md
