### ISSUE TITLE
Speed-up the the redirects retrievement 

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#325]
Currently, redirects are retrieved one by one. But they could be retrieved by bulk of 5-10 or maybe even more. That would allow to speed-up seriously this part of the scrapping.

**Comment by ISNIT0** [comment]
Unless I'm mis-understanding something, we currently fetch redirects concurrently:
https://github.com/openzim/mwoffliner/blob/master/src/mwoffliner.lib.ts#L442
`speed * 3`

@kelson42 Is this issue for increasing the concurrency, or have I mis-interpreted this issue?

**Comment by kelson42** [comment]
@ISNIT0 Maybe but we still make too many API calls (one per title)... and API calls throughput are usually throttled.

**Comment by ISNIT0** [comment]
Looks like there are some edge-cases I've not found before...
It seems BM wikipedia allows a maximum of 50 titles per request...

**Comment by kelson42** [comment]
@ISNIT0 From what I know you can retrieve high level of things via API if you are logged in. To me it looks more robust if you only retrieve 50 elements at a time, it is still 50x faster than before.

**Comment by ISNIT0** [comment]
@kelson42 I've implemented a backoff, so we will start at a maximum of:
- 500 articles per request
- 7000 characters per request
And whenever a request fails, we reduce the article number by 20%
