### ISSUE TITLE
Rephrase page footer.

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#328]
Current wording at bottom of pages is "This article is issued from Wikipedia. Text licensed under CC-by-SA 4.0. Additional terms may apply for media files."

Let's get some visibility and rephrase as "This article is taken from [Wikipedia](wikipedia.org). Text licensed under CC-by-SA 4.0. Additional terms may apply for media files. Powered by [Kiwix](kiwix.org)."

**Comment by kelson42** [comment]
After discussion we came to an other (hopefully better) idea:
https://github.com/kiwix/kiwix-tools/issues/230
