### ISSUE TITLE
wikipedia_en_medicine_novid_2018-05.zim appears to break search in Kiwix JS (Windows)

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#332]
@kelson42 , @mossroy , I have been preparing the WikiMed UWP app for release with wikipedia_en_medicine_novid_2018-05 which has just been released, when I notice that searching the ~~index~~ directory entries (basic search) appears to be broken. I reproduce this not only on Kiwix JS Windows, but also on Kiwix JS reference app. Entering terms in the search box produces no results even for known articles. This does not occur in either app when picking wikipedia_en_medicine_novid_2018-03. Therefore the problem would seem to be with the latest ZIM.

Has something in the ~~indexing~~ ZIM format changed? Or is it a bad encode of the file?

EDIT: I also reproduce this issue with wikivoyage_en_all_novid_2018-05.zim . I should perhaps specify that I am not referring to indexed ZIM files, I am referring to basic search (without a compiled index) of directory entries. It is still possible to jump to different articles with hyperlinks or with the random button, but no dirEntry search on these ZIMs.

**Comment by Jaifroid** [comment]
@kelson42 , search also fails on these ZIMs in the standard x86 app. I think this confirms that the issue is with the ZIMs rather than with Kiwix JS (Windows).

**Comment by kelson42** [comment]
I confirm the problem, probably a problem with zimwriterfs. Here is the file:
https://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_novid_2018-05.zim

An other corrupted file https://download.kiwix.org/zim/wikipedia/wikipedia_en_wikipedia_en_computer_novid_2018-05.zim

@mgautierfr Do you know what is going on, this ZIM file has been created with the last version of zimwriterfs. Might that be that now zimwriterfs writes a *.zim file before the whole creation process is over?

**Comment by kelson42** [comment]
This issue was moved to openzim/zimwriterfs#48
