### ISSUE TITLE
Search finds but does not open articles in Wikivoyage with the May update

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#333]
I've tried with both Kiwix-JS and Android, so I suspect this is a zim issue though there are some minor differences.

On Android, when opening wikivoyage_en_europe_nopic_2018-03.zim, the search function correctly identifies articles and retrieves them EXCEPT the one with a funky accent (e.g. Korčula). In that case, it finds the article but does not open it (but the article is there, as I can access it through regular wikilinks from other articles). I do not have this issue with Kiwix-JS (ie it finds and opens all articles).

With wikivoyage_en_europe_nopic_2018-05.zim Kiwix-JS will not find any article with the search bar. Kiwix-Android will find it but not open it. Articles can however still be opened when clicking on relevant links in text in both cases.

**Comment by mgautierfr** [comment]
Probably related to openzim/wimwriterfs#48

**Comment by kelson42** [comment]
@mgautierfr @Popolechien Definitly, newly uploaded ZIM file of Wikiovyage Europe in English works fine so far I have tested.

**Comment by Popolechien** [comment]
I re-downloaded the Europe zim (2018-05-20) and it's still not working on Android 2.4
Is it worth re-opening the ticket?

**Comment by kelson42** [comment]
@Popolechien Probably not, download the file directly from http://mirror.download.kiwix.org and be carefull you are not redirected somewhere outside http://mirror.download.kiwix.org.

**Comment by Popolechien** [comment]
Tesetd with WikiVoyage Europe 2018-06-10 from mirror.download.kiwix.org -> Works with most names but not those with special characters (Saint-Lô, Zürich, Korčula): they are found in search, even without typing ô, ü or č, but clicking/tapping the name in the search list will return to the previously opened article.

**Comment by kelson42** [comment]
@Popolechien You can try with http://library.kiwix.org/wikivoyage_en_europe_2018-06 and it works. For me, all three examples you have given work fine. So this is not a problem with neither mwoffliner nor zimwriterfs. Could you please open a ticket in the repo of the reader (android? ios?) and if Android, please try with the last nightly.
