### ISSUE TITLE
Wrong redirect on zh zim

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#334]
On the Chinese wikipedia zim file the search for Karl Marx (马克思) returns the correct article as top result but then sends the user to 姓氏 (which means "surname", as in the generic article about last names). This is strange since on Wikipedia itself Marx ([马克思](https://zh.wikipedia.org/wiki/%E9%A9%AC%E5%85%8B%E6%80%9D)) will redirect to Karl Marx (卡尔·马克思)

Tested on both Android and Kiwix-JS.

**Comment by kelson42** [comment]
@Popolechien I have no explanation. Quite strange bug the file is really old. I'm generating a new file.

**Comment by kelson42** [comment]
@Popolechien could you please test again with new https://download.kiwix.org/zim/wikipedia/wikipedia_zh_all_novid_2018-06.zim

**Comment by Popolechien** [comment]
Tried on Kiwix-JS and it worked fine. But I could not check on Android as I suspect I got the same issue as [#760](https://github.com/kiwix/kiwix-android/issues/760)
