### ISSUE TITLE
Path error

### ISSUE THREAD

**Issue by dueni0** [openzim/mwoffliner#335]
mwoffliner throws a path error:

Downloading http://localhost/load.php?debug=false&lang=de&modules=ext.visualEditor.desktopArticleTarget.noscript|mediawiki.legacy.commonPrint%2Cshared|mediawiki.sectionAnchor|mediawiki.skinning.interface|skins.vector.styles&only=styles&skin=vector...
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1361:5)
    at /usr/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:1608:41
    at async.retry (/usr/lib/node_modules/mwoffliner/lib/Downloader.js:157:7)
    at /usr/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:676:51
    at /usr/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:726:13
    at /usr/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:52:16
    at /usr/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:264:21
    at /usr/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:44:16
    at /usr/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:723:17

**Comment by dueni0** [comment]
node version is v6.14.2
npm version is 3.10.10

**Comment by kelson42** [comment]
@dueni0 What is your exact command?

**Comment by dueni0** [comment]
The command I use is
mwoffliner --verbose --mwUrl=http://localhost --adminEmail=test@localhost --mwWikiPath= --mwApiPath=/api.php

**Comment by kelson42** [comment]
Please reopen the ticket if needed, that time I'll try to look more quickly.
