### ISSUE TITLE
MobileLayout flag works only for Wikimedia Mediawiki instances

### ISSUE THREAD

**Issue by keyduq** [openzim/mwoffliner#336]
I'm trying to create a zim file mobile version of https://es.stardewvalleywiki.com, using this
```
mwoffliner --redis="redis://redis" --verbose --mwUrl=https://es.stardewvalleywiki.com --mwWikiPath=/ --withZimFullTextIndex --localParsoid --mwApiPath=mediawiki/api.php --adminEmail=admin@admin.com --speed=0.1
```
It's works for create a desktop version but adding `--mobileLayout` flag it keeps throwing on all pages
```
Error handling json response from api. FetchError: invalid json response body at https://es.stardewvalleywiki.com/Api/rest_v1/page/mobile-sections/Conejo reason: Unexpected token < in JSON at position 0
```
As far I can see it's trying to resolve an incorrect url

The desktop version of an article like Jugador is `https://es.stardewvalleywiki.com/mediawiki/index.php?title=El_Jugador&mobileaction=toggle_view_desktop`
The mobile version is `https://es.stardewvalleywiki.com/mediawiki/index.php?title=El_Jugador&mobileaction=toggle_view_mobile`
So it only change a get parameter `mobileaction`

Is there a way that I can make this work to get a zim mobile version?

**Comment by kelson42** [comment]
@keyduq You are right, the code should be fixed to work properly with the local parsoid.  Here something seems to be wrong https://github.com/openzim/mwoffliner/blob/8fe37c551fe9e8474393b49331a1a22a696e9eb2/lib/mwoffliner.lib.js#L1419

**Comment by kelson42** [comment]
With MWoffliner 1.8 we do only mobile layout and if the remove Mediawiki does not provide and API, we manage this automatically within mwoffliner. So problem should be fixed.
