### ISSUE TITLE
Problem with latest wikipedia_de_all_nopic.zim file

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#337]
From an OTRS comment:
"Hello, i was downloading new zim files today, and md5 test was good, but
they do not work. I have a old file from 2016, this works.
The file „wikipedia_de_all_nopic.zim“ and also the older version with pictures works not in Windows and Android.  My OS Builds are Win 10 64bit Version 1803 (Build 17134.81) and android 7.0"
File tested: wikipedia_de_all_nopic_2018-05.zim 

Note: I've just tested it on Kiwix-JS and it works. Currently downloading on Android.

**Comment by Popolechien** [comment]
A couple more comments have arrived for the same zim file. Tried on my own Android device and it worked (download was problematic though but I think it's a different issue).

**Comment by Popolechien** [comment]
Ah, someone even added a picture
![frage](https://user-images.githubusercontent.com/21675885/41143389-58012ace-6af9-11e8-9ebe-5ccedc781d51.jpg)

**Comment by kelson42** [comment]
@mgautierfr Do you have a clue what happens here? I can confirm the kiwix-desktop can not open that files at all!

**Comment by ramonak** [comment]
Is it possible to get the older files from somewhere? As for me I got the same issue also for the novid version and thus I am not able to get the current German offline wikipedia anywhere (neither on my Samsung Galaxy S7 phone nor on my Ubuntu Laptop with Kiwix Java App) running. 
On my Kiwix Apps on Android and Ubuntu I am not even able to see the German Wikipedia as a download option.
Thanks for any help!

**Comment by kelson42** [comment]
@ramonak Thank you for your patience. Most recent big ZIM files are incompatible with older version of Kiwix on all plateform. For Windows and Ubuntu, we recommend to give a try to our beta of Kiwix-Destkop 2.0 available here https://download.kiwix.org/release/kiwix-desktop/. On Android Kiwix for Android 2.4 should be able to read these new ZIM files of Wikipedia in German. I close the ticket first as all of this has been tested. Please open a new ticket if you still have problems with Kiwix. Thank you again for reporting that issue.

**Comment by ForelliCH** [comment]
Based on this post: Is there any way to run the big files on a Raspberry Pi (kiwix-server-0.9-linux-armv5tejl.tar.bz2)?

I have the same error with the file wikipedia_en_all_nopic_2018-09.zim. I have many installations with Kiwix Server on Raspberry PI abroad and would need to update the ZIM files now... :-(

**Comment by kelson42** [comment]
@ForelliCH Please open a new ticket with the details of what you do, get and expect.
