### ISSUE TITLE
MWoffliner should mirror PDF included content too

### ISSUE THREAD

**Issue by BPier** [openzim/mwoffliner#338]
I have a wiki with plenty of references and pdf files included in it.
I would like to have an offline access to the pdf files in the zim file. The file are on the zim file but with a size of 0kb.

How is it possible to add the pdf files on my ZIM archive ?

Thank you

PS : This is an example of my ZIM file, There is an example of pdf included on the main page under the DEBUG title.
[renaissance_fr_all_2018-06-06_1245.zip](https://github.com/openzim/mwoffliner/files/2075798/renaissance_fr_all_2018-06-06_1245.zip)
https://renaissance.miraheze.org/wiki/Accueil

**Comment by kelson42** [comment]
@BPier Thank you for your bug report. It seems we have indeed here a limitation.

A workaround might be (not tested) to:
* Use `[[File:` instead of `[[media:`
* MIrror in addition the namespace `6` (the one with the description of the image/pdf) with `mwoffliner`

**Comment by BPier** [comment]
I tried to change the link with `[[File:` and `[[:File` but it doesn't work, the link with `[[file:` are not included in the ZIM file. However the size of the ZIM file change and add the size of the pdf file, but I don't know how to access it.

I don't understand the second proposition, how do I mirror the namespace `6` ?

[renaissance_fr_all_2018-06-10_1612.zip](https://github.com/openzim/mwoffliner/files/2090215/renaissance_fr_all_2018-06-10_1612.zip)

**Comment by BPier** [comment]
I tried with mirroring the namespace `6`. It does include the page File:myPDFfile.pdf but I don't have any link on this page to download the pdf.

But the size difference of the ZIM files still seems to indiquate that the pdf is included in the file but I can't find a way to access it

[renaissance_fr_all_2018-06-11_1718.zip](https://github.com/openzim/mwoffliner/files/2090659/renaissance_fr_all_2018-06-11_1718.zip)

![image](https://user-images.githubusercontent.com/25386763/41241354-fe60b3bc-6d9c-11e8-96b0-5cbf66bb0b18.png)

**Comment by ISNIT0** [comment]
@BPier The PDFs are stored on a different domain, and so MWOffliner ignores them.
MWOffliner is a tool for scraping MediaWikis and doesn't download external files.

PR #437 fixes a regression that wasn't present when you reported this issue.

As far as I know, MWOffliner will never support downloading external files.

**Comment by kelson42** [comment]
@ISNIT0 I understand what you mean but I don't think this is really a valid argument. Think about all Wikipedia files hosted on upload.wikimedia.org. What is the real difference with that use case?

**Comment by ISNIT0** [comment]
Okay, in that case how should we compress the PDF file and the images within it?

**Comment by ISNIT0** [comment]
And the difference is that the PDFs are linked in an anchor tag, rather than as a resource (img/vid)
