### ISSUE TITLE
Create SCP zim file

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#356]
A pretty popular fiction site, and all CC-by-SA. One of them is already using Kiwix ^^
https://www.reddit.com/r/SCP/comments/8y4hqn/kiwix_zim/
 
http://www.scp-wiki.net/

**Comment by kelson42** [comment]
@Popolechien This is not a Mediawiki as far as I can see?!

**Comment by Popolechien** [comment]
Isn't it just a different skin? Or are there non-mediawiki based wikis aout there?

**Comment by fattredd** [comment]
No, SCP uses Wikidot as a backend.

**Comment by Popolechien** [comment]
Ah well. Too bad.
