### ISSUE TITLE
Missing articles in custom selection

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#358]
See screenshot: a lot of actors are missing from the selection eventhough they are correctly categorized/tagged from the relevant projects.
![capture d ecran 2018-08-09 a 16 10 01](https://user-images.githubusercontent.com/21675885/43904528-25d0830c-9bef-11e8-9ee6-21a9e725aaa7.png)

**Comment by kelson42** [comment]
I think I have fixed most of the problem https://github.com/kiwix/maintenance/commit/b24bbdbbbfcbd63db35863304c9331d2a6e38672
