### ISSUE TITLE
MWoffliner misses some tables when indented

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#359]
see article Molecular Geometry in English: under 3D representations are images inserted as wikitables. They do not appear on-screen (see screenshot)

![molecular geometry](https://user-images.githubusercontent.com/21675885/43911554-12476768-9c00-11e8-85d1-7686e64f1cec.jpg)

I suspect it is because the wikitext has an indent (:)

**Comment by ISNIT0** [comment]
@Popolechien Do you recall which page/wiki this was on?

**Comment by ISNIT0** [comment]
This looks like a Parsoid issue to me 
Is there anything we can do from our end?

@cscott @subbuss

**Comment by ISNIT0** [comment]
***ping*** @cscott @subbuss

**Comment by kelson42** [comment]
@ISNIT0 If you think the Wikipedia API does not return the proper information, which seems the case here, then a bug report needs to be open on their side and referenced here. Please open a ticket here https://phabricator.wikimedia.org/project/view/487/ and subscribe me (user:Kelson).

**Comment by ISNIT0** [comment]
As per the issue, this particular case has been fixed and another resolution will be found on Parsoid's side.
