### ISSUE TITLE
Change arabic wikimed landing page

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#361]
The new address is
https://ar.wikipedia.org/wiki/%D9%88%D9%8A%D9%83%D9%8A%D8%A8%D9%8A%D8%AF%D9%8A%D8%A7:%D9%85%D8%B4%D8%B1%D9%88%D8%B9_%D9%88%D9%8A%D9%83%D9%8A_%D8%B7%D8%A8/%D9%85%D8%B1%D8%AC%D8%B9_%D8%A8%D8%AF%D8%A7%D9%8A%D8%A9_%D8%A7%D9%84%D8%AA%D8%B7%D8%A8%D9%8A%D9%82_%D8%A7%D9%84%D8%B7%D8%A8%D9%8A2

**Comment by kelson42** [comment]
Done

**Comment by kelson42** [comment]
It's done, but not all the link are valid (in the ZIM) in this welcome page and in the topic sub pages. The reasons is that all pages (except the welcome page) are selected base on interwiki links from English to Arabic, so it seems that many of these topic pages and articles are not interwiki linked properly in Wikidata, so fail to be present in the ZIM in Arabic. This shoudl be fixed.

**Comment by Popolechien** [comment]
When you say this is incorrectly linked in wikidata, do you mean there is a typo? I'm trying to be as clear as possible because from my tests I don't see where the problem is (all links check out on wiki, there is no redirect).

**Comment by Popolechien** [comment]
The following four links on the landing page work on-wiki, have valid interlinks, but not on the zim file (2nd, 3rd, 5th, 10th links, respectively) :
صحة نفسية
أمراض الجلد
صحة نفسية
صحة نفسية

**Comment by kelson42** [comment]
Problem fixed, ZIM going to be regenerated.
