### ISSUE TITLE
Assess English WikiMed actual size

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#366]
The assessment page of the WikiProject Medicine indicates [42'990 articles within the project](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Medicine/Assessment#Statistics), yet the Wikimed zim file apparently has 52'123.

Considering both counts are supposedly automated, what could explain this discrepancy?

**Comment by kelson42** [comment]
We do not only scrappe the "medicine" project. See https://github.com/kiwix/maintenance/blob/master/mwoffliner/mwoffliner3_dump.sh#L48
