### ISSUE TITLE
Generate Bollywood app

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#38]
A Bollywood app would include articles listed in both Wikiproject Film and WikiProject India (see, e.g. [https://en.wikipedia.org/wiki/Talk:List_of_Bollywood_films_of_2016](https://en.wikipedia.org/wiki/Talk:List_of_Bollywood_films_of_2016)).

**Comment by kelson42** [comment]
done, will be online in the next days.

**Comment by Popolechien** [comment]
logo has been uploaded to commons 
[https://commons.wikimedia.org/wiki/File:Bollywood_Kiwix.png](https://commons.wikimedia.org/wiki/File:Bollywood_Kiwix.png)

Can you please generate the app without images, and change the landing page to [https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Film/Offline_Bollywood](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Film/Offline_Bollywood) ?

**Comment by kelson42** [comment]
The welcome page has been changed. For the rest this is an Android specific topic, I will migrate the ticket.

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-android-custom#14
