### ISSUE TITLE
Move requests for ZIMs to a separate issues tracker and decide criteria for making themed ZIMs of Wikipedia

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#380]
This issue tracker is getting flooded with requests for specific ZIMs, and they are drowning out the issues that relate to problems in mwoffliner. I realize there is a tagging mechanism, so that they can in principle be filtered out, but I wonder if it might be better to have a separate issue list for ZIM requests on the openzim GitHub? Just a thought!

Related to this, I note lots of requests for, for example, cycling, skiing, cricket, swimming, rowing, etc. Wouldn't it be better to produce a "sports" ZIM instead of lots of little ZIMs of small subcategories? I could request "poetry", "plays", "novels", but wouldn't "literature" be more useful and avoid fragmenting the ZIM offerings too much? It's already a labyrinth to navigate the ZIM server... Again, this is just my tuppence -- I don't mean to interfere in policy decisions, so please ignore if I've got the wrong end of the stick.

**Comment by bradyhunsaker** [comment]
I love this clean up!

It made it so for the first time I felt comfortable looking through every
non-zim-request issue for mwoffliner to get a better sense of where things
are.
