### ISSUE TITLE
In the Ray Charles zim, ogg audio file shows up inside an img tag

### ISSUE THREAD

**Issue by sharun-s** [openzim/mwoffliner#381]
In the Ray Charles zim (wikipedia_en_ray_charles_2015-06.zim) the Eleanor Rigby article references an ogg audio file inside an <img> tag 
`<img src="../I/m/Beatles_eleanor_rigby.ogg" data-file-width="" data-file-height="" data-file-type="audio" >
`
Fix:
When audio file references are detected they should ideally be turned into something like
`<audio preload='none' controls><source src='...'></audio>`

Also effecting src link is what namespace/directory the src path of ogg file and subtitle file should use. In this case for some reason it is in I (image namespace?). The videos links of the TED talks zim for example are in the I namespace/directory while the subtitles are in the meta namespace/directory. Maybe this is the convention for audio/video. Requires clarification.

Related issues: https://github.com/openzim/zimwriterfs/issues/80, https://github.com/kiwix/kiwix-js/issues/409

**Comment by kelson42** [comment]
Problem should be fixed, I have generated new ZIM for the "Ray Charles" selection here https://download.kiwix.org/zim/wikipedia/ and will do so every month from now.

**Comment by kelson42** [comment]
I reopen the ticket, we still have a problem here. With 1.9.4, the whole audio box has disappeared. Scraped with `mwoffliner --mwUrl="https://en.wikipedia.org/" --adminEmail="contact@kiwix.org" --articleList="https://download.kiwix.org/wp1/enwiki_2019-05/customs/ray_charles" --verbose`

**Comment by ISNIT0** [comment]
Related to the CI tests, and the `keepEmptyParagraphs` issue, this is now fixed

**Comment by kelson42** [comment]
In fact this is not working... but by having a look again, this is because of a "noprint" class.
