### ISSUE TITLE
Code Style Guide

### ISSUE THREAD

**Issue by ISNIT0** [openzim/mwoffliner#383]
After speaking with @kelson42 and @bradyhunsaker we agreed that this project would benefit from some simple code style rules.

AirBnB has some pretty comprehensive and inoffensive guidelines here: https://github.com/airbnb/javascript

I propose we use the AirBnB guidelines and re-visit if needs be.

# A summary of the AirBnB guidelines:
### Use named function expressions instead of function declarations
```javascript
// This
function add (a, b) {
    return a + b;
}
// Not
const add = function (a, b) {
    return a + b;
}
```

### Use data literals when possible
```javascript
// This
const arr = [];
const obj = {};

// Not
const arr = new Array();
const obj = new Object();
```

Addendum:

### Use appropriate logging level
```javascript
try {
    // ...
} catch (err) {
    // This
    console.error(err);
    // Not
    console.info(err);
}
```

### Log error objects, not stringified errors
```javascript
// This
console.error('Failed to load file:', err);
// Not
console.error('Failed to load file: ' + err);
```

## Code Formatting
We use the default [Visual Studio Code](https://code.visualstudio.com/) formatting rules. These are generally non-offensive and something that most JavaScript developers will be comfortable with.

These will also be enforced by eslint.

(Copied from the VSCode default settings.json file):
```json
{
  "javascript.format.enable": true,
  "javascript.format.insertSpaceAfterCommaDelimiter": true,
  "javascript.format.insertSpaceAfterConstructor": false,
  "javascript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": true,
  "javascript.format.insertSpaceAfterKeywordsInControlFlowStatements": true,
  "javascript.format.insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": false,
  "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": true,
  "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false,
  "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
  "javascript.format.insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": false,
  "javascript.format.insertSpaceAfterSemicolonInForStatements": true,
  "javascript.format.insertSpaceBeforeAndAfterBinaryOperators": true,
  "javascript.format.insertSpaceBeforeFunctionParenthesis": false,
  "javascript.format.placeOpenBraceOnNewLineForControlBlocks": false,
  "javascript.format.placeOpenBraceOnNewLineForFunctions": false
}
```

I'm currently preparing a monster change that will fix many linting errors and formatting normalisation

**Comment by bradyhunsaker** [comment]
Airbnb Style looks good to me.  It appears to be widely used by other organizations and is in fact the first search result for me in a Google search for "javascript style guide", which is evidence of its popularity.

It looks like you are making a separate statement about code formatting, though.  Do I understand that right?  Does the Airbnb style guide not address formatting issues?  They include a link to an Airbnb ESlint configuration.  Shouldn't we be recommending that?

**Comment by ISNIT0** [comment]
Yes, the AirBnB style guide is widely used.

Yes, you're right - I should probably have left out the VSCode bit - they are the same rules :)

In my branch I've brought in the AirBnB eslint file and am working through the errors! 😉

**Comment by kristinn93** [comment]
You might wan't to add prettier with a pre-commit hook while you are at it, [example](https://github.com/gladly-team/tab/pull/352). 
I can also make a PR with this if wanted

**Comment by ISNIT0** [comment]
After moving to TypeScript, we're using the following TSLint options:
```json
{
    "defaultSeverity": "error",
    "extends": [
        "tslint:recommended"
    ],
    "linterOptions": {
        "exclude": []
    },
    "jsRules": {},
    "rules": {
        "quotemark": [
            true,
            "single"
        ],
        "ordered-imports": false,
        "max-line-length": false,
        "no-console": false,
        "no-shadowed-variable": false,
        "only-arrow-functions": false,
        "object-literal-sort-keys": false,
        "space-before-function-paren": false
    },
    "rulesDirectory": []
}
```

Most importantly we're basing this from `tslint:recommended` (https://github.com/palantir/tslint/blob/master/src/configs/recommended.ts).
This is currently in the codebase. Please comment on this issue if you'd like to suggest a change in the future.
