### ISSUE TITLE
Consider switching to TypeScript

### ISSUE THREAD

**Issue by ISNIT0** [openzim/mwoffliner#386]
This somewhat relates to #383 

One of the barriers to entry with the current codebase is that it's pretty monolithic, and it's quite easy to break other things when fixing bugs.

TypeScript is a tool that makes the maintenance and development of large JavaScript applications much easier.

## What is TypeScript and why should we use it?
If you've got 5 minutes: https://stackoverflow.com/questions/12694530/what-is-typescript-and-why-would-i-use-it-in-place-of-javascript
If you've got 10 minutes: https://hackernoon.com/typescript-vs-javascript-b568bc4a4e58
If you've got 50 minutes: https://channel9.msdn.com/posts/Anders-Hejlsberg-Introducing-TypeScript

### Summary of benefits
TypeScript allows us to sprinkle little bits of typing into our code.
This:
- makes it easier for new developers to understand what's going on
- helps IDEs give better intellisense
- catches bugs (related to types) that humans miss

## What it would mean
- adding a build-step (TypeScript -> JavaScript)
- introducing linting (a la #383)
- we commit to this repository (and to NPM) both the source, and a built copy of MWOffliner
- using ES2015+ in our source code

It would also be a good chance to standardise formatting etc.

## Alternatives to TypeScript
- Flow (https://flow.org/)
   As far as I know, Flow is the only other reasonably mature TypeScript competitor.
   I've used it in small amounts, but I believe it's much less used/popular than TypeScript. It's worth looking at comparisons online.

## Proposed plan
1. "Switch to TypeScript" (rename files etc.) but with most checks turned off.
  This allows us to quickly get some benefit without spending lots of time up-front fixing type errors
2. Slowly enable more and more checks in the TypeScript compiler and Linter
3. ...Profit?

I have created a branch which achieves step 1: https://github.com/openzim/mwoffliner/tree/ISNIT0/code-style

What are people's thoughts on moving to TypeScript? Are there better alternatives?

**Comment by subbuss** [comment]
> One of the barriers to entry with the current codebase is that it's pretty monolithic, and it's quite easy to break other things when fixing bugs.

Indeed. That is the precise reason why I started refactoring the codebase and extracting components out of it last year in the Kiwix hackathon and did more work in spurts since then. Reno also contributed to some of that. The end goal was to be able to add unit and integration tests after that was done. But, I / we couldn't finish that work. There are other components that could be extracted from the codebase still.

The hard work of refactoring the codebase into components still needs to be completed. My hunch is that a move to Typescript will be a distraction till that is done.

**Comment by ISNIT0** [comment]
That's a good point, but I think having types in place makes it much easier to extract components without breaking things (having well defined inputs and outputs).

The branch linked has done a bunch of the up-front work (though there will be other humps) and still provides some value without investing any more time in the code itself.

Obviously there will be a startup cost for contributors that haven't worked with TypeScript before.

**Comment by subbuss** [comment]
Since I am not very active on this project, I don't have a strong opinion either way about the use of TypeScript :) but, just wanted to flag the refactoring components piece of it.

**Comment by kelson42** [comment]
Thank you @ISNIT0 for raising up this topic and @subbuss for commenting it so far.

From what I understand:
* Added value of TypeScript is clear and consensual
* Risk of moving too quickly seem to be also relatively consensual
* The real open questions seem to be more when? how? than why?
* It seems also consensual that continuing the refactoring job started by @subbuss and @darkenvy last year is really necessary maybe even the top priority

So on my side my recommendations would be:
* Lets focus on refactoring - beside traditionall bug fixing and feature implementation
* If @ISNIT0 and anybody else wants to push Typescript, they should do it, but we count on them to bring it to the end (at least not making/leaving a mess) without impacting much for example the refactoring effort.
* All of this should happen step-by-step, please try to avoid big merges/commit with thousands of lines
* Transparency about intentions and followed path is really important within the small group of devs of MWoffliner.

**Comment by ISNIT0** [comment]
@kelson42 
This PR: #394 is the minimum required changes to transition to TypeScript.
The changed line count is artificially inflated for a few reasons:
- Quite a few new packages which add many lines to `package-lock.json`
- There are now two copies of each file (src and compiled)
- Files were moved & renamed

I think we loose little from making this change now, and gain:
- refactoring is made easier by types and typechecking
- better ways of expressing code (classes etc.)
- better and more standardised module system (`import` and `export`)

e.g. TypeScript has augmented the refactoring job that @subbuss and @darkenvy started by using the class syntax sugar which simplifies the code further.

During the process of converting to TypeScript, the compiler caught quite a few illegal operations (possible nulls/NaNs/incomplete if-statements)

I personally think the best time is now, so we can enjoy the benefits as soon as possible 😄

**Comment by darkenvy** [comment]
I second this. We recently started using typescript at work for a React
based project. The only downside is that you must transpile your code (I
think this is an upside, but it adds tooling and a higher barrier to entry
for those that may know javascript but not the JS ecosystem).

What is great about Typescript is that the conversion to it is not abrupt.
You can add as little or as much TS as you want.

PS: I still want to reflow the application but hit a snag. I think the
intensence added by TS might actually help a lot.

**Comment by ISNIT0** [comment]
Another benefit of the compilation stage is related to #398. We can target older versions of JavaScript and support older Node for free :)
