### ISSUE TITLE
mwoffliner now requires node 8.12.0 (or something near there)

### ISSUE THREAD

**Issue by bradyhunsaker** [openzim/mwoffliner#398]
package.json indicates node >=7.4.0, if I'm reading it correctly.

But 7.4.0 does not work due to the "async" keyword now being used in one place in lib/mwoffliner.lib.js.

8.12.0 is the latest LTS version and works for me.
I suggest we update package.json to reflect that.

But I'm new to these aspects, so maybe I'm getting it all wrong.  I'm willing to make a PR if I get confirmation that it's reasonable.  But it's also OK with me if someone else just makes the simple change.

**Comment by kelson42** [comment]
@bradyhunsaker Sounds good to me. I see no reason to support more than current + LTS versions of Nodejs. If with do - by luck - then OK, but that would be all.

**Comment by ISNIT0** [comment]
Oops, I thought I'd commented on this already - I'll add some checks for current node version when mwoffliner starts as well and warn if it's not up to the engine spec in `package.json`
