### ISSUE TITLE
Skipped Wikipedia paragraph in "mobile_view"

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#404]
By scrapping https://pt.wikipedia.org/wiki/Hipotiroidismo, I see only the "Referências" paragraph in the ZIM file. For example have a look there http://library.kiwix.org/wikipedia_pt_medicine_2018-09/A/Hipotiroidismo.html

**Comment by ISNIT0** [comment]
The query that MWOffliner makes to the API for mobile views doesn't include the additional information: https://pt.wikipedia.org/api/rest_v1/page/mobile-sections/Hipotiroidismo

I'm not entirely clear as to why we use this particular api rather than Parsoid - do you have any ideas? @kelson42

**Comment by kelson42** [comment]
@ISNIT0 If you think the Wiipedia API does not return the proper information, which seems the case here, then a bug report needs to be open on their side and referenced here. Please open a ticket here https://phabricator.wikimedia.org/project/view/487/ and subscribe me (user:Kelson).

Remark: Wikipedia `rest_v1` API is Parsoid.

**Comment by ISNIT0** [comment]
I created an issue here: https://phabricator.wikimedia.org/T209158

**Comment by kelson42** [comment]
@ISNIT0 As this bug is proven to be a bug related Wikimedia backend, we will have to wait a new release on their side and I do not want to block 1.6 because of this. I'll therefore move it to 1.7 to allow to go ahead with 1.6.

**Comment by ISNIT0** [comment]
This is fixed already by the mediawiki instance using the latest Parsoid and MCS, so this could be closed, I'll leave it open anyway until the above PR is merged
