### ISSUE TITLE
Integrate non-Wikimedia content to Wikimedia zim files

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#405]
In the case of partnerships we should be able to offer customized text and logo from the host organization as a landing page. On Wikimedia projects it is not possible to show logos on non-mainspace wikis:  we should therefore be able to manufacture a landing page on an external wiki, and "connect" it to the regular Wiki content.

**Comment by kelson42** [comment]
Following our short disucssion about a new « Wikipedia for school » ZIM, probably we should think about an option to allow to somehow allow a custom welcome page or pages.

**Comment by kelson42** [comment]
This ticket is pretty old meanwhile, and i don’t think we will anytime allow mwoffliner to scrape multiple wikis in one run (simply too complex to handle).

**Comment by Popolechien** [comment]
@kelson42 Close the issue then?

**Comment by kelson42** [comment]
Yes, sorry for not been clearly able to provide a twchnical solution.
