### ISSUE TITLE
Easy mistake

### ISSUE THREAD

**Issue by findagnar** [openzim/mwoffliner#409]
https://github.com/openzim/mwoffliner/blob/8668dea9ba20d270d00c29652191846e290672a1/lib/mwoffliner.lib.js#L386

Debian GNU/Linux 9 (stretch) 
root@localhost:~# pngquant --strip
pngquant: unrecognized option '--strip'
root@localhost:~# pngquant -V
2.5.0 (June 2015)

Not interesting.

**Comment by ISNIT0** [comment]
Hi @findagnar,
You're referring to a JS file, we've recently moved to TypeScript - could you update your issue to point to the source file (`src/*`) please?

**Comment by findagnar** [comment]
@ISNIT0 It's not a big deal, it's just that there's an error in the command. --strip
I don't know what you're talking about.Sorry.

**Comment by kelson42** [comment]
@findagnar This is a "new" option of pngquant, install a recent version of pngquant.
