### ISSUE TITLE
In articles with a ? in the URL, links to footnotes are not in the right namespace

### ISSUE THREAD

**Issue by mossroy** [openzim/mwoffliner#412]
For example, in wikipedia_fr_all_novid_2018-03.zim, if you search for "? (album de Nena)", and open this article, the cite notes hyperlinks point to namespace I instead of A (and are not working).

Same problem in wikipedia_en_all_novid_2018-06.zim, in the article Boy_or_Girl?.html, the footnote anchor href appears as `../I/Boy_or_Girl%3F.html#cite_note-1` instead of `../A/Boy_or_Girl%3F.html#cite_note-1`

**Comment by kelson42** [comment]
@mossroy This problem has been fixed in 1.9.5
