### ISSUE TITLE
Rename "nodet" to "mini"

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#417]
Nobody knows what nodet means : mini is much easier to grasp and generally speaking should be branded as that part of our portfolio that has zim files 90% smaller than the full ones (ie easy to download)

**Comment by kelson42** [comment]
@Popolechien The question of the overall naming and filenaming seems answered with https://github.com/openzim/zim-requests/issues/129. We have then the question of the tagging which should be handled with https://github.com/openzim/mwoffliner/issues/485

**Comment by Popolechien** [comment]
Yup. Closing the ticket then.
