### ISSUE TITLE
Large blank spaces inserted after images

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#418]
Seen in the Wikimed zim (Medicine novid 2018-10-09) file but I see no reason why it shouldn't be elsewhere: there is a number of article where a large piece of blank space is inserted below images. See screenshots:
Antibiotic sensitivity
![screenshot_20181022-021148](https://user-images.githubusercontent.com/21675885/47287450-8b429a80-d5f2-11e8-843a-a14cd02bef62.png)

Flap (surgery):
![screenshot_20181022-021131](https://user-images.githubusercontent.com/21675885/47287472-a2818800-d5f2-11e8-876c-a17464ddd837.png)

Lumbricals of the hand (#Structure subsection):
![screenshot_20181022-021104](https://user-images.githubusercontent.com/21675885/47287506-ba590c00-d5f2-11e8-8ba1-c749fb24b972.png)

**Comment by kelson42** [comment]
@ISNIT0 Do you have an explanation why we need to specify this manually? The CSS coming from Wikipedia should be proper IMO! Why it is not?
