### ISSUE TITLE
Implement review system before adding new zim files to library

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#422]
I'm looking at http://library.kiwix.org/granbluefantasy_en_all_all_nopic_2018-10/ (the last release of Granblue fantasy wiki) and it is obvious that a bunch of things are broken, rendering the file unusable and a waste of data/download time for users. 
It seems to be a rather recent addition to the library, so can we think of some simple confirm/vetting process (a.k.a. Quality control) before adding new zims?

**Comment by kelson42** [comment]
This issue was moved to openzim/zimfarm#58
