### ISSUE TITLE
Add information about TypeScript to README.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by ISNIT0** [openzim/mwoffliner#423]
@bradyhunsaker

**Comment by bradyhunsaker** [comment]
As a start, we need to know which files are generated automatically and which files to edit instead.
Plus how/whether to generate them as part of a pull request.

I think it is:
- Don't edit lib/ files, edit src/ instead.
- But I'm not sure the correct way to generate the lib/ files.

I'm not certain about other .js files, like in bin/ and res/ and index.js.  I think they do not have .ts counterparts and so are still correct to edit directly.

**Comment by ISNIT0** [comment]
Edit
- `src/**` files
- `bin/**` files

To generate `lib/**` files from `src/**` files, run `./build.sh`.

To watch `src/**` files and rebuild automatically, run `./watch.sh`

Would you like to add this to the README?

**Comment by bradyhunsaker** [comment]
Yes, but I guess it should wait for your pending README PR?

**Comment by ISNIT0** [comment]
@bradyhunsaker I've merged that PR, please do go ahead and add those bits 👍

**Comment by kelson42** [comment]
@ISNIT0 @bradyhunsaker What is the status on this? We are preparing the release of 1.8, which is the second release with typescript. This should be ready for 1.8 IMO.
