### ISSUE TITLE
Multi-threaded scraping

### ISSUE THREAD

**Issue by ISNIT0** [openzim/mwoffliner#429]
There are various tools/libraries that make muti-threaded NodeJS possible ([node-webworker-threads](https://github.com/audreyt/node-webworker-threads) comes to mind).

It would be nice to specify the number of threads to run MWOffliner with. This _might_ improve the speed of scraping.

**Comment by ISNIT0** [comment]
I'm not sure it's necessary, but it's worth having a ticket to discuss this in.

**Comment by kelson42** [comment]
I really don't think we should do that. We should optimize the process with less CPU usage and better asynchronous mgmt... but not make multithreading, this will make the whole far more complex for the benefit brought.
