### ISSUE TITLE
Project Gutenberg ZIMs are barely accessible for clients that do not support JavaScript in the ZIM

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#445]
I am not sure if mwoffliner is used to produce Project Gutenberg ZIMs, or some other scraping system, so feel free to move this issue if it is not related to mwoffliner.

Recent Project Gutenberg ZIMs now come with a proprietary interface that requires the ability to execute JavaScript in the ZIM to access any of the texts in a meaningful way. Although texts are still accessible by title in the ZIM index, not enough information is provided to recognize a text by title unless it is very famous ("Don Quijote" is OK...). Books should be listed in the ZIM index by author surname. An entry should look something like:

`Cervantes Saavedra, Miguel de - Don Quijote`

Currently all we have is `Don Quijote`. If the text is `Novelas y cuentos`, there is no way to tell who it's by unless I open it. This is the case at least for `gutenberg_es_all_2018-10.zim`.

Authors are listed in the index of this ZIM, but alphabetically by first name, which is not very useful. To find "Unamuno" I have to know his first name was "Miguel". However, there is no corresponding author page for Miguel de Unamuno in the ZIM, and the client tries to open a "page" that has to be rendered dynamically in JavaScript, which of course fails in a client that cannot run JavaScript in the ZIM.

**So, is it possible to have a more meaningful and usable ZIM index for these files?** Ideally, we should also have `noscript` versions of author pages rather than relying on dynamic construction of them.

It would be a shame to lock out users on low-end devices. Currently, no Kiwix JS version running in an extension (Chrome or Firefox), for example, or Kiwix JS UWP, can  run JS in the ZIM. We have support for JS in the ZIM only for clients that can run from a localhost or other server (not from the file protocol) in Kiwix JS in Service Worker mode, so it is currently very restricted. And it looks very difficult to support JS in the ZIM with mainstream file:// protocol access in Kiwix JS. JavaScript that constructs dynamic pages would need to be patched somehow to hook into the extraction engine, and most (all mainstream) browsers do not support `XMLHttpRequests`  when running from the file:// protocol.

**Comment by kelson42** [comment]
This issue was moved to openzim/gutenberg#75
