### ISSUE TITLE
ZIM file of InstallGentoo Wiki

### ISSUE THREAD

**Issue by icsoa** [openzim/mwoffliner#45]
https://wiki.installgentoo.com/index.php/Main_Page

**Comment by kelson42** [comment]
@icsoa This would be easy if the Mediawiki would provide the Parsoid/VisualEditor API backend https://www.mediawiki.org/wiki/VisualEditor

**Comment by kelson42** [comment]
@icsoa Done https://download.kiwix.org/zim/other/installgentoo_en_all_2018-01.zim, will be updated one time a month. Would be great if you can advert it a bit.

**Comment by kelson42** [comment]
We had to stop to do so because the API as been disabled.
