### ISSUE TITLE
Wikipedia descargable sin imágenes 

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#455]
_From @DaviidPaez on December 5, 2018 17:32_

Pues apenas soy un usuario principiante y viéndola por un tiempo, menor de un mes, me di cuenta que las imágenes eran necesarias, pero no vi una opción de descarga para estas :( 
Y mi opinión es que sería muy util tener una opción en las páginas que diga "Descargar imágenes para esta página (si están disponibles)" pero no sé si haya algo similar o si lo estén pensando para proyectos futuros.

_Copied from original issue: kiwix/overview#11_

**Comment by Popolechien** [comment]
_From @kelson42 on December 6, 2018 6:27_

@Popolechien No clue about what is this ticket, but probably at the wrong place.

**Comment by Popolechien** [comment]
He says that he did not understand the different files, ended up with the nopic version and would like us to be clearer about what is with/without images. Very much related to what I flagged in [#190](https://github.com/openzim/mwoffliner/issues/190)

**Comment by Popolechien** [comment]
_From @kelson42 on December 6, 2018 6:48_

@Popolechien thx

**Comment by Popolechien** [comment]
Hola @DaviidPaez los imagenes se encuentran en los archivos que se llaman "_all" o "_novid". Los que son sin imagenes son los "_nopic". Pero tienes razon que debemos hacerlo mas facil de entender.

**Comment by Jaifroid** [comment]
@Popolechien is right that the user has perhaps not understood the difference between nopic ZIMs and versions with images. However, this user is also asking for an option in the client to download the images for the nopic article he is reading. Full translation:

> I'm just a beginner, but after having used this for some time (less than a month) I realized that images are necessary, but I can't see an option to download them :( . I think it would be really useful to have an option on each page: "Download images for this page (if available)". I don't know if you have something like this or are planning it for future versions.

So, this would be a hybrid offline/online solution. You have a fully functional offline version with no pictures, that fits on your phone, but when you do have connectivity, you could optionally grab the pictures from the corresponding online Wikipedia page, if they are still available. (This kind of functionality would have to be provided in the client, it's not really a ZIM issue.)

**Comment by kelson42** [comment]
@Popolechien There is a ticket somewhere about that feature. We can not deal with that for now. The effort to have same URL path that @ISNIT0 is doing is anyway a prerequisite for that.
