### ISSUE TITLE
What is "--mcsUrl" for

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#479]
What is the typical use case for a Wikipedia or an other Wikipedia. Example welcome. I ask, because to me it should IMO just work - so not needing a special parameter!

**Comment by ISNIT0** [comment]
I added it just to keep parity with `--parsoidUrl` in case it was needed. I guess it would be needed in the same cases.

**Comment by ISNIT0** [comment]
@kelson42 Can we close this issue?

**Comment by kelson42** [comment]
@ISNIT0 I think we need the `--parsoidUrl` because otherwise we rely on the visual editor API which might not be installed... This is a bit an edge case (parsoid but not VE), but this happened in the past. Do we have this kind of use case for MCS? In which use case this option would concretely be needed?

**Comment by kelson42** [comment]
@ISNIT0 Could you please remove the option if we do not have a concrete usecase of it?

**Comment by ISNIT0** [comment]
`--parsoidUrl` has been removed. We no longer use Parsoid directly. We only use MCS.

- Some sites have their own MCS (Wikipedia etc.), some don't.
- Some sites may host their MCS at a different url/path.

I'm happy to remove it, and will do so today
