### ISSUE TITLE
mwoffliner still fail to retrieve online content properly

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#488]
```
$ mwoffliner --verbose --articleList="https://download.kiwix.org/wp1/enwiki/tops/100" --customZimFavicon="https://cdn6.aptoide.com/imgs/a/6/c/a6ce175a6230fa6921300d3f742d1ace_icon.png" --withZimFullTextIndex --adminEmail="kelson@kiwix.org" --mwUrl="https://en.wikipedia.org/"
[warn] [2019-01-08T12:44:27.248Z] ***********

	Current node version is [v8.11.3]. We recommend [>=8.12.0]

***********
[log] [2019-01-08T12:44:27.290Z] Downloading article list from [https://download.kiwix.org/wp1/enwiki/tops/100] to [tmp/articleList]
[error] [2019-01-08T12:44:27.592Z] Failed to read articleList from [tmp/articleList] { Error: ENOENT: no such file or directory, open 'tmp/articleList'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:2091:75)
    at step (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:35:23)
    at Object.next (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:16:53)
    at fulfilled (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:7:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'tmp/articleList' }
Failed to run mwoffliner after [0s]: {
	"stack": "Error: ENOENT: no such file or directory, open 'tmp/articleList'\n    at Object.fs.openSync (fs.js:646:18)\n    at Object.fs.readFileSync (fs.js:551:33)\n    at Object.<anonymous> (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:2091:75)\n    at step (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:35:23)\n    at Object.next (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:16:53)\n    at fulfilled (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:7:58)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)",
	"message": "ENOENT: no such file or directory, open 'tmp/articleList'",
	"errno": -2,
	"code": "ENOENT",
	"syscall": "open",
	"path": "tmp/articleList"
}
```

**Comment by ISNIT0** [comment]
Odd, I can't reproduce this locally. I'll look into it more later. Have you definitely updated?

**Comment by kelson42** [comment]
@ISNIT0 Maybe a problem with relative/abslute path? I wonder about `[tmp/articleList]`... it should not be `[/tmp/articleList]`?

**Comment by ISNIT0** [comment]
@kelson42 It's supposed to be relative, storing in the generated `tmp` directory

**Comment by kelson42** [comment]
@ISNIT0 Two other minor bugs:
* You might also create a subdirectory with a random name to `tmp`... otherwise if you have two `mwoffliner` running on the same directory they will write and overwrite the file.
* An other point is that the name of the file should be kept, because it has an impact in the final ZIM file name (at least for the `--articleList` option).

**Comment by ISNIT0** [comment]
@kelson42 Looking at the code, I'm using `zim.tmpDirectory` to decide where to put the `articleList` file. I think it's best we put the downloaded files inside the MWOffliner directory?

**Comment by kelson42** [comment]
@ISNIT0 What is the `mwoffliner` directory? Why?

**Comment by ISNIT0** [comment]
@kelson42 I mean the `node_modules/mwoffliner` directory. I've started working on this and changed my mind now.
I'm creating a timestamped mwoffliner tmp directory in the user's working dir which we download the article list to.

**Comment by kelson42** [comment]
@kelson42 OK, "yes" this was a bad idea. How is the current dir better than `zim.tmpDirectory` ?

**Comment by ISNIT0** [comment]
The `zim.tmpDirectory` is what we are currently using, it doesn't work!

**Comment by kelson42** [comment]
@ISNIT0 OK but why? Any fondamental problem? To me this is just a bug, this does not proove the approach is wrong!

**Comment by ISNIT0** [comment]
@kelson42 I don't know how `zim.tmpDirectory` is expected to behave, but I believe this is expected behaviour.

**Comment by kelson42** [comment]
@ISNIT0 Please secure that things happen in `zim.tmpDirectory` following these instructions: https://github.com/openzim/mwoffliner/issues/488#issuecomment-452341935. This is how things should behave, and so far it's not.

**Comment by ISNIT0** [comment]
I'm now successfully able to run the above command:
![image](https://user-images.githubusercontent.com/5173131/51170058-c11fb400-18ad-11e9-90c3-30fd9dab1afa.png)
