### ISSUE TITLE
Remove "--localMcs" option (replace by autodetection)

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#490]
and what is its relationship to Parsoid?

**Comment by ISNIT0** [comment]
See https://github.com/openzim/mwoffliner/pull/467

MCS depends on Parsoid.

**Comment by kelson42** [comment]
@ISNIT0 But why having removed `--localParosoid` if this basically to replace it with `--localMcs`? The goal of removing `--localParsoid` (I don't find anymore in which ticket this was discussed) was to start local parsoid/mcs only if necessary and automotically - so the option becomes useless.

**Comment by ISNIT0** [comment]
@kelson42 I don't know what you mean about removing `--localParsoid`, I don't remember being involved in that conversation.

In #467 I say:
> I've removed the options --localParsoid and --parsoidUrl in favour of --localMcs and --mcsUrl.

This is because Parsoid would be started when MCS is started anyway.
We have now removed `--mcsUrl`, so the only way to control behaviour of MCS is with the `--localMcs` flag.

**Comment by kelson42** [comment]
@ISNIT0 OK, I understand/remember better now. Would that be possible, to just detect if MCS is available online and just start it locally if necessary?

**Comment by ISNIT0** [comment]
Possible, yes. Let's add it to 1.8?

**Comment by kelson42** [comment]
@ISNIT0 Thx for the explanation and proposal, that would be great yes.

**Comment by berndsi** [comment]
Hi, just noticed this from a bug report against MCS. I wouldn't add a dependency to MCS at this point unless you are in a rush. We're actually in the process of implementing its successor, called [Page Content Service](https://www.mediawiki.org/wiki/Page_Content_Service). It's not quite ready at this time but it would also be based on Parsoid HTML.

**Comment by ISNIT0** [comment]
@kelson42 Do you think it would be sensible to just always use a local version of MCS/Parsoid? It would mean MWOffliner would have control over the version etc. and wouldn't be caught out by old instances

**Comment by kelson42** [comment]
> Hi, just noticed this from a bug report against MCS. I wouldn't add a dependency to MCS at this point unless you are in a rush. We're actually in the process of implementing its successor, called [Page Content Service](https://www.mediawiki.org/wiki/Page_Content_Service). It's not quite ready at this time but it would also be based on Parsoid HTML.

@berndsi thx for the info. What is the timeline for a version ready for us to integrate? What would be the advantage versus Parsoid+MCS like we have currently?

**Comment by kelson42** [comment]
@ISNIT0 No, because we need to save cpu/memory resources on our end. So, we should launch MCS only if this is not available on the remote end.

**Comment by kelson42** [comment]
@berndsi thx
