### ISSUE TITLE
No images are downloaded

### ISSUE THREAD

**Issue by itcotta** [openzim/mwoffliner#497]
Hey, I'm successfully being able to fetch all the text and structure of my wiki but the images aren't being fetched for some reason, while the dump is ongoing i see this:

`Unable to download content [1] http://mywiki/wiki/images/1/1a/myimage.png (response code: 406).
Absolutely unable to retrieve async. URL: Unable to download content [3] http://mywiki/wiki/images/1/1a/myimage.png
(response code: 406).
Caching myimage.png at /home/cac/10_en/m/aa19639737c392225811.png...
`
I'm running these arguments:
`mwoffliner --mwApiPath=wiki/api.php --mwUrl=http://mywiki.com --adminEmail=foo@bar.net --outputDirectory=/home/ --verbose --tmpDirectory=/dev/shm/ --keepHtml`

There is actually an image stored in that url when i manually attempt to check if its valid, but for some reason i get this response code. If i check the cached image it's actually 0 bytes. Any ideas on what could be causing this?

**Comment by kelson42** [comment]
@itcotta Which version of `mwoffliner` do you use?

**Comment by itcotta** [comment]
@kelson42 I'm running the docker version. I started my docker container from the docker-compose located in the git repo (after cloning the git repo to my disk).

`docker-compose --file   C:\Users\morish\Downloads\mwoffliner-master\docker\docker-compose.yml run mwoffliner`

**Comment by kelson42** [comment]
@itcotta OK, it's the first time I see this kind of problem. A dump at the HTTP server level would probably allow to identify what is different between your manual test request and mwoffliner. So far I know the `mwoffliner` do not do anything special.

**Comment by ISNIT0** [comment]
I think this might be specific to the Wiki, without any more information I can't do anything about this.
MWOffliner just downloads images using normal HTTP requests, so possibly the Wiki is limiting certain user-agents (HTTP 406)

**Comment by kelson42** [comment]
@itcotta You should give more infomration about `http://mywiki/wiki/images/1/1a/myimage.png` and the HTTP 406 error code. That looks strange. Is that the right path where the file is available? why 406?

**Comment by ISNIT0** [comment]
Closing this because I don't have enough information to investigate further
Please re-open if there is more info you can give @itcotta
