### ISSUE TITLE
ZIM file creation for local wiki gets repeated retrieval error

### ISSUE THREAD

**Issue by p-deli** [openzim/mwoffliner#499]
Issuing following command `mwoffliner --mwUrl=http://192.168.56.5/UnifiedICTDoc --adminEmail=foo@bar.net --verbose --redis=redis://127.0.0.1:6379 --mwWikiPath=/ --mwApiPath=api.php` leads to repeated `Getting…`, followed by `Downloading`, then `Caching`, and finally `Error by retrieving article…` as shown below (please note that this error might be linked to another problem mentioned in a [separate issue](https://github.com/openzim/mwoffliner/issues/500) as both errors originate from the same command):

```
Getting (desktop) article from http://192.168.56.5/UnifiedICTDoc/api.php?action=visualeditor&format=json&paction=parse&page=IT&oldid=69
Downloading http://192.168.56.5/UnifiedICTDoc/api.php?action=visualeditor&format=json&paction=parse&page=IT&oldid=69...
Caching http://192.168.56.5/UnifiedICTDoc/api.php?action=visualeditor&format=json&paction=parse&page=IT&oldid=69 at /home/pit/Downloads/cac/192_en/6a89ec3991120c028d52...
Error by retrieving article: Unrecognized value for parameter "action": visualeditor.
```

----

- mwoffliner version 1.6.0
- Ubuntu release 18.10 (cosmic, desktop edition)
- `redis-server --version`: Redis server v=4.0.11 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=fc908f68b3e66abd

**Comment by kelson42** [comment]
@p-deli Do you have both Parsoid/Visualeditor working properly on your wiki? If not, please use the option `--localParsoid`

**Comment by p-deli** [comment]
> @p-deli Do you have both Parsoid/Visualeditor working properly on your wiki? If not, please use the option `--localParsoid`

@kelson42 . Thanks for the tip. Adding the argument `--localParsoid` worked. The ZIM file has been created. However, many pages of the wiki are missing. Any ideas?

**Comment by kelson42** [comment]
@p-deli in which namespace(s) are these pages?

**Comment by p-deli** [comment]
> @p-deli in which namespace(s) are these pages?

Everything is in (Main). But by adding the argument ` --keepEmptyParagraphs` everything seems to be there.

The only apparent issue I see now is that the automatic Figure and Table numbering and references thereof (extension [CrossReference](https://www.mediawiki.org/wiki/Extension:CrossReference)) do not work: all figures and tables have the number 1 and the inline references show 3 question marks (`???`).

**Comment by kelson42** [comment]
@p-deli Yes, probably this is not properly supported by Parsoid. I recommend to open a bug at https://phabricator.wikimedia.org/

**Comment by p-deli** [comment]
@kelson42 as suggested I opened a query at Phabricator ([mwoffliner ZIM file: All figure and table numbers set to 1 and references have "???" for extension "CrossReference"](https://phabricator.wikimedia.org/T214475)) and this is the answer I got:

> The extension probably uses some page-global state. Parsoid doesn't support that and is unlikely to support that ever. This will require a Parsoid-native implementation to be supported. But, given that Parsoid is currently being ported from JS to PHP, probably best to wait till that happens.

**Comment by p-deli** [comment]
There is another similar issue and I don't if I should be filing an issue here. That is why I allow myself to first as the question expose the problem in this thread:

- I encounter the same type of problem with extension [SimpleMatJax](https://www.mediawiki.org/wiki/Extension:SimpleMathJax) as with [CrossReference](https://www.mediawiki.org/wiki/Extension:CrossReference). In the rendered ZIM file, when opened with Kiwix (macOS and iOS versions), the math tags are shown (although with brackets instead of the usual <code><></code>) with the code in it (e.g., [math]\leftarrow[/math]), instead of the desired rendition (in this case a left arrow).

Where is it suggested to post the issue…?

**Comment by kelson42** [comment]
@p-deli I this many of these error won't happen with version 1.9.4 we have released yesterday. I would really like to hear back from you still get so many errors like before.

**Comment by kelson42** [comment]
Nonfeedback, so I guess the problem is fixed. Ticket should be reopen if not.
