### ISSUE TITLE
Remove --writeHtmlRedirects option

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#506]
I do not see any added value anymore to that option.

**Comment by kelson42** [comment]
@ISNIT0 If I remember/understand correctly, `--writeHtmlRedirects` writes the Mediawiki redirects as plain HTML redirect files. If not set, is uses the TSV file with redirects. I do not see the added value of the first alternative. IMO we could alway use the TSV file. Do you agree? Do you see any feature regression if we do so?

**Comment by ISNIT0** [comment]
This makes sense to me, I'll implement it now
