### ISSUE TITLE
repo two Bug

### ISSUE THREAD

**Issue by findagnar** [openzim/mwoffliner#516]
see image.
七堵一交通流
七坊镇
![screenshot_2019-01-05-08-26-46-398_io neoterm](https://user-images.githubusercontent.com/16982413/51113121-ed9ae800-183b-11e9-80a0-f6d4c76c502b.png)
![screenshot_2019-01-05-08-30-48-660_io neoterm](https://user-images.githubusercontent.com/16982413/51113137-fd1a3100-183b-11e9-9d28-ba8cce9e43c1.png)
![screenshot_2019-01-06-17-22-15-568_io neoterm](https://user-images.githubusercontent.com/16982413/51113140-01dee500-183c-11e9-9f27-7ddbe2934583.png)
![screenshot_2019-01-11-10-37-44-904_io neoterm](https://user-images.githubusercontent.com/16982413/51113158-0e633d80-183c-11e9-8960-6f48b0ab55d8.png)

**Comment by kelson42** [comment]
@findagnar Please put your command line and error as text. Otherwise I don't understand exactly what is the problem? Or do you report many problems?

**Comment by findagnar** [comment]
Here are two error.
The first error is that Chinese is converted to sixteen digits. The resulting HTTP get is very large.
The second error is due to an attempt to download articles that do not exist.

commit e461dcc3d1c4989c05714185351a89aee9a39e3b (HEAD -> master, origin/master, origin/HEAD)
Merge: b6ff8db 57e824c
Author: Kelson <kelson@kiwix.org>
Date:   Sun Jan 13 14:41:03 2019 +0100

mwoffliner --mwUrl=https://zh.wikipedia.org/ --adminEmail=**** --keepHtml --minifyHtml --speed=4 --format=novid,nopdf

这里有两个错误。
第一个错误是因为，中文转换为十六位。导致的http get非常大。
第二个错误，是因为它试图在下载不存在文章而导致的错误。

**Comment by ISNIT0** [comment]
I think this is linked to something I observed here: https://github.com/openzim/mwoffliner/issues/388
While the API documentation says it can serve up to 500 redirect requests in one URL, there are problems parsing longer URLs.
I will look into what the length constraint is, but for now I will also reduce the number of redirects we fetch per request

**Comment by ISNIT0** [comment]
@kelson42 I've built a fix for this which constructs many URLs instead of one, with the aim of keeping request urls to under 7000 characters long. PR pending...
