### ISSUE TITLE
Temporary redirect has the bad name

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#517]
I run
```
mwoffliner --verbose --adminEmail="kelson@kiwix.org" --mwUrl=https://bm.wikipedia.org/ --keepHtml
```

and I see
```
[log] [2019-01-14T18:09:49.806Z] Building ZIM file /tmp/out/wikipedia_bm_all_2019-01.zim (zimwriterfs --welcome=index.htm --favicon=favicon.png --language=bam --welcome=Nyɛ_fɔlɔ.html --verbose  --tags="wikipedia" --name="kiwix.wikipedia_bm_all" --redirects="tmp/mwo-dump-1547489341907/wikipedia_en_all.redirects" --title="Wikipedia" --description="Wikipedia, ɔnsikopedi hɔrɔn ka nyɛ" --creator="Wikipedia" --publisher="Kiwix" "/tmp/tmp/wikipedia_bm_all_2019-01/" "/tmp/out/wikipedia_bm_all_2019-01.zim")...
```

It should be:
```
--redirects="tmp/mwo-dump-1547489341907/wikipedia_en_all.redirects"
```

The redirect name should ideally have the same name like the directory where the temporary files are, here: `wikipedia_bm_all_2019-01.redirects`

**Comment by ISNIT0** [comment]
Do you think this is particularly important? This file will be removed in 1.8 anyway

**Comment by kelson42** [comment]
@ISNIT0 This is not the most important thing, but this is wrong an clearly misleading. It is important that the name is the proper one. At least to help me verify everything works fine.I would prefer to have things done properly.
