### ISSUE TITLE
Translation of the footer in French fails

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#519]
From a ZIM file made with:
```
mwoffliner --verbose --articleList="https://download.kiwix.org/wp1/frwiki/tops/100" --withZimFullTextIndex --adminEmail="kelson@kiwix.org" --mwUrl="https://fr.wikipedia.org/"
```

I got the following footer:
![fireshot](https://user-images.githubusercontent.com/1029718/51134012-b1b15400-1836-11e9-8fe4-c1ffd37620fe.png)

**Comment by ISNIT0** [comment]
Now working: 
![image](https://user-images.githubusercontent.com/5173131/51168894-d0e9c900-18aa-11e9-8877-1d63769a2a1f.png)

This was scraped using the same command as above with the latest master code
