### ISSUE TITLE
Try to reduce jpg size use new Google Guetzi

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#53]
Source code of guetzi is here:
https://github.com/google/guetzli

Probably in addition of jpegoptim.

We need to find the best combination

**Comment by kelson42** [comment]
@darkenvy Would you volunteer to have a look to this?

**Comment by darkenvy** [comment]
This is right up my alley. I'm on it!

-Reno



[image: --]
*Reno McKenzie*
[image: https://]
http://RenoMcKenzie.com/
<http://renomckenzie.com/>
Reno@RenoMcKenzie.com

US Tel: +1.727.612.5919
<https://dl.dropboxusercontent.com/u/41544972/RenoMcKenzie-2016r1-Contact.vcf>

**Comment by kelson42** [comment]
Result of investigation:
* guetzli is not more efficient in size reduction (at the same level of compression) than jpegoptim
* guetzli with the level 84 might be used on the top of jpegoptim compression with a gain of 20%
* guetzli might be also used with 84 level of compression on png (so replace png with jpeg) without visual impact (no numbers about size optimisation, but this might be significant).

Using guetzli is CPU/memory intensive, this should be use with cautious.

I recommend the implementation as an option first.
