### ISSUE TITLE
Should give a nicer error when we can't connect to Redis

### ISSUE THREAD

**Issue by ISNIT0** [openzim/mwoffliner#531]
See #530

**Comment by kelson42** [comment]
@ISNIT0 Agree, no scenario should lead to an unmanaged stop/fail.

**Comment by vaibhavmatta** [comment]
May I start working on this issue if anyone else is not?

**Comment by kelson42** [comment]
@vaibhavmatta Yes, would be really welcome.

**Comment by Fontirroig** [comment]
Hello, I like to help with this issue, I created a pull request
