### ISSUE TITLE
Rational Wiki is horrible dis-info

### ISSUE THREAD

**Issue by okkebal** [openzim/mwoffliner#532]
Please check this out:
https://rationalwiki.org/wiki/Donald_Trump

"is an American (un)intentional comedian"

This whole article is just smear, name-calling and horribly rude. I do not understand why anyone would like to spread terrible dis-info like this. 

Or this: "Michael T. Snyder is a hopelessly deluded Christian evangelist crank who has started numerous blogs"

How is this informational? It just very low name-calling and slander.

Please remove this terrible Zim from your servers! 

If you would like to include REAL open discussion please add the discussion pages to wikipedia's ZIM.

**Comment by Popolechien** [comment]
Hi there,
thanks for sharing this but at the end of the day it probably would make more sense to share your concerns with the owners of rationalwiki or psiram: issues on github are for technical discussions.

**Comment by okkebal** [comment]
If these people write such an immoral and irrational page about president Trump do you really think you can argue with people like that? Its obiously run by extreme left wing nutcases.

My issues is that the site is being promoted and made available here.  It appears only left-wing over the top crazy sites get a spot here while there is no effort to convert something like www.conservapedia.com to a ZIM.

**Comment by ISNIT0** [comment]
@okkebal Please make a request here: https://github.com/openzim/zim-requests/issues
There is a formal process for requesting ZIM files, they take a lot of resources to create and update 😄
