### ISSUE TITLE
Can mwoffliner generate files of multiple version of the same site in one scrape?

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#536]
I have a question. If I run mwoffliner with `--format=nopic --format=novid` in the command, does mwoffliner scrap the site once and generate two zim file? Or does it scrap the site twice?

From what I have observed, it seems to be scraping the site twice. If that is true, why don't the offliner scrape the site once, cache data, and generate different zim file flavors?

**Comment by kelson42** [comment]
@automactic With 1.6-, we had always a cache, now it is optional with option `--useCache`. If you use `--useCache` it should work like with 1.6.

**Comment by automactic** [comment]
@kelson42 Thanks!

Follow up: do we have a size estimate on the cache in relation to the final zim file size? For example, if the generated zim file is a 1GB nopic, how much disk space is the cache use?

**Comment by kelson42** [comment]
@automactic makes zim size x10 for the cache (text only)

**Comment by automactic** [comment]
@kelson42 We need to estimate the disk size requirement for the extra large zim files, namely wikipedia_en
