### ISSUE TITLE
Impossible to scrape dragonage.fandom.com: Cannot read property 'size'

### ISSUE THREAD

**Issue by shikulja** [openzim/mwoffliner#537]
try new version, on two computers the same error
Is there something wrong?

`sudo mwoffliner --mwUrl=https://dragonage.fandom.com/ --adminEmail=test@gmail.com --format=zim --mwApiPath=/api.php --redis=redis://127.0.0.1:6379 --customZimFavicon=/home/shikulja/dump/Forum_book.ico --withZimFullTextIndex --localMcs --writeHtmlRedirects --verbose
`

`[info] [2019-01-30T21:33:02.767Z] Downloading https://slot1-images.wikia.nocookie.net/extensions/wikia/EmbeddableDiscussions/images/social/wykop-active.svg at /home/shikulja/tmp/dragonage_en_all_2019-01/s/wykop-active.svg...
[info] [2019-01-30T21:33:02.767Z] Downloading [https://slot1-images.wikia.nocookie.net/extensions/wikia/EmbeddableDiscussions/images/social/wykop-active.svg]
[info] [2019-01-30T21:33:03.028Z] Downloading https://slot1-images.wikia.nocookie.net/extensions/wikia/EmbeddableDiscussions/images/icon-avatar.svg at /home/shikulja/tmp/dragonage_en_all_2019-01/s/icon-avatar.svg...
[info] [2019-01-30T21:33:03.028Z] Downloading [https://slot1-images.wikia.nocookie.net/extensions/wikia/EmbeddableDiscussions/images/icon-avatar.svg]
[info] [2019-01-30T21:33:03.163Z] Downloading https://slot1-images.wikia.nocookie.net/extensions/wikia/EmbeddableDiscussions/images/plus-x-large.svg at /home/shikulja/tmp/dragonage_en_all_2019-01/s/plus-x-large.svg...
[info] [2019-01-30T21:33:03.163Z] Downloading [https://slot1-images.wikia.nocookie.net/extensions/wikia/EmbeddableDiscussions/images/plus-x-large.svg]
[log] [2019-01-30T21:33:03.693Z] Saving favicon.png...
{"name":"mwoffliner","hostname":"ubuntu","pid":17574,"level":60,"err":{"message":"","name":"TypeError","stack":"TypeError: Cannot read property 'size' of undefined\n    at /usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:1655:89\n    at FSReqCallback.oncomplete (fs.js:159:21)","levelPath":"fatal/service-runner/unhandled"},"msg":"Cannot read property 'size' of undefined","time":"2019-01-30T21:33:03.707Z","v":0}
{"name":"mwoffliner","hostname":"ubuntu","pid":17574,"level":60,"levelPath":"fatal/service-runner/unhandled","msg":"Cannot read property 'size' of undefined","time":"2019-01-30T21:33:03.708Z","v":0}
[log] [2019-01-30T21:33:03.809Z] Deleting tmp dump dir [/home/shikulja/tmp/mwo-dump-1548883929982]
`

**Comment by kelson42** [comment]
I confirm the problem with a slightly simpler example:
```
mwoffliner --mwUrl=https://dragonage.fandom.com/ --adminEmail=kelson@kiwix.org --mwApiPath=/api.php --withZimFullTextIndex --localMcs --customZimFavicon=favicon.png --verbose
```

After around 2 minutes I get:
```
[info] [2019-02-01T11:12:26.356Z] Downloading [https://slot1-images.wikia.nocookie.net/extensions/wikia/EmbeddableDiscussions/images/social/wykop-active.svg]
[info] [2019-02-01T11:12:26.410Z] Downloading https://slot1-images.wikia.nocookie.net/extensions/wikia/EmbeddableDiscussions/images/icon-avatar.svg at /tmp/tmp/dragonage_en_all_2019-02/s/icon-avatar.svg...
[info] [2019-02-01T11:12:26.410Z] Downloading [https://slot1-images.wikia.nocookie.net/extensions/wikia/EmbeddableDiscussions/images/icon-avatar.svg]
[info] [2019-02-01T11:12:26.474Z] Downloading https://slot1-images.wikia.nocookie.net/extensions/wikia/EmbeddableDiscussions/images/plus-x-large.svg at /tmp/tmp/dragonage_en_all_2019-02/s/plus-x-large.svg...
[info] [2019-02-01T11:12:26.474Z] Downloading [https://slot1-images.wikia.nocookie.net/extensions/wikia/EmbeddableDiscussions/images/plus-x-large.svg]
[error] [2019-02-01T11:12:29.363Z] Absolutely unable to retrieve async. URL: https://images.wikia.nocookie.net/dragonage/images/a/a7/Morrigan-opacity10.jpg
[error] [2019-02-01T11:12:30.339Z] Absolutely unable to retrieve async. URL: https://images.wikia.nocookie.net/dragonage/images/4/4d/Dragon-opacity10.jpg
[log] [2019-02-01T11:12:30.340Z] Saving favicon.png...
{"name":"mwoffliner","hostname":"rhys","pid":17032,"level":60,"err":{"message":"","name":"TypeError","stack":"TypeError: Cannot read property 'size' of undefined\n    at /usr/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:1655:89\n    at FSReqWrap.oncomplete (fs.js:154:21)","levelPath":"fatal/service-runner/unhandled"},"msg":"Cannot read property 'size' of undefined","time":"2019-02-01T11:12:30.357Z","v":0}
{"name":"mwoffliner","hostname":"rhys","pid":17032,"level":60,"levelPath":"fatal/service-runner/unhandled","msg":"Cannot read property 'size' of undefined","time":"2019-02-01T11:12:30.358Z","v":0}
[log] [2019-02-01T11:12:30.458Z] Deleting tmp dump dir [/tmp/tmp/mwo-dump-1549019530391]
```

@ISNIT0 Any ideas?

**Comment by shikulja** [comment]
maybe help

`shikulja@ubuntu:~$ sudo systemctl status redis
● redis-server.service - Advanced key-value store
   Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor pre
   Active: active (running) since Wed 2019-01-30 23:42:47 MSK; 1 day 15h ago
     Docs: http://redis.io/documentation,
           man:redis-server(1)
 Main PID: 2004 (redis-server)
    Tasks: 4 (limit: 7146)
   Memory: 41.0M
   CGroup: /system.slice/redis-server.service
           └─2004 /usr/bin/redis-server 127.0.0.1:6379

янв 30 23:42:47 ubuntu systemd[1]: Starting Advanced key-value store...
янв 30 23:42:47 ubuntu systemd[1]: redis-server.service: Can't open PID file /ru
янв 30 23:42:47 ubuntu systemd[1]: Started Advanced key-value store.
lines 1-14/14 (END)
`

`npm --version
6.7.0
`

`mwoffliner --version
1.7.1
`

`nodejs --version
v8.11.4
`

`node --version
v11.8.0
`

`sudo apt-get install jpegoptim advancecomp gifsicle pngquant imagemagick
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Уже установлен пакет advancecomp самой новой версии (2.1-1).
Уже установлен пакет gifsicle самой новой версии (1.91-5).
Уже установлен пакет imagemagick самой новой версии (8:6.9.10.14+dfsg-7ubuntu2).
Уже установлен пакет jpegoptim самой новой версии (1.4.6-1).
Уже установлен пакет pngquant самой новой версии (2.12.2-1).
Обновлено 0 пакетов, установлено 0 новых пакетов, для удаления отмечено 0 пакетов, и 178 пакетов не обновлено.
`

ubuntu 19.04

**Comment by kelson42** [comment]
An other case:
```
mwoffliner --verbose --mwUrl="https://en.wikipedia.org/" --adminEmail=kelson@kiwix.org --customZimFavicon="https://upload.wikimedia.org/wikipedia/en/thumb/e/ec/Soccer_ball.svg/900px-Soccer_ball.svg.png" --customZimTitle="Football by Wikipedia" --customZimDescription="Wikipedia articles dedicated to Football" --articleList=https://download.kiwix.org/wp1/enwiki/projects/Football
```

@ISNIT0 I'm quite blocked with this problem as I need urgently to release new ZIM files. Even if this seems to be fied in 1.8, for now and probably the next two weeks we have to deal with 1.7. Would that be possible to backport the fix and publish mwoffliner 1.7.2?

**Comment by ISNIT0** [comment]
I'll look into it this evening, but the error is coming from `Parsoid`

**Comment by kelson42** [comment]
@ISNIT0 Are you sure about that? With my last example (I hope this is not an other problem), if I remove `
--customZimFavicon` then it works fine.

**Comment by ISNIT0** [comment]
@kelson42 
I've created a 1.7.2 branch, can you check this works for you? (I've scraped all of BM wiki with it and some of the dragonage one)

https://github.com/openzim/mwoffliner/tree/ISNIT0/1.7.2

**Comment by kelson42** [comment]
@ISNIT0 THX but I have a hard time to find the `npm` command to install it.
```
sudo npm install -g openzim/mwoffliner#ISNIT0/1.7.2
```
fails.

**Comment by ISNIT0** [comment]
@kelson42 Same command works fine on my vps

**Comment by kelson42** [comment]
@ISNIT0 Finally achieved to install it and your fix seems to work fine. OK to me to release. Thx.
