### ISSUE TITLE
Error handling json response from api

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#553]
When running mwoffliner, I have sometimes encountered errors like this one:
`
[error] [2019-02-10T21:06:15.650Z] Error handling json response from api. FetchError: invalid json response body at https://am.wikipedia.org/api/rest_v1/page/mobile-sections/%E1%8A%A5%E1%8A%95%E1%8B%B2%E1%88%85_%E1%88%8D%E1%8C%A0%E1%8C%8D%E1%89%A5_%E1%89%A0%E1%88%AC%E1%8B%AA%E1%8A%95_%E1%8A%A0%E1%88%A8%E1%8B%B5%E1%8A%A9%E1%89%B5 reason: Unexpected token < in JSON at position 0
`

I believe this is due to attempting to parse a html response from the server as json. (like one of the standard apache or Nginx error page)

**Comment by kelson42** [comment]
@automactic With 1.7?
@ISNIT0 Any idea?

**Comment by ISNIT0** [comment]
Is it possible that we're sending too many requests and are getting some kind of HTML warning page?

**Comment by kelson42** [comment]
@ISNIT0 Without more information, everything is possible.

**Comment by automactic** [comment]
Would it be a good idea to check response code first? if it is 200 and content type is json, then go ahead and parse the json

**Comment by kelson42** [comment]
@automactic We better check the HTTP response code in 1.8... but checking the content-type sounds a good idea too (in particular before parsing) ! @ISNIT0?

**Comment by ISNIT0** [comment]
We already check the response code, this will only happen if the response is an a "2XX" but the response is the wrong format. In which case there is nothing to do except throw an error

**Comment by kelson42** [comment]
@ISNIT0 I think what @automactic suggest is to check that we get the proper content-type in the HTTP response - in addition to the HTTP code - tu be sure that you don't send bad stuff (HTML for example) to the JSON parser.

**Comment by ISNIT0** [comment]
Since this ticket was opened, all of the querying has been moved to the Downloader class, which uses `axios` for network requests. We specify a `responseType`, and axios then checks that the response is valid.
I'm going to close this because the suggestion is now done by a library 😄
