### ISSUE TITLE
Publish automatically on npmjs & docker hub

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#556]
I synchronise manually the Docker hub image, this is something I want to automatise
* For each merge to master, update a "dev" version
* For each release tag, publish a new version for "latest" and one with the tag.

Same should happen on npmjs. All of this should run/be trigerred on Travis-CI.

**Comment by ISNIT0** [comment]
@kelson42 I will need you to configure the docker build - I don't have visibility of the process at the moment

**Comment by kelson42** [comment]
@ISNIT0 You don't need to do anything for Docker, because Docker already monitors the git repository. I have created the build of the `dev` tagged Docker image. Just take care that

**Comment by kelson42** [comment]
@ISNIT0 I have to repo this ticket. The releases on npmjs are not triggered by the git tab. According to https://www.npmjs.com/package/mwofflinerm 1.9.13 has been published 24 days ago, but I just have tagged the release.

**Comment by kelson42** [comment]
@midik Could you please secure the official releases will happen automatically on npmjs.org for next release? Docker is done and we already upload the dev versions on npmjs.org... should be trivial to secure that on proper git tagging event.
