### ISSUE TITLE
Add canonical link

### ISSUE THREAD

**Issue by wesleylima** [openzim/mwoffliner#564]
html snapshots should have a canonical tag back to the page that issued them.

Like <link rel="canonical" href="https://en.wikipedia.org/wiki/Collision" />

In addition to being good semantics, it will help search engines give more relevant results when someone publishes snapshots on the web (like this project is doing https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/Collision.html)

**Comment by kelson42** [comment]
@wesleylima How this should/could concretely looks like?

**Comment by wesleylima** [comment]
I would insert a tag like this in the `<head>`:
`<link rel="canonical" href="https://en.wikipedia.org/wiki/Collision"/>`

Looks like the relevant place for this is

`res/templates/page.html`

So would adding `<link rel="canonical" href="{{ webUrl }}{{ articleId }}"/>` to the `<head>` tag here work? I'm not sure if  `webURL` and `articleID` are present in this template's namespace.

**Comment by kelson42** [comment]
@ISNIT0 Any thoughs about that proposal?

**Comment by kelson42** [comment]
So, I think this should be done, we should not forget to put the proper revision id. We will try for milestone 2.0

**Comment by lidel** [comment]
We need this for https://github.com/ipfs/distributed-wikipedia-mirror/issues/48

What is the ETA for milestone 2.0? 
Could this be contributed via PR?

**Comment by kelson42** [comment]
> What is the ETA for milestone 2.0?

Difficult to say, we have still a bit of work with 1.9. I would guess that this bug might be fixed around end of September.

> Could this be contributed via PR?

Absolutely, this is a quite trivial one IMO.
