### ISSUE TITLE
Code to remove writer temporary date should be in the libzim

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#568]
Now that `libzim` writes directly (without `zimwriterfs`) the ZIM files, I have remarked that the temporary data have been kept:
```
drwxrwxrwt 4 root   root        280 Feb 17 19:17 ..
drwxr-xr-x 2 kelson kelson    20100 Feb 17 19:17 wikipedia_bm_all_2019-02.tmp
-rw-r--r-- 1 kelson kelson    24576 Feb 17 19:17 wikipedia_bm_all_2019-02.tmp.idx
drwxr-xr-x 2 kelson kelson      120 Feb 17 19:15 wikipedia_bm_all_2019-02.tmp.idx.tmp
-rw-r--r-- 1 kelson kelson 24675489 Feb 17 19:17 wikipedia_bm_all_2019-02.zim
```
This should be IMO removed automatically.

**Comment by mgautierfr** [comment]
The code is already in libzim.
The files are removed when the creator instance is destructed. (The destructor is called)
So you must delete the zimCreator at a moment to clean the temporary files.

**Comment by kelson42** [comment]
@ISNIT0 Can you secure please the zimCreator is deleted properly, so we don't leave the zimCreator temporary files?
