### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#588]
* Explain that it works only on Linux
* That the following software need to be installed: git, make, g++, gcc, libjpeg

**Comment by ISNIT0** [comment]
- It also works on MacOS

**Comment by kelson42** [comment]
@ISNIT0 How can it work on MacOS without the binary libzim for macos?

**Comment by ISNIT0** [comment]
I develop on MacOS :)
If the user is not on Linux, node-libzim logs on install that they should install libzim globally: https://github.com/openzim/node-libzim/blob/master/download-libzim.js#L18

**Comment by kelson42** [comment]
ah ok, I understand.
