### ISSUE TITLE
Spanish Wikipedia landing page is incorrect

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#59]
The eswp/nopic zim opens on [!!!](https://es.wikipedia.org/wiki/!!!) rather than [the planned landing page](https://es.wikipedia.org/wiki/Usuario:Stephane_(Kiwix)/Landing)

**Comment by kelson42** [comment]
Bug is already fixed but will release a new version of the WPES ZIM file first before closing the ticket.

**Comment by kelson42** [comment]
Fixed in https://download.kiwix.org/zim/wikipedia/wikipedia_es_all_novid_2017-08.zim

**Comment by Popolechien** [comment]
Tested http://download.kiwix.org/zim/wikipedia/wikipedia_es_all_novid_2019-06.zim on macOS 2.0 
Now it is a copy of sorts of the mobile landing page, but with serious design element issues
![Capture d’écran 2019-06-17 à 14 17 38](https://user-images.githubusercontent.com/21675885/59603985-27358f00-910b-11e9-8ae1-d9f51f1c7f76.png)

**Comment by kelson42** [comment]
My bad because I made that file manually. ZIMfarm & MWoffliner are OK.
