### ISSUE TITLE
Red link are not removed in the welcome page

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#591]
tested with bm.wikipedia.org. This link is available in the welcome page
```
<a href="/wikipedia_bm_all_nopic_2019-02/w/index.php?title=Tomond%C9%94n&amp;action=edit&amp;redlink=1" class="new" title="Tomondɔn (page inexistante)">Tomondɔn</a>
```

**Comment by kelson42** [comment]
@ISNIT0 I think you have broken many things here, css and pictures are not loaded at all in my test. bm.wikipedia.org home page does not have any valid picture for example.

**Comment by ISNIT0** [comment]
@kelson42 Can you check this again?
