### ISSUE TITLE
What does mean warning "Couldn't compress"

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#598]
For example:
```
[warn] [2019-02-24T08:36:22.584Z] Failed to get [http://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Coat_of_arms_of_the_Seychelles.svg/125px-Coat_of_arms_of_the_Seychelles.svg.png] [5] times
[warn] [2019-02-24T08:36:22.584Z] Failed to download item [http://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Coat_of_arms_of_the_Seychelles.svg/125px-Coat_of_arms_of_the_Seychelles.svg.png], skipping
[warn] [2019-02-24T08:36:22.696Z] Couldn't compress [http://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Cup-o-cofee-no-spoon.svg/20px-Cup-o-cofee-no-spoon.svg.png]... Went from [771] to [776]
[warn] [2019-02-24T08:36:24.276Z] Couldn't compress [http://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/NKo_Ny.svg/30px-NKo_Ny.svg.png]... Went from [446] to [597]
```

**Comment by ISNIT0** [comment]
It just says that when running all compressions for that file type, no space was saved. (I did attempt, but the filesize didn't change)

**Comment by kelson42** [comment]
@ISNIT0 I propose to:
* Replace "Couldn't compress" by "Failed to reduce file size after optimisation attempt" (the rest of the message is OK)
* Stop writing the warnings to STDERR, they should be printed to STDOUT
* Print only warnings if `--verbose` is activated.

**Comment by ISNIT0** [comment]
Currently:
- Warnings are only printed with `--verbose`
- We're using the standard JavaScript `console.warn`, I think it would be unwise to change this as it would be counter-intuitive

**Comment by kelson42** [comment]
@ISNIT0 hm, agree with your point, even if disagree with the result. OK, so please just change the wording (if proper English ;) and this would be fine to me
