### ISSUE TITLE
Only png, gif and jpeg files should be tried to be optimized

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#599]
But it looks like other files are too:
```
[warn] [2019-02-24T08:36:49.198Z] Couldn't compress [https://upload.wikimedia.org/wikipedia/commons/transcoded/3/36/WV0045-D33_Riaille.ogv/WV0045-D33_Riaille.ogv.120p.vp9.webm]... Went from [4140008] to [4140008]
 ``

This should not.

**Comment by ISNIT0** [comment]
Okay, in this case, they're not actually being attempted. There is a generic compression module that compresses everything downloaded using `Downloader.getContent`.

It doesn't actually try to optimise it.

**Comment by kelson42** [comment]
@ISNIT0 How does that work? Do we have a filter somewhere to avoid going through for non-supported type?

**Comment by ISNIT0** [comment]
That's part of the library `imagemin`, I pass everything to it and it decides what it can and can't compress. It means that in future it should be easy to add/remove more file types

**Comment by kelson42** [comment]
@ISNIT0 A filter should happen here before we send things to imagemin. We should have a white list of mimetypes which includes only png/jpg/gif. These warnings should not happen because we should not sent videos, audios, js, css, etc... file through the image optimisation process.

**Comment by ISNIT0** [comment]
Okay, this will only be duplicating the filter within imagemin, but I'll implement it
