### ISSUE TITLE
libzim seems not able (anymore) to create properly the xapian index

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#610]
```
kelson@camber:/dev/shm/tmp$ zimdump -L bm_wikipedia.zimwriterfs.zim | grep -i xapian
Z	/fulltextIndex/xapian	Xapian Fulltext Index	1946	A	application/octet-stream+xapian	573440
kelson@camber:/dev/shm/tmp$ zimdump -L bm_wikipedia.libzim.zim | grep -i xapian
X	fulltext/xapian	Xapian Fulltext Index	2673	A	application/octet-stream+xapian	24576
```
The first has been created with mwoffliner 1.7 using zimwriterfs and the second using mwoffliner 1.8 using only the libzim via the node binding.

**Comment by ISNIT0** [comment]
@kelson42 Just merged a fix in :)

**Comment by ISNIT0** [comment]
@kelson42 Have you checked this? I'm not sure the best way verify it, but I get search results in Kiwix Mac App now

**Comment by kelson42** [comment]
I confirm that this seems to be fixed
