### ISSUE TITLE
mwoffliner 1.8 does not rewrite URLS properly

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#613]
Running `mwoffliner --verbose --mwUrl=https://bm.wikipedia.org/ --adminEmail=kelson@kiwix.org` with both 1.71. and 1.8 give the following result:

With 1.8:
```
# zimdump -f Maninkakan -d out/wikipedia_bm_all_2019-03.zim | grep script
  <script>
  </script>
  <script src="/-/j/js_modules/script.js" class=""></script><script src="/-/j/js_modules/masonry.min.js" class=""></script><script src="/-/j/js_modules/article_list_home.js" class=""></script><script src="/-/j/js_modules/images_loaded.min.js" class=""></script>
  <noscript>
  </noscript>
  <script src="/-/j/js_modules/jsConfigVars.js" class=""></script>
  <script src="/-/j/js_modules/startup.js" class=""></script>
<script src="/-/j/js_modules/jquery.js" class=""></script>
<script src="/-/j/js_modules/mediawiki.js" class=""></script>
<script src="/-/j/js_modules/site.js" class=""></script>
```

With 1.7:
```
# zimdump -f Maninkakan -d out/wikipedia_bm_all_2019-03.zim | grep script
  <script>
  </script>
  <script src="../-/j/js_modules/script.js" class=""></script><script src="../-/j/js_modules/masonry.min.js" class=""></script><script src="../-/j/js_modules/article_list_home.js" class=""></script><script src="../-/j/js_modules/images_loaded.min.js" class=""></script>
  <noscript>
  </noscript>
  <script src="../-/j/js_modules/jsConfigVars.js" class=""></script>
  <script src="../-/j/js_modules/startup.js" class=""></script>
<script src="../-/j/js_modules/jquery.js" class=""></script>
<script src="../-/j/js_modules/mediawiki.js" class=""></script>
<script src="../-/j/js_modules/site.js" class=""></script>
```

Like written in the spec https://wiki.openzim.org/wiki/ZIM_file_format#URLs:

> Absolute URLs, ie. with a leading slash (/) are forbidden, because this avoid including the ZIM contents in any HTTP sub-hierachy. ZIM contents URLs must consequently be relative. Be careful, <article_url> may itself contain slashes (for example "BMW_501/502"). 

This bug is extremely visible in `kiwix-serve` as none of the pictures and CSS and JS is served.

This also seems to be a regression, I don't remember having se that bug 2 weeks ago in 1.8

**Comment by ISNIT0** [comment]
I have deleted everything on my vps, re-installed `openzim/mwoffliner` and scraped the `bm` wiki

This is my kiwix-serve, the images seem to load fine: http://209.250.226.220:8080/wikipedia_bm_all_2019-03/

**Comment by kelson42** [comment]
@ISNIT0 What give you my `zimdump` command with a ZIM file you have generated with mwoffliner git master?

**Comment by ISNIT0** [comment]
```
user@vultr:~$ zim-tools_linux-x86_64-1.0.0-2/zimdump -f Maninkakan -d out/wikipedia_bm_all_2019-03.zim | grep script
  <script>
  </script>
  <script src="/-/j/js_modules/script.js" class=""></script><script src="/-/j/js_modules/masonry.min.js" class=""></script><script src="/-/j/js_modules/article_list_home.js" class=""></script><script src="/-/j/js_modules/images_loaded.min.js" class=""></scrip >
  <noscript>
  </noscript>
  <script src="/-/j/js_modules/jsConfigVars.js" class=""></script>
  <script src="/-/j/js_modules/startup.js" class=""></script>
<script src="/-/j/js_modules/jquery.js" class=""></script>
<script src="/-/j/js_modules/mediawiki.js" class=""></script>
<script src="/-/j/js_modules/site.js" class=""></script>
```

Looks like it is absolute urls, but it does work with `kiwix-serve` for me

**Comment by kelson42** [comment]
@ISNIT0 I will try to understand why it works for you... but your link are not relative, it does not fit the spec. Which version of kiwix-seve do you use?

**Comment by ISNIT0** [comment]
`0.9.0`

**Comment by kelson42** [comment]
The reason why it fails for me is because I was testing with a nightly version of kiwix-serve which brakes the support with ZIM with absolute URLS, see my bug report https://github.com/kiwix/kiwix-tools/issues/262

**Comment by ISNIT0** [comment]
Do we still want to make the urls relative then?

**Comment by kelson42** [comment]
@ISNIT0 We have too, this is a ZIM spec requirement.
