### ISSUE TITLE
offline.css retrieval generates errors

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#614]
To avoid that we should properly test if the content exists before downloading it.

**Comment by kelson42** [comment]
@ISNIT0 Here again I don't understand why you just have removed everything? How is offline.css retrieved now?

**Comment by ISNIT0** [comment]
The url doesn't work (I've not modified it ever). The file exists but `?action=raw` gives an error.
Also, all the skin CSS is fetched separately

**Comment by kelson42** [comment]
@ISNIT0 It has worked and should work. The ticket is not about removing that feature, it is about checking if the online article exist before scraping it. That way we avoid silly error messages in the log. To warp up: If `offline.css` exists online, scrape it and integrate to the stylesheet to superseed the rest. Otherwise just don't try to download its content.

**Comment by ISNIT0** [comment]
@kelson42 How can we get access to the raw css then?
This exists: https://en.wikipedia.org/wiki/Mediawiki:offline.css
This (what is in the code) does not: https://en.wikipedia.org/wiki/Mediawiki:offline.css?action=raw

**Comment by kelson42** [comment]
@ISNIT0 Ok, it seems that something has changed on the backend. That is why it is important to have a unit test for that too. I think https://en.wikipedia.org/w/index.php?title=Mediawiki:offline.css&action=raw would make the job?

**Comment by ISNIT0** [comment]
@kelson42 Perfect, thanks :)

**Comment by kelson42** [comment]
There is no automated tests. We will still have errors is it does not exist.

**Comment by ISNIT0** [comment]
Tests for what?

**Comment by kelson42** [comment]
@ISNIT0 Ticket description is "offline.css retrieval generates errors", we agree that it still does (one time if optional if `offline.css` does not exist online)? `offline.css` online article is optional, it should not generate an error if it is not available online.

A method able to test if an online article exists (or not) should be implemented, I'll call it (and this is only an example): `articleExistsOnline()`. This method should be automatically tested with a unit test and of course should not generate any log error whatever the tested article is online or not.

One time `articleExistsOnline()` is done. A method to download the `offline.css` specific stylesheet should be done. I'll call it `downloadOfflineStylesheet()` (here again, this is only an example of name). Of course, the `offline.css` should be downloaded only `if articleExistsOnline("offline.css")`. This should also be automated tested (to detect the kind of problem your reported [here](https://github.com/openzim/mwoffliner/issues/614#issuecomment-500875385)). This method should generate an error if something goes wrong during the download.

Finally, `downloadOfflineStylesheet()` should be used. Here we need an automated E2E to really check that the offline stylesheet really applies to the final ZIM.

**Comment by ISNIT0** [comment]
The only way to test if `offline.css` exists (to my knowledge) is to try and download it.
If we were to check everything exists before downloading it, we would end up doubling the number of requests we make.
This seems crazy to me.

**Comment by kelson42** [comment]
@ISNIT0 I don't have written I want to have that workflow for all content. Like the title says, this is about `offline.css`.

**Comment by ISNIT0** [comment]
Sorry, I was confused by `articleExistsOnline`.

Either way, we'd still be trying to download it twice, which seems silly
