### ISSUE TITLE
SVG are not integrated properly - at least one

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#616]
By Creating a ZIM of bmwiki, I have remarked that `Coat_of_arms_of_the_Seychelles.svg` is not scraped... but it is part of the article `Nyɛ_fɔlɔ` (and is not rendered in the infobox).

```
$ zimdump -l out/wikipedia_bm_all_2019-03.zim | grep "Coat_of_arms_of_the_Seychelles"
root@camber:/dev/shm/mwoffliner
$
```

It should.

**Comment by kelson42** [comment]
I suspect here the problem might be the conversion using imagemagick instead of rsvg (like it was before)

**Comment by ISNIT0** [comment]
I don't see the SVG in the original `Nyɛ_fɔlɔ` article:
https://bm.wikipedia.org/wiki/Ny%C9%9B_f%C9%94l%C9%94

**Comment by ISNIT0** [comment]
I have found it missing in this article though: http://209.250.226.220:8080/wikipedia_bm_all_2019-03/A/Seshel

**Comment by ISNIT0** [comment]
MWOffliner is trying and failing to read download this file which is in-fact missing:
`http://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Coat_of_arms_of_the_Seychelles.svg/125px-Coat_of_arms_of_the_Seychelles.svg.png`

It gets this url from the `MCS` query. I've opened a ticket:
https://phabricator.wikimedia.org/T217540

**Comment by kelson42** [comment]
@ISNIT0 Thx, I have unscoped this ticket from the milestone. This seems to be a bug on Parsoid side.

**Comment by kelson42** [comment]
I would like to keep that ticket open as this still impact us but as we won't make anything about it and this might take ages to fix. I prefer to close it.
