### ISSUE TITLE
Adjust number of tiles for high screen resolutions

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#617]
While the current 2-columns layout fits well on mobile, it makes for kind of huge tiles on desktop, with the maximum width currently being limited to four tiles.
![capture d ecran 2019-03-04 a 15 08 26](https://user-images.githubusercontent.com/21675885/53738398-65c27900-3e8f-11e9-8a26-a2b61231c4a9.png)

We should increase that number (probably double it), and even make it so that all 100 images appear when in fullscreen (optional, but worth a shot).

**Comment by ISNIT0** [comment]
Would the titles fit if we had that many tiles?

**Comment by kelson42** [comment]
@ISNIT0 In the example given on the top, I think we can easily increase a bit before the titles can not be displayed (worse case we should have an ellipsis).

**Comment by ISNIT0** [comment]
I think this should be in a different release, to do it properly (as @kelson42 recommended in #693 ) this will need more work than a simple bug fix.

**Comment by ISNIT0** [comment]
This will probably need a flexbox polyfill, and we can get rid of `masonry js`

**Comment by ISNIT0** [comment]
I now remember why we have to use JavaScript for this.
The images aren't a consistent height, so logic is required to properly position them.

There are no masonry libraries out there that allow for specifying a minimum width, so the existing implementation is the best balance of simplicity and function.

@kelson42 If you would *really* like this to be changed, I could switch to another library and generate config for different screen widths, but it would be effectively the same as we have.

**Comment by kelson42** [comment]
@ISNIT0 Lets have a talk tomorrow about that to see if we can find a reasonable thing to do. Problem is a bit more complex than expected first.

**Comment by kelson42** [comment]
Lets extend the current configuration to width ~8000 pixels, and then this is good to me.
