### ISSUE TITLE
Generate zim of wikipedia articles with only intro part

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#63]
In order to drastically diminish zim size (particularly for mobile storage), can we generate zim files that only take the infobox and intro paragraphs?
An article's structure normally is:
Banners
Infobox
intro text (leade)
==section title==
and so on. The idea would be to take everything (leade+infobox) that's above the first section title. If we can do without the banners that's even better.

**Comment by kelson42** [comment]
@ISNIT0 Hi Joe, please: would that be possible for you to have a look to that feature request? This would be really helpful for the project!

**Comment by kelson42** [comment]
done
