### ISSUE TITLE
Make all new wikipedia zim files use the tiled landing page as default

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#630]
Not only for subsets, but all wikipedias. It's a lot nicer than the current pages, so the sooner the better.

**Comment by Jaifroid** [comment]
@Popolechien Presumably not WikiMed, which is a subcategory of Wikipedia? And some other subcategories with carefully composed front pages, like country-specific ones (e.g. Venezuela)? Sorry, this feels like déjà-vu, I'm sure we've had this conversation before!

**Comment by Popolechien** [comment]
@Jaifroid WikiMed might be a separate animal indeed, though honestly we really should think about how we can also improve that one.

**Comment by kelson42** [comment]
We basically have to change the zimfarm selections to use a list with all articles and then it will work like this. No need to change the software.
