### ISSUE TITLE
Some issues with wikipedia_fr_medicine_2018-03.zim

### ISSUE THREAD

**Issue by mgautierfr** [openzim/mwoffliner#631]
Fixing few thing on zimCheck, I discover some errors on wikipedia_fr_medicine_2018-03.zim.

- [ ] Redundant data :  m/Nuvola_apps_download_manager2-70%.svg.png (idx 45915) and s/15px-Nuvola_apps_download_manager2-70%25.svg.png (idx 51196) are identical
- [ ] Wrong html code in the content (See 'A/Acetobacter.html' for exemple with
```Selon <a href="/wiki/Catalogue_of_Life" title="Catalogue of Life">Catalogue of Life</a><span> </span><small about="#mwt23">(30 novembre 2015)</small><span class="mw-ref" id="cite_ref-CatalogueofLife_genre30_novembre_2015_6-0"><a href="#cite_note-CatalogueofLife_genre30_novembre_2015-6" style="counter-reset: mw-Ref 3;"><span class="mw-reflink-text">[3]</span></a></span>```)
Other articles have the same issue.

- [ ] Wrong id (anchor). See `id="Forme_linéaire }}"` in `A/Glucose.html`)
- [ ] Empty link. See A/Actinobacteria.html.
- [ ] Wrong external link without scheme (`dx.doi.org/%2010.1021/je0497496` in `A/1,1,1,2-Tétrafluoroéthane.html`)

**Comment by kelson42** [comment]
I'll splitted this ticket in atomic ones
