### ISSUE TITLE
localeCompare in src/util/dump.ts seems to be unnecessarily slow

### ISSUE THREAD

**Issue by cm8** [openzim/mwoffliner#635]
removeDuplicatesAndLowRes()  takes a very long time to compute if the number of dependencies is fairly large (say >100k).  Do we really need localeCompare to do the sorting?  And if so, wouldn't [obtaining a collator object beforehand](https://stackoverflow.com/questions/14677060/400x-sorting-speedup-by-switching-a-localecompareb-to-ab-1ab10/25775469) be of help?

We're comparing URLs -- localeCompare() should not be needed in this place, as URLs are non-localized.

**Comment by cm8** [comment]
The filter to find highest resolution versions of image urls also seems bogus complexity-wise.  It filters items uniqueItems.length times.  The following proposed patch runs in O(n), i.e. linear time, but is untested - please test and compare before applying.

For ~200k URLs in an items argument, the previous implementation takes around an hour to complete on the test machine here - this function may additionally benefit from parallelism like other parts of mwoffliner already do (not yet harnessed by the patch below).

```diff
--- mwoffliner/src/util/dump.ts
+++ mwoffliner/src/util/dump.ts.new
@@ -106,41 +106,27 @@
 }
 
 export function removeDuplicatesAndLowRes(items: Array<{ url: string, path: string, namespace: string }>) {
-    items = items.sort((a, b) => {
-        return a.url.localeCompare(b.url);
+    const items = items.sort((a, b) => {
+        return a.url < b.url ? -1 : (a.url > b.url ? 1 : 0);
     });
 
-    const uniqueItems = items.filter((it, index, arr) => {
-        if (index >= arr.length - 1) {
-            return true;
+    let m = new Map();
+    items.map((it) => {
+        const hasMult = item.url.includes('x.');
+        let multiplier = '1x';
+        if (hasMult) {
+            multiplier = item.url.split('-').slice(-1)[0].split('.').slice(0, -1).join('.'); // e.g. "1.5x"
         }
-        return it.path !== arr[index + 1].path;
-    });
-
-    const itemsWithHighestRequiredRes = uniqueItems.map((it) => {
-        const similarItems = items.filter((item) => item.path === it.path);
-
-        // const uniqueNamespaces = items.map((it) => it.namespace).sort().filter((it, i, arr) => it !== arr[i + 1]);
-        // This de-dup could cause issues if the duplicate files are in different namespaces, ignoring for now.
-
-        const itemsWithMult = similarItems.map((item) => {
-            const hasMult = item.url.includes('x.');
-            let multiplier = '1x';
-            if (hasMult) {
-                multiplier = item.url.split('-').slice(-1)[0].split('.').slice(0, -1).join('.'); // e.g. "1.5x"
-            }
+        const mult = Number(multiplier.slice(0, -1));
 
-            const mult = Number(multiplier.slice(0, -1));
-
-            return {
-                ...item,
-                mult,
-            };
-        });
-
-        const itemsSortedByMult = itemsWithMult.sort((a, b) => a.mult < b.mult ? 1 : -1);
-        return itemsSortedByMult[0];
+        let e = m.get(it.path);
+        if (e === undefined) {
+            m.set(it.path, { ...item, mult, });
+        } else if (e.mult < mult) {
+            m.set(it.path, { ...item, mult, });
+        }
     });
+    const itemsWithHighestRequiredRes = Object.values(m);
 
     logger.info(`Not downloading [${items.length - itemsWithHighestRequiredRes.length}] low-res images`);
     return itemsWithHighestRequiredRes;
```

**Comment by kelson42** [comment]
@ISNIT0 Could you please have a look?

**Comment by ISNIT0** [comment]
@cm8
Thanks for this suggestion 😄 
Please make a pull request and I'll take a look at it - this code has been adapted over time, so may well be over-complicated and slow 👍

**Comment by cm8** [comment]
I have no interest in cloning the repo.  Just thought it may be of use.  If you don't want to take it, well don't take it.

**Comment by ISNIT0** [comment]
Okay, well thanks for the suggestion anyway, any future contributions are welcome 👍

**Comment by kelson42** [comment]
@cm8 The point is that we want to review your patch... and you too... so why not following the rules? Making PR is trivial, but merging code which is not properly available as a PR is a hassle.

**Comment by kelson42** [comment]
@ISNIT0 I created a branch with the code of @cm8 but it does not pass the CI, I suspect it is buggy to some extend. That said, the quality (performance) of this piece of code is fundamental, please have a look to the PR, maybe the problems are minor.
