### ISSUE TITLE
Broken HTML in wikipedia_fr_medicine_2018-03.zim

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#637]
Fixing few thing on zimCheck, I discover some errors on wikipedia_fr_medicine_2018-03.zim.

- [ ] Wrong html code in the content (See 'A/Acetobacter.html' for exemple with
```Selon <a href="/wiki/Catalogue_of_Life" title="Catalogue of Life">Catalogue of Life</a><span> </span><small about="#mwt23">(30 novembre 2015)</small><span class="mw-ref" id="cite_ref-CatalogueofLife_genre30_novembre_2015_6-0"><a href="#cite_note-CatalogueofLife_genre30_novembre_2015-6" style="counter-reset: mw-Ref 3;"><span class="mw-reflink-text">[3]</span></a></span>```)
Other articles have the same issue.

Reported first in #631

**Comment by kelson42** [comment]
@mgautierfr @ISNIT0 What is wrong exactly, I don't get it!?

**Comment by mgautierfr** [comment]
This is directly in the text (displayed to the user). What I copy/paste is not the html source.

**Comment by kelson42** [comment]
@mgautierfr Indeed, I can not see this problem.
