### ISSUE TITLE
Empty links in article "Actinobacteria" in wikipedia_fr_medicine_2018-03.zim

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#639]
Empty link. See A/Actinobacteria.html.

Reported first in #631

**Comment by kelson42** [comment]
@mgautierfr This file is "old". I have created a new one with mwoffliner 1.8.1 and was not able to see any empty link by:
* Searching for `href=""` in the source
* Running the `zimcheck` of your branch `fix_check`

Might be the problem is not here anymore.

**Comment by mgautierfr** [comment]
> Or do you have more details where the problem was?

No, I've discover the issue with the branch `fix_check`. If it is ok on your side with a new zim,  you can close the issue.

**Comment by ISNIT0** [comment]
What is the issue here?

**Comment by kelson42** [comment]
Seems to be fixed.
