### ISSUE TITLE
New landing page for the Turkish Wikipedia

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#64]
Here it is : [https://tr.wikipedia.org/wiki/Kullanıcı:Stephane_(Kiwix)/Landing](https://tr.wikipedia.org/wiki/Kullanıcı:Stephane_(Kiwix)/Landing)

(watch it the i in Kullanici are some specific Turkish characters. This is rather urgent in light of the current Wikipedia ban in Turkey.

**Comment by kelson42** [comment]
done, first ZIM with that homepage available here http://download.kiwix.org/zim/wikipedia/wikipedia_tr_all_2017-04.zim
