### ISSUE TITLE
Removing --speed option

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#647]
Since 1.8, we have a solution to auto-adapt the speed, so this option could/should be removed IMO

**Comment by ISNIT0** [comment]
I agree, it is now only really used for parallelisation of queries (how many concurrent auto-adapting fetchers to use)

**Comment by kelson42** [comment]
We need to fix the speed autoadapt approach first. I seems to be weak.

**Comment by ISNIT0** [comment]
@kelson42 Have you got examples of it not performing well?

**Comment by kelson42** [comment]
@ISNIT0 Vikidia #660

**Comment by ISNIT0** [comment]
I think this should be renamed, but not removed.
Maybe something like `--parallel` or `--workers` would be better?

**Comment by kelson42** [comment]
I have changed the milestone, we are not ready for this.

**Comment by kelson42** [comment]
We need to keep that option for Vikidia (at least)
