### ISSUE TITLE
Questioning removal of --minifyHtml option

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#648]
We never use this option. The belief is that it could brake the HTML. This should be checked. If we have a solution which is reliable, we should use it. Otherwise we should really remove the option.

**Comment by kelson42** [comment]
@ISNIT0 Any idea on this?

**Comment by ISNIT0** [comment]
The code uses `html-minifier` (https://www.npmjs.com/package/html-minifier) A minifier is useless if it breaks the HTML. 
It should not break the html, and I think we should be fine using `--minifyHtml`

**Comment by kelson42** [comment]
OK, will open a bug if it does
