### ISSUE TITLE
Wikipedia  (EN 2016-12) startpage is wrong

### ISSUE THREAD

**Issue by okkebal** [openzim/mwoffliner#66]
When I open Wikipedia (EN 2016-12) the startpage is a music band called "!!!" instead of a nice Welcome to Wikipedia landing page.   

Everything else seems to work fine, I even have the index installed an fulltext search seems to work now on android.

**Comment by kelson42** [comment]
I confirm. The bug is fixed but we need a new release.

**Comment by okkebal** [comment]
The new release is here with a nice new startpage
