### ISSUE TITLE
Automate User Acceptance Tests

### ISSUE THREAD

**Issue by ISNIT0** [openzim/mwoffliner#668]
Would be nice to automate UATs.
Probably best to do it with some bash tool like https://github.com/sstephenson/bats to do simple and representative executions

https://github.com/openzim/mwoffliner/wiki/User-Acceptance-Tests

**Comment by ISNIT0** [comment]
We now have e2e tests for BM and EN100.

We also test the `--help` and `--version` output.

Not sure of the best way to run `zimdump` etc.
I don't really like the idea of executing a local version of zimdump through a `process.exec` because the tests will be useless for anyone without zimtools installed

Thoughts @kelson42

**Comment by kelson42** [comment]
@ISNIT0 The automated tests run on Ubuntu Xenial. You can found `zimcheck` and `zimdump` binaries to be run here https://download.openzim.org/release/zim-tools/. It is a (optional?) test dependence. Just download/install them (if not already done) and then run them.
