### ISSUE TITLE
not working --mwWikiPath ?

### ISSUE THREAD

**Issue by shikulja** [openzim/mwoffliner#669]
`
mwoffliner --mwUrl=https://dragonage.fandom.com/ru --adminEmail=123@11.com --format=zim --mwWikiPath=wiki/ --mwApiPath=api.php --redis=redis://127.0.0.1:6379 --keepHtml --minifyHtml --useCache
[log] [2019-04-09T16:47:19.502Z] Getting text direction...
[log] [2019-04-09T16:47:19.504Z] Getting site info...
[log] [2019-04-09T16:47:19.504Z] Getting sub-title...
(node:25427) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
[log] [2019-04-09T16:47:20.719Z] Text direction is [ltr]
[log] [2019-04-09T16:47:29.942Z] Using a local MCS instance, couldn't find a remote one
[log] [2019-04-09T16:47:29.942Z] Starting Parsoid & MCS
{"name":"parsoid","hostname":"ubuntu","pid":25427,"level":30,"levelPath":"info","msg":"loading ...","time":"2019-04-09T16:47:30.788Z","v":0}
{"name":"parsoid","hostname":"ubuntu","pid":25427,"level":30,"levelPath":"info","msg":"ready on :8000","time":"2019-04-09T16:47:30.835Z","v":0}
{"name":"mcs","hostname":"ubuntu","pid":25427,"level":30,"levelPath":"info","msg":"Worker 25427 listening on 0.0.0.0:6927","time":"2019-04-09T16:47:31.001Z","v":0}
[log] [2019-04-09T16:47:31.007Z] Redis databases flushed.
Getting JSON from [https://dragonage.fandom.com/ru/api.php?action=query&format=json&prop=coordinates%7Crevisions&colimit=max&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&rawcontinue=true]
The response contained warnings: { query:
   { '*': "Unrecognized value for parameter 'prop': coordinates" } }
Getting JSON from [https://dragonage.fandom.com/ru/api.php?action=query&format=json&prop=coordinates%7Crevisions&colimit=max&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&rawcontinue=true]
The response contained warnings: { query:
   { '*': "Unrecognized value for parameter 'prop': coordinates" } }
Getting JSON from [https://dragonage.fandom.com/ru/api.php?action=query&format=json&prop=coordinates%7Crevisions&colimit=max&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&rawcontinue=true]
The response contained warnings: { query:
   { '*': "Unrecognized value for parameter 'prop': coordinates" } }
`
with --mwWikiPath=wiki/  and without  i get
https://dragonage.fandom.com/ru/api.php?

and
[log] [2019-04-09T16:47:31.007Z] Redis databases flushed.
  { '*': "Unrecognized value for parameter 'prop': coordinates" } }
what need to do?

`
sudo systemctl status redis
[sudo] password for asss: 
● redis-server.service - Advanced key-value store
   Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor pre
   Active: active (running) since Tue 2019-04-09 08:50:39 PDT; 1h 19min ago
     Docs: http://redis.io/documentation,
           man:redis-server(1)
 Main PID: 13497 (redis-server)
    Tasks: 4 (limit: 2311)
   Memory: 2.5M
   CGroup: /system.slice/redis-server.service
           └─13497 /usr/bin/redis-server 127.0.0.1:6379
`

**Comment by kelson42** [comment]
@shikulja What is the problem exactly? The stuff with "coordinates" should not be blocking.

**Comment by shikulja** [comment]
> @shikulja What is the problem exactly? The stuff with "coordinates" should not be blocking.

1. I did not block "coordinates", so everything is fine?

2. mwWikiPath = wiki/
gives you the address https://dragonage.fandom.com/ru/api.php?
is this ok too?

**Comment by kelson42** [comment]
1. yes
2. no, because there is not relationship between both. Have a look to mwApiPath if you want to customise the API URL

But again: what is wrong with this scraping?

**Comment by shikulja** [comment]
> 1. yes
> 2. no, because there is not relationship between both. Have a look to mwApiPath if you want to customise the API URL
> 
> But again: what is wrong with this scraping?

Apparently I'm confused. because .. can not configure.
I have already tried differently.
The result is the same as above, no dump.

**Comment by ISNIT0** [comment]
@shikulja Could you post the last 20 lines of logs you get please? This would be helpful for our debugging

**Comment by shikulja** [comment]
> @shikulja Could you post the last 20 lines of logs you get please? This would be helpful for our debugging
well, but it does not stop, but continues .. until I stop it manually.
If you need what will be at the end of the entire dump, need to wait a very long time.

**Comment by shikulja** [comment]
> @shikulja Could you post the last 20 lines of logs you get please? This would be helpful for our debugging

well, but it does not stop, but continues .. until I stop it manually.
If you need what will be at the end of the entire dump, need to wait a very long time.

**Comment by ISNIT0** [comment]
These logs are to be expected - there is no failure that I can see, could you run this from end-to-end and re-open this issue if you have a problem with the output please? 👍

**Comment by shikulja** [comment]
>    { '*': "Unrecognized value for parameter 'prop': coordinates" } }
> Getting JSON from [https://dragonage.fandom.com/ru/api.php?action=query&format=json&prop=coordinates%7Crevisions&colimit=max&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&rawcontinue=true]
> The response contained warnings: { query:
>    { '*': "Unrecognized value for parameter 'prop': coordinates" } }
> Getting JSON from [https://dragonage.fandom.com/ru/api.php?action=query&format=json&prop=coordinates%7Crevisions&colimit=max&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&rawcontinue=true]
> The response contained warnings: { query:
>    { '*': "Unrecognized value for parameter 'prop': coordinates" } }
> Getting JSON from [https://dragonage.fandom.com/ru/api.php?action=query&format=json&prop=coordinates%7Crevisions&colimit=max&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&rawcontinue=true]
> The response contained warnings: { query:
>    { '*': "Unrecognized value for parameter 'prop': coordinates" } }
> Getting JSON from [https://dragonage.fandom.com/ru/api.php?action=query&format=json&prop=coordinates%7Crevisions&colimit=max&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&rawcontinue=true]
> The response contained warnings: { query:
>    { '*': "Unrecognized value for parameter 'prop': coordinates" } }
> Getting JSON from [https://dragonage.fandom.com/ru/api.php?action=query&format=json&prop=coordinates%7Crevisions&colimit=max&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&rawcontinue=true]
> The response contained warnings: { query:
>    { '*': "Unrecognized value for parameter 'prop': coordinates" } }
> Getting JSON from [https://dragonage.fandom.com/ru/api.php?action=query&format=json&prop=coordinates%7Crevisions&colimit=max&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&rawcontinue=true]
> The response contained warnings: { query:
>    { '*': "Unrecognized value for parameter 'prop': coordinates" } }
> Getting JSON from [https://dragonage.fandom.com/ru/api.php?action=query&format=json&prop=coordinates%7Crevisions&colimit=max&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&rawcontinue=true]
> The response contained warnings: { query:
>    { '*': "Unrecognized value for parameter 'prop': coordinates" } }
> Getting JSON from [https://dragonage.fandom.com/ru/api.php?action=query&format=json&prop=coordinates%7Crevisions&colimit=max&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&rawcontinue=true]
> The response contained warnings: { query:
>    { '*': "Unrecognized value for parameter 'prop': coordinates" } }
> Getting JSON from [https://dragonage.fandom.com/ru/api.php?action=query&format=json&prop=coordinates%7Crevisions&colimit=max&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&rawcontinue=true]
> The response contained warnings: { query:
>    { '*': "Unrecognized value for parameter 'prop': coordinates" } }
> Getting JSON from [https://dragonage.fandom.com/ru/api.php?action=query&format=json&prop=coordinates%7Crevisions&colimit=max&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&rawcontinue=true]
> The response contained warnings: { query:
>    { '*': "Unrecognized value for parameter 'prop': coordinates" } }
> Getting JSON from [https://dragonage.fandom.com/ru/api.php?action=query&format=json&prop=coordinates%7Crevisions&colimit=max&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&rawcontinue=true]
> The response contained warnings: { query:
>    { '*': "Unrecognized value for parameter 'prop': coordinates" } }
> Getting JSON from [https://dragonage.fandom.com/ru/api.php?action=query&format=json&prop=coordinates%7Crevisions&colimit=max&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&rawcontinue=true]
> The response contained warnings: { query:
>    { '*': "Unrecognized value for parameter 'prop': coordinates" } }
> Getting JSON from [https://dragonage.fandom.com/ru/api.php?action=query&format=json&prop=coordinates%7Crevisions&colimit=max&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&rawcontinue=true]
> The response contained warnings: { query:
>    { '*': "Unrecognized value for parameter 'prop': coordinates" } }
> Killed
> asss@ubuntu:~/dump$ 
> asss@ubuntu:~/dump$ 
>
