### ISSUE TITLE
Discussion: definition of a stuck container

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#673]
We should define when a container can be determined as "stuck". 

Rationale 
In zimfarm, a mechanism should be added to determine a container is not going to succeed and should thus be terminated to free up resource.

One proposal from @kelson42 is: stuck means 1hr without stdout update (which seems reasonable to me)

**Comment by ISNIT0** [comment]
Yes, this seems reasonable. I've been able to reproduce this a couple of times now - working on it!

**Comment by kelson42** [comment]
@ISNIT0 @automactic If we agree on this definition, may I close the ticket?

**Comment by automactic** [comment]
sure
