### ISSUE TITLE
--verbose should be able to get a log threshold

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#674]
The `--verbose` option works as a boolean option for now. This should continue to be able to work that way but we should also be able to put a log level, under which, any log message should not be displayed.

For example `--verbose=warning` will print all errors above warning, ie. warning and error probably.

**Comment by kelson42** [comment]
@uriesk Does that proposal sounda a reasonable way to be more flexible with logging printing on terminal?

**Comment by uriesk** [comment]
@uriesk yes, sounds great

**Comment by kelson42** [comment]
@pavel-karatsiuba seems ready to implement to me
