### ISSUE TITLE
mwoffliner is not able to deal correctly with audio/video 

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#68]
Currently, if a Mediawiki page serves an audio/video content (using HTML5 features), this content is not directly usable in the ZIM file for the end user.

They are two reasons for this:
(1) Parsoid does not provide all the information necessary for this (for example an icon, a player, and an adapted version: an ogg link in case of a flac file) https://phabricator.wikimedia.org/T64270
(2) mwoffliner has anyway a problem to provide an offline version of the "resourceLoader"

Reported first here https://sourceforge.net/p/kiwix/bugs/877/

**Comment by kelson42** [comment]
Problem (1) has been fixed on Wikimedia servers side... so we only have a problem on our side now.

**Comment by kelson42** [comment]
Here a page with both video and audio https://en.wikipedia.org/wiki/Johann_Sebastian_Bach

**Comment by ISNIT0** [comment]
Can't reproduce problem 2 
![image](https://cloud.githubusercontent.com/assets/5173131/26571306/376c383e-450d-11e7-9263-f3a9fcc499f5.png)
Seems to be playing fine using HTML5 Video(?) tags.

Are we sure its not a ZIM/Kiwix issue?

**Comment by kelson42** [comment]
@ISNIT0 Hmmm... I did not expect it would work out-of-the-box honestly. So you confirm video/audio files are offlined correctly and can both be played?

**Comment by ISNIT0** [comment]
Good shout, should've checked that:
![image](https://user-images.githubusercontent.com/5173131/27001985-81fefc50-4dce-11e7-950e-6294b1538a77.png)

**Comment by kelson42** [comment]
@ISNIT0 I'm not sure what is exactly about, but the ZIM file should provide a video/audio in webm (mp4?) format. It seems the link you have given is the link to the original version (not downscaled and not in a web format). Hope this is not what is included.

**Comment by ISNIT0** [comment]
Yes, it's the original (it references the online version), I'm working on it now.

**Comment by kelson42** [comment]
This has finally been fixed for both desktop and mobile Layouts.
