### ISSUE TITLE
Docker: separate redis from default command

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#69]
**Proposal**:

In the dockerfile of this repo, change the end of file from:
```
CMD service redis-server restart && /bin/bash
```
to 
``` 
RUN service redis-server restart
CMD /bin/bash && mwoffliner
```

Reason for change:
`CMD` is the default command, can be overridden but the user. So if the user run `docker run -it openzim/mwoffliner mwoffliner --mwUrl=https://bm.wikipedia.org/ --adminEmail=chris@kiwix.org`, the following error will be produced, since the redis server start command is overridden and never executed.
```
Error: Redis connection to /dev/shm/redis.sock failed - connect ENOENT /dev/shm/redis.sock
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
```

I recently encountered this error while building [openzim/zimfarm](https://github.com/openzim/zimfarm). I have celery workers based on `mwoffliner` container and I have to manually boot up redis.

**Update**: looks like `RUN` won't work, since it only got executed in the build phase. I personally think it is a bad idea to put redis together with mwoffliner. mwoffliner should use a docker-compose and depend on an official redis image, so that different concerns are separated. It's just like if you have a website that use mysql as backend, you would have a container for the website and another for mysql. 

In zimfarm I could get around this by using `ENTRYPOINT service redis-server restart && celery -A tasks worker --loglevel=info`

**Comment by kelson42** [comment]
I kind of like to have everything in one image for simple thing like mwoffliner.

What about ?
```
ENTRYPOINT service redis-server start
CMD /bin/bash && mwoffliner
```

**Comment by automactic** [comment]
I don't think it will work, because in zimfarm, I will have to override `ENTRYPOINT ` and `CMD`. And also I think you cannot have both `ENTRYPOINT ` and `CMD`, because there is only one main process of a container

**Comment by kelson42** [comment]
After a small discussion it seems to me that the most promising is:
* To have a worker which just run job in other "sibling" docker containers
* logs should be caughts with "docker logs" to be then transmitted to the dispatcher.

This would avoid us complex discussion about how to X scrapper dockerfile in one worker docker file.

**Comment by kelson42** [comment]
This is basically done
