### ISSUE TITLE
Move ./bin to TypeScript and fully integrate VSCode debugger with ts-node

### ISSUE THREAD

**Issue by ISNIT0** [openzim/mwoffliner#691]
There are still a few files in `./bin` which are in JavaScript (`mwoffliner.script.js`, `mwmatrixoffliner.script.js`).
It would be nice to move them to TypeScript. This would allow us to properly integrate the TS debugger (using something like `ts-node`).

`mwoffliner.script.js` is the main entry file for command line usage, so a bit of futsing will be necessary in the build and publish process to make it executable
(Something like: https://github.com/ISNIT0/gfs-scraper/blob/master/build.sh#L4)

**Comment by ISNIT0** [comment]
@barczag

**Comment by kelson42** [comment]
@ISNIT0 I think we can remove mwmatrixoffliner

**Comment by barczaG** [comment]
https://github.com/openzim/mwoffliner/pull/696

**Comment by kelson42** [comment]
@ISNIT0 Any chance to get this ticket closed/PR reviewed?
