### ISSUE TITLE
nopic welcome page thumbnails in really bad quality

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#693]
Looks like that if you do a `--format=nopic` the quality of the images in the welcome page thumbnails is really bad.
![scr](https://user-images.githubusercontent.com/1029718/56455497-47d9a680-635f-11e9-8e06-2a9313566e89.png)

**Comment by ISNIT0** [comment]
I thought this was desired behaviour?
What resolution should we show instead?
These are the default "thumbnail" resolutions from the "pageimages" query:
https://en.wikipedia.org/w/api.php?action=query&prop=pageimages&titles=London&format=json

**Comment by kelson42** [comment]
@ISNIT0 I see... use whatever the minimal resolution needed so it displays properly on screens considering the size of the images you have configured on this welcome page.

**Comment by ISNIT0** [comment]
But this depends on the devices rendering. These images look better on a small mobile than on an ultra-wide monitor. We need to decide on a resolution. I'm not sure people will be expecting images at all if they set `--format=nopic`, so they may be unhappy when their zim file is full of images

**Comment by kelson42** [comment]
Probably this would also fix #617

**Comment by kelson42** [comment]
We had an agreement on:
* no max column anymore
* column wide should not scale (like crazy anymore). there is a max-width
* Thumbnail max-width fit to column max-width
* Not image scaling blurring the pictures anymore

**Comment by ISNIT0** [comment]
I would prefer the following:
- Modify the default thumbnail width to `500px`
- Above `2024px` show 8 columns
- Above `4048px` show 16 columns

This means that on the top end of the 4 column layout, the thumbnails will be scaled by `+6px` (`2023/4 - 500`).

And the only time the user will see meaningful image scaling is when their screen is wider than `8096px`.

I'm not a huge fan of limiting the user's use of their screen

**Comment by kelson42** [comment]
@ISNIT0 This will go banana if someone has a screen of 8000px isn't it? Why not making just a generic logic?

**Comment by ISNIT0** [comment]
Not sure what you mean by "go banana", but I don't think setting a maximum width of displaying things is "generic logic"

**Comment by kelson42** [comment]
@ISNIT0 "go banana" mean mwoffliner will scale the images because it can not display more than 16 images in a row. Like this the requirements won't be respected.

**Comment by ISNIT0** [comment]
I've now updated the PR to have a max-width of `8096px`

**Comment by kelson42** [comment]
@ISNIT0 OK, but you see the problem, why all of this is not generic? why we still jumb from 4 tiles instead of just increasing of 1 tile if the width allows it?

**Comment by ISNIT0** [comment]
@kelson42 This would be possible if we were using just CSS, but the specific CSS features we need (masonry grids) are not available on older devices, so we just a JavaScript library called MasonryJS. I haven't looked into it all that much, just extended what was implemented originally by @tamasfabi

**Comment by kelson42** [comment]
@ISNIT0 ok, please secure that this works fine even with extremly large screens. And we should really have a one by one progression step, not 4 by 4, by doing so, the max width of a picture should be reduces.. and that would be also good for the overall ZIM size right?

**Comment by ISNIT0** [comment]
Found this: https://github.com/callmecavs/bricks.js
Should make defining the new requirements more concise. Will re-implement the grid layout...

**Comment by ISNIT0** [comment]
The above is not specific to the issue and to do it properly required re-doing the article list. I think it's not for this release.

I think we should make a separate issue for "improving" the article list page (making the images re-size more frequently).

**Comment by ISNIT0** [comment]
Actually, we already have a separate issue: https://github.com/openzim/mwoffliner/issues/617

**Comment by kelson42** [comment]
@ISNIT0 This ticket just complains that the quality of the pictures is not OK in "nopic". This has nothing todo with a layout problem like #617 says. This can also be fixed without changing anything in the layout. We "just" have to retrieve the picture in the adequate resolution.

**Comment by ISNIT0** [comment]
Yes, I corrected myself above and in #617
