### ISSUE TITLE
Provide file generation result identifier and file location when execution finished

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#70]
Please provide a way to identify 
- if the file generation is successful (maybe through return code?)
- the output file path (maybe through stdout when return code is success?)

**Comment by kelson42** [comment]
Regarding the second question, I would start with deciding of a place ("/data" >) where jobs should put the ZIM files and this directory should be then directly synced with the online system hosting the ZIM files. We could then refine a bit this principle if this is a bit too stupid/simple.

**Comment by kelson42** [comment]
@automactic Do we really need to keep this ticket open?

**Comment by sivaraam** [comment]
FWIW, I would really love to know the path of the output file as it would save some searching. At least, the file name seems to be present when the verbose option is true. It would be nice if it were available without verbose too.

**Comment by kelson42** [comment]
@sivaraam You dont' know the full path of the ZIM file(s) but you know in which directory it will be created.

**Comment by sivaraam** [comment]
> You dont' know the full path of the ZIM file(s) but you know in which directory

Yeah ([or may be not?](https://github.com/openzim/mwoffliner/pull/753)).

It would be great if the tool's output just confirms that the file we think it has generated is actually the one it has generated. I know that the last modified time of a file could help identify the latest file in the output directory but printing the path would be even more useful. At least it would help the skeptical people. Of course, this is just my opinion :slightly_smiling_face:

**Comment by automactic** [comment]
I am ok with closing this ticket
