### ISSUE TITLE
Create a ZIM of Wikem.org

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#71]

**Comment by kelson42** [comment]
This needs #35 to be implemented

**Comment by tim-moody** [comment]
in case it is relevant

mwoffliner of 5-18-2017 uses api.php action=visualeditor to retrieve pages and that action is not supported by wikem.org:

Parameters:
action
Which action to perform.

One of the following values: block, checktoken, clearhasmsg, compare, createaccount, delete, edit, emailuser, expandtemplates, feedcontributions, feedrecentchanges, feedwatchlist, filerevert, help, imagerotate, import, login, logout, managetags, mobileview, move, opensearch, options, paraminfo, parse, patrol, protect, purge, query, revisiondelete, rollback, rsd, scribunto-console, setnotificationtimestamp, stashedit, tag, tokens, unblock, undelete, upload, userrights, watch

**Comment by kelson42** [comment]
@tim-moody yes, mwoffliner should be used with local parsoid.

**Comment by tim-moody** [comment]
using local parsoid worked.

**Comment by ISNIT0** [comment]
![Fistpump](https://images.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.giphy.com%2Fmedia%2FlXiRy0RCPLMQSVqx2%2Fgiphy.gif&f=1)

**Comment by kelson42** [comment]
Done, I have published a frist version here http://download.kiwix.org/zim/other/wikem_en_all_2017-06.zim
