### ISSUE TITLE
Write redirects at the end of the process

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#711]
To optimize memory consumption (see https://github.com/openzim/libzim/issues/226) it would be better to write the redirects at the end of the process. Is that the case? Could we do so?

**Comment by ISNIT0** [comment]
I suppose we would still have the same total memory, but there would be less early on

**Comment by ISNIT0** [comment]
Redirects are already stored at the end of the process https://github.com/openzim/mwoffliner/blob/master/src/mwoffliner.lib.ts#L451
