### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by bitcoineler** [openzim/mwoffliner#714]
she@host234$ mwoffliner --mwUrl=https://de.wikipedia.org/ --adminEmail=foo@bar.net

```
/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/nbind/dist/nbind.js:15
        throw (err);
        ^

Error: Could not locate the bindings file. Tried:
/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/nbind.node
/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/nbind.node
/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/Debug/nbind.node
/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/Release/nbind.node
/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/out/Debug/nbind.node
/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/Debug/nbind.node
/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/out/Release/nbind.node
/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/Release/nbind.node
/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/default/nbind.node
/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/compiled/8.11.3/linux/x64/nbind.node
/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/nbind.js
/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/nbind.js
/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/Debug/nbind.js
/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/Release/nbind.js
/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/out/Debug/nbind.js
/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/Debug/nbind.js
/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/out/Release/nbind.js
/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/Release/nbind.js
/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/default/nbind.js
/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/compiled/8.11.3/linux/x64/nbind.js
    at findCompiledModule (/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/nbind/dist/nbind.js:83:15)
    at find (/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/nbind/dist/nbind.js:93:13)
    at Object.init (/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/nbind/dist/nbind.js:104:5)
    at Object.<anonymous> (/home/she/.nvm/versions/node/v8.11.3/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/binding.js:4:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```

**Comment by ISNIT0** [comment]
@bitcoineler I'm afraid we don't support node version `v8.11.3`. Could you try using something like `v11.14.0`

(We also currently don't support the latest version of node - `v12.0.0` #707 )

**Comment by bitcoineler** [comment]
@ISNIT0 I tried with v11.14.0 and have the same problem.

'''
/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/nbind/dist/nbind.js:15
        throw (err);
        ^

Error: Could not locate the bindings file. Tried:
/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/nbind.node
/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/nbind.node
/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/Debug/nbind.node
/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/Release/nbind.node
/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/out/Debug/nbind.node
/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/Debug/nbind.node
/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/out/Release/nbind.node
/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/Release/nbind.node
/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/default/nbind.node
/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/compiled/11.15.0/linux/x64/nbind.node
/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/nbind.js
/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/nbind.js
/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/Debug/nbind.js
/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/Release/nbind.js
/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/out/Debug/nbind.js
/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/Debug/nbind.js
/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/out/Release/nbind.js
/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/Release/nbind.js
/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/default/nbind.js
/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/compiled/11.15.0/linux/x64/nbind.js
    at findCompiledModule (/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/nbind/dist/nbind.js:83:15)
    at find (/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/nbind/dist/nbind.js:93:13)
    at Object.init (/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/nbind/dist/nbind.js:104:5)
    at Object.<anonymous> (/home/she/.nvm/versions/node/v11.15.0/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/binding.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
'''

**Comment by ISNIT0** [comment]
Did you get any errors when running `npm install`?

**Comment by bitcoineler** [comment]
working now.
