### ISSUE TITLE
Limburgian Wiktionary homepage is incomplete

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#715]
Currently the Limburgian (?) wiktionary landing page is pretty minimal
http://library.kiwix.org/wiktionary_li_all_2016-12/A/Wiktionary:Veurblaad.html

The zim file is from December 2016 and the landing page from March 2015, but it already existed in its current, rather wordy form already then ([it's the current landing format](https://li.wiktionary.org/w/index.php?title=Wiktionary:Veurblaad&oldid=463202))

I hesitated flagging this as a bug as the zim is pretty old (why hasn't it been updated since is another question). I would even think it removes a ton of useless clutter and does, in fact, look better than the original. Nonetheless does anyone have any idea why this happened?

**Comment by kelson42** [comment]
The link points to an old ZIM files, a newer one would:
http://library.kiwix.org/wiktionary_li_all_novid_2019-05/A/Wiktionary:Veurblaad

But the problem is there! Here is the mobile version online:
https://li.m.wiktionary.org/w/index.php?title=Wiktionary:Veurblaad&mobileaction=toggle_view_mobile

**Comment by Popolechien** [comment]
> The link points to an old ZIM files, a newer one would be:
> http://library.kiwix.org/wiktionary_li_all_novid_2019-05/A/Wiktionary:Veurblaad

@kelson42 Ah well then we have another issue here: why is library.kiwix.org showing the old zim (it's at column 3, line 4)?

**Comment by kelson42** [comment]
> @kelson42 Ah well then we have another issue here: why is library.kiwix.org showing the old zim (it's at column 3, line 4)?

@Popolechien Agree. I have cleanup all wiki* on download.kiwix.org. Should be better now.

**Comment by ISNIT0** [comment]
@kelson42 There is explicit logic that forces scraping the desktop version of wiki main pages. Disabling the logic gives the expected mobile main page: 
![image](https://user-images.githubusercontent.com/5173131/59267466-40899780-8c42-11e9-860f-f2aab785cda6.png)

I can make this change if you'd like, but I guess there's a reason this check is there...
Here is the en Main_Page outputted with the same change (looks very empty): 
![image](https://user-images.githubusercontent.com/5173131/59267592-8a727d80-8c42-11e9-9edd-03174b30f7c6.png)

**Comment by kelson42** [comment]
@ISNIT0 You are right, we scrape the desktop version (and this is right) but does the desktop version does not work better.

**Comment by ISNIT0** [comment]
What should we do in this case then?

**Comment by kelson42** [comment]
@ISNIT0 I don't konw, why our welcome page does not looks like https://li.wiktionary.org/w/index.php?title=Wiktionary:Veurblaad&mobileaction=toggle_view_desktop ? Do you?

**Comment by ISNIT0** [comment]
Looks like the API isn't returning anything more than that: https://li.wikipedia.org/w/api.php?action=visualeditor&format=json&paction=parse&page=Wiktionary:Veurblaad

**Comment by ISNIT0** [comment]
I believe MWO is behaving correctly here. It seems that the unexpected behaviour is coming from the API (I'm not sure that it's a bug though)

Please re-open if you think there is something we can do on MWO

**Comment by kelson42** [comment]
@ISNIT0 This does not looks like an upstream bug to you?

**Comment by ISNIT0** [comment]
https://phabricator.wikimedia.org/T227851

**Comment by kelson42** [comment]
Latest scrapping is http://library.kiwix.org/wiktionary_li_all_maxi/A/Wiktionary:Veurblaad. The page is scraped but somehow incomplete if we compare with original https://li.wiktionary.org/wiki/Wiktionary:Veurblaad.

But it is already returned incompleted by the REST API, see https://li.wiktionary.org/api/rest_v1/page/html/Wiktionary:Veurblaad. I believe this is a bug upstream and have updated the upstream ticket.

**Comment by kelson42** [comment]
Like explained in the upstream ticket, this is the combinaison of a bug in the Parsoid and a strange wiki code. The wiki code has been fixed and now the REST API returns the proper code. I'm generating a new ZIM. Problem is fixed.
