### ISSUE TITLE
How come the Football nopic zim (2019_04) still has 40,000+ media files?

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#718]
I'm seeing this on library.kiwix.org
![Capture d’écran 2019-05-01 à 11 22 52](https://user-images.githubusercontent.com/21675885/57011739-7bd88580-6c03-11e9-9077-752882520dad.png)
(the corresponding zim file is http://library.kiwix.org/wikipedia_en_football_nopic_2019-04/)
I'd have expected the number of media files to be around 100 (those on the landing page)

I've clicked on a number of random articles and saw no image whatsoever - so what are really these media files, if not pictures?

**Comment by ISNIT0** [comment]
I think that must have been generated before this was fixed: https://github.com/openzim/mwoffliner/issues/699

**Comment by Popolechien** [comment]
Hopefully, though the number of media isn't the same (40 vs 139 k). Closing for now. Thanks!
