### ISSUE TITLE
Lots of missing articles in wikivoyage_en_all_novid_2019-05.zim

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#724]
Many articles are missing. To see an example, load the page for Singapore, and also open the equivalent page on en.wikivoyage.org. You will see that half of the "district" links are missing, e.g. for Marina Bay, Little India, Sentosa and Harbourfront, etc. These articles are simply missing from the ZIM (they are not in the index either). Similarly on the Africa page, overview articles are missing for North Africa, West Africa, Central Africa, East Africa, East African Islands, etc.

This looks like a bad encode, and I suggest this ZIM should be pulled before it makes its way into Wikivoyage-specific clients.

**Comment by ISNIT0** [comment]
@kelson42 Not sure if it will make any difference, but it seems the mentioned article was not made with 1.8.6

**Comment by kelson42** [comment]
@ISNIT0 If that has not been made with 1.8.6, this has been made with 1.8.5 which AFAIK should indeed not have changed anything fundamental in a way how articles are retrieved. Like for #173, we really need to secure all the stuff is here. I though you had fixed that after the missing JS code in 1.8.1 or 1.8.2!
@Jaifroid Thx for reporting. I will remove the file.

**Comment by ISNIT0** [comment]
I don't think this is anything to do with JavaScript, but I'm looking into the missing articles

**Comment by ISNIT0** [comment]
I think this is likely to be related to the pageId `.replace(/ /g, '_')`

**Comment by Jaifroid** [comment]
You're probably right, @ISNIT0 , because I notice that the article `Singapore/Little India` has an illegal URL in `wikivoyage_en_all_novid_2019-05.zim`:
`Singapore/Little India` (URLs should not have spaces). This is the `dirEntry` for the article:

![image](https://user-images.githubusercontent.com/4304337/57473738-6d840c80-7288-11e9-84a3-5018dfb3d415.png)

By contrast, the same article in `wikivoyage_en_all_novid_2019-04.zim` has the more reasonable "Singapore/Little_India" (underscore).

**Comment by Jaifroid** [comment]
By the way @ISNIT0 , the forward slash in the URL is causing problems in Kiwix JS (see https://github.com/kiwix/kiwix-js/issues/494). I wonder if it might be causing problems for you too. For example, the article `Singapore` references its assets like this:
```
<link href="../-/s/css_modules/ext.kartographer.link.css" …>
```
Whereas the article `Singapore/Riverside` references its assets like this:
```
<link href="../../-/s/css_modules/ext.kartographer.link.css" …>
```
Note the extra `../../`, because the browser thinks it's accessing an article Riverside in the subdirectory Singapore. This would all be fine, except that the hrefs in the `Singapore/Riverside` article are written like this:
```
<p>The <b>Singapore River</b> forms a central artery in <a href="Singapore"
title="Singapore">Singapore</a>'s densely packed Central Business District.
```
Note that to access the hyperlink on this page from a browser, we would need to write that link as `<a href="../Singapore" ...>`.

So there seems to be some inconsistency. Are we inside a subdirectory from the browser's perspective, or not? The subroutine that writes the location of the assets seems to think so, while the one that writes the location of the hyperlinks doesn't! Do you think this is an mwoffliner issue?

**Comment by kelson42** [comment]
@Jaifroid I have hidden your last comment as this is IMO a separate bug, I have open a ticket with your same comment here #726. Thank you for reporting that problem too.

**Comment by ISNIT0** [comment]
This seems to have been inadvertently fixed by https://github.com/openzim/mwoffliner/pull/725
