### ISSUE TITLE
MainPage for selection "Ray Charles" is plain black with 1.8.6

### ISSUE THREAD

**Issue by rgaudin** [openzim/mwoffliner#728]
When creating a ZIM from a selection without specifying a mainPage, the generated main page appears plain black.
It actually displays a blue on white multi-column list for a fraction of a second before going black.

Here's the command used:
``` sh
docker run --volume /tmp:/out:rw \
--link redis openzim/mwoffliner:1.8.6 mwoffliner \
--format= --format=nodet \
--articleList="http://download.kiwix.org/wp1/enwiki/customs/ray_charles" \
--customZimTitle="Ray Charles" \
--mwUrl="https://en.wikipedia.org/" \
--adminEmail="reg@kiwix.org" \
--redis="redis://redis" --useCache
```

Tested with Kiwix Desktop Mac and Kiwix-serve

![Image from iOS](https://user-images.githubusercontent.com/57929/57548115-ac30ca00-734f-11e9-8a56-03d39e9987f3.png)

![Screen Shot 2019-05-10 at 5 56 29 PM](https://user-images.githubusercontent.com/57929/57548130-b783f580-734f-11e9-82a1-c668073ef1a2.png)

**Comment by ISNIT0** [comment]
This happens only when there are under 10 thumbnail images available. I was vaguely aware of this, but thought it was not affecting any use-cases.

**Comment by kelson42** [comment]
@ISNIT0 Would that be possible to just get the list of articles displayed in that case (like for nojs browser)?
