### ISSUE TITLE
Redis "details" key seems not to be deleted at the right moment

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#732]
Redis seems to have one key to store articles details (`1557597035596-detail`) and one to store media details (`1557597035596-media`).

Here an example
```
$ redis-cli --scan 
1557597035596-media
1557597035596-detail
```

The article details Redis key seems to be kept until the end of the scraping process, but in fact I strongly suspect it could be purged earlier (before the downloading of the pictures). Or is that because of the redirects? But then why we still have redirects files?

**Comment by ISNIT0** [comment]
It's used throughout the whole process, for checking that articles exist etc (when checking links)

**Comment by kelson42** [comment]
@ISNIT0 OK, but why you need that after all the articles (not the pictures) are scraped?

**Comment by ISNIT0** [comment]
You're right, we could delete before downloading the media
