### ISSUE TITLE
Checking how mwoffliner deals with picture redirects

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#738]
It is not clear if it works fine:
* no duplicate of pictures
* proper resolution (picture visible)

**Comment by ISNIT0** [comment]
MCS returns raw `img` tags. A few "smart" things are done to ensure only the highest resolution of the same image name (extracted from `img[src]`) is downloaded, but there is currently no check for redirects.

Out of interest, how would one find redirects from this url? `//upload.wikimedia.org/wikipedia/commons/thumb/c/cd/London_Montage_L.jpg/275px-London_Montage_L.jpg`

**Comment by ISNIT0** [comment]
@kelson42 this has been answered, closing for now. Please re-open if you have any follow-up questions

**Comment by kelson42** [comment]
From what I have understood about Parsoid/MCS, it already resolves the redirects. So for us it should be transparent.
