### ISSUE TITLE
Latest version of wikipedia_ps_all_novid_2019-05.zim lacks images on frontpage

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#739]
Interestingly there *are* images in articles.
![Capture d’écran 2019-05-13 à 10 56 16](https://user-images.githubusercontent.com/21675885/57609139-93eac600-756e-11e9-83fc-a863cfdebf54.png)

**Comment by rgaudin** [comment]
It might be linked to #741 as images on other pages are working.

**Comment by Popolechien** [comment]
Already mentioned in #723, I'd say
