### ISSUE TITLE
Mediawiki:offline.css?action=raw is not found

### ISSUE THREAD

**Issue by masgo** [openzim/mwoffliner#74]
I am trying to zim an older (internatl) MediaWiki installation by using the ZIMmakerVMv6.

Doing the following:
`node /usr/local/lib/node_modules/mwoffliner/bin/mwoffliner.script.js --mwUrl=https://my.url --adminEmail=my@mail.net --mwWikiPath /intern/mediawiki --mwApiPath /intern/mediawiki/api.php 
` (url censored)
gives me:
```
Unable to download content [1] https://my.url/intern/mediawiki/Mediawiki:offline.css?action=raw (statusCode=404).
Unable to download content [2] https://my.url/intern/mediawiki/Mediawiki:offline.css?action=raw (statusCode=404).
Unable to download content [3] https://my.url/intern/mediawiki/Mediawiki:offline.css?action=raw (statusCode=404).
Absolutly unable to retrieve async. URL: Unable to download content [3] https://my.url/intern/mediawiki/Mediawiki:offline.css?action=raw (statusCode=404).
TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:88:11)
    at Object.urlParse [as parse] (url.js:82:5)
    at /usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:2484:41
    at /usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:2217:21
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:676:51
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:726:13
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:264:21
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:723:17
```

The file `Mediawiki:offline.css` does not exist on the server. But I checked the real wikipedia and some other public mediawiki installations and it exists nowhere.

Am I doing something wrong or is this a bug?

The MediaWiki installation I want to capture is version 1.19.20+dfsg-2.3

**Comment by kelson42** [comment]
The problem is not offline.css and your mwoffliner call seems ok. Not sure what happens exactly here.

**Comment by masgo** [comment]
Adding a slash does not help. Error changes to:
`Unable to download content [1] https://my.url//intern/mediawiki/Mediawiki:offline.css?action=raw (statusCode=404).
`

**Comment by kelson42** [comment]
@masgo Hmmm without a repro case it might be difficult to identify the exact problem unfortunately.

**Comment by mgautierfr** [comment]
It doesn't seems related to `Mediawiki:offline.css`. I've got the same message (but with 403) and `mwoffliner` still finish "correctly".

Here, it seems that mwoffliner somehow fail to define a variable and try to download a `undefined` variable. Maybe an option is missing ?

**Comment by kelson42** [comment]
@mgautierfr Mediawiki::Offline.css does not exist on most Mediawiki instances... so not a problem to get an error here. The main problem here is that we probably shoudl check if the file exist before trying to downloading it.

**Comment by masgo** [comment]
Can I somehow add this file to my instance - as a workaround?

**Comment by kelson42** [comment]
@masgo Do you still have a problem with git master?

**Comment by masgo** [comment]
@kelson42 I gave up to use mwoffliner to save a copy of the wiki. Instead I used HTTrack. It's not that good and requires a lot of fiddeling, but gives okay-ish results for a mediawiki instance.

**Comment by kelson42** [comment]
Fixed
