### ISSUE TITLE
--format parameter description unclear

### ISSUE THREAD

**Issue by rgaudin** [openzim/mwoffliner#740]
The `--format` description in the help is the following:

```
--format                   To custom the output with comma separated values :
                             "nopic,novid,nopdf,nozim,nodet"
```

I find it misleading as, reading this, the expected output for a `--format=nodet,nopic` would be 2 files, one with each of the specified formats.

This is not the case.

The current behavior of `mwoffliner` is:

* `--format` can be used multiple times and produce a file (of a folder in case of `nozim` for each occurrence of `--format`.
* Using a comma-separated list creates an combined output. `--format=nopic,novid` creates a `_nopic_novid_` file without pictures and without medias.
* Not setting `--format` creates a *full* dump without restrictions.
* To generate both a formatted and a full ZIM at once, it is required to use `--format=''` in addition to the other format.

Also, a description of the formats (particularly `nodet` would be welcome).

* `nodet` restricts output to first paragraph. **excludes video** yet **includes pictures**.
* `nopic` **excludes pictures and video**.
* `novid` **excludes video**.

**Comment by kelson42** [comment]
@ISNIT0 I reopen the ticket, the fix does not fully implement what is required. Details about what does each option is not given and `nodet` seems to have dispappeared. Please make on PR pro ticket, this makes the review easier. Ask @rgaudin (or me) for the review.

**Comment by ISNIT0** [comment]
@kelson42 Could you make a suggestion for some text that should go in the `--help` menu please? I don't think it makes sense to put a lot of detail in there. Perhaps we should document the individual options somewhere on GitHub?

**Comment by kelson42** [comment]
@ISNIT0 Yes, I'll
