### ISSUE TITLE
Latest version of wikipedia_ps_all_novid_2019-05.zim has text rather than tiles

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#741]
Follow up to #739 - normally such wiki should have the new tile layout for landing, shouldn't it? (no alternate landing page has been specified)
![Capture d’écran 2019-05-13 à 10 56 16](https://user-images.githubusercontent.com/21675885/57611515-59cff300-7573-11e9-911b-d94bf375ed2c.png)

**Comment by kelson42** [comment]
@Popolechien no, this is for selection only. See #630.

**Comment by Popolechien** [comment]
Well #630 specifically requests the tile layout to be applied to all zims, with a possible exception for Wikimed.
I'll rephrase it then: what compelling reason is there not to apply the tile layout to the full wikipedias?

**Comment by kelson42** [comment]
@Popolechien The feature is not implemented in the code, so you can not complain that the ZIM file are not working like this

**Comment by Popolechien** [comment]
Got it.
