### ISSUE TITLE
Allow customization of formats's name in filename

### ISSUE THREAD

**Issue by rgaudin** [openzim/mwoffliner#742]
At the moment, one can specify multiple formats or combinations of (see #740) and `mwoffliner` will build a file name like:

`{host}_{lang}_all|{selection}_{formats_combination}_{date}.zim`

Alternatively, one can specify a `--filenamePrefix` to replace everything up to the `_{date}`.

This is not ideal for the zimfarm use case for two reasons:

* we are not satisfied with the formats names inside the output file name.
* we don't want to post-process filenames.
* `filenamePrefix` prevents `mwoffliner` from inserting the format in the filename so it must be used for single-format requests only.

At the moment, our biggest need is the ability to rename the format's string in the filename (`nodet`, `nopic`, `novid`, `nopdf`).

From our perspective, being able to specify alternate names right in the `--format` parameter would be ideal:

```sh
mwoffliner --format=nodet:mini --format=novid:maxi --format=nopic
mwoffliner --format= --format=nodet,nopic:small
```

It might raises additional questions like:
* Shouldn't the *no format* format have a name? like `full` or something.
* Shouldn't the `filenamePrefix` be able to act as a template filled with the current parts ?

**Comment by kelson42** [comment]
It make the format paramter even more comple, but agree with the approach.

**Comment by kelson42** [comment]
Done
