### ISSUE TITLE
--requestTimeout not usable

### ISSUE THREAD

**Issue by rgaudin** [openzim/mwoffliner#747]
The `--requestTimeout` parameter is unusable as it's value is not converted to integer and sent straight to the `Downloader`, resulting in an `undefined` value if set.

https://github.com/openzim/mwoffliner/blob/55b6c663fdeb05792369bd8eca5eb82dc24062da/src/mwoffliner.lib.ts#L171

**Comment by kelson42** [comment]
@rgaudin @ISNIT0 I'm not aware about any MWoffliner command line option called `--requestTimeout`. What is that?

**Comment by ISNIT0** [comment]
The `requestTimeout` is passed as a header to all http requests.
@rgaudin I've inspected the running code and it is passed as a number, so I'm not sure exactly what your issue is 😢

**Comment by rgaudin** [comment]
Ah my bad, I though it failed right away when fixing a `20s` timeout but the timeout is actually in ms!
Nevermind, sorry.
