### ISSUE TITLE
docker image fails on zimwriterfs

### ISSUE THREAD

**Issue by tim-moody** [openzim/mwoffliner#75]
•	sudo docker  pull openzim/mwoffliner
•	sudo docker create openzim/mwoffliner
•	sudo docker run -it -v ~/wikishrink:/files -v /etc/localtime:/etc/localtime:ro openzim/mwoffliner

•	mwoffliner --mwUrl=https://en.wikipedia.org/ --adminEmail tim@timmoody.com   --articleList /files/Test_Seed_List_enwiki.lst --cacheDirectory /files/cache --outputDirectory /files/out --filenamePrefix wikishrink --withZimFullTextIndex --verbose

yields Failed to build successfuly the ZIM file /files/out/wikishrink_test_seed_list_enwiki_2017-05.zim (Error by executing zimwriterfs)

**Comment by tim-moody** [comment]
timm@nuc ~ $ ll wikishrink/cache/wikishrink/
total 4696
drwxr-xr-x 3 root root    4096 May 17 11:43 ./
drwxr-xr-x 3 root root    4096 May 17 11:43 ../
-rw-r--r-- 1 root root   42872 May 17 11:43 07019dd1cdb779a73985
-rw-r--r-- 1 root root    1242 May 17 11:43 07019dd1cdb779a73985.h
-rw-r--r-- 1 root root   75674 May 17 11:43 0f2c04279e78e8c2abdb
-rw-r--r-- 1 root root    1241 May 17 11:43 0f2c04279e78e8c2abdb.h
-rw-r--r-- 1 root root   41639 May 17 11:43 0f780199c2e5510e491c
-rw-r--r-- 1 root root    1240 May 17 11:43 0f780199c2e5510e491c.h
-rw-r--r-- 1 root root  927972 May 17 11:43 1131fc10ce60cae7733d
-rw-r--r-- 1 root root    1236 May 17 11:43 1131fc10ce60cae7733d.h
-rw-r--r-- 1 root root   75362 May 17 11:43 1e2f34b21370ecc9ed5c
-rw-r--r-- 1 root root    1241 May 17 11:43 1e2f34b21370ecc9ed5c.h
-rw-r--r-- 1 root root  343321 May 17 11:43 26d9e3d9b57376675c34
-rw-r--r-- 1 root root    1241 May 17 11:43 26d9e3d9b57376675c34.h
-rw-r--r-- 1 root root  191811 May 17 11:43 27163b6b4372ca2cacf9
-rw-r--r-- 1 root root    1241 May 17 11:43 27163b6b4372ca2cacf9.h
-rw-r--r-- 1 root root  213557 May 17 11:43 2b41992597d471c1293d
-rw-r--r-- 1 root root    1235 May 17 11:43 2b41992597d471c1293d.h
-rw-r--r-- 1 root root   71684 May 17 11:43 4388a17bed2be756f8f1
-rw-r--r-- 1 root root    1242 May 17 11:43 4388a17bed2be756f8f1.h
-rw-r--r-- 1 root root   73472 May 17 11:43 4ba6b86ff4dfb6fdad16
-rw-r--r-- 1 root root    1728 May 17 11:43 4ba6b86ff4dfb6fdad16.h
-rw-r--r-- 1 root root 1033835 May 17 11:43 501657c40f9116846d19
-rw-r--r-- 1 root root    1236 May 17 11:43 501657c40f9116846d19.h
-rw-r--r-- 1 root root  179570 May 17 11:43 5bad824a509528cf59d9
-rw-r--r-- 1 root root    1239 May 17 11:43 5bad824a509528cf59d9.h
-rw-r--r-- 1 root root  247865 May 17 11:43 5f7ccea3013658cecb98
-rw-r--r-- 1 root root    1242 May 17 11:43 5f7ccea3013658cecb98.h
-rw-r--r-- 1 root root   55905 May 17 11:43 62fcb3b13483eea2970d
-rw-r--r-- 1 root root    1241 May 17 11:43 62fcb3b13483eea2970d.h
-rw-r--r-- 1 root root  171362 May 17 11:43 6983c3d5b19ed9aebfbe
-rw-r--r-- 1 root root    1239 May 17 11:43 6983c3d5b19ed9aebfbe.h
-rw-r--r-- 1 root root   63524 May 17 11:43 826666dcde98d4ef3f86
-rw-r--r-- 1 root root    1242 May 17 11:43 826666dcde98d4ef3f86.h
-rw-r--r-- 1 root root   80860 May 17 11:43 a605b152a123cb7a47ee
-rw-r--r-- 1 root root    1242 May 17 11:43 a605b152a123cb7a47ee.h
-rw-r--r-- 1 root root  120322 May 17 11:43 b87e443da7c96655d204
-rw-r--r-- 1 root root    1241 May 17 11:43 b87e443da7c96655d204.h
-rw-r--r-- 1 root root  465389 May 17 11:43 d3eec3fcfa8547b76176
-rw-r--r-- 1 root root    1243 May 17 11:43 d3eec3fcfa8547b76176.h
-rw-r--r-- 1 root root   69192 May 17 11:43 e52de514fca7242235e1
-rw-r--r-- 1 root root    1241 May 17 11:43 e52de514fca7242235e1.h
-rw-r--r-- 1 root root   94571 May 17 11:43 f928ead66099e2ace92f
-rw-r--r-- 1 root root    1240 May 17 11:43 f928ead66099e2ace92f.h
drwxr-xr-x 2 root root   20480 May 17 11:43 m/
-rw-r--r-- 1 root root       2 May 17 11:43 ref
-rw-r--r-- 1 root root   10405 May 17 11:43 wikishrink_test_seed_list_enwiki.redirects
timm@nuc ~ $ ll wikishrink/out
total 1680
drwxr-xr-x 2 root root    4096 May 17 11:43 ./
drwxrwxr-x 4 timm timm    4096 May 17 11:40 ../
-rw-r--r-- 1 root root 1709235 May 17 11:43 wikishrink_test_seed_list_enwiki_2017-05.zim

**Comment by tim-moody** [comment]
timm@nuc ~ $ cat wikishrink/Test_Seed_List_enwiki.lst
Discobolus
William_John_Macquorn_Rankine
Andrews_Field
Enspel
Anarchism
Jumiles
Ian_Rankin
Another_Cinderella_Story
Wine_press
Autism
Temperature_(song)
Ivan_Reitman
Angiostrongyliasis
Kay_Walsh
Fantastic_Four_(2015_film)
Albedo
Mecoptera
Muhammad_al-Bukhari
Mental_representation
Datura_metel

**Comment by tim-moody** [comment]
if I remove  --withZimFullTextIndex  I get

sort 401 directory entries (aid)
remove invalid redirects from 401 directory entries
sort 401 directory entries (url)
set index
translate redirect aid to index
401 directory entries createdcreate title index
401 title index created3 clusters createdfill header
write zimfile
ready
ZIM file built at /files/out/wikishrink_test_seed_list_enwiki_2017-05.zim

**Comment by kelson42** [comment]
I confirm the bug, but rootcause seems pretty unclear to me.

**Comment by tim-moody** [comment]
not sure how to help. I can tell you that zimwriterfs did some work as the file sizes are different between --withZimFullTextIndex and without:

-rw-r--r-- 1 root root 1324039 May 17 12:14 wikishrink_test_seed_list_enwiki_2017-05.zim
-rw-r--r-- 1 root root 1709235 May 17 11:43 wikishrink_test_seed_list_enwiki_2017-05.zim.1 (with index)

**Comment by tim-moody** [comment]
I can try just to run the zimwriterfs part if you tell me what parameters mwoffliner would supply based on the command line above.

**Comment by kelson42** [comment]
@mgautierfr After testing, it seems pretty clear to me that the problem is in the zimlib and has been introduced at (or after) the creation of the dedicated libzim git repo. Please have a look, this is critical.

**Comment by mgautierfr** [comment]
@tim-moody What is the exact error of the `mwoffliner` command. Can you give the backtrace ?

Where does `wikishrink_test_seed_list_enwiki_2017-05.zim.1` come from ? (I may wrongly understand the bug report, but it seems from what you say that `mwoffliner` **cannot** generate it)

**Comment by tim-moody** [comment]
Error message is
Failed to build successfuly the ZIM file /files/out/wikishrink_test_seed_list_enwiki_2017-05.zim (Error by executing zimwriterfs)

there is no backtrace; it just issues the message and halts.

wikishrink_test_seed_list_enwiki_2017-05.zim.1 was in the output in spite of the message (I renamed it .1 to do a second run without --withZimFullTextIndex, which completes)

seems it failed late in the process of creating zim file (see the size difference above)

**Comment by tim-moody** [comment]
btw, perhaps 'Error by executing zimwriterfs' should read 'Error when executing zimwriterfs'

**Comment by kelson42** [comment]
This is what I get
```
isArticleIndexer running: yes
isArticleIndexer running: yes
isArticleIndexer running: yes
isArticleIndexer running: yes
isArticleIndexer running: no
sort 402 directory entries (aid)
remove invalid redirects from 402 directory entriessort 402 directory entries (url)
set index
translate redirect aid to index402 directory entries createdcreate title index402 title index created3 clusters createdfill headerwrite zimfile
ready
*** Error in `zimwriterfs': double free or corruption (!prev): 0x0000000001c11ed0 ***
Failed to build successfuly the ZIM file /srv/kiwix-maintenance/mwoffliner/out/wikishrink_test_2017-05.zim (Error by executing zimwriterfs)

```

**Comment by kelson42** [comment]
This issue was moved to openzim/libzim#18

**Comment by kelson42** [comment]
@tim-moody I have fixed the error msg
