### ISSUE TITLE
Introduce code coverage with codecov

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#754]
kiwix-android can be taken as example

**Comment by ISNIT0** [comment]
Codecov badge is reporting "unknown"

**Comment by kelson42** [comment]
@ISNIT0 A few additional questions:
* Are unit tests and e2e tests mixed? Any way to see the difference?
* Do we have any guaranty that codecov review all PRs and refuse the review if the code coverage decrease (in comparison to the branch on which the PR will be merged)?
