### ISSUE TITLE
Are cookies from API login used when embedded files are being downloaded?

### ISSUE THREAD

**Issue by osnard** [openzim/mwoffliner#758]
I want to use `mwoffliner` on a private wiki. Therefore I need to specify `username` and `password` to allow an API login. Unfortunately all files/images are missing in the result. I believe that this is due to the fact, that my source wiki instance is configured to deliver files/images only via the `img_auth.php` entrypoint. But this entrypoint needs a valid user session.

Could it be, that the coockies that are set by the API login are not reused when `mwoffliner` tries to download the files/images?

What would need to be done to change that? Maybe I can provide a patch.

[1] https://www.mediawiki.org/wiki/Manual:Image_Authorization

**Comment by kelson42** [comment]
@osnard Which version of mwoffliner are you using? Which version of Mediawiki? Do you have errors in the log?

**Comment by osnard** [comment]
Unfortunately I did not perform this myself and I am not 100% sure about how my colleague did it, but he probably used "v1.8.6". The MediaWiki version is 1.31.2 (LTS). I am not aware of any errors in the log, but will ask my colleague about it.

**Comment by kelson42** [comment]
@osnard Ok, this sounds a bit difficult to debug the problem if you work as a proxy. I'm also surprised that you are able to login considering this ticket #42.

**Comment by gokhangeyik** [comment]
Hello @kelson42
I am the colleague of @osnard, I tested on v1.8.6
Actually I didn't get any errors. Our main concern is the result. When I created a ZIM file from a MediaWiki or directly Wikipedia.org, I realized internal links were not there. Internal links replaced to regular text.

Also, I couldn't reach the PDF files which are included with pages. Pages were there with PDF icon but document itself were not inside the ZIM file.

Image thumbnails were inside the pages but also were not clickable or zoomable.

Zim Reader: Kiwix

**Comment by kelson42** [comment]
It is important we focus on one problem per ticket, otherwise it will be difficult to handle your request. Lets focus on the picture problem. First report was "all files/images are missing in the result", then you said "Image thumbnails were inside the pages but also were not clickable or zoomable".

MWoffliner does only mirror the thumbnails, this is how it works so far.  So If you have the thumbnails but not the fullres underlying pictures then this is normal.

Could you please confirm:
* This is how it behaves for you.
* You want a way to download the "File:" pages too, and these pages should provide the fullress images (like online)

**Comment by gokhangeyik** [comment]
I created a new ZIM file. Example page contains `File:` link, thumbnail and full res. Thumbnail and Full Res working as you mentioned.

Also attached two screenshots. One is taken from web, other is taken from kiwix.

Based on your explanation, Images working as expected.

**ZIM File:**
<img width="1352" alt="kiwix" src="https://user-images.githubusercontent.com/17786242/58704526-fe946200-83b4-11e9-92a3-5d3285695fa0.png">

**Web:**
<img width="981" alt="web" src="https://user-images.githubusercontent.com/17786242/58704527-ff2cf880-83b4-11e9-9cc5-cdc4e29ad150.png">

**Comment by kelson42** [comment]
I should check this again and see if Wikipedia is impacted.

**Comment by kelson42** [comment]
Duplicate of #42.
