### ISSUE TITLE
mwoffliner halts on Error: ENAMETOOLONG: name too long

### ISSUE THREAD

**Issue by tim-moody** [openzim/mwoffliner#76]
•	sudo docker pull openzim/mwoffliner
•	sudo docker create openzim/mwoffliner
•	sudo docker run -it -v ~/wikishrink:/files -v /etc/localtime:/etc/localtime:ro openzim/mwoffliner

root@aef968c683d9:~# mwoffliner --mwUrl=https://en.wikipedia.org/ --adminEmail tim@timmoody.com   --articleList /files/Grown_Seed_List_enwiki_2016-06.lst --cacheDirectory /files/cache --outputDirectory /files/out --filenamePrefix wikishrink --verbose

yields

Unable to create symlink to /root/tmp/wikishrink_grown_seed_list_enwiki_2016-06_2017-05/m/2016-05-09_17_23_45_National_Oceanic_and_Atmospheric_Administration_headquarters_at_the_intersection_of_Colesville_Road_(Maryland_State_Route_384)_and_East-West_Highway_(Maryland_State_Route_410)_in_Silver_Spring,_Montgomery_County,_Maryland.jpg at /files/cache/wikishrink/m/1ee736612049d19f8541.jpg: Error: ENAMETOOLONG: name too long, symlink '/files/cache/wikishrink/m/1ee736612049d19f8541.jpg' -> '/root/tmp/wikishrink_grown_seed_list_enwiki_2016-06_2017-05/m/2016-05-09_17_23_45_National_Oceanic_and_Atmospheric_Administration_headquarters_at_the_intersection_of_Colesville_Road_(Maryland_State_Route_384)_and_East-West_Highway_(Maryland_State_Route_410)_in_Silver_Spring,_Montgomery_County,_Maryland.jpg'

This corresponds to 

https://en.wikipedia.org/wiki/File:2016-05-09_17_23_45_National_Oceanic_and_Atmospheric_Administration_headquarters_at_the_intersection_of_Colesville_Road_(Maryland_State_Route_384)_and_East-West_Highway_(Maryland_State_Route_410)_in_Silver_Spring,_Montgomery_County,_Maryland.jpg

in the current EN wikipedia

**Comment by kelson42** [comment]
@tim-moody You confirm that behin /files, you have ext4?

**Comment by tim-moody** [comment]
yes

on host OS
timm@nuc ~ $ df -T
Filesystem     Type     1K-blocks     Used Available Use% Mounted on
udev           devtmpfs  16396208        0  16396208   0% /dev
tmpfs          tmpfs      3283520   157184   3126336   5% /run
/dev/sda1      ext4     447674208 96329776 328580864  23% /
tmpfs          tmpfs     16417588     4016  16413572   1% /dev/shm
tmpfs          tmpfs         5120        4      5116   1% /run/lock
tmpfs          tmpfs     16417588        0  16417588   0% /sys/fs/cgroup
cgmfs          tmpfs          100        0       100   0% /run/cgmanager/fs
tmpfs          tmpfs      3283520       16   3283504   1% /run/user/1000
tmpfs          tmpfs      3283520        4   3283516   1% /run/user/1001

oh docker OS
root@aef968c683d9:~# df -T
Filesystem     Type  1K-blocks     Used Available Use% Mounted on
none           aufs  447674208 96329784 328580856  23% /
tmpfs          tmpfs  16417588        0  16417588   0% /dev
tmpfs          tmpfs  16417588        0  16417588   0% /sys/fs/cgroup
/dev/sda1      ext4  447674208 96329784 328580856  23% /files
shm            tmpfs     65536        0     65536   0% /dev/shm
tmpfs          tmpfs  16417588        0  16417588   0% /sys/firmware
root@aef968c683d9:~#

**Comment by tim-moody** [comment]
not sure why I got the cross-outs

**Comment by bradyhunsaker** [comment]
I'm not an expert here, but it looks like many unix-like systems have a symlink limit of 255 bytes, set by _POSIX_SYMLINK_MAX.

The base filename also often has a 255-character limit, but the path can be longer.
In this case the base filename is less than 255 but the full path is longer.

@kelson42 If the diagnosis above is correct, then here are two options.  If you like either one of them, let me know and I'll try to do it.

Proposal A:  check the length before making a symlink and if it is too long use a hashed filename instead.

Proposal B (work-around):  check the length and if it is too long do not cache it.  Just download it every time.  That would be bad for a frequently used image, but may be better than failing.
  Proposal B2: Add a command-line parameter to enable this behavior.  That comes at the cost of an additional parameter, but it protects against a haywire situation in which somehow every image is too long.

**Comment by kelson42** [comment]
Considering that mwoffliner 1.8 writes the ZIM file "on the fly" this kind of problem should not appear anymore
