### ISSUE TITLE
Expected behavior on 404 / Crash of wikipedia_en_movies scraping

### ISSUE THREAD

**Issue by rgaudin** [openzim/mwoffliner#764]
When running `wikipedia_en_movies`, a bunch of articles threw `404` errors (@kelson42 why?)

Result is a `SyntaxError: Unexpected end of JSON input` as the output of probably empty or definitely not an article JSON.

What should be the desired behavior of `mwoffliner` when an article is missing? 

* should the process ignore and continue?
* should it fail?
* should it fail, shouldn't it fail on `4xx` or `5xx` status codes?

```
mwoffliner --adminEmail="contact@kiwix.org" --format="nopic" --format="novid" --mwUrl="https://en.wikipedia.org/" --customZimFavicon="https://upload.wikimedia.org/wikipedia/commons/8/84/Biofilm.png" --customZimTitle="Movies by Wikipedia" --customZimDescription="A selection of Wikipedia articles on movies" --articleList="http://download.kiwix.org/wp1/enwiki/customs/movies" --useCache --redis="redis://redis" --outputDirectory="/output"
```

**Comment by ISNIT0** [comment]
At least some of these failures are not on articles, but on MW setups.
E.g. https://farm.openzim.org/tasks/5cf5360d8b9bc4001ffc44ea
Fails to get `https://awoiaf.westeros.org/w/load.php?debug=false&lang=en&modules=ext.cite.a11y&only=styles&skin=vector&version=&*`
Which is correct, because the proper url is `https://awoiaf.westeros.org/load.php?debug=false&lang=en&modules=ext.cite.a11y&only=styles&skin=vector&version=&*`

Note the `/w/`. There is a zero tolerance for these setup requests to fail, but you're right - the errors should be caught and thrown properly.

This particular mentioned issue can be fixed by setting `--modulePath=load.php` (the default is `--modulePath=w/load.php`)

**Comment by dueni0** [comment]
Also affected by this problem. Where can I set the modulePath argument? I get a "unknown argument: modulePath". Tested with mwoffliner 1.9.2

**Comment by kelson42** [comment]
> Also affected by this problem. Where can I set the modulePath argument? I get a "unknown argument: modulePath". Tested with mwoffliner 1.9.2
```
mwoffliner --help
```

**Comment by ISNIT0** [comment]
@dueni0 Sorry, I suggested the wrong argument, as per `mwoffliner --help`, the correct parameter is `--mwModulePath`

**Comment by kelson42** [comment]
@ISNIT0 The original question is not answer, your comment talks about something else "westeros" and @rgaudin talks about "Movies selection".

**Comment by kelson42** [comment]
> * should the process ignore and continue?

Yes, to a certain extend... but we need a bit of tolerance. Not sure exactly how in detailed this should be handled (command line argument? differenciation beetween pictures and articles ? hardcoded in src?)

> * should it fail?

No, at least not systematically
 
> * should it fail, shouldn't it fail on `4xx` or `5xx` status codes?

Good question!

**Comment by ISNIT0** [comment]
At the end of a scrape, mwo logs the number of successful and unsuccessful articles and images scraped.
I think it's unwise for the scraper to exit on a 4xx or 5xx, they seem to happen every now and again

**Comment by kelson42** [comment]
@Joe We can discuss this, but the problem for now, it that mwoffliner seems to crash, see https://farm.openzim.org/tasks/5d02afb98b9bc40020fc534e

Command

```
mwoffliner --adminEmail="contact@kiwix.org" --format="nopic" --format="novid" --mwUrl="https://en.wikipedia.org/" --customZimFavicon="https://upload.wikimedia.org/wikipedia/commons/8/84/Biofilm.png" --customZimTitle="Movies by Wikipedia" --customZimDescription="A selection of Wikipedia articles on movies" --articleList="http://download.kiwix.org/wp1/enwiki/customs/movies" --useCache --redis="redis://redis" --outputDirectory="/output"
```

Standard Error
```
[error] [2019-06-13T20:33:06.278Z] Error retrieving article: HTTP 404
[error] [2019-06-13T21:09:39.723Z] Error retrieving article: HTTP 404
[error] [2019-06-13T23:54:11.999Z] Error retrieving article: HTTP 404
[error] [2019-06-14T00:43:50.921Z] Error retrieving article: HTTP 404
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to redis:6379 failed - write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:788:14)
Emitted 'error' event at:
    at RedisClient.on_error (/usr/local/lib/node_modules/mwoffliner/node_modules/redis/index.js:406:14)
    at Socket.<anonymous> (/usr/local/lib/node_modules/mwoffliner/node_modules/redis/index.js:279:14)
    at Socket.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at Socket._destroy (net.js:613:3)
    at Socket.destroy (internal/streams/destroy.js:37:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:790:10)
```

**Comment by kelson42** [comment]
@rgaudin I don't know which articles generate exactly the error, see the new ticket I have open specifically for that #818.

**Comment by ISNIT0** [comment]
@kelson42 This seems like a Redis issue. I'm not sure what I can add to this... We use a standard Redis client to connect to the db, noting custom here.

**Comment by ISNIT0** [comment]
The above looks like this now: https://github.com/openzim/mwoffliner/issues/765

**Comment by kelson42** [comment]
I have move the crash we were talking about the last comments to #832

**Comment by kelson42** [comment]
So for now we have all necessary monitoring stuff in MWoffliner. MWoffliner does not crash on 404 because this is a valid scenario which might happen in edge cases.
