### ISSUE TITLE
write EPIPE from Redis

### ISSUE THREAD

**Issue by rgaudin** [openzim/mwoffliner#765]
When running `wikipedia_en_football`, `mwoffliner` crashed with `Redis connection to redis:6379 failed - write EPIPE` which means that redis closed the connection before the end of the write.

Not sure what went wrong:

* did redis crash? the *Flushing Redis DBs* after might indicate that it didn't
* was the content (article?) too big? I doubt it.
* did it reach a memory cap? it's not such a big ZIM but the worker has parallel jobs.

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to redis:6379 failed - write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:779:14)
Emitted 'error' event at:
    at RedisClient.on_error (/usr/local/lib/node_modules/mwoffliner/node_modules/redis/index.js:406:14)
    at Socket.<anonymous> (/usr/local/lib/node_modules/mwoffliner/node_modules/redis/index.js:279:14)
    at Socket.emit (events.js:189:13)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:604:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:781:10)
```

```
[log] [2019-06-02T23:46:31.927Z] Worker [3] Processing batch of [10] article ids
[log] [2019-06-02T23:46:32.231Z] Progress downloading articles [98520/251326] [39.2%]
[log] [2019-06-02T23:46:36.821Z] Worker [2] Processing batch of [11] article ids
[log] [2019-06-02T23:46:36.883Z] Worker [0] Processing batch of [10] article ids
[log] [2019-06-02T23:46:38.660Z] Worker [1] Processing batch of [11] article ids
[log] [2019-06-02T23:46:39.116Z] Worker [3] Processing batch of [11] article ids
[log] [2019-06-02T23:46:44.373Z] Worker [0] Processing batch of [11] article ids
[log] [2019-06-02T23:46:45.891Z] Worker [3] Processing batch of [11] article ids
[log] [2019-06-02T23:46:46.636Z] Worker [1] Processing batch of [10] article ids
[log] [2019-06-02T23:46:46.694Z] Worker [2] Processing batch of [10] article ids
[log] [2019-06-02T23:46:51.511Z] Worker [3] Processing batch of [11] article ids
[log] [2019-06-02T23:46:52.293Z] Worker [1] Processing batch of [10] article ids
[log] [2019-06-02T23:46:52.594Z] Worker [0] Processing batch of [10] article ids
[log] [2019-06-02T23:46:53.070Z] Worker [2] Processing batch of [10] article ids
[log] [2019-06-02T23:47:00.788Z] Worker [1] Processing batch of [10] article ids
[log] [2019-06-02T23:47:01.361Z] Worker [0] Processing batch of [10] article ids
[log] [2019-06-02T23:47:01.900Z] Worker [2] Processing batch of [10] article ids
[log] [2019-06-02T23:47:48.751Z] Exiting with code [1]
[log] [2019-06-02T23:47:48.753Z] Deleting tmp dump dir [/tmp/mwo-dump-1559500595557]
[log] [2019-06-02T23:47:48.815Z] Clearing Cache Directory
[log] [2019-06-02T23:47:48.820Z] Flushing Redis DBs
```

```
mwoffliner --adminEmail="contact@kiwix.org" --format="nopic" --format="novid" --mwUrl="https://en.wikipedia.org/" --customZimFavicon="https://upload.wikimedia.org/wikipedia/en/thumb/e/ec/Soccer_ball.svg/100px-Soccer_ball.svg.png" --customZimTitle="Football by Wikipedia" --customZimDescription="A selection of Wikipedia articles on football" --articleList="http://download.kiwix.org/wp1/enwiki/projects/Football" --useCache --redis="redis://redis" --outputDirectory="/output"
```

cc @automactic @kelson42

**Comment by kelson42** [comment]
@rgaudin Per default mwoffliner looks to Redis via a socket. If you Redis runs locally on a port, you should use the argument `--redis="redis://localhost"`.

**Comment by rgaudin** [comment]
redis is properly configured and worked for thousands of articles before hitting this as the stdout shows.

**Comment by ISNIT0** [comment]
The "Flushing Redis DBs" happens whenever mwo exits (with any code)

**Comment by rgaudin** [comment]
> The "Flushing Redis DBs" happens whenever mwo exits (with any code)

yeah I guess, was wondering if it would throw another error should the connection had been lost completely

**Comment by kelson42** [comment]
@rgaudin Yes REDIS would generate an exception and mwoffliner stop. I'm not so sure what happen here, but I believe this is related to the overall memory problem with had with 1.8.6. I believe we should retry with the mwoffliner 1.9.3 to just see if the error happens again.

**Comment by ISNIT0** [comment]
Could this be related? https://github.com/NodeRedis/node_redis/issues/435

**Comment by kelson42** [comment]
@ISNIT0 @rgaudin We have this in zimwriterfs Dockerfile:
```
# Increase standards system limits
RUN echo "* - nofile unlimited" >  /etc/security/limits.conf
RUN echo "* - stack  unlimited" >> /etc/security/limits.conf
```
... but now that we have lost it, it is not part of mwoffliner Docker image anymore.

With the use of node-libzim with libzim 5.0.0 we should write a lot less files in the fs, do I propose to put the new 3 lines to the mwoffliner Dockerfile and close the ticket and this is this happen again.

**Comment by kelson42** [comment]
@ISNIT0 @rgaudin I have in addition open https://github.com/openzim/zimfarm/issues/239. Can we do more here? Or should be run our improvements to see if the problem occurs again?

**Comment by kelson42** [comment]
I close the ticket, if we still have a problem after openzim/zimfarm#239 is implemented, we could reopen it.
