### ISSUE TITLE
Collapsing of article does not behave like online (1.8.2)

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#786]
Here is an example. Only paragraphe should be collabsable. Here not only the sub-paragraph are collapsable (wrong) but they are collapsed although the paragraph is not (wrong).

![FireShot Capture 017 - Toronto_Harbourfront - localhost](https://user-images.githubusercontent.com/1029718/59159550-79533080-8acb-11e9-8b83-3a4de47c4b18.png)

**Comment by kelson42** [comment]
@ISNIT0 I'm not sure this has been done correctly, I don't have the feeling from the PR that sub-sections are uncollapsable. Could you please confirm?

**Comment by ISNIT0** [comment]
No, they are not "uncollapsable". I believe they were collapsible in previous versions of MWO?

**Comment by kelson42** [comment]
@ISNIT0 I would really be surprised if they were. That is not what is described anyway in the ticket. We really need this collapsable only on top-level like it is on online mobile Wikipedia.

**Comment by kelson42** [comment]
@ISNIT0 OK, so lets try if this "default open" collapsed sub-section annoys a bit other users like me. I will reopen the ticket if this happens. Thanks for the fix.

**Comment by Popolechien** [comment]
Uh just to be clear - a user just complained that top-level section titles were collapsed by default (and it's hard to disagree with him). Am I right to understand that this will be corrected to a wikipedia-like mobile view?
![comparaison](https://user-images.githubusercontent.com/21675885/59604636-02dab200-910d-11e9-96db-4a048296761b.jpg)
@kelson42 's to be honest I'm not sure I even understand the issue you described, as expanded top-level sections and collapsed everything below that seems to be the correct approach :-/

**Comment by kelson42** [comment]
@Popolechien In your screenshot, this is not the top-level section which is collapsed, this is the first paragraph... and this is the normal behaviour: all paragraphs are collapsed if screen width is "small". I have checked with https://de.m.wiktionary.org/wiki/Franse and in that case it is true that online the first paragraph is open.
