### ISSUE TITLE
A DNS cache should be installed in the Docker

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#789]
Considering the large amount of DNS request, this is an easy way to speed-up things.

**Comment by kelson42** [comment]
@ISNIT0 I think using https://www.npmjs.com/package/dnscache within mwoffliner is probably even a better idea. Isn't it?

**Comment by kelson42** [comment]
Ok, just checked, this is already in place.

**Comment by kelson42** [comment]
No, it's not. Valid ticket.

**Comment by ISNIT0** [comment]
I think it makes much more sense to do this on the docker side, than the mwo side

**Comment by kelson42** [comment]
@ISNIT0 What speeks again using `dnscache` ? At a low level this would help a lot of people to benefit transparently of it.

**Comment by ISNIT0** [comment]
It complicates the code with something that really isn't mwoffliner's job. This seems like an OS level task, rather than a scraper task.
I'm trying to keep the MWO codebase as clear as possible. (e.g. we used to handle gzipping and http redirects within MWO, but that's the kind of thing an HTTP library is for)

**Comment by kelson42** [comment]
@ISNIT0 dnscache seems to be already in use by Parsoid? Are you sure the scope of its usage does not impact the rest of mwoffliner already?

**Comment by ISNIT0** [comment]
I suppose it would only make a difference if we were using parsoid locally :)

**Comment by kelson42** [comment]
@ISNIT0 Good point. Thank you for your feedback, will install a DNS cache in Docker.

**Comment by kelson42** [comment]
After discussing with @rgaudin, we decided to abandon this approach in favour of another one: creating a DNS cache (container) with dnsmasq and setup it in the ZIM farm.
