### ISSUE TITLE
mwoffliner reports success when failed and tries to make zim

### ISSUE THREAD

**Issue by tim-moody** [openzim/mwoffliner#79]
mwoffliner 5-18-2017 failed to download any articles (due to api.php action=visualeditor  not supported) but reported

'All articles were retrieved and saved.'

and then tried to build zim

which failed with 'zimwriterfs: unable to find welcome page'

**Comment by tim-moody** [comment]
example:

Getting article from http://wikem.org/w/api.php?action=visualeditor&format=json&paction=parse&page=Venlafaxine&oldid=128911
Error by retrieving article: Unrecognized value for parameter 'action': visualeditor

**Comment by hashworks** [comment]
You should try `--localParsoid`. @kelson42 maybe this should be added as a user tip when that error occurs.

**Comment by hashworks** [comment]
Since `action=visualeditor not supported` usually means one needs `--localParsoid`, maybe that should be added as a help message.

**Comment by kelson42** [comment]
@tim-moody @hashworks yes

**Comment by ISNIT0** [comment]
@tim-moody Could you confirm this is still an issue? Have you tried with `--localParsoid`?

**Comment by tim-moody** [comment]
@ISNIT0 I did try --localParsoid, but I have not tried again since I originally posted.
