### ISSUE TITLE
Only redirects sharing the same namespace as targeted article should taking in account

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#790]
For example, on this https://it.wikivoyage.org/w/api.php?action=query&format=json&prop=revisions|redirects|coordinates&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&rawcontinue=true&rdlimit=max&colimit=1&gapcontinue=Itinerario_delle_cascine_di_Brugherio

Article "Itinerario delle cascine di Brugherio" has a redirect called "Utente:Sofii257/Sandbox". "Itinerario delle cascine di Brugherio" is in namespace 0 and "Utente:Sofii257/Sandbox" in namespace 2. Redirect "Utente:Sofii257/Sandbox" should be ignored.

**Comment by ISNIT0** [comment]
Would it be better to just check that both namespaces are being scraped? We if someone scraped a specific namespace, we could end up losing a lot of useful redirects

**Comment by kelson42** [comment]
@ISNIT0 That is not a bad argument ;) Agree
