### ISSUE TITLE
geo.position HEAD node entries are not written anymore.

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#795]
In `wikivoyage_en_all_novid_2019-04.zim` "Paris" article HTML you can read
```<meta name="geo.position" content="48.856;2.351">```

In a newly created Wikivoyage ZIM file (with 1.9.3-rc2) this entry does not exists anymore.

**Comment by kelson42** [comment]
@ISNIT0 I don't know where is the problem if this is by the retrieving of information or by the writting of the `geo.position` node entry but please create automated tests for both things and let me review the PR.

**Comment by ISNIT0** [comment]
Seems to be being written on master: `<meta name="geo.position" content="48.856;2.351">`

**Comment by kelson42** [comment]
@ISNIT0 Quite sure both code + test are wrong. I will be convinced I we have remade a full Wikivoyage ZIM like reported in the ticket and tested it properly.

```
$./node_modules/.bin/ts-node ./src/cli.ts --mwUrl=https://en.wikivoyage.org --adminEmail=kelson@kiwix.org --format=novid &> /dev/null
$ zimdump -f Paris -d out/wikivoyage_en_all_novid_2019-06.zim  | grep "geo.position"
$
```
