### ISSUE TITLE
Any reason why details-element-polyfill.js is in the code base

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#806]
Instead of being a dependence?

**Comment by ISNIT0** [comment]
This is copied from `res/` to the ZIM file. This is the easier and simpler way to do things.
The alternative is installing it into node_modules, then hard-code a url like `node_modules/details-element-polyfill/dist/index.js` which would be more fragile and possibly give weird errors if node modules haven't been installed

**Comment by kelson42** [comment]
> This is copied from `res/` to the ZIM file. This is the easier and simpler way to do things.
> The alternative is installing it into node_modules, then hard-code a url like `node_modules/details-element-polyfill/dist/index.js` which would be more fragile and possibly give weird errors if node modules haven't been installed.

If node modules are not installed or not fully installed according to the json files, mwoffliner does not work properly anyway? That is why npm checks this properly, isn't it?
 
> It _also_ creates a new vector for someone to maliciously update a dependence

How would that be introduced without going through a PR review?

**Comment by kelson42** [comment]
There is a gold rule in code mgmt: never put into your repo something which is not your source code. This includes:
* automatically generated files
* code belonging to other projects
* ...

**Comment by kelson42** [comment]
I reopen the ticket as we still have a problem here:
```
$ zimcheck out/wikipedia_bm_all_2019-07.zim 
[INFO] Checking zim file out/wikipedia_bm_all_2019-07.zim
[INFO] Verifying Internal Checksum.. 
  [INFO] Internal checksum found correct
[INFO] Searching for metadata entries..
[INFO] Searching for Favicon..
[INFO] Searching for main page..
[INFO] Verifying Articles' content.. 
[INFO] Searching for redundant articles..
  Verifying Similar Articles for redundancies..
[ERROR] Invalid internal links found :
  -/j/node_modules/details-element-polyfill/dist/details-element-polyfill.js (../-/j/js_modules/../node_modules/details-element-polyfill/dist/details-element-polyfill.js) was not found in article A/(ߒߞߏ)
[INFO] Overall Test Status: Fail
[INFO] Total time taken by zimcheck: 2 seconds.
```

**Comment by kelson42** [comment]
@vaibhavmatta This is one which is quite easy and I would really like to get rid of it.

**Comment by Fontirroig** [comment]
Hello @kelson42 this issue was happing due to 
src/util/misc.ts:174 always add the ".js" extension 
that is why 
`jsResources: ['script', 'masonry.min', 'article_list_home', 'images_loaded.min',
                  '../node_modules/details-element-polyfill/dist/details-element-polyfill.js'],`
is not a valid configuration parameter it will add details-element-polyfill.js.js
I created a pull request to solve this issue
