### ISSUE TITLE
Audio links are not removed properly

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#815]
Looking at http://library.kiwix.org/wikipedia_dv_all_novid_2019-06/A/%DE%8B%DE%A8%DE%88%DE%AC%DE%80%DE%A8%DE%83%DE%A7%DE%87%DE%B0%DE%96%DE%AC

The Audio stuff (in the infobox) is still there, it still points to the online resources. It should have been removed like any other video content.

**Comment by ISNIT0** [comment]
Is this related to https://github.com/openzim/mwoffliner/issues/745

**Comment by kelson42** [comment]
Both are wrong: #745 because it points to an not-existing resource in the ZIM and this one because there is no URL rewritting at all. Considering that this is a major problem for Wikimedia dump, this should be fixed and automated tested in 1.9.
