### ISSUE TITLE
Missing article errors should explicit about which article is missing

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#818]
Currently we only see 404 errors, but no clue why (no article name, no URL). For example:
```
[error] [2019-06-13T20:33:06.278Z] Error retrieving article: HTTP 404
[error] [2019-06-13T21:09:39.723Z] Error retrieving article: HTTP 404
[error] [2019-06-13T23:54:11.999Z] Error retrieving article: HTTP 404
[error] [2019-06-14T00:43:50.921Z] Error retrieving article: HTTP 404
```

We should be able to know what kind of content generates these error to carry on with the analysis. See #764

**Comment by ISNIT0** [comment]
@kelson42 This message show when parsing the JSON. This means the response from MW was a full JSON body:
```
{
   error: {
        info: "HTTP 404"
    }
}
```

Which is odd...

I'll update the log too, but it seems like there are other problems. Which wiki is this?
