### ISSUE TITLE
mwoffliner creates an invalid redirect to homepage

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#824]
On WPES scrap log is see the following entry:
```
Invalid redirection index redirecting to (missing) AWikipedia%3APortada
```

Which means that mwoffliner creates an invalid redirection to the home page. I suspect something is wrong in `createMainPageRedirect()`, maybe an escaping problem?

**Comment by ISNIT0** [comment]
Hmmm, it's odd that `:` is being encoded to `%3A`
Seems like it'll probably be a minor fix when I find it :)

**Comment by kelson42** [comment]
@ISNIT0 WPES
