### ISSUE TITLE
Many errors in creation of WPEN movies selection ZIM on zimfarm (1.9.3)

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#828]
See error log at https://farm.openzim.org/tasks/5d089968cde19e001fef23fe ( can don't achieve to copy it)

**Comment by ISNIT0** [comment]
What do you think this means?
```
Impossible to add ABhansali_Productions
  dirent's title to add is : Bhansali Productions
  existing dirent's title is : Sanjay Leela Bhansali
```

**Comment by kelson42** [comment]
@ISNIT0 I don't know. Looks like the libzim says, you are giving incoherent information, so I won't do anything.

**Comment by ISNIT0** [comment]
Ah, I think issue this was fixed by https://github.com/openzim/mwoffliner/commit/e9291b80cabf2079340fa5ae0774bca1241a512b

**Comment by kelson42** [comment]
@ISNIT0 Will try again

**Comment by kelson42** [comment]
Problem is still there, I see a lot of errors like:
```
Impossible to add AKarwaan_(Film)
Impossible to add AAndagaadu
Impossible to add AJeff_Gillen
Impossible to add AEmpire_award_for_best_soundtrack
Impossible to add ABest_soundtrack_empire_award
Impossible to add ALorraine_McFly
Impossible to add AJennifer_Parker
Impossible to add ASeamus_and_Maggie_McFly
Impossible to add AThe_Small_Miracle
Impossible to add ARao_Gopalrao
Impossible to add ATales_of_a_Sea_Cow
Impossible to add ASLB_Films
Impossible to add ABhansali_Productions
Impossible to add AKaren_Klein
Impossible to add AI_Think,_They_Call_Him_John
Impossible to add ARaakilipattu
Impossible to add AUn_dollaro_bucato
Impossible to add AChris_Newman_(sound)
Impossible to add AList_of_awards_and_nominations_received_by_Elle_(film)
Impossible to add AShrek_(series)
Impossible to add AShrek_5
Impossible to add APuss_in_Boots_2:_Nine_Lives_&_40_Thieves
Impossible to add AStuck!_(film)
Impossible to add AStuck!
```

**Comment by ISNIT0** [comment]
This is now reporting a different message (`not printing dirent's title to add is` etc.) Any idea what is causing this?

**Comment by kelson42** [comment]
No, but I tend to think that we might handle these kind of errors reported by the libzim more seriously. Do you have a scenario in mind for which it does not lead to MWoffliner?

**Comment by ISNIT0** [comment]
I'm trying to handle them seriously, but the error message has no content. I have absolutely no idea of the context, or what is stopping libzim from writing the article (or maybe it's a redirect??).

**Comment by kelson42** [comment]
What I mean with "seriously" is that the whole process should maybe just stop?

**Comment by ISNIT0** [comment]
At the moment, these warnings are just logs, the C++ call does not throw an error, so we couldn't detect it from `node-libzim` if we were trying. For it to be handled more thoroughly, we'll need some C++ changes

**Comment by kelson42** [comment]
@ISNIT0 OK, that is unfortunate. Lets keep it like it is for now... but we still need to fix the bug

**Comment by ISNIT0** [comment]
What is the bug?

**Comment by kelson42** [comment]
@ISNIT0 The one reported in a first place: we send dubious/wrong data to the libzim (or the libzim is buggy here - what I doubt).

**Comment by ISNIT0** [comment]
The original problem is fixed: https://github.com/openzim/mwoffliner/issues/828#issuecomment-505354028

**Comment by kelson42** [comment]
@ISNIT0 You don't believe that if the libzim reports `Impossible to add AAndagaadu` then we have a bug?

**Comment by ISNIT0** [comment]
I do, but that is not the original bug report.

I have no idea what this new second bug report is, because the logs have no context.

**Comment by kelson42** [comment]
@ISNIT0 At least we agree now there is a bug. To verify if the bug was fixed I just have checked if I had again "Impossible to add" with the exact same MWoffliner command because this is basically what I complain about. For the bug, it will be resolved when the libzim stops complaining because mwoffliner send wrong/incoherent information to it. If you need more information from me because you have difficulties to reproduce the bug, please let me know. If you are stuck, then please like usual tell upstream (here @mgautierfr).

**Comment by ISNIT0** [comment]
To me, this is a different bug.
The original report was: 

```
Impossible to add ABhansali_Productions
  dirent's title to add is : Bhansali Productions
  existing dirent's title is : Sanjay Leela Bhansali
```

This new report is just a single line.

**Comment by ISNIT0** [comment]
Need more information before being able to debug this: https://github.com/openzim/libzim/issues/242

**Comment by kelson42** [comment]
@ISNIT0 I recommand to just run 
```
./node_modules/.bin/ts-node ./src/cli.ts --adminEmail="contact@kiwix.org" --format="nopic" --format="novid" --mwUrl="https://en.wikipedia.org/" --customZimFavicon="https://upload.wikimedia.org/wikipedia/commons/8/84/Biofilm.png" --customZimTitle="Movies by Wikipedia" --customZimDescription="A selection of Wikipedia articles on movies" --articleList="http://download.kiwix.org/wp1/enwiki/customs/movies" --verbose &> movies.log
```

and inspect the log, you will have more information.

**Comment by ISNIT0** [comment]
I've been running the above command. so far no warnings from libzim (60% through zim creation)

**Comment by kelson42** [comment]
I can easily reproduce one of the scenarios explaining that kind of error, this is because of a bad redirect mgmt. Here the reprocase:
```
$ cat articles 
Enter_The_Pitch
Pinewood_Studios
$ mwoffliner --mwUrl=https://en.wikipedia.org/ --adminEmail=kelson@kiwix.org --verbose --articleList=articles
```

We might have a bug upstream, but this kind of case can really happen even if we have an other bug upstream, see https://github.com/openzim/wp1_selection_tools/issues/18

**Comment by ISNIT0** [comment]
So what is the solution? ignore redirects?

**Comment by kelson42** [comment]
@ISNIT0 I propose to make the request for article details (only if we have a hardcoded list given) able to detect if this is a redirect. If this is a redirect, then find the target and add it to the list of articles to mirror (if not already in the list). I would be OK to create a dedicated ticket and move it to the 2.0 milestone, if this is what you want.

**Comment by ISNIT0** [comment]
Okay, this makes sense.
I'd quite like to get 1.9 done soon, so probably makes sense to move to 2.0

**Comment by kelson42** [comment]
@ISNIT0 I have created #889. We also have had a successful run to scrap this WPEN movie selection on the zimfarm with `1.9.4` :)
