### ISSUE TITLE
Russin desktop main page rendering in-correctly

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#841]
With 1.9.3. Look for example homepage of https://download.kiwix.org/zim/wikipedia/wikipedia_ru_all_novid_2019-06.zim

**Comment by ISNIT0** [comment]
I've run a simple scrape of the RU main page (because I don't want to download a 25Gb file to test the full ZIM). The article looks odd, but it actually starts as the desktop version.

If this is an issue, it's not a regression, and should be renamed to something like "RU desktop main page rendering poorly"

**Comment by kelson42** [comment]
@ISNIT0 Will make the content visible online, but if this is "desktop", we have a serious problem because it does not look at all like the online desktop version.

**Comment by kelson42** [comment]
This is it: http://library.kiwix.org/wikipedia_ru_all_novid/A/%D0%97%D0%B0%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0

Here how the desktop looks like online: https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0

Like we can see, two fundamentally different rendering!

**Comment by ISNIT0** [comment]
Yes, this is what I saw...

> Ishould be renamed to something like "RU desktop main page rendering poorly"

**Comment by kelson42** [comment]
@ISNIT0 If this is the desktop rendering, why we do have a regression here? If we compare with `wikipedia_ru_all_novid_2018-07.zim` this was fine before.

**Comment by ISNIT0** [comment]
I've just done a scrape with 1.7.1 and the output looks very similar to with 1.9
I believe the content has changed in a way that has broken the rendering in MWO

**Comment by kelson42** [comment]
I hardly believe that. Hard facts would help IMO.

**Comment by ISNIT0** [comment]
The problem is caused by overly specific inline CSS on the WPRU side. This is not an MWO bug.

**Comment by kelson42** [comment]
@ISNIT0 This when inline CSS is a problem for MWoffliner?
