### ISSUE TITLE
Audio/Video within blacklisted CSS containers is still downloaded

### ISSUE THREAD

**Issue by ISNIT0** [openzim/mwoffliner#849]
Take this html:
```html
<div class='noprint'>
    <audio><source src='...'/></audio>
</div>
```

The source url is added to the list of medias to download in pre-processing, but the element itself is removed later in the treatment process. This means we download the content, but it's not visible

**Comment by vaibhavmatta** [comment]
Sir, Should I start resolving this issue now?

**Comment by kelson42** [comment]
@vaibhavmatta Would be great! May you please exolain first what would be your approach to solve this problem?

**Comment by vaibhavmatta** [comment]
Thanks alot @kelson42 sir.! I think I am capable of working on many bugs simultaneously. I will reply for resolving strategies as fast as I can.

**Comment by kelson42** [comment]
@ISNIT0 I let you handle tech. details with @vaibhavmatta.

**Comment by ISNIT0** [comment]
My recommendation would be to apply the blacklists/html processing before extracting the urls.

This would be done by re-ordering the calls to `processArticleHtml`, `getModuleDependencies`, and `templateArticle`: https://github.com/openzim/mwoffliner/blob/master/src/util/saveArticles.ts#L90
I'm not sure it it'll just work, or need further tweaking

**Comment by vaibhavmatta** [comment]
Yes, That's what I was exactly thinking @ISNIT0
