### ISSUE TITLE
Picture not correctly aligned to the right with --mobileLayout

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#85]
If I have a look to this article with mobile view:
https://en.m.wikipedia.org/wiki/Elastic_bandage

We see the picture (with Legend "US elastic bandage, used in Vietnam War Era") right aligned.

Unfortunately this is not the case in the offline version (with --mobileView activated in mwoffliner), the picture is in the middle of the page and the text is not wrapped around.

**Comment by ISNIT0** [comment]
--mobileLayout seems to be behaving properly, it's the HTML returned by MW that's not right:
Desktop Version:
![image](https://cloud.githubusercontent.com/assets/5173131/26570907/daad112e-450a-11e7-9049-ec392e15fca1.png)

Mobile Version:
![image](https://cloud.githubusercontent.com/assets/5173131/26571148/4d705ac6-450c-11e7-9bcb-617fb282d4f5.png)


Data from MWApi:
![image](https://cloud.githubusercontent.com/assets/5173131/26571122/2450c590-450c-11e7-891b-5dbe1afb3222.png)

As I see it, our options are:

1. Add custom styles to .mwAw (may break other things)
2. Some kind of hack where we right-align the first image that appears (will probably break things)
3. Hackily strip out the image from text and add in JSON.image.file in a custom way (may break itself)
4. Nothing

Awaiting orders, cap'n

**Comment by kelson42** [comment]
@ISNIT0 Can we mockup how it works online? The online mobile-view version works fine (click on "Mobile view" link a the bottom of the page if you use desktop). Please also do not forget that the DOM (around IMG) is transformed here (I suspect) by the mwoffliner, so I suspect this modifications break the rendering (assuming all the correct CSS is there).

**Comment by kelson42** [comment]
I have fixed this.
