### ISSUE TITLE
Improve e2e tests by checking output

### ISSUE THREAD

**Issue by ISNIT0** [openzim/mwoffliner#851]
From @kelson42 (https://github.com/openzim/mwoffliner/pull/847#issuecomment-505507182)
>  I propose to make a run (of the article details retrieval part) on a small wiki and check afterward that the values in the redis are ok:
> - Good number of articles
> - Good number of redirects
> - Good number of geo coordinates
> - whatever else is retrieved at that time from the query api.
>
> That way we secure that we will never again make a scrape and forgetting a big part.

I'd like to do this using `node-libzim` as part of the e2e tests. There is already some commented out code. For now (until `node-libzim` is improved enough) we can do it with MWO's reported file status.

**Comment by kelson42** [comment]
The goal of my request was to verify that article detail retrieval works fine. That means:
* All articles of namespaces are correctly evaluated
* all properties are properly read: redirects, geo-coordinates, etc...
* Good amount of requests

This should be doable in an isolated manner - not at e2e level. I don't see why this should be tested at e2e level and why we talk about ZIM for that request.

**Comment by kelson42** [comment]
Implementing this like requested would probably have achieved to catch half of #899 problem.

**Comment by kelson42** [comment]
@ISNIT0 I would like to discuss with you what should still be done here. I'm not comfortable if we leave massive potential regression potential open previously to 2.0 dev.

**Comment by ISNIT0** [comment]
@kelson42 I just realised we are fully checking the output with `zimcheck`, not sure this is still required.

**Comment by kelson42** [comment]
@ISNIT0 zimcheck should be kept as last barrier in the e2e tests... but this does not exempt of witting proper unit tests.

**Comment by ISNIT0** [comment]
There are unit tests for redirects, geo meta, etc. I'm not sure exactly what this ticket represents...
