### ISSUE TITLE
Empty paragraphs are kept

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#857]
They should not, except if `--keepEmptyParagraphs` is specified. I don't know at which point this regression as been introduced.

**Comment by kelson42** [comment]
Not working in my test, article "Western_Greenland" of Wikivoyage English has the paragrphaph "See" (which is empty).

I think there is a fundamental weakness in your unit testing on this because you have your own HTML, and not the HTML produced by Mediawiki... so you have no garanty that it will work in a real case. IMO all this parsing test, should be based on a Mediawiki generated source code.

**Comment by ISNIT0** [comment]
Okay, so this was me not understanding what it was supposed to do (https://github.com/openzim/mwoffliner/pull/861#issue-293447050)
Seems we're supposed to remove sections, not paragraphs.

**Comment by kelson42** [comment]
It should work at any level.

**Comment by kelson42** [comment]
I reopen the ticket we still have empty paragraphs. See for example "Klima" at http://library.kiwix.org/wikivoyage_de_all_maxi/A/Vend%C3%A9e
