### ISSUE TITLE
Articles not hyperlinked if link contains a space in wikivoyage_en_all_novid_2019-06.zim

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#858]
Compare the screenshot for the United States of America article from wikivoyage online and this ZIM. You can see that all the names of places that have a space in the name are not hyperlinked. The underlying article exists (it can be found by searching), but clearly something is going wrong with the hyperlinking still.

Online version:
![image](https://user-images.githubusercontent.com/4304337/60397896-f19c9700-9b49-11e9-8b1e-ec0b28a092b0.png)

ZIM version:
![image](https://user-images.githubusercontent.com/4304337/60397910-16910a00-9b4a-11e9-8e5d-291fb98ac282.png)

**Comment by kelson42** [comment]
@Jaifroid Thx, probably the same as #729

**Comment by kelson42** [comment]
@ISNIT0 says  " I've also tried to reproduce https://github.com/openzim/mwoffliner/issues/858 with no success."

**Comment by kelson42** [comment]
@ISNIT0 Have you run the scraper command like it is run on the ZIMfarm?

**Comment by ISNIT0** [comment]
No, the comment was in the other PR because I was trying to reproduce it in a test environment, not by running the command

**Comment by kelson42** [comment]
@ISNIT0 Ok, please try do so.

**Comment by kelson42** [comment]
I can not reproduce the problem now. @Jaifroid I have a bad feeling here were people keep reporting this kind of problems, but we fail to reproduce it. I really hope the bug is finally fixed... but I'm happy if you check twice that in the future. Thx again for this ticket.
