### ISSUE TITLE
Wiktionary subsection headings are wrongly displayed

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#872]
Tested on ar.wiktionary_nopic_2019_06 on Android - Some section headings are not displayed in arabic but as actual code:
![sublevel](https://user-images.githubusercontent.com/21675885/60644016-2607a000-9e35-11e9-83da-1d6a928eccc2.jpg)

**Comment by ISNIT0** [comment]
I can't find an article with lots of sections on `ar.wiktionary.org`, and I've no hope of typing that article title. How did you get to that page? Or if possible, could we get the article title somewhere I can copy it

**Comment by Popolechien** [comment]
I've randomly clicked on links but look at #884, which for instance discusses [أَرَادَ](https://ar.wiktionary.org/wiki/%D8%A3%D9%8E%D8%B1%D9%8E%D8%A7%D8%AF%D9%8E)

**Comment by Popolechien** [comment]
Also here the word is [طَلَبَ](https://ar.wiktionary.org/wiki/%D8%B7%D9%8E%D9%84%D9%8E%D8%A8%D9%8E) I think

**Comment by ISNIT0** [comment]
Looks like the data coming back from MCS is a bit odd.
I've opened a ticket on Phabricator: https://phabricator.wikimedia.org/T227586

The data coming back from those queries on AR look different to on EN: https://en.wiktionary.org/api/rest_v1/page/mobile-sections/scusarvi

**Comment by ISNIT0** [comment]
I don't think this should be in the 1.9 milestone

**Comment by kelson42** [comment]
Ticket has been closed upstream, with explanation, but seems to work properly on there side.

**Comment by ISNIT0** [comment]
This is not a new bug on our end.

**Comment by kelson42** [comment]
@ISNIT0 Just a reminder: this milestone "1.9-milestone" has been created - although it was not on the agenda - and just to get Wikimedia scraping working properly. Nothing more, nothing less. Here we have a serious rendering issue which seems to me relatively easy to fix. So except if there is a really good reason why we could not fix that bug, I want to have fix before we start on 2.0.
