### ISSUE TITLE
Wikivoyage DE homepage is not displayed properly

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#873]
Here is how it looks like after a scrape with git master head:
![FireShot Capture 021 - Hauptseite - localhost](https://user-images.githubusercontent.com/1029718/60667336-96c8af80-9e69-11e9-9ef9-96089fa215f8.png)

To be compared to https://de.wikipedia.org/wiki/Wikipedia:Hauptseite

**Comment by ISNIT0** [comment]
It seems the live page (https://de.wikivoyage.org/wiki/Hauptseite) has lots of inline styles in the article `<head>`.
This inline style isn't returned by the visual editor api: https://de.wikivoyage.org/w/api.php?action=visualeditor&mobileformat=html&format=json&paction=parse&page=Hauptseite

**Comment by ISNIT0** [comment]
@kelson42 What's the sensible thing to do in this case?

**Comment by kelson42** [comment]
@ISNIT0 I don't see anything special with that page in the wiki code. This is a standard Wikivoyage page. We should not consider this "inline style" as an exception, but as something which should be supported. It as working before, it should still work. Or do we have a technical problem here?

**Comment by ISNIT0** [comment]
The api doesn't return the inlined styles, I'm not sure how else to get it...

**Comment by kelson42** [comment]
@ISNIT0 Which nodes are we talking about exactly? Can you copy there please?

**Comment by ISNIT0** [comment]
In the `<head>` element on this page: https://de.wikivoyage.org/wiki/Hauptseite
There are 7 `<style>` elements. Normally the css is exposed as modules, which we then have access to, but in this case we don't

**Comment by kelson42** [comment]
@ISNIT0 I don't see any `<style>` element. Please copy them here.

**Comment by ISNIT0** [comment]
Looks like these style elements aren't causing this specific issues (though might cause other issues).
The most important thing now is that the API returns no style modules: https://de.wikivoyage.org/w/api.php?action=parse&format=json&page=Hauptseite&prop=modules%7Cjsconfigvars

The specific module we need is `site.styles`, but this isn't returned for the article

**Comment by ISNIT0** [comment]
I don't think this is a 1.9 issue

**Comment by ISNIT0** [comment]
https://phabricator.wikimedia.org/T232092
