### ISSUE TITLE
Mediawiki video subtitles should be scraped too

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#877]
See for example https://commons.wikimedia.org/wiki/File:Carcinoid_syndrome.webm. It has arabic subtitle. Article of WPEN integrates it https://en.wikipedia.org/wiki/Carcinoid_syndrome. Currently the subtitle links are in the HTML code, but the subtitles files are not downloaded and URL not rewritten.

**Comment by kelson42** [comment]
@bakshiutkarsha This one is trivial IMO.

**Comment by bakshiutkarsha** [comment]
The example mentioned above seems to be quite outdated, as the video no longer exists on that article. I tried to find videos with subtitle(which are getting used in some article) using:
https://commons.wikimedia.org/w/index.php?title=Special:Search&search=haswbstatement%3AP180%3DQ309440&ns0=1&ns6=1&ns12=1&ns14=1&ns100=1&ns106=1

But so far I am not able to get any. Any new example would be very much helpful.

**Comment by kelson42** [comment]
@kelson42 I have create a page with this video https://en.wikipedia.org/wiki/User:Kelson/test. Hope that helps.

**Comment by bakshiutkarsha** [comment]
@kelson42 Thanks for creating the page, it is really helpful. I checked the HTML for this page and original wikipedia is fetching the subtitles by calling an API :
https://commons.wikimedia.org/w/api.php?action=timedtext&title=File%3ACarcinoid_syndrome.webm&lang=ar&trackformat=srt&origin=%2A

So, when MWoffliner is scraping this article, it is not getting the corresponding DOM element for subtitles, instead it is trying to set the API as "src" of track tag. 

Were we assuming that the subtitle would be present as a link or are we supposed to  make the API call to get the subtitle?

**Comment by kelson42** [comment]
@bakshiutkarsha I see the subtitle at https://en.wikipedia.org/api/rest_v1/page/html/User:Kelson%2Ftest :
```
<track kind="subtitles" type="text/x-srt" src="//commons.wikimedia.org/w/api.php?action=timedtext&amp;title=File%3ACarcinoid_syndrome.webm&amp;lang=ar&amp;trackformat=srt&amp;origin=%2A" srclang="ar" label="العربية (ar) subtitles" data-mwtitle="" data-dir="rtl" id="mwEw">
```

**Comment by kelson42** [comment]
@bakshiutkarsha Like expected, in the mobile version as well https://en.wikipedia.org/api/rest_v1/page/mobile-sections/User:Kelson%2Ftest
