### ISSUE TITLE
Wikipedia has issues

### ISSUE THREAD

**Issue by m-anish** [openzim/mwoffliner#878]
I don't know if this issue belongs here (probably not), but the latest official kiwix zim version for wikipedia has issues where many country pages don't load properly. 

Example:
http://iiab.me/kiwix/wikipedia_en_all_novid_2018-10/A/India.html

**Comment by kelson42** [comment]
@m-anish Thank you for this bug report, we hope to have fixed that problem of missing pictures already. Should be OK in next ZIM.

**Comment by holta** [comment]
> @m-anish Thank you for this bug report, we hope to have fixed that problem of missing pictures already. Should be OK in next ZIM.

Thanks @kelson42.  What's the original / duplicate tkt here, if possible?

**Comment by kelson42** [comment]
@holta One I have in mind is #496. We have many reasons why a picture might be missing in the ZIM file and the current situation is that we are not aware about a problem on our side so far (all we have identified are fixed). That said, I'm sure this is still not perfect. Let us know if you have problems with newer ZIM files.
