### ISSUE TITLE
[Regression] Something looks very wrong with the Arabic Wiktionary

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#884]
Comparing the Arabic Wiktionary for أَرَادَ (to want) with wiktionary_ar_all_novid_2019-06.zim and wiktionary_ar_all_novid_2019-05.zim
Note: the original article hasn't changed since 2018
![comparison](https://user-images.githubusercontent.com/21675885/60816856-e1646780-a19a-11e9-892d-68106b407d9f.jpg)

The first issue is that ``Disambiguation`` and ``__SUB_LEVEL_SECTION_-1`` should not be there.

The second problem is that a table of conjugations has appeared out of nowhere between the two dates where zim files where generated (I've seen similar tables in other articles).

**Comment by ISNIT0** [comment]
Should the table be there or not?

**Comment by Popolechien** [comment]
Ah yes, never mind, it's actually a subsection that's unfolded. If you go to [the article](https://ar.wiktionary.org/wiki/%D8%A3%D9%8E%D8%B1%D9%8E%D8%A7%D8%AF%D9%8E) and click on the one word below the red book, it unfolds and the table appears. 
Ok, so one less problem, I guess the ticket is now redundant with #872 and I will close it.
