### ISSUE TITLE
Lots of issues with JavaScript

### ISSUE THREAD

**Issue by ISNIT0** [openzim/mwoffliner#894]
JavaScript scraping seems broken, I think it has been for quite a while.

- JSConfigVar (`mw.config.set`) calls have been moved to the footer, from the header. Meaning the existing code for scraping that is not doing anything
- `hackStartUpModule` breaks startup.js
- for mobile we need to request the normal `startup` module as well as `mobile.startup` 
- module requests need `target=mobile` adding

**Comment by ISNIT0** [comment]
I spent quite a few hours on this last week with little progress. I got stuck on importing OOJS using the MW api, the live sites don't seem to request it in an obvious way, but it's depended upon by the code.

**Comment by kelson42** [comment]
@ISNIT0 Considering that this looks like to have a serious impact on the way page are rendered. I would like to have here a complete (from the user impact to the root cause) and detailed explanation about the problem. Then we should try to gather third party opinion about it.

**Comment by vaibhavmatta** [comment]
Is anyone working on this issue now? Please confirm, else, I will start resolving this issue.

**Comment by kelson42** [comment]
@vaibhavmatta Thx for your offer. AFAIK this is a quite complex one. Please explain first what would be your approach to solve it.

**Comment by Jaifroid** [comment]
We should un-stale this. These are the errors that show in Kiwix JS for any Media Wiki ZIM (running in SW mode). Very similar to those reported by @tim-moody in #1242 :
```
Uncaught SyntaxError: Unexpected end of input
startup.js:11 Uncaught SyntaxError: Unexpected token '.'
jquery.js:144 JQMIGRATE: Migrate is installed with logging active, version 3.1.0
jquery.js:156 Uncaught ReferenceError: mw is not defined
    at VM36 jquery.js:156
(anonymous) @ jquery.js:156
mediawiki.js:1 Uncaught ReferenceError: mw is not defined
    at VM37 mediawiki.js:1
(anonymous) @ mediawiki.js:1
site.js:1 Uncaught ReferenceError: mw is not defined
    at VM38 site.js:1
(anonymous) @ site.js:1
ext.cite.ux-enhancements.js:1 Uncaught ReferenceError: mw is not defined
    at ext.cite.ux-enhancements.js:1
    at ext.cite.ux-enhancements.js:1
(anonymous) @ ext.cite.ux-enhancements.js:1
(anonymous) @ ext.cite.ux-enhancements.js:1
mediawiki.page.gallery.js:4 Uncaught ReferenceError: mw is not defined
    at mediawiki.page.gallery.js:4
    at mediawiki.page.gallery.js:5
(anonymous) @ mediawiki.page.gallery.js:4
(anonymous) @ mediawiki.page.gallery.js:5
ext.scribunto.logs.js:1 Uncaught ReferenceError: mw is not defined
    at ext.scribunto.logs.js:1
(anonymous) @ ext.scribunto.logs.js:1
```

**Comment by kelson42** [comment]
This ticket is very old. I would like to see a refresh and have more concrete errors, actually one ticket per error would be better. Closing.
