### ISSUE TITLE
[REGRESSIONS] Redis memory consumption is far too high

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#899]
I don't understand what is exactly going on here... but we have a waste of memory (in comparison to earlier version I have coded) by at least a factor x10 I guess.

I also see this kind of things in the redis:
```
{"pageid":12612419,"ns":0,"title":"Drown  in My Own Tears","redirects":[{"pageid":13209454,"ns":0,"title":"Drown  In My Own Tears"},{"pageid":14367420,"ns":0,"title":"Drown in my own  tears"},{"pageid":41493354,"ns":0,"title":"I'll Drown in My Own  Tears"}],"revisions":[{"revid":870146860,"parentid":864011370,"user":"86.147.194.118","anon":"","timestamp":"2018-11-22T18:41:50Z","comment":"/*  Other recordings */"}]}
```

Most of this should never be in the Redis, we only need title, revisionid, (date?) coordinates.

**Comment by kelson42** [comment]
I tried to figure out what went wrong here... and can not find out... it seems this is a really old massive bug.

**Comment by ISNIT0** [comment]
Do you think this affects the performance a lot?

**Comment by kelson42** [comment]
@ISNIT0 Obviously yes. Worse this is a blocking issue as we will never be able to run WPEN full dump with 16GB of RAM with such a bug. This really disappointing to understand (if my analysis is right) today that as Matthieu was revamping the writing process in the libzim to save memory in May, at the same time MWoffliner was (and still is) just putting in memory what looks like to be GB of data without any reason.

**Comment by kelson42** [comment]
@ISNIT0 I think most - if not all the regressions - have been introduced in 1.9. I say "regressions" with a "s", because many things which were properly done (I mean working and memory efficient) have been rewritten in a memory intensive manner:
* keys have been changed from a charecter string to a full character strings
* Images URLs are now saved with the full URLs (it was not). You multiply this by 50.000.000 entries you can figure the impact of that.
* many useless fields have been written in the Redis, at least in the "details" table.

**Comment by ISNIT0** [comment]
I don't think this came in in 1.9.
Probably 1.8 or 1.7

**Comment by kelson42** [comment]
The problem which is about the "details" table is trivial, I think it simply has to be done like before with (1) short key names (2) only the absolute necessary. The problem around full media URL is a bit more subtitle, it looks like it has been done in a generic mode (which is good) but this came at a price of an extremly higher memory consumption (which is bad). A better compromise solution could be found IMO, but we need to discuss it first here as I see nothing completely trivial.

**Comment by kelson42** [comment]
Re-opening the ticket, we still need to have a look to the "media" Redis entry
