### ISSUE TITLE
Achieve to get WPEN medical videos displayed

### ISSUE THREAD

**Issue by WikiDocJames** [openzim/mwoffliner#900]
We have https://en.wikipedia.org/wiki/MediaWiki:Offline.css

Which is used here as an example

https://en.wikipedia.org/w/index.php?title=Carcinoid_syndrome&diff=892173610&oldid=863033018&diffmode=source

Not sure the steps required for this to be followed by mwoffliner.

**Comment by kelson42** [comment]
@WikiDocJames I think you are quite lucky. I finally have found a "hack* which is easy and not too stinky.

**Comment by WikiDocJames** [comment]
Perfect :-)
