### ISSUE TITLE
--useCache should rely only on the fs

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#908]
like in older version and not on Redis like in 1.9.

**Comment by kelson42** [comment]
Like I have reported 2 times on the PR which was merged without my review: The cache is deleted at the end of the run, it should not. Please also secure that --skipCacheCleaning works fine.

**Comment by ISNIT0** [comment]
I don't see the issue.
When using just `--useCache`, the cache is written to, then deleted.
when using both `--useCache` and `--skipCacheCleaning`, the cache is written to and not deleted.
I have found a bug that the log "Clearing Cache Directory" was outside the `if`, so was being logged regardless of `--skipCacheCleaning`, but the cache is behaving correctly (as far as I can see)

**Comment by kelson42** [comment]
I don't know how to phrase it better: `--useCache` should not delete any file at the end, this is how I want it to work to be able to benefit from the cache between two runs. This is how it was working.

Here is how `--skipCacheCleaning` should work and has worked (comes from the usage()):
```
 --skipCacheCleaning        Do not search for old/outdated files in the cache
```

None of the option can/should fully delete the cache content, this has to be done manually if the user want.

**Comment by ISNIT0** [comment]
I think we need to have a call about this.

**Comment by kelson42** [comment]
@ISNIT0 I'm unsure if there is still work to do to finalize our decision of:
* Removing `--skipCacheCleaning`
* Securing the that cache directory is not emptied at the end of the process.

Maybe this ticket could be closed now?

**Comment by ISNIT0** [comment]
@kelson42 Once the pull request is closed :)
