### ISSUE TITLE
Create a Zim file of encyclopediaofmath.org.

### ISSUE THREAD

**Issue by ScyllaHide** [openzim/mwoffliner#91]
Hi,

i would like to have a zim file of encyclopediaofmath.org for offline use.

"The Encyclopedia of Mathematics wiki is an open access resource designed specifically for the mathematics community. The original articles are from the online Encyclopaedia of Mathematics, published by Kluwer Academic Publishers in 2002. With more than 8,000 entries, illuminating nearly 50,000 notions in mathematics, the Encyclopaedia of Mathematics was the most up-to-date graduate-level reference work in the field of mathematics."

not sure if the MathJax and Latex rendering is a problem.

thank you!

**Comment by kelson42** [comment]
Sounds doable will try to have a look. That said, the welcome page seems to rely pretty much on categories and for now we do not mirror them.

**Comment by ScyllaHide** [comment]
for me it is only important to have a way to search for all articles.
like "Lie Algebra" and then i should all result which are in their database. Not sure if this is doable.
I dont use categories anyway (not sure how others see this?)

thank you!

**Comment by kelson42** [comment]
This issue was moved to openzim/zim-requests#92
