### ISSUE TITLE
Slashes in URL are not encoded properly on welcome page

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#911]
Juste mirroring "User:Kelson/MWoffliner_CI_reference" on WPEN and then having a list of one item in the welcome page. Unfortunately the link has the slashes encoded.. so the content is then not displayed properly.

**Comment by Jaifroid** [comment]
@kelson42 I wonder if this is related:

In the ZIM you made for the article Piracetam, which also has just one item on the landing page, the href of the single link is `<a href="Piracetam">Piracetam</a>`, but clicking on it fails to find the dirEntry. No slashes here, but the reason for the failure is that the dirEntry.url is `piracetam` (lowercase). I had to search for the article to find it.

**Comment by kelson42** [comment]
@Jaifroid It is not related. For the `Piracetam`, the entry in the `articleList` was lowercase and because Wikipedia is configured to deal with both `Piracetam` and `piracetam` in the same manner (= load `Piracetam`) and that MWoffliner does not check anything here we had the problem. In fact this is an other weakness in MWoffliner... but not so sure we could say this is a bug.
