### ISSUE TITLE
Interwiki links not visually different

### ISSUE THREAD

**Issue by rgaudin** [openzim/mwoffliner#914]
Not sure it's systematic but at least on Wikibooks, external links appear as links but with no visual distinction with in-zim links (or maybe it's there but too subtle).

You can check by looking at the first link (_Astronomy_) in the top box [on kiwix-serve](http://library.kiwix.org/wikibooks_en_all_nopic/A/Shelf%3AAstronomy).

It's a link to WPEN so maybe this affects only wikimedia-related links? Anyway, for ZIM users, those are external.

Given the number of tools we have to read ZIM files, we can't assume any specific behavior for external links so a visual distinction would really help.

**Comment by kelson42** [comment]
Concrete example "Main_Page", the link to the Wikimedia Foundation looks like:
```
<a href="https://en.wikipedia.org/wiki/Wikimedia%20Foundation" title="w:Wikimedia Foundation" class="null">Wikimedia Foundation</a>
```

Because it does not have the `external` class, it does looks like an internal link, although from the offliner reader perspective it is an external link.

The reason behind is that this link is not an external link from the Mediawiki/Parsoid perspectiv, this is an interwiki links (=a link within the Wikimedia wikis galaxy).

**Comment by kelson42** [comment]
Backend output gives:
```
<a rel="mw:WikiLink/Interwiki" href="https://en.wikipedia.org/wiki/Wikimedia%20Foundation" title="w:Wikimedia Foundation">Wikimedia Foundation</a>
```

So if `rel="mw:WikiLink/Interwiki"` we should just add the "external" class if this happens.

**Comment by kelson42** [comment]
In fact this is a regression, here is something I have seen in an older version `dbf2773`:
```
            /* Add 'external' class to external links */
            if (rel.substring(0, 10) === 'mw:ExtLink' || rel === 'mw:WikiLink/Interwiki') {
              DU.appendToAttr(linkNode, 'class', 'external');
	    }
```

**Comment by ISNIT0** [comment]
Interestingly on Wikinews I *am* seeing the external link icon (On Kiwix Mac)
<img width="347" alt="image" src="https://user-images.githubusercontent.com/5173131/61946776-63c29900-af9b-11e9-92bb-d0a5ee66d2ea.png">

**Comment by ISNIT0** [comment]
> In fact this is a regression, here is something I have seen in an older version

This code still exists

**Comment by kelson42** [comment]
Then something has changed an make it not working anymore, because it was.

**Comment by ISNIT0** [comment]
My screen shot shows it working from master

**Comment by kelson42** [comment]
@ISNIT0 Please test what has been reported by @rgaudin and then me - not something else.
