### ISSUE TITLE
Meta Description is not scraped/written properly to the ZIM file

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#915]
Running:
```
./node_modules/.bin/ts-node ./src/cli.ts --mwUrl=https://wikem.org/ --adminEmail=kelson@kiwix.org --verbose --useCache --format=novid --format=nopic
```

and then
```
$ zimdump -n M -f Description -d out/wikem_en_all_nopic_2019-07.zim ; echo 
kiwix.wikem_en_all
```

It should give like before:
```
$ zimdump -n M -f Description -d wikem_en_all_2018-09.zim ; echo
From WikEM
```

**Comment by ISNIT0** [comment]
In this case, the `#siteSub` element isn't present on the homepage, so the standard logic:
```
Description = dump.opts.customZimDescription || dump.mwMetaData.subTitle || zimName,
```
Is falling back to `zimName`
I don't think this is a regression, it looks like the wiki has changed.
If there is a better way to do the subTitle check, we can look at implementing it as a feature

**Comment by kelson42** [comment]
@ISNIT0 First of all: never close a ticket which is not implemented. Then this is 100% sure a regression as I would never have done that.... and this is here 100% sure of not fitting the ZIM spec. Just replace `zimName` with `""` like it was before.
