### ISSUE TITLE
Create a Zim file of https://proofwiki.org?

### ISSUE THREAD

**Issue by ScyllaHide** [openzim/mwoffliner#92]
Proof Wiki seems to have a typical "wikipedia structure" so far i can see. I have used it a few times to learn proof methods and to look up things, but it would be nice to have an offline version as a zim file.
Hope that is possible. 

"ProofWiki is an online compendium of mathematical proofs! Our goal is the collection, collaboration and classification of mathematical proofs."

**Comment by kelson42** [comment]
This issue was moved to openzim/zim-requests#93
