### ISSUE TITLE
Empty Wikipedia References sections

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#920]
**Reported by nobody on 2014-12-05 08:44 UTC**
In some articles in the zim for the english wikipedia with images (possibly others too) the  references are empty. For example in the article "Ön, Umeå", see the attached image.

http://en.wikipedia.org/wiki/%C3%96n%2C_Ume%C3%A5

**Comment by vaibhavmatta** [comment]
Sir, May I start working on it?

**Comment by kelson42** [comment]
@vaibhavmatta If the problem is still there, not so sure, please caary on with a PR.

**Comment by kelson42** [comment]
I see the references in http://library.kiwix.org/wikipedia_en_all_nopic/A/%C3%96n,_Ume%C3%A5. Has been fixed probably.
