### ISSUE TITLE
3 problems with the WikiMed homepage

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#925]
With MWoffliner1.9.5:
* Navigation path and title on the top of the page should not be visible
* The font for the first paragraph is wrong.

![image](https://user-images.githubusercontent.com/1029718/62415319-f6aca480-b627-11e9-96a6-3c772c3183b5.png)

**Comment by ISNIT0** [comment]
The title says there are 3 issues, but the body has only two. What is the third?

Is there logic for not writing the title on specific pages?

Is the font anything to do with https://github.com/openzim/mwoffliner/issues/19 ?

**Comment by ISNIT0** [comment]
@kelson42 I just realised that the logic defining how the article is rendered as a main page is related to `--customMainPage`. Could you paste your command please?

**Comment by kelson42** [comment]
@ISNIT0 one problem with the path and one with the title.

I'm not sure, but I might have implemented a rule removing the title on the mainpage.... but that does not explain why the path was not displayed. A other approach would be that we have a special code to avoid the display online... and something has changed around this.

I you want, you can already fix the font problem.... and I will investigate a bit around the rest.

**Comment by kelson42** [comment]
@ISNIT0 Problem of font is still there http://library.kiwix.org/wikipedia_en_medicine_maxi_2019-08/A/Wikipedia:WikiProject_Medicine/Open_Textbook_of_Medicine2... and a new problem has appeared. Why the paragraph is not at the top of the article?

**Comment by ISNIT0** [comment]
MWOffliner gets raw HTML back, I don't think it's appropriate for that to be modified.
https://en.wikipedia.org/w/api.php?action=visualeditor&mobileformat=html&format=json&paction=parse&page=Wikipedia%3AWikiProject_Medicine%2FOpen_Textbook_of_Medicine2

The structure, and the fonts are set in the HTML

**Comment by kelson42** [comment]
@ISNIT0 It was working fine, so I guess something has been changed on our end OR a bug has been introduced upstream. I don't see any other possible scenario. In both case something needs to be done.

**Comment by kelson42** [comment]
Works fine, @ISNIT0 You are definitly right.
