### ISSUE TITLE
[URGENT] --Filenameprefix does not work like before

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#935]
It seems the tag are now included even if `--filenamePrefix` is used. For example this call:
https://farm.openzim.org/tasks/5d4ab4672189039b3b18eeef

has generated a wrong fliename (duplicate `_nopic`):
https://download.kiwix.org/zim/wikipedia/wikipedia_fr_all_nopic_nopic_2019-08.zim

**Comment by kelson42** [comment]
@ISNIT0 We should ASAP fix the bug and make a new release

**Comment by rgaudin** [comment]
As detailed in #742 and in the help message, previous behavior was `--filenamePrefix` to replace everything up to the `_{date}`.

```
--filenamePrefix           For the part of the ZIM filename which is before
                             the date part.
```

**Comment by kelson42** [comment]
See also #742

**Comment by ISNIT0** [comment]
This behaviour doesn't seem to have changed since 1.5.0

**Comment by ISNIT0** [comment]
Closing in favour of https://github.com/openzim/mwoffliner/issues/742
