### ISSUE TITLE
wikipedia_es_venezuela stops sending output after ~20mn

### ISSUE THREAD

**Issue by rgaudin** [openzim/mwoffliner#940]
On the zimfarm, `wikipedia_es_venezuela` was killed about 30mn after starting using 1.9.6.
It was killed because it didn't emit output for 10mn.

[Details on the zimfarm](https://farm.openzim.org/tasks/5d528aa11339d1137618f0e5)

I relaunched it with `noLocalParserFallback` but the result is the same (killed after about 30mn). [Details on the second run](https://farm.openzim.org/tasks/5d53e1601339d1137618f245).

Output is full of `Bad title` lines like:

```
[error] [2019-08-14T10:59:35.521Z] Error in retrieved article [Johann_von_Uslar
]: { code: 'invalidtitle',
  info: 'Bad title "Johann_von_Uslar ".',
  '*':
   'See https://es.wikipedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.' }
[error] [2019-08-14T10:59:35.978Z] Error in retrieved article [Juan_Barreto
]: { code: 'invalidtitle',
  info: 'Bad title "Juan_Barreto ".',
  '*':
   'See https://es.wikipedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.' }
[error] [2019-08-14T10:59:36.171Z] Error in retrieved article [Angelo_Peña
]: { code: 'invalidtitle',
  info: 'Bad title "Angelo_Peña ".',
  '*':
   'See https://es.wikipedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.' }
```

**Comment by kelson42** [comment]
I will have a look what is going on here

**Comment by Popolechien** [comment]
I suggest we simply kill that thing. There is no demand for country-specific material (at least not under this form or shape) and it ends up cluttering the catalog.

**Comment by kelson42** [comment]
@Popolechien If the catalog is cluttering, then we need to improve the library because we are going to multiple the size of the catalog by many factors. The problem here is if this selection needs a lot of work on our size for a small audience... but I don't think this is the case. I'll take care about it.
@rgaudin The problem seems here to be untrimmed line and/or file in windows format (dos2unix seems to have fixed the pb).
