### ISSUE TITLE
Allow custom flavour plugins

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#941]
This is necessary to allow to make https://github.com/openzim/zim-requests/issues/148 properly

**Comment by julianharty** [comment]
@kelson42 can you provide a couple of examples of these custom flavour plugings please?

**Comment by ISNIT0** [comment]
@julianharty the format of them hasn't yet been defined. I'll be "discovering" what they'll look like while implementing :)

**Comment by kelson42** [comment]
> @kelson42 can you provide a couple of examples of these custom flavour plugings please?

@julianharty Sorry for late answer, but here is our first plugin #989
