### ISSUE TITLE
Selection filename part doesn't support `.`

### ISSUE THREAD

**Issue by rgaudin** [openzim/mwoffliner#943]
When building a selection, the output filename includes the `--articleList` basename as the *selection* name.

For instance, `http://download.kiwix.org/wp1/enwiki/customs/football` would look like `wikipedia_en_football_xxx`.

If the URL's basename contains a `.`, only the left part of the `.` is used.

So `--articleList="http://download.kiwix.org/wp1/enwiki/customs/wp1-0.8"` generates `wikipedia_en_wp1-0` instead of the expected `wikipedia_en_wp1-0.8`.

It's reasonable to think it was done on purpose so that URLs ending in `football.txt` would result in `_football_` and not `_football.txt_`… @kelson42 ?

**Comment by rgaudin** [comment]
Please also not that the `Name` metadata is incorrect in the same way.

**Comment by kelson42** [comment]
@ISNIT0 Please confirm the bug and the reason if the solution is not obvious
