### ISSUE TITLE
WPEN is not scrapeable anymore in 16GB of RAM

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#948]
See https://farm.openzim.org/tasks/5d5c519f1339d1137618f4b1
An additional effort should be done on memory consumption

**Comment by kelson42** [comment]
@ISNIT0 Any idea how we could do better?

**Comment by kelson42** [comment]
Here is the monitoring at that time
![image](https://user-images.githubusercontent.com/1029718/63546275-b7d48500-c529-11e9-8ca7-a0091ff6dd29.png)

**Comment by kelson42** [comment]
@ISNIT0 I'm not so sure anymore mwoffliner has crashed because of lack of memory considering that we had still a lot of memory cached.

**Comment by kelson42** [comment]
@ISNIT0 I have asked @rgaudin to restart a scrape, the error is quite weird to me. I want to see if the problem is reproducable.

**Comment by ISNIT0** [comment]
@kelson42 Any news?

**Comment by rgaudin** [comment]
Failed again in the favicon resize. https://farm.openzim.org/tasks/5d611a341339d1137618f565

**Comment by ISNIT0** [comment]
Looks like it's related to this: https://github.com/nodejs/node/issues/25382

**Comment by kelson42** [comment]
@ISNIT0 You told me that the problems comes probably from the fact that a process fork happens here at at time the Node.js process is already quite big. Maybe the solution is simply to move this image resize to the start of the scraping process?

**Comment by ISNIT0** [comment]
It seems imagemin (our image compression library) also suffers from this problem, so we could potentially save even more memory by finding a node configuration variable. https://github.com/nodejs/node/issues/25382#issuecomment-497083280

The favicon is done at the end because favicon downloading etc. is handled the same way any other media file is downloaded.

**Comment by ISNIT0** [comment]
This PR _may_ help https://github.com/openzim/mwoffliner/pull/968

**Comment by kelson42** [comment]
@ISNIT0 Still same problem
```
T:91842; 16000/19032
T:91844; 17000/19032
T:91846; 18000/19032
T:91848; 19000/19032
T:91900;  write checksum
T:91900; finish
[log] [2019-09-09T15:10:53.780Z] Summary of scrape actions: {
	"files": {
		"success": 30889,
		"fail": 0
	},
	"articles": {
		"success": 5925375,
		"fail": 11
	},
	"redirects": {
		"written": 8408528
	}
}
[log] [2019-09-09T15:10:53.787Z] Finished dump
[log] [2019-09-09T15:10:53.794Z] Doing dump
[log] [2019-09-09T15:10:53.798Z] Writing zim to [/output/wikipedia_en_all_nopic_2019-09.zim]
[log] [2019-09-09T15:10:53.799Z] Flushing Redis file store
[log] [2019-09-09T15:10:54.098Z] Found [5] stylesheets to download
[log] [2019-09-09T15:10:54.098Z] Downloading stylesheets and populating media queue
[log] [2019-09-09T15:10:54.166Z] Downloaded stylesheets
[log] [2019-09-09T15:10:54.167Z] Saving favicon.png...
Failed to run mwoffliner after [102343s]: {
	"stack": "Error: spawn ENOMEM\n    at ChildProcess.spawn (internal/child_process.js:366:11)\n    at Object.spawn (child_process.js:551:9)\n    at exec2 (/tmp/mwoffliner/node_modules/imagemagick/imagemagick.js:24:25)\n    at Object.exports.convert (/tmp/mwoffliner/node_modules/imagemagick/imagemagick.js:253:10)\n    at Promise (/tmp/mwoffliner/lib/mwoffliner.lib.js:417:47)\n    at new Promise (<anonymous>)\n    at resizeFavicon (/tmp/mwoffliner/lib/mwoffliner.lib.js:416:28)\n    at /tmp/mwoffliner/lib/mwoffliner.lib.js:433:28\n    at Generator.next (<anonymous>)\n    at /tmp/mwoffliner/lib/mwoffliner.lib.js:9:71\n    at new Promise (<anonymous>)\n    at __awaiter (/tmp/mwoffliner/lib/mwoffliner.lib.js:5:12)\n    at saveFavicon (/tmp/mwoffliner/lib/mwoffliner.lib.js:413:20)\n    at /tmp/mwoffliner/lib/mwoffliner.lib.js:331:23\n    at Generator.next (<anonymous>)\n    at fulfilled (/tmp/mwoffliner/lib/mwoffliner.lib.js:6:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
	"message": "spawn ENOMEM",
	"errno": "ENOMEM",
	"code": "ENOMEM",
	"syscall": "spawn"
}
```

**Comment by kelson42** [comment]
Maybe using a lib like https://github.com/lovell/sharp would fix the pb?
