### ISSUE TITLE
in which package is unixsocket command in Ubuntu 16.04?

### ISSUE THREAD

**Issue by kensully** [openzim/mwoffliner#95]
I feel embarrassed for asking such a basic tool I must be aware of. I searched for it on the net but I can not locate it to run below  commands:

      unixsocket /dev/shm/redis.sock
      unixsocketperm 777
Where do I find that tool?

**Comment by kensully** [comment]
OK.  I just found out that they are not commands they are config parameters of redis server.

      echo "" >> /etc/redis/redis.conf
      echo "unixsocket /dev/shm/redis.sock" >> /etc/redis/redis.conf 
      echo "unixsocketperm 777" >> /etc/redis/redis.conf
      echo "save \"\"" >> /etc/redis/redis.conf
      echo "appendfsync no" >> /etc/redis/redis.conf

**Comment by kelson42** [comment]
@kensully Indeed the doc was quite unclear, I just have improved it.
