### ISSUE TITLE
[REGRESSION] Collapsing of section don't work fine anymore

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#952]
See http://library.kiwix.org/wikipedia_en_geography_maxi/A/England.

Collapsing "Toponymy" does not hide subsection "Prehistory and antiquity". It should also "hide" all the subsection (but not collapse then). It does not.

**Comment by Jaifroid** [comment]
We've been discussing this wrt a workaround that I proposed in Kiwix JS for opening all details sections. @mossroy is of the opinion, and I agree, that it would be best to get this right in mwoffliner, as it's not quite working as intended. I made a related report in https://github.com/openzim/mwoffliner/issues/838#issuecomment-522311757. To summarize, we have some inconsistency with the way the `open` attribute is added to the `<details>` tags: it's added at lower heading levels (h3, h4) but not at higher levels (h2). There's probably a similar underlying cause as for this issue. I'd be happy to take a look at the code if @ISNIT0 can guide me as to where the details-summary tags are added.

**Comment by ISNIT0** [comment]
@Jaifroid This ticket represents a bug, which will hopefully be fixed soon - the other issues should probably be discussed on the other ticket.

**Comment by kelson42** [comment]
@ISNIT0 This is still not working fine! with WPTL article Guam, here is what I get on my phone!
![Screenshot_20191004-094610](https://user-images.githubusercontent.com/1029718/66194487-39791000-e69d-11e9-9b62-fabb97fbdb1f.png)

Not only the sections are expanded where they should not but the arrows do not stick anymore to the title!

**Comment by kelson42** [comment]
We have also a double horizontal lines appearing!

**Comment by ISNIT0** [comment]
@kelson42 This looks like a different issue to what's reported?

**Comment by kelson42** [comment]
@ISNIT0 Might be... But I'm out of patience and don't have the time to go through all the multiple tickets I have been opening in the last 6 months about this really specific small feature to know which is the best match.

**Comment by kelson42** [comment]
@ISNIT0 This is easy to verify. What are the HTML difference?

**Comment by kelson42** [comment]
Looks good with http://library.kiwix.org/wikipedia_tl_all_maxi_2020-02/A/Guam
