### ISSUE TITLE
Use new tagging system

### ISSUE THREAD

**Issue by rgaudin** [openzim/mwoffliner#961]
In order to update ZIM files to the [new tagging system](https://wiki.openzim.org/wiki/Tags), please make sure your scraper:

* is using the lastest zimwriterfs (`1.3.5+` or `:latest` docker image). It supports new options and fixes important metadata (tags, favicon) and LZMA compression level.
* is including a `_category:xxx` tag (See [kiwix-tools#317](https://github.com/kiwix/kiwix-tools/issues/317))
* is including a tag for your content (ex: `Wikipédia`, `DirtyBiology`, etc.)
* is setting a proper `--name`.
* is using a proper `--flavour` (if relevant)
* is setting a `--scraper`.

**Note**: I believe mwoffliner already implements most of it. `Scraper` metadata might be the only missing bit.

**Comment by kelson42** [comment]
@rgaudin AFAIK all of this has been implemented in the last 2 weeks

**Comment by rgaudin** [comment]
Are you sure about the `Scraper` metadata?

```
grep "Scraper" ./* -R
./lib/mwoffliner.lib.js:                    url: 'Scraper',
./node_modules/clarinet/samples/npm.json:    "description": "Modular Scraper using Jquery and a plugin that allow you to use regex as selector.",
./src/mwoffliner.lib.ts:      url: 'Scraper',
```

**Comment by kelson42** [comment]
@rgaudin Pretty sure, otherwise this won't be possible http://library.kiwix.org/wikisource_as_all_novid_2019-07/M/Scraper.

**Comment by rgaudin** [comment]
perfect then!
