### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by iyuter** [openzim/mwoffliner#965]
Hello, I am an OS Windows user, and I want to make a current ZIM image of English Wiktionary, 
wiktionary_en_all_novid_2018-06.zim  -- is a year-ago. 
I have no experience with Virtual Java machine or Python. 
Is there a program to make a dump into ZIM on Windows easely?

**Comment by kelson42** [comment]
Hi, MWoffliner does not run natively on Windows. But you are right the ZIM file is really old, we should make a new one in September. You just need to be a bit more patient :)

**Comment by iyuter** [comment]
Thanks, I asked onto kiwix.org 3 times, no avail. 
I am going to cut off myself from internet till the end of my life.

**Comment by iyuter** [comment]
Is there a program (even in Linux) to repack into ZIM from image made by Wikimedia dump service
https://dumps.wikimedia.org/enwiktionary/20190820/
enwiktionary-20190820-pages-articles-multistream.xml.bz2  ?
It would decrease the consumed trafic (one big file, not the many small); will only have to convert locally on fast strorage spaces...

**Comment by kelson42** [comment]
@iyuter No and the dumps do not provide the same kind of information like necessary to do a ZIM file.

**Comment by iyuter** [comment]
September has passed away

**Comment by iyuter** [comment]
October has passed away.
