### ISSUE TITLE
Image size optimization seems to not happen in memory

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#966]
Which is really sad because it generates a lot of fs access and slows down significantly the whole scraper. If it is not possible to make it in memory could we at least use `/dev/shm` instead of `/tmp`?

**Comment by kelson42** [comment]
@ISNIT0 This is unclear to me which part of the software decides to write in `/tmp`. Do you know it?

**Comment by ISNIT0** [comment]
Image minification is handled by https://github.com/imagemin/imagemin

**Comment by kelson42** [comment]
@ISNIT0 Do we have a way to tell imagemin to stop dealing with `/tmp` a temporary directory?

**Comment by kelson42** [comment]
I have asked the question here https://github.com/imagemin/imagemin/issues/332

**Comment by kelson42** [comment]
@ISNIT0 By surfing through old bugs I found this https://github.com/imagemin/imagemin/issues/188. It looks like we could configure this.

**Comment by kelson42** [comment]
@ISNIT0 @rgaudin I achieve to get the imagemin to write to `/dev/shm` by just setting `export TMPDIR=/dev/shm` before launching MWoffliner. I fail so far to do that within MWoffliner using Javascript. I guess I fail to get the environment variable transmitted properly to the child process. Would that be an option to your opinion to set the whole TMPDIR env variable to /dev/shm in the MWoffliner Docker?

**Comment by rgaudin** [comment]
I'd prefer it to be handled properly, either via an imagemin option (haven't looked at the issues you mentioned) or by passing the ENV properly.

That said, we could still change our Dockerfile in the meantime as a temporary fix. Could you try and make sure it behaves as expected inside a container?

**Comment by kelson42** [comment]
Having in a look in details, it looks like that part of the problem is that a few Node.js modules generating temporary name don't take care properly from the `$TMPDIR` variable, actually from the Node.js `[os.tmpdir](https://nodejs.org/api/os.html#os_os_tmpdir)`. I have already open two bugs:
* `[tempty](https://github.com/sindresorhus/tempy/issues/16)`
* `[tempfile](https://github.com/sindresorhus/tempfile/issues/12`

Luckily it seems that the `tmp` modules works fine and should IMO advantageously replace these modules in the `imagemin-*` plugin needing this king of feature. Will have a look to open a few PRs.

**Comment by kelson42** [comment]
First [ticket](https://github.com/imagemin/imagemin-advpng/issues) & [PR](https://github.com/imagemin/imagemin-advpng/pull/9) to fix `imagemin-advpng`.

**Comment by kelson42** [comment]
@rgaudin @ISNIT0 Finally the problem was somewhere else: compiletime vs runtime... and the PR is a lot quicker. Still took me 4 hours to fully understand/fix the pb :(
