### ISSUE TITLE
Zim of Katlas.org?

### ISSUE THREAD

**Issue by ScyllaHide** [openzim/mwoffliner#97]
http://katlas.org/wiki/Main_Page

katlas is a wiki for knot theory.

thank you!

**Comment by kelson42** [comment]
I think the license of this wiki is not clear at all. We won't create a ZIM file of a non-free wiki.

**Comment by ISNIT0** [comment]
Looks like it will become MIT?
![image](https://user-images.githubusercontent.com/5173131/28274334-853f24f6-6b08-11e7-9842-749d1a3b4f72.png)

http://katlas.org/wiki/To_Do

**Comment by ScyllaHide** [comment]
@kelson42 is this enough what @ISNIT0 found?

**Comment by kelson42** [comment]
@ScyllaHide I really would prefer to have clearly indicated.

**Comment by ScyllaHide** [comment]
@kelson42 should i write them a mail and ask?

**Comment by kelson42** [comment]
@ScyllaHide yes please

**Comment by ScyllaHide** [comment]
so i havnt received an answer about the license of this wiki. So i guess we can close it.

**Comment by kelson42** [comment]
This issue was moved to openzim/zim-requests#97
