### ISSUE TITLE
--format=nozim creates a directory with the wrong name

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#971]
```
mwoffliner --mwUrl=https://bm.wikipedia.org/ --adminEmail=kelson@kiwix.org --format=nozim --verbose
```

Creates a `out/wikipedia_bm_all_2019-09.zim`.

It should create a directory `out/wikipedia_bm_all_2019-09`.

**Comment by kelson42** [comment]
The whole feature seems broken. Files are not disposed properly like they were before (it seems they follow a ZIM like structure). Articles are blank.

**Comment by ISNIT0** [comment]
I'm not sure what you mean by this. I use `nozim` for testing all the time.

**Comment by kelson42** [comment]
* articles are written in the `A`, they should probably be at the root like it was.
* `A/index.html` is empty
* images are in `I/m`, they were in `m`.
* `A/Bamako.html` is empty
...

**Comment by ISNIT0** [comment]
The structure of the ZIM file needs to be retained for the output to actually be usable (`nozim` doesn't and shouldn't affect the re-writing of urls).

`A/index.html` is a redirect to `Nyɛ_fɔlɔ`
`A/Bamako.html` is a redirect to `Bamakɔ.html`

I also believe that the folder should end in `.zim`. I've deliberately tried to keep the `nozim` output and logic as close to the normal modes as possible.

**Comment by kelson42** [comment]
The filestructure should be like it was. We never have discussed that it should change. Redirects should be HTML redirects, no empty files (pretty sure this was also working fine). The output of `nozim` should and was clear and directly usable with a browser. It is not anymore.

**Comment by ISNIT0** [comment]
- The redirects are Symlinks, not empty files.
- The file structure writing has changed. This all changed when introducing `node-libzim`. It is not feasible to change it back

I don't understand what the issue with this structure is. It is far more representative of actual ZIM files.

**Comment by kelson42** [comment]
Sorting out the nature of the problem...

**Comment by kelson42** [comment]
I think I'm confusing two different things:
* the option `--keepHtml` and `--writeHtmlRedirects`
* and the `--format=nozim`

To the contrary to what I have written before, the `--format=nozim` had no impact on what was written to the fs (except the ZIM file was not generated). This is the combination of `--keepHtml` and `--writeHtmlRedirects` was able to produce a perfectly viable local dump.

Now, `--keepHtml` and `--writeHtmlRedirects` have been removed, but we still have `--format=nozim` which in fact works slightly differently as before as it is responsible to write something to the fs... but like I said before the result is not usable at all like the stuff `--keepHtml` and `--writeHtmlRedirects` was doing (I have put an example available online [here](http://tmp.kiwix.org/wikipedia_bm_all_2019-09.html.tar.bz2)).

@ISNIT0 Does my analysis does make sense to you too?

**Comment by kelson42** [comment]
@ISNIT0 Unfortunately no feedback. I still have written something wrong, `--keepHtml` is not a removed feature. Not sure exactly how that should still work considering the fact that we don't write any HTML anymore on the filesystem. The most probably scenario is that is does not work at all anymore.

**Comment by kelson42** [comment]
To conclude, MWoffliner has lost its capacity to produce a coherent local HTML dump. Its unfortunate this lost has not been done with fulll awareness but this is a fact now.

Rebuilding it would need quite a bit of work and as this is not a use case we really need at openZIM, I propose to abandon it. As a consequence the format `nozim` and the option `--keepHtml` would be definitely useless and then removed. The good point is that `nozim` was a fake flavour... so this move will add coherency their.

All of this should simplify a bit MWoffliner. That said it would be good still at some point to be able to get an HTML file based version. This is the kind of thing a project like Wikipedia on IPFS needs for example. I think this should be easily possible by fixing a few easy stuff in the directory dump feature of `zimdump` and this will be even more true one time we will have remove the ZIM namespace concept... and this would not be MWoffliner specific, which is good. An other way to achieve that would be to implement a fuse driver for ZIM, a thing which would be helpful for many people/use cases.

@ISNIT0 @Popolechien @rgaudin Please let me know if anything I plan to do raise a problem to your opinion.

**Comment by Popolechien** [comment]
@kelson42 Well I did not know it even existed, so no big loss for. But when you say
> This is the kind of thing a project like Wikipedia on IPFS needs

What do you mean? Or rather, do you mean that at the moment they can't distibute our content?

**Comment by kelson42** [comment]
@Popolechien Not so sure how they proceed, but they need the HTML files.

**Comment by rgaudin** [comment]
hum, couple of statements first:

* I don't have any real use case in mind for this feature.
* I believe it's important to have this feature working because it:
  * provides flexibility. we're tweaking mwoffliner to our needs because it's out tool but it doesn't mean other people's needs are similar. Julien's solution for creating a dynamic (JS) homepage of a ZIM file could be hacked using this feature for instance.
  * it forces us to make sure our different tools work together. This prevents breaking the *concept/spirit* of the zim.

As I said, I'm not using this feature ATM but I feel bad about loosing the ability to scrape mediawikis and customize the result before recreating a zim. As you said, a similar result could be achieved by improving zimdump or creating other tools but… those doesn't exist yet and we already lack communication skills regarding our tools: how many people scraping mediawikis already because they don't know mwoffliner or failed to use it properly?

Now on the exact topic, your messages looked like the change was very minimal and the proposal to remove the feature altogether suprizing, so I tested it.

Indeed, the HTML folder structure is not the same as it historically was but… is that a problem? I could successfuly dump `wikipedia_fr_test` and look at files in the browser locally and I could successfuly recreate a ZIM file from it using zimwriterfs.

I had to fix a broken symlink though (`A/Orbite_midi/minuit.html`). So maybe it's a quick fix?

**answer**: no, I can't think of any current use case for this feature.

**Comment by kelson42** [comment]
@rgaudin Thank you for your feedback. We should discuss that in a call I guess as I have many remarks to give to your comment.

**Comment by ISNIT0** [comment]
I have strong feelings about this - we shouldn't remove `nozim`.

1. it make it **much** faster and easier to test non-zim related functionality
2. it makes it easier for people to get started when their machine doesn't support libzim easily
3. it makes MWOffliner more generic and useful for other communities that want to distribute MW content in non-zim formats

> To conclude, MWoffliner has lost its capacity to produce a coherent local HTML dump

I don't understand how you came to this conclusion. It works/is coherent when I use it. I've even used it to create valid ZIP files of content.

**Comment by ISNIT0** [comment]
> If the feature is not there, there is nothing to test. I have removed the test in my PR

I mean manual tests

> If node-libzim is not fully working, MWoffliner can not fully work and it should not start

But it can fully work if the user doesn't want to produce ZIMs

> now it starts to cost to maintain it due to the introduction of node-libzim

This is not the case.
During development, the nozim functionality has not caused development to be harder, and handling this functionality happens completely separately from node-libzim. (the ZimCreator isn't even instantiated).


This feels very much like we're creating a walled-garden, not an open, community tool.

**Comment by kelson42** [comment]
Developers should:
* Implement feature needed by users, not the other way around
* rely on automated tests, not manual test
* developer dedicated tools, if this is really needed to achieve what is needed by users... But here I don't see any reason to have one.

My PR has removed a dedicated FS backend module, so obviously there is dedicated code so it costs and this has been introduced because of node-libzim.

ZIM is not a wall, the spec is open, the std implementation is FOSS, the std tools are FOSS and the developpement is community based. If people care about the HTML file based version, they can open tickets if zimdump does not do the deal for them.
