### ISSUE TITLE
Redirect to homepage is not handled properly

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#984]
It generates a blank homepage.

For example:
```
mwoffliner --adminEmail="contact@kiwix.org" --format="nodet,nopic:mini" --format="nopic:nopic" --format="novid:maxi" --mwUrl="https://tr.wikipedia.org/" --customZimFavicon="https://tr.wikipedia.org/static/images/project-logos/trwiki.png" --customZimTitle="Vikipedi" --customZimDescription="Wikipedia 'nın çevrimdışı çevirisi" --customMainPage="Kullanıcı:Stephane_(Kiwix)/Landing" --redis="/tmp/sockets/redis_5d763c7a1d1619754c6a55af.sock" --outputDirectory="/output"
```

**Comment by ericblancas23** [comment]
will take a look at this!

**Comment by kelson42** [comment]
@ericblancas23 any success?

**Comment by kelson42** [comment]
This is the case for example for http://library.kiwix.org/wiktionary_io_all_nopic/ (see #1007) and a few others.

**Comment by kelson42** [comment]
@ritikkuril Yes, please! Just make a PR when this is fixed!

**Comment by MananJethwani** [comment]
@kelson42 I want to work on this issue

**Comment by kelson42** [comment]
@MananJethwani Thank you for your offer. I believe you should be able to get that problem with an `--articleList` as well. That should solve your problem.

**Comment by MananJethwani** [comment]
@kelson42 doesn't customMainPage needs to be a valid URL for redirection to work or did I miss understood the argument?

**Comment by kelson42** [comment]
@MananJethwani customMainPage argument does not expect a Url. It expects an articleId. Obviously a valid articleId. But a redirect is a valid article.

**Comment by MananJethwani** [comment]
@kelson42 the Kullanıcı:Stephane_(Kiwix)/Landing is itself redirecting to another article namely Kullanıcı:The other Kiwix guy/Landing and using this in argument for customMainPage works fine.
from this the only inference I could make is Kullanıcı:Stephane_(Kiwix)/Landing is not an article anymore to find that page I have to use the link [https://tr.wikipedia.org/w/index.php?title=Kullan%C4%B1c%C4%B1:Stephane_(Kiwix)/Landing&redirect=no](url)

**Comment by MananJethwani** [comment]
so I think the search for this page is not performed properly so should I make a search or can you suggest something else?

**Comment by kelson42** [comment]
The fix should be that if the customMainPage is a redirect, than it should be a redirect in the ZIM itself, and the page which is redirect to, shouild be mirrored as well.

**Comment by kelson42** [comment]
Or, you just detect this is a redirect and then you generate an error (probably better),

**Comment by MananJethwani** [comment]
@kelson42 I will go with the second one but It may take me few days because of some COVID19 related issue.

**Comment by kelson42** [comment]
@MananJethwani Great, thank you.
