### ISSUE TITLE
Sample custom plugin for wiktionary

### ISSUE THREAD

**Issue by rgaudin** [openzim/mwoffliner#989]
In order to produce better wiktionary ZIM ([#147](/openzim/zim-requests/issues/147) [#148](/openzim/zim-requests/issues/148)), we need to be able to manipulate the received DOM for each article.

This is why #941 was opened: to allow custom article DOM processing in mwoffliner through a plugin mechanism. Discussion about how to implement this mechanism is up to #941 so I am documenting here a sample requirement for the *demo wiktionary plugin* we'll use to bootstrap the feature.

### Main objective

* simplify [fr-wiktionary](https://fr.wiktionary.org) ZIM with french-only info.
* ideally it should work with all wiktionaries but for this use case, we'll test over FR version.
* the *target* language would be the main wiktionary language (FR in this case) but we might want to keep it an option to extract specific foreign-to-french language ZIM (BM-FR or IT-FR for instance).
* in this regard, we might want to set a list of languages to keep? @kelson42 @Popolechien what do you think?
  * In `fr`, we might need to include `fro` (Ancien français)…
* articles without a section of the target language(s) should not be included.
  * Ex: with `fr` target, [buru article](https://fr.wiktionary.org/wiki/buru) should not be included.
* the TOC should be removed if we have a single language target and reduced if not.
* only the target-language(s) section(s) should be kept.
* in-section content should be kept as is.

### DOM Manipulations

* [pain](https://fr.wiktionary.org/wiki/pain) is a good example
* we'll need a mapping for `targetLanguage(s)` to `#AnchorLink(s)` as this is what's usable (in the rendered version).
* `h1#firstHeading` is kept
* rest happens solely within `div.mw-parser-output`
* if we can know that `div.bandeau-voir` will not have valid links, remove it. (otherwise, it will be a link-less sentence). this classname being french, I bet it's specific.
* if `div#toc > ul li a[href]` (without `#`) is not in our `anchorLinks` then the whole `li` is removed.
* if there's only `div#toc > ul > li` left, then remove `div#toc`
* if there's no `div#toc > ul > li`, then the page doesn't contain wanted content and should not be included.
* for the rest of the article, if `h2 > span.mw-headline[id]` not in `anchorLinks` then every elements from that `h2` up to the next `h2` (or end of `div.mw-parser-output`)

**Comment by Popolechien** [comment]
> In fr, we might need to include fro (Ancien français)…

That would be nice but except for French and a couple of other languages we'd be hard-pressed to know what's what. Probably not worth the effort.

> `h1#firstHeading` is kept

Not sure I understand this one, but just in case if this means that "Français" is kept (which is H1) then I don't see the point. Coming back to the [Pain](https://fr.wiktionary.org/wiki/pain) (bread) example, the first heading seen should `h2` _Etymologie_... and we should not take `h3`-level content (and below) for the time being. Seeing this as an android app, I'd rather save as much space as possible and focus on the essentials.

Last but not least: within that same ambit of saving space the app will be illustration-less, see e.g. [bread](https://fr.wiktionary.org/wiki/pain#Nom_commun) again.

**Comment by rgaudin** [comment]
> > In fr, we might need to include fro (Ancien français)…
> 
> That would be nice but except for French and a couple of other languages we'd be hard-pressed to know what's what. Probably not worth the effort.

Noted for this example but what about the other (`fr-it` or similar) ?

> > `h1#firstHeading` is kept
> 
> Not sure I understand this one, but just in case if this means that "Français" is kept (which is H1) then I don't see the point. Coming back to the [Pain](https://fr.wiktionary.org/wiki/pain) (bread) example, the first heading seen should `h2` _Etymologie_... and we should not take `h3`-level content (and below) for the time being. Seeing this as an android app, I'd rather save as much space as possible and focus on the essentials.

No, `h1#firstHeading` is **pain**.

> Last but not least: within that same ambit of saving space the app will be illustration-less, see e.g. [bread](https://fr.wiktionary.org/wiki/pain#Nom_commun) again.

Hum, I don't recall file size every been mentioned so I think we should postpone this decision to after we've had the opportunity to run it with and without images. I think illustrations are quite rare in the wiktionary and we need data to decide whether it's worth removing them of not.

**Comment by Popolechien** [comment]
The size issue is something that's been discussed since our first proposal to the Foundation last year, with users unwilling to install things above 100 Mb (!). 
Wiktionary maxi: 2.3Gb / nopic: 2.0 Gb (and that was a year ago). So here's 300Gb easily saved.

Either way, that's only for clarification - I was a bit too focused about the android app, in any case the zim itself can follow the regular format(s).

> Noted for this example but what about the other (`fr-it` or similar) ?

Do you have an example?

**Comment by kelson42** [comment]
@jetownfeve21 Any news on this? We are meanwhile so late!

**Comment by bakshiutkarsha** [comment]
All the h4 titles and details for the french wiktionary are removed. It would be great if i can get clarity on these two things as well:

> we should not take h3-level content (and below) for the time being.
Attaching how the wiki looks after removing h4 tags. Do we need to remove "everything"  after first h3 tag. Eg: In this wiki, after "Nom commun", everything else should be removed or wiki should be produced as shown in screenshot?

> if we can know that div.bandeau-voir will not have valid links, remove it.
For this we need to loop one more time after scarping every article in wiktionary just to check which of them will have a valid link, and the purpose of this ticket mainly focuses on reducing the size of the page. So do we really need to do that?

<img width="400" alt="Screenshot 2020-03-18 at 3 31 43 AM" src="https://user-images.githubusercontent.com/13726478/76937121-91fa3d80-68ca-11ea-8be2-ab3034e431e2.png">

**Comment by rgaudin** [comment]
I think we need @Popolechien's input on this.

Bellow is the full TOC for that article on the online version. Without the `h4`, it's gonna be quite short (loosing dérivés, vocabulaire, proverbes, traductions, etc) but without the `h3` content there's nothing left. Is that what you want @Popolechien ?

![Screen Shot 2020-03-18 at 10 13 57](https://user-images.githubusercontent.com/57929/76951281-562f9a00-6903-11ea-8282-fe1eebd7d455.png)

**Comment by Popolechien** [comment]
To clarify, with an objective of this content being published as an android custom app, size should be prioritized (we should aim for 100 Mb): as much content as possible will be removed to focus on the core. So from the example above I would keep `h3` and get rid of everything else, including the top-level (`h2`?) section title ("Français") and all other `h2` sections (including this time their subsections):

![Capture d’écran 2020-03-18 à 14 42 17](https://user-images.githubusercontent.com/21675885/76967026-1ed2e480-6927-11ea-97f5-4e22877c959c.png)

Meaning all of this needs to be gone:

![Capture d’écran 2020-03-18 à 15 01 49](https://user-images.githubusercontent.com/21675885/76968907-f3052e00-6929-11ea-96b0-9f32cc367d1b.png)

The problem I see right now is that this would only apply to the French Wiktionary because English and probably others, of course, do not have the exact same structure.

**Comment by rgaudin** [comment]
Thanks, this looks clear enough. I'd say we tackle this first and look into making this more generic afterwards.

You didn't reply concerning the medias (pronunciation). @kelson42 would using `maxi` format get rid of those audio files as well?

**Comment by bakshiutkarsha** [comment]
Updated the PR as per requirement, please have a look.

**Comment by rgaudin** [comment]
Do you have a screenshot of the result to share with @Popolechien?

I have created a `test` tag on the docker image pointing to your branch and a [`wiktionary_fr_app`](https://farm.openzim.org/recipes/wiktionary_fr_app) recipe in the zimfarm to build it.

@kelson42 it's enabled but without periodicity and not requested for now. Based on `wiktionary_fr` duration, it should take about 2 days to complete.

**Comment by bakshiutkarsha** [comment]
Hope this can help!

![image](https://user-images.githubusercontent.com/13726478/77218221-6c09ae80-6aff-11ea-8a4a-494c5a02f432.png)

**Comment by rgaudin** [comment]
Could you do one in which we see some of the content ?

**Comment by Popolechien** [comment]
And also what's the file size?

**Comment by rgaudin** [comment]
@kelson do you want to launch it so we’ll have this info on monday ?

**Comment by kelson42** [comment]
@rgaudin I have merged a last small PR related to this ticket. Do we have a recipe ready?

**Comment by rgaudin** [comment]
> @rgaudin I have merged a last small PR related to this ticket. Do we have a recipe ready?

I think the answer is in a comment above ;)

**Comment by kelson42** [comment]
@kelson42 @Popolechien @rgaudin The GSoC has started and we would like to have your feedback on the ZIM generated. On my side I had discovered a few missing articles... but last version `wiktionary_fr_app_maxi_2020-04.zim` does have them... so this is sporadic or has been fixed. But please share your feedback here with @bakshiutkarsha so we can finish the Wiktionary FR before tackling other languages.

**Comment by bakshiutkarsha** [comment]
> @kelson42 @Popolechien @rgaudin The GSoC has started and we would like to have your feedback on the ZIM generated. On my side I had discovered a few missing articles... but last version `wiktionary_fr_app_maxi_2020-04.zim` does have them... so this is sporadic or has been fixed. But please share your feedback here with @bakshiutkarsha so we can finish the Wiktionary FR before tackling other languages.

@kelson42 Any news on this?

**Comment by kelson42** [comment]
>     * Number of entries is remarkably accurate: 1,785,552 seems in line with the number of entries in the category:français.
>       -> **Question**: should be keep the current sorting mechanism to only keep the local language or should we try to grab all mainspace articles in the category (and subcategories)?

@bakshiutkarsha The point @Popolechien tackled is pertinent. If there is a `shouldKeepArticle()` defined in the custom flavour, then we know we won't scrape all the articles (whatever they come from a list or from the namespaces scan). Unfortunatley to rewrite any article, we need to know which articles will be in and which ones will be out. This means, in that case, when `shouldKeepArticle()` is defined, we need to make two runs, one to build the list of articles to mirrors and one to rewrite the DOM.
