### ISSUE TITLE
Input arguments should be tested properly at the start of the process

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#990]
Many times, if the URLs given (or any another command line arguments) are wrong, then the process starts and dies later. All the arguments should be properly tested before anything else.

**Comment by kelson42** [comment]
See #1069 and #491

**Comment by MananJethwani** [comment]
@kelson42 I would like to work on this if no one is working on it

**Comment by MananJethwani** [comment]
the solution I think would be good is to make another test.ts file and make individual as well as combined test for all arguments so that this file can be re used at other places as well.

**Comment by kelson42** [comment]
@MananJethwani Your are welcome to make a PR. Start small, just test one or two things first.
